setup.py

Do not import parsl before dependencies are set up.

---

.github/CONTRIBUTING.rst

This clarifies that hot fixes can be pushed to master, and that
we do not need an issue for very minor changes. Fittingly, I did
not open an issue for this. The main idea here is that issues
are useful if we need to discuss and plan BEFORE development
happens. For very minor, quick fixes, it is more work to explain
the change you want to make than just make it and discuss in the PR.

Add a few details to the contributing doc

---

parsl/__init__.py

Are milliseconds helpful, or are they just more information to parse when you read the log? I favor removing them and using that space for line numbers, which I find more useful.
before:
```
2018-03-21 16:14:18,827 parsl.executors.swift_t [DEBUG]  Initializing TurbineExecutor
```
after:
```
2018-03-21 19:47:54 parsl.executors.swift_t:286 [DEBUG]  Initializing TurbineExecutor
```

Remove milliseconds and add line number to log

---

parsl/app/futures.py

Now that `File` is subclassed from `str`, `isinstance(File, str)`
will always evaluate as True. Fixes #185.

Allow strings in `DataFuture` initialization

---

parsl/dataflow/usage_tracking/usage.py

This fixes #202 
The new additions show up on the tracking server side as: 
``` json
{ "python_v" : "3.6.4",
"parsl_v" : "0.5.0a0"
} 
```

Adding version info from parsl and python to usage tracking.

---

parsl/app/errors.py
parsl/app/python_app.py
parsl/dataflow/futures.py
parsl/executors/ipp.py
parsl/tests/test_ipp/test_python_apps.py
parsl/tests/test_threads/test_python_apps.py
requirements.txt

Here's a first take on #110. I'm sure there are much cleaner ways to accomplish this, but I figure that maybe we can review it, then if desired merge and run with it for a while and get a better sense for what else might be required. This provides our own wrapper around remote errors. I had to add two dependencies: `tblib` to get around the fact that tracebacks are not pickleable or dillable and `dill` to get locally defined classes that might not be imported on the local side (which `pickle` can't handle). We may eventually want to remove the wrapper bits from the traceback-- for now I left them in, because sometimes hiding things makes them more confusing. The main changes are 1) now the traceback includes the location the exception happened in addition to the type and 2) now the …

Unwrap ipp errors #110

---

parsl/tests/checklist.rst
parsl/tests/cleanup
parsl/tests/test_docker/test_docker.py
parsl/tests/test_docker/test_without_containers.py
parsl/tests/test_flowcontrol/setup.sh
parsl/tests/test_flowcontrol/test_bash.py
parsl/tests/test_flowcontrol/test_python.py
parsl/tests/test_flowcontrol/test_python_diamond.py
parsl/tests/test_globus/test_#177.py
parsl/tests/test_ipp/__init__.py
parsl/tests/test_ipp/test_at_scale.py
parsl/tests/test_ipp/test_bash_apps.py
parsl/tests/test_ipp/test_early_attach_bug.py
parsl/tests/test_ipp/test_multiline_bash.py
parsl/tests/test_ipp/test_python_apps.py
parsl/tests/test_ipp/test_python_fibonacci_iterative.py
parsl/tests/test_ipp/test_python_fibonacci_recursive.py
parsl/tests/test_runner.sh
parsl/tests/test_stress/test_python_ipp.py
parsl/tests/test_stress/test_python_simple.py
parsl/tests/test_stress/test_python_threads.py
parsl/tests/test_threads/test_configs.py
parsl/tests/test_threads/test_ipp_configs.py
parsl/tests/user_env.sh

@annawoodard I'm not sure how much this helps in terms of testing work. There's tons of duplication which I haven't been able to trim down.
This PR adds a `test_runner.sh` script that sources a `user_env.sh` script to set some global vars and begin testing of pretty much all the tests we have.
* Some tests will hang, for eg, the ipp version of recursive fibonacci.
* The globus tests will hang if you haven't already started the globusconnect service and done pre-auth.
* Site tests will work only if you have access to the sites and have setup passwordless auth

Testing local

---

parsl/dataflow/dflow.py

Previous behaviour truncated and overwrote the checkpoint
file at each checkpoint, although it was intended to
append.
The previous mode, wb+, means to open the file for both reading and
writing, truncating if necessary - some documentation refers to
this as "updating", which may be the source of confusion.
The new mode, ab, means to open the file for writing, but without
truncating, and positioned initially at the end of the file.

Change checkpoint file modes to append. Fixes issue #230.

---

parsl/dataflow/memoization.py

There were two problems:
1. Task was treated as a collection of tasks, not a single task.
2. The % formatting was not properly bracketed
This code was throwing an exception when encountered, which is
elsewhere silently discarded, and would instead manifest as a hang
in execution.

Fix incorrect logging statement which would throw an exception.

---

parsl/dataflow/dflow.py
parsl/utils.py

Users that have installed pip with `pip install parsl` will continue to
just see the Parsl version. Developers will additionally see the hash of
the last commit and `dirty` or `clean`, depending on if there are
uncommitted changes. Fixes #242.

Describe code state more precisely in the logging

---

parsl/dataflow/rundirs.py

Do not raise a `KeyError` if `globals` is missing

---

docs/devguide/dev_docs.rst
docs/reference.rst
docs/stubs/parsl.dataflow.dflow.DataFlowKernelLoader.rst
docs/userguide/examples/config.py
docs/userguide/examples/library.py
docs/userguide/examples/run_increment.py
docs/userguide/importing.rst
docs/userguide/index.rst
parsl/__init__.py
parsl/app/app.py
parsl/app/app_factory.py
parsl/app/bash_app.py
parsl/app/python_app.py
parsl/dataflow/dflow.py
parsl/dataflow/error.py
parsl/tests/test_threads/test_factory.py

This PR adds a singleton class for loading the DFK which allows for more natural importing of apps. These changes were necessary in order to allow the testing framework to swap DFKs in and out such that we can factorize the testing code and the testing configurations, and cycle through such that each test is run on each configuration. Note it is possible to load a DFK either from a file containing a configuration or from a local DFK instance; I have only documented the latter way in the docstring, trying to keep things simple for now. Here is a preview of the new documentation:

Allow default dfk #50

---

docs/userguide/checkpoints.rst
parsl/utils.py

(not for pushing to master)
The docs previously contained example code that can be pasted, but
as it is non-trivial, it is better placed as a helper function.
This commit also enhances that code to deal with the case where
no checkpoints exist yet - for example, on a first run.
However, this PR does not find all the needed checkpoints, I think, because they are made incrementally, and this will only find the most recent increment (?)

(for discussion) Move boilerplate for last checkpoint into code from docs into helper

---

parsl/tests/conftest.py

This improves the situation for #298. I see far fewer peak ipengine
processes, but still more than I would expect if cleanup was working as
expected after each test.

Call cleanup after each test

---

parsl/dataflow/dflow.py

Prior to this, parsl/tests/test_checkpointing/test_regression_233.py
was failing on benc's laptop fairly regularly - within 10 iterations of
while pytest parsl/tests/test_checkpointing/test_regression_233.py; do echo TICK ; done

Serialise checkpointing with a lock

---

parsl/utils.py

This is confusing. If the version is the vanilla version instead of in
the format '{v}-{head}-{status}', we can assume that the check failed.
There is no need to show the user the traceback, as that makes it appear
like there was a fatal error. Fixes #326 and fixes #327.

Do not log traceback if version check fails

---

parsl/tests/test_staging/test_implicit_staging_ftp.py

Changes ftp server used by the ftp staging test from ftp://ftp.cs.brown.edu which it turned out to be not too reliable to ftp://ftp.iana.org/.

Change test FTP server address

---

parsl/app/bash_app.py
parsl/tests/test_bash_apps/test_basic.py

We had removed code bits that copied all the kwarg defaults from the app_base earlier to fix issues related to complex python objects that cannot be compared. This logic has now been moved to bash_apps.
Test for this behavior included.

Fixes for #349. Adds extra kwarg defaults extraction to bash_app.

---

parsl/config.py

This makes it so that a user that passes the default config will not see
an error message. It adds messages in case a user creates a config with
options which will have no effect. Fixes #379.

Remove confusing error message

---

parsl/data_provider/globus.py

It adds logging.StreamHandler to parsl.data_provider.globus logger with default logging level set to WARN. In effect, error Globus events are printed to stderr. (The log message is still printed to the Parsl log file). Also the following time parameters have been decreased:
- polling the Globus Transfer service for a status of a transfer job (every 15 seconds),
- processing error Globus events (every 60 seconds) and printing them out to stderr and the Parsl log file.

Log error Globus events to stderr

---

parsl/dataflow/strategy.py
requirements.txt

Considering a config with two IPP executors `midway-1` and `midway-2`, this changes the logging line in `strategy.py` from
```
2018-08-14 18:01:26 parsl.dataflow.strategy:260 [DEBUG] Tasks: 0 Slots: 0 Parallelism: 1
2018-08-14 18:01:26 parsl.dataflow.strategy:260 [DEBUG] Tasks: 0 Slots: 0 Parallelism: 1
```
to
```
2018-08-14 18:01:26 parsl.dataflow.strategy:260 [DEBUG]  
executor      active tasks    running blocks    submitting blocks    pending blocks    connected engines
----------  --------------  ----------------  -------------------  ----------------  -------------------
midway-1                 0                 0                    0                 1                    0
midway-2                 0                 0                    0                 1                    0
``` …

Improve strategy logging

---

docs/userguide/data.rst
parsl/tests/configs/local_threads_globus.py
parsl/tests/test_staging/test_implicit_staging_globus.py

It corrects the 'Data management' documentation page where storage_access in an example should be a list instead of a GlobusSchema object.

Fix data.rst - storage_access should be a list

---

parsl/utils.py

THe old `getargspec` did not work as expected on python3.5
and some parsl configs could not be rendered properly,
most urgently at the point that the DFK tries to log the
config that it has been initialised with, preventing use
of those configs on python 3.5

Use more cross-version-compatible `getfullargspec`

---

parsl/dataflow/futures.py

If a callback was added to an AppFuture before it had a parent assigned,
that callback was silently discarded.
This commit changes that so that the callback behaviour is delegated to
the (Future) superclass - similar to how result() processing is so
delegated.

Potential bugfix for add_done_callback on AppFutures

---

parsl/tests/test_error_handling/test_retries.py

These tests pass for me.
This testing is necessary to help validate callback-based dependency management in #583 (which *does not* pass these tests at the moment, if they are enabled there)

Re-enable retry tests

---

parsl/dataflow/dflow.py

Prior to this commit, there were two ways in which a task would be launched,
depending on whether there were dependencies pending when the task was
created or not.
These two ways were similar but not identical.
This commit makes a single `launch_if_ready` method which captures one of those
launch behaviours - the case where a launch had been deferred.
This commit also changes the initial submission to always submit as if
dependencies were pending, and then immediately calls `launch_if_ready`.
This makes the code easier to follow, I think, as tidying up the separation
of creating a non-running task first, and then separately visiting it
to decide if it can be run.
There is a (hopefully minor) increased expense in visiting all of the dependencies
twice to see if they are done, on task …

Factor launch code

---

parsl/data_provider/scheme.py

Simple inheritance change to close #475.

Closes #475. Now printing globus schemes should print nicely.

---

parsl/dataflow/dflow.py

This was my original intended behaviour of #610
A task does not always have an exec_fu, and in some cases in
testing, the final wait was failing rather than waiting,
because it could not find an exec_fu to wait for.

Make DFK shutdown wait for app futures, not exec futures

---

parsl/dataflow/dflow.py

[I probably want to test this in some more depth for a few days before merging]
This PR splits the `handle_update` callback into two separate callbacks: `handle_exec_update` which is intended to run when an executor future is done; and `handle_app_update` which is intended to run when an app future is done.
Inside `handle_update` previously, it was not definitely true that the relevant app future was done (in the `future.done()` sense); but some code potentially assumed that was so (checkpointing and stage out).
Tasks which are related to executor completion (handling retries and completion logging) are handled in `handle_exec_update` and do not rely on either the task `['status']` field or app future being done.
Tasks which are related to app completion (memoization and stage out) are …

Separate exec and app completion code more.

---

parsl/dataflow/dflow.py
parsl/dataflow/futures.py

Exceptions were appearing in strange places with lazyFail=False.
On investigation, two unexpected things were happening. Each of the two commits on this branch fixes one of those things:
* handle_update was throwing an exception in the case on a non-lazy fail, rather than `return`ing. In general, it doesn't make sense for a callback to throw an exception as there is no where for the exception to go. One commit on this branch replaces that explicit raise with a `return`.
EXCEPT:
* if a callback fires straight away when added to a future, and that callback throws an exception, then (sometimes?) the exception propagates to up through add_done_callback call and out into the code containing that. That gives a race condition where sometimes a failing task (if it fails fast enough) will cause an …

Deal with spurious callback exceptions.

---

test-requirements.txt

Readthedocs will now switch to using test-requirements.txt instead of requirements.txt

Adding nbsphinx to test-requirements for readthedocs.

---

parsl/utils.py

Previously, one minute was added, to attempt to deal with
a specific degenerate situation of 0 minutes being specified.
Now, zero minutes will be parsed as 0 minutes, but a warning will
be emitted if the return vales is <1, to nudge the user in the
right direction.

Parse walltime strings to actual number of minutes

---

.travis.yml
parsl/tests/test_bash_apps/test_error_codes.py
parsl/tests/test_bash_apps/test_file_bug_1.py
parsl/tests/test_bash_apps/test_stdout.py
parsl/tests/test_flowcontrol/test_python.py
parsl/tests/test_python_apps/test_basic.py
parsl/tests/test_python_apps/test_outputs.py
parsl/tests/test_regression/test_226.py
parsl/tests/test_sites/test_mpi/test_mpi.py
parsl/tests/test_staging/test_docs_1.py
parsl/tests/test_staging/test_implicit_staging_ftp.py
parsl/tests/test_threads/test_immediate_error.py

The `for` loop in travis.yml affected by this PR was buggy, I think.
Previous to this PR, the loop would terminate silently at the first test that ended with exit code 5, which is `parsl/tests/test_flowcontrol/test_doc_config.py`
I think this is because the value of `$?`, which is compared with the number 5, is not the exit code expected (the pytest exit code), but is the exit code of the last thing executed (which is the command `[[ "$?" != 0 ]]`).
This PR introduces a new named variable to store the desired $? value, and uses that in future comparisons.
It looks like this broke in PR #525.
With that change in place, several tests that are now run fail; this PR puts a skip annotation on those  so that this PR can at least get all the other tests running.

Fix broken test runner

---

parsl/providers/slurm/slurm.py

This PR adds a new KWarg "exclusive" to the SlurmProvider. Htex and Exex assume nodes are exclusive and that assumption is exposed more clearly via setting the default to True.

Adding slurm exclusive kwarg

---

setup.py

Fixes #665 
Please note that python-novaclient required for jetstream is removed from setup since it isn't maintained.

Pip all option

---

parsl/__init__.py
parsl/dataflow/dflow.py

In practice, this turned out to be awkward when, for example, ctrl-C
was pressed and parsl spent a long time waiting (or sometimes hung).
This commit intends that the same wait code is executed explicitly
at the place in the workflow code that the wait is desired (usually
the end). Ctrl-C and other abnormal exits will not cause this wait
to happen.

Remove implicit wait for outstanding tasks at DFK shutdown.

---

parsl/providers/slurm/slurm.py

Without this, SlurmProviders cannot be printed at
startup, with the below exception.
```
...
File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 187, in __repr__
raise AttributeError(template.format(self.__class__.__name__, arg))
AttributeError: class SlurmProvider uses exclusive in the constructor, but does not define it as an attribute
```

Record exclusive parameter for RepresentationMixin

---

parsl/providers/local/local.py
parsl/tests/configs/htex_ad_hoc_cluster.py
parsl/tests/configs/ipp_ad_hoc_cluster.py

The LocalProvider was not generalized enough to work with both the local and ssh channels.
This PR adds support for the LocalProvider + SSHChannel combination allowing users to launch pilots on ad-hoc clusters. There are still issues with cancelling remote workers due to issues with killing nested process trees safely. For now, ipp workers will timeout in a few minutes and cleanup automatically while HTEX workers linger around.
PR also adds example configs.
Fixes #670

Ad hoc cluster #670

---

parsl/data_provider/data_manager.py

@App is deprecated with a warning, which means before this commit, an
App deprecation warning was issued when using staging.

Change file staging to use @python_app decorator

---

parsl/providers/aws/aws.py
parsl/providers/cluster_provider.py
parsl/providers/kubernetes/kube.py
parsl/providers/local/local.py
parsl/providers/provider_base.py

Previously, there was no requirement that an ExecutionProvider have
a label, yet some code assumes there always is a label.
This modifies all providers which are ExecutionProviders to have
such a property (although I have not tested them all).
Some providers in this directory are not ExecutionProviders, and I
have not touched those: googlecloud, jetstream.
This commit also introduces a potential bugfix when using the kubernetes
provider, which did not implement a label property.
This commit makes mypy happy that labels are used properly.

Attempt to enforce the presence of a label on ExecutionProviders

---

parsl/app/bash.py

This means exceptions thrown by bash apps will come back as RemoteExceptionWrapper objects, with benefits such as stack traces.

Wrap bash apps like python apps for remote exception wrapping

---

setup.py

Renames the pip optional extra keyword from parsl-visualize -> visualize
Adds visualize options to "all" keyword

Renaming parsl-visualize to visualize and adding extras to 'all'

---

parsl/channels/ssh/ssh.py

As @josephmoon points out, what was implemented in #686 is not really host-based authentication-- it's a hack to skip auth altogether. This PR clarifies the naming to reflect that.

Change HostAuth -> NoAuth

---

parsl/executors/extreme_scale/executor.py
parsl/executors/high_throughput/executor.py

Before this, process_worker_pool.py was not invoked correctly as
all of the command line parameters were jumbled together without
separators.
I have not tested the mpi_worker part of this commit.

Add necessary spaces into multiline string literals.

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

The current model of manager selection is heavily biased by the dict.keys sorting. The rate at which tasks are received is not much greater that the rate at which tasks could be distributed. So this bias leads to the managers earlier in sorting receiving most (or all) tasks.
This PR adds a random shuffle to give managers a fairer chance at getting sent tasks.
Some sleeps added by mistake from testing are also removed.

Fair task distribution

---

parsl/providers/torque/template.py

I think this line tries to send stdout and stderr to the same file. I'm
not really sure why removing it causes the later specification of the
stdout and stderr lines to be respected, but we don't want them in the
same file in any case. Fixes #647.

Remove line which was preventing stdout redirect

---

parsl/channels/ssh/ssh.py
setup.py

Needed to make this change to get SSHChannel working on a remote cluster with Kerberos/GSS-API authentication.
To test on a system with Kerberos:
python3 -m pip install git+https://github.com/jmoon1506/parsl.git --user
python3 -m pip install python-gssapi --user
kinit

Add GSS-API support

---

.travis.yml
test-requirements.txt

This uses coverage.py to measure test coverage of everything under `parsl/` (including the test suites themselves).
It looks like this bug: https://github.com/spack/spack/issues/6887 in coverage.py is being triggered, which I think is harmless.

Measure test coverage during CI

---

test-requirements.txt

parsl/test/conftest.py looks like it is incompatible
with changes introduced in pytest commit 847eacea which
is released in 4.1.0
That commit incompatibly changes the parameter format for runner.CallInfo

Restrict the versions of pytest

---

.travis.yml

There was previously a bug where this test would fail after a
relatively small number of tasks executed, and so this test
was introduced to CI with a small number of tasks.
This bug was fixed in PR #725, and so a more intensive test can be
run now - this commit makes that change.

Increase the number of tasks in htex CI test

---

parsl/app/app.py
parsl/config.py
parsl/dataflow/dflow.py
parsl/executors/ipp_controller.py

This will introduce a potential behaviour change: previously, `is`
was used to compare strings; now `==` is used to compare strings.
Where the strings have been interned (which I hope has been always),
then the behaviour should be the same; but there are potential cases
(at least abstractly) where `is` was returning false for strings that
were ==-equal, and `is not` was returning true for string that were
==-equal. So if you've bisected a problem back to this commit,
check that out!

Fix changes introduced upgrade to flake8 3.7.1

---

parsl/__init__.py
parsl/executors/high_throughput/interchange.py

Prior to this PR, the interchange inspects every worker registration for every task message received.
This means when allocating n tasks to n workers, this is O(n^2)
In practice with imsim in production this was producing noticeable slowdowns.
This PR changes the behaviour so that a set of interesting workers is maintained, and only interesting workers are inspected when allocating a task. Interesting workers are the workers which have available capacity.
In the imsim work which motivated this PR, there are on the order of 2000 workers, and a larger number of long running (many hour) jobs. Testing and thinking-about should happen for different workloads (for exmaple, the case where workers are starved of work, and when jobs are very short.

Remove some n^2 scaling in interchange

---

parsl/providers/torque/torque.py

Remove wait times from torque provider, thus using the base wait time.
Addresses issue #755

refactor(torque.py): remove explicit time out values for execute_wait

---

parsl/data_provider/globus.py

Prior to this commit, importing this module caused
a write to be made to a user's home directory. In
some cases (see bug #780), a user's home directory
is not always writeable, and in those cases this
module could not be imported at all - instead, it would
throw an exception at import time.
After this commit, such home directory write problems
should appear when attempting to use Globus transfers,
but not otherwise.

Move module level definitions into Globus class.

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/process_worker_pool.py

This gives more useful stack traces on the submit
side.

Use RemoteExceptionWrapper for htex exceptions

---

parsl/data_provider/files.py

This throws an exception for unknown URI schemes
rather than defaulting to the file: behaviour,
to give more resilience when adding new schemes.

Tighten cases of File.filepath()

---

parsl/app/bash.py
parsl/app/errors.py
parsl/tests/test_bash_apps/test_stdout.py

Modes can be specified via a (file,mode) tuple as an alternative
option to a simple filename string.
Default mode remains "a+" for now.  Typical alternative fir simple
file overrwite is ('filename','w')
Also fixes error in exception handling for BadStfFileStream and
MissingOutputs exception.  Problem was that the exception superclass
needs to be initialized withthe same member variables as the
subclassed execption in order for it to pickle correctly in the
"remote" execution context.
Other exceptions have similar issues, but were not corrected, pending
review of the proposed fix.
The app_stdout.py pytest was extended to test the new options, and
corrected to initialize correctly (by not attempting to clear and
reset the dfk, which seemed to causing this test to file.
Note that only the …

Allow alternate modes to be specified for bash app stdout and stderr.

---

parsl/tests/test_bash_apps/test_stdout.py

PR #797 correctly removed the global DFK initialisation, but
should have added a DFK initialisation into the `__main__`
block so that a DFK is available in non-pytest mode. This
commit adds that.
PR #797 also added an incorrect invocation of the parameterised
test_bad_stdout_specs. This commit removes that.

Fix standalone stdout test modified in PR 797

---

parsl/data_provider/data_manager.py

Prior to this patch, if no execute-side working directory is known for a
globus transfer, the client side current directory is used.
This is very likely to be wrong (unless the execute side and client side
are running on the same filesystem, perhaps), so this patch causes an
exception to be raised asking for more explicit configuration rather
than guessing.

Raise an exception rather than use wrong cwd for globus paths (#788)

---

parsl/app/errors.py

This is related to #548, and seems related to the
specific exception class being re-raised - so this
debug information is probably useful to keep around
permanently, to help diagnose the next misbehaving
exception class.

Adding debugging info for issue #785

---

parsl/data_provider/data_manager.py
parsl/dataflow/dflow.py

This is in support of PR #803 which possibly does not support staging using dynamically added executors without this patch.

Remove DataManager's duplicated executor list and get it live from DFK

---

parsl/tests/sites/test_dynamic_executor.py

The test module is imported on the remote side by canning code,
as part of uncanning some lambda expression (I'm not sure
exactly which one).
This was causing a DFK to be loaded on the remote side, because
the DFK was being loaded as a module-level global.
Initialising two DFKs close in time seems to result in a race
condition creating working directories.

Make DFK initialisation not module-global in dynamic executor test

---

parsl/app/futures.py

Prior to this, the superclass Future implementation was given
a result that was inconsistent with the values returned by
(for example) DataFuture custom implementations of result().
This leads to fragility and potential inconsistency about what
a DataFuture's result value actually is.
This change makes that value always be the wrapped File object,
which is the result that the custom implementations attempt to
return.

Set the Future-result of a DataFuture to the correct result

---

.travis.yml
mypy.ini
parsl/app/futures.py
parsl/dataflow/usage_tracking/usage.py
parsl/executors/serialize/canning.py
parsl/executors/serialize/serialize.py
parsl/monitoring/monitoring.py
parsl/tests/configs/user_opts.py
parsl/tests/test_python_apps/test_memoize_2.py
test-requirements.txt

This PR fixes all of the errors that happen when trying to make mypy tests against the configuration and test files; and then makes that check happen in CI.
On my laptop, this additional testing takes 1m25s of realtime.

Make it so mypy can make basic check of codebase

---

parsl/tests/test_staging/test_docs_1.py
parsl/tests/test_staging/test_implicit_staging_ftp.py

PR #693 made the test framework more aggressive about loading DFKs
in test code when the test framework should be loading DFKs.
As cleannet tests are not run in pytest, this breakage was not
discovered by CI: these now-fixed tests are disabled by the
'-k not cleannet' flag to pytest in CI.

Fix cleannet tests broken by PR #693

---

parsl/app/futures.py

Before this commit, set_result changed from being a method to
being a file object in the case that no parent AppFuture was
supplied; fortunately in that case, set_result was never
actually invoked, and the superclass Future result was never
actually used.

Fix incorrect assignment rather than invocation of set_result

---

test-requirements.txt

This broke in CI roughly when pytest-xdist when from around 1.26.1 to 1.28

Pin pytest-xdist as newer versions are incompatible with pinned pytest

---

parsl/executors/high_throughput/interchange.py

The changes in this PR:
1. Remove a duplicate logging line.
2. Change logging level of several lines from `debug` to `info` level, so that they won't slow down the interchange.

remove duplicate logging and change logging levels of few loggings

---

parsl/executors/high_throughput/executor.py

Previously, any exception thrown from the interchange that was not
associated with an identified task was reported as a version mismatch.
That is not the only reason an exception might be thrown.

Broaden error message when interchange error has no task id

---

parsl/dataflow/futures.py

Almost the same output, but with more detail,
comes from asking super() and parent for their
own `__repr__` and concatenating them.
The previous code relied heavily on the parent
state, which is not so directly tied to AppFuture
state nowadays: for example, an AppFuture may
have failed with an exception while the parent
future has returned a successful result of
a `RemoteExceptionWrapper`.
```
<AppFuture super=<AppFuture at 0x7fa7a0d08a20 state=finished raised AppTimeout> parent=<Future at 0x7fa7a0d08cc0 state=finished returned RemoteExceptionWrapper>>
```

Remove most complexity from AppFuture __repr__

---

mypy.ini
parsl/config.py
requirements.txt

After doing some futher work to get runtime type checking on some more common functions (which exists in the `benc-more-type-annotations` branch), I ended up switching to `typeguard`, away from `enforce`, because I was encountering problems with `enforce` on some annotations, and it has a most recent commit much futher in the past than `typeguard`.
The syntax for annotations is unchanged, but the decorator to use is from `typeguard` now.

Switch from `enforce` to `typeguard` as it is more maintained

---

parsl/executors/high_throughput/interchange.py

This PR changes python version check in HTEX interchange from micro to minor level, e.g., now python 3.6.6 is compatible with python 3.6.8.
Fixes #857

Htex python version check #857

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

This is a squashed cherry pick with a few changes removed
in order to just collect the changes related to prefetch capacity.
It is based on the following commits:
75f9d4eca8ec179564768c74b8c5cd67154ea1d8
5a221f2e8ad581b23e4b4b1ec86d3ee02e41e460
c89f3b2def16023bd08360705e923eeb73815013

Add support for configuring prefetch capacity

---

parsl/data_provider/files.py
parsl/dataflow/dflow.py

Prior to this, file objects pretty much just forwarded on
staging requests to the data manager without doing anything
interesting.
This removes that indirection.
It removes some of the need for a file to be associated
with a data manager - something which sits awkwardly with
wanting to reuse Files between DFKs, for example in
interactive notebook use.
Instead, each DFK has a reference to a data manager directly.

Remove indirection of staging via File objects

---

parsl/dataflow/dflow.py

This removes some of the special casing for memoized results - instead result callbacks are handled the same whether the Future comes from execution or memoization.
This is from part of the PR #722 work on callbacks that I'm pulling into separate PRs.

Unify callback paths for execution and memo-based results

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

Support for identifying managers by block_id, and putting managers in a block on hold
Managers are given a block identifier at initialization that is reported back at registration.
This allows the executor to track tasks/worker slots at the block level.
The executor also has a _hold_block() function that puts all managers in a block on hold
preventing further task scheduling, and making it safe to terminate the block.
(cherry picked from commit dc94c0223bccd0159813e8425f787f624790bbae)
Extracted from #826 .

Managers to report block_id on registration

---

parsl/providers/local/local.py

Previously, no state transition happened for completed processes: any
process labelled as RUNNING would not trigger any of the state transitions.
This commit removes the incorrect non-RUNNING restriction on transitions
to COMPLETED or FAILED.
This commit also extends the FAILED transition to happen with any non-zero
return code, not just negative ones: this means that a FAILED transition
should happen when a process exits with a failing return code.
This commit also adds in a error statement when none of these state
transitions fire.
Prior to this commit, some failures to launch would manifest as hangs
waiting for the launched code to start, as the failure would be ignored.
After this commit, those failures to launch result in a COMPLETED
or FAILED state, and so for example the …

Fix state machine in local provider

---

parsl/executors/high_throughput/interchange.py

Issue #898 shows a confusing log message, where a heartbeat
incorrectly logs that HEARTBEAT_CODE tasks have been requested,
in addition to logging a heartbeat.
This commit moves that log into the non-heartbeat path only, so
that exactly one of the heartbeat or task request messages will be
logged.
The phrasing of the heartbeat log message is modified to be in the
same sense as the task request message.

Tidy debug messages around heartbeat/task requests

---

parsl/dataflow/strategy.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/ipp.py

This fix makes the `connected_workers` method return the number of connected workers. Note this is needed to more conveniently debug issues (to be posted shortly) with dynamic slot sizes on Condor with @lgray.

Make `connected_workers` consistent

---

.travis.yml
mypy-stubs/typeguard.pyi
mypy.ini
parsl/dataflow/dflow.py

Introduce mypy stub for typeguard, and type-check parsl.load()
This allows mypy to understand the type signatures of functions
decorated with @typeguard.typechecked, allowing the type signatures
on such functions to be used by both enforce and mypy.
Prior to this commit, adding @typeguard.typechecked removed the ability of mypy to
type-check calls to decorated functions, as it did not understand that
the type of such a decorated function is the same as the original
function. The added stub makes this declaration.
The test-suite mypy calls are modified to use that stub file.
The immediate motivation for this is to keep mypy passing when adding a
type annotation for parsl.load; that type annotation is also added in
this commit.
This commit fixes some of problem described in the commit …

Introduce mypy stub for typeguard, and type-check parsl.load()

---

parsl/data_provider/files.py

This better reflects the position of File as an object which will be
serialised and moved between processes - it does not make sense to have
a data manager reference in that situation.

Remove remaining dman references in File

---

parsl/data_provider/data_manager.py

Previously, the globus staging code attempted to guess
an executor if none was specified. In practice, an executor
always was specified.
This commit removes that unused code path.

Require an executor to be specified for globus staging code

---

parsl/data_provider/files.py

File had a custom de-/serializer to cope with/ignore some fields that were meaningless/wrong to move between processes.
Those fields are gone now, so the custom serialization code is not needed.

Remove File custom serializer

---

parsl/channels/local/local.py

Without changing the permission, parsl cannot submit the job on Theta. Not sure 777 is too aggressive though.

change permission of job submit file, this is needed on theta

---

parsl/dataflow/strategy.py

Currently the strategy does not properly set the maximum blocks. This PR should fix multiple similar issues, e.g., #868, #704

add constraints in strategy to cap the maximum blocks

---

parsl/utils.py

Applying `@typechecked` to a function means that function does not
have the metadata needed for `RepresentationMixin` to work properly.
`@typechecked` uses `functools.update_wrapper()`, which makes the original
undecorated function available as a `__wrapped__` attribute on the
decorated function.
This commit makes `RepresentationMixin` inspect that
`__init__.__wrapped__` function for metadata if it exists, in preference
to the top level `__init__`.
This makes `RepresentationMixin` work properly with `@typechecked`
functions.

Fix RepresentationMixin vs @typechecked

---

parsl/tests/manual_tests/test_worker_count.py

This test was the main cause of travis logs exceeding travis' maximum
log length of 10000 lines, as it outputed roughly 5 lines per task.
This PR leaves the full CI run at about 5000 lines of output.

Reduce verbosity of test_worker_count

---

parsl/dataflow/dflow.py

This prints path to stdout and stderr for failed tasks. Note that this might not be as helpful in situations where there is no shared filesystem. But we have various issues describing that and related problems, and I think it's ok to keep it factorized out. In any case, this is consistent with what is saved in the monitoring DB.

Print path to stdout and stderr for failed tasks

---

README.rst
parsl/executors/extreme_scale/mpi_worker_pool.py
parsl/executors/high_throughput/executor.py

CI testing of the extreme scale executor are reporting the following error non-deterministically. I think I fixed this in htex before (but I can't find that fix), and I think that we're seeing it with exex recently because exex was only recently added into CI (in 7e54e7d842b3821312eb01ab49d2158375a9bca0 on 23rd May).
This PR adds in handling for the case where the deserialised object is an exception, rather than an exception wrapper, and also ports some of the exception wrapping that I put in htex workers into the equivalent MPI worker code.
```
elif 'exception' in msg:
try:
s, _ = deserialize_object(msg['exception'])
try:
>                                   s.reraise()
E                                   AttributeError: 'FileExistsError' object has no attribute 'reraise'
```

Make exex wrap exceptions, and cope with exceptions even when they aren't wrapped

---

parsl/executors/high_throughput/executor.py

* Fixes a typo in executor code, `RemoteExecutionWapper` -> `RemoteExecutionWrapper`
* Adds a missing import

Importing and fixing typo on RemoteExceptionWrapper

---

parsl/executors/high_throughput/executor.py

Truncate long arguments in logs for htex, this was causing logs to explode in size and also become useless.

Prevent htex logs from becoming huge when sending blobs as arguments.

---

parsl/dataflow/dflow.py
parsl/monitoring/visualization/templates/app.html
parsl/monitoring/visualization/templates/dag.html
parsl/monitoring/visualization/templates/resource_usage.html
parsl/monitoring/visualization/templates/task.html
parsl/monitoring/visualization/templates/workflow.html
parsl/monitoring/visualization/templates/workflows_summary.html
parsl/monitoring/visualization/views.py

this PR 
1. converts workflow_duration from `86401.12432s` to `1 day, 00:00:01`
2. trims the microseconds for `workflow_version`
3. displays the datetime object without microseconds on viz server.
fix #979

Fix vis datetime precision #979

---

docs/userguide/monitoring.rst
parsl/monitoring/visualization/app.py

This allows arbitrary IP addresses to be bound for listening, rather
than only allowing a choice between 0.0.0.0 and 127.0.0.1
This fits more in line with how most server software allows listening
address to be chosen (see apache httpd, BIND, postgres).
As a side effect, that also allows the visualization code to listen on
IPv6.
This should fix issue #1023

Change visualization --external to --listen

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py
parsl/monitoring/visualization/models.py
parsl/monitoring/visualization/templates/task.html

Minor fixes for stderr for monitoring
partially for #987
[Discussion?] Issue #987 mentions only `File` type inputs/outputs should be logged. But currently, the monitoring logs any types of inputs, and only the outputs that are already specified when the app is submitted (actually only `str` type as a file path I think).
Do you think the monitoring should be kept in current version right now?

fix stderr for monitoring

---

parsl/dataflow/dflow.py

With these changes, exceptions still happen in the same circumstances
as before (when a user supplies an incorrect executors value to an
app definition) but with better explanations: they are reported as the
type being wrong, rather than some later piece of code breaking.

Better error handling when app 'executors' parameter is wrong

---

parsl/executors/base.py
parsl/executors/swift_t.py

This is needed in the now-less-obscure case of calling scale_in with
named parameters - the base class previously said that scale_in could be
called with (count=1) as a parameter but no subclasses accepted that.
The terminology now pretty much is settled as 'blocks', so that is
what this PR changes everything to.

Make scale_in parameter name consistent in all executor classes

---

parsl/dataflow/memoization.py

The returned value is now a bool as documented,
rather than a different value which can be used
in a bool context.
This shouldn't change behaviour of the code as
used now, but reduces this programmer's confusion
and makes mypy happy.

Make check_memo return its documented type

---

parsl/channels/local/local.py
parsl/providers/condor/condor.py
parsl/providers/error.py

**timeout error**
Before:
```
~/parsl/providers/condor/condor.py in submit(self, command, blocksize, tasks_per_node, job_name)
229         cmd = "condor_submit {0}".format(channel_script_path)
230         retcode, stdout, stderr = super().execute_wait(cmd, 30)
--> 231         logger.debug("Retcode:%s STDOUT:%s STDERR:%s", retcode, stdout.strip(), stderr.strip())
232 
233         job_id = []
AttributeError: 'NoneType' object has no attribute 'strip'
```
After:
```
~/parsl/providers/condor/condor.py in submit(self, command, blocksize, tasks_per_node, job_name)
235             retcode, stdout, stderr = super().execute_wait(cmd)
236         except Exception as e:
--> 237             raise ScaleOutFailed(self.label, str(e))
ScaleOutFailed: Unable to scale out condor provider: Command …
```

Fix muted condor #1059

---

parsl/monitoring/monitoring.py
requirements.txt

The import location for AccessDenied has changed in psutil.
This commit uses the latest location, and requires psutil to
be at least the version that introduced that new location.
This was discovered as part of the investigations for
issue #1069

Track psutil API changes for AccessDenied exception

---

parsl/providers/kubernetes/kube.py

Channels are not required, but where a `channel` attribute is provided, it should actually be a `Channel`. This was not the case.

Remove unused channel-related code from kubernetes provider

---

parsl/executors/extreme_scale/mpi_worker_pool.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

This PR is a small part of PR #1024 . This includes:
1. rename `hname` to `hostname`
2. Add `reg_time` to manager registration message -- this specifically refers to the time on the manager node, but not the interchange node. I have seen the times on manager node and on interchange node have huge difference (e.g., on Theta). We need the manager-side time to infer the resource efficiency plot, as all the info like resource usage is collected on managers.
3. Add `cpu_count` and `total_memory` to registration message in HTEX.

add reg_time, cpu and memory, rename hostname in manager registration msg

---

parsl/monitoring/monitoring.py

In use with setuid children (such as singularity containers), permission
exceptions are thrown that are different to the psutil.AccessDenied
already caught.

Broaden scope of caught exceptions in IO counter handling, and log them

---

parsl/monitoring/monitoring.py

Global `logging` is used because UDPRadio() is used inisde
monitor() which uses global logging, not a specific `logger`.

Change UDPRadio prints to global logs

---

parsl/monitoring/visualization/plots/default/workflow_plots.py
parsl/monitoring/visualization/views.py

This PR is part of the big PR #1024, which mainly improves the layout of the first `task_gantt` plot.
1. Remove useless `print`
2. Change y axis -- not showing task IDs on y axis in case there are too many tasks and texts overlap, instead task ID is shown in hover text.
3. Minor correction of time.

Task gantt plot improvement

---

parsl/channels/ssh/ssh.py

This would result in the wrong exception being raised in this
error-handling path.

Fix incorrect variable name in error handling

---

parsl/app/bash.py

In some cases, this message wasn't being sent to stderr
before the stderr of the spawned executable, meaning the
executable diagnostic information appeared at the end,
rather than start, of the logged stderr.
This added flush should provide the necessary sequencing
to ensure the message appears before the stderr of the
spawned process.
See issue #1008

Flush stderr after printing executable diagnostic

---

parsl/providers/aws/template.py

Addresses #1094 
- set DEBIAN_FRONTEND to noninteractive in aws template.py to prevent apt-get from starting interactive prompts

Make aws template use non-interactive apt-get

---

parsl/monitoring/db_manager.py

This PR is to partially address @TomGlanzman 's suggestion for monitoring when `retries` mechanism is enabled, including
1. Fix bug in monitoring for retries.
2. Add `task_fail_count` column to TASK table. It logs the number of task failures for a task. This is useful when `retries` mechanism is enabled.
3. Add `hostname` column to STATUS table. For each trial of a task, it logs the `hostname` of the node where the task run on.
I will make a separate PR to add the `task_fail_history` to TASK table that logs all history exceptions.

fix monitoring for retries, add hostname, task_fail_count to monitoring

---

parsl/monitoring/db_manager.py

When a task is written to the DB which has not been submitted, then
prior to this commit, a database integrity error was raised, as the
database required a task to have a submit time.
This manifests in #1100 where unsubmitted tasks are written out to
the monitoring DB at the point that a workflow fails.
I haven't checked if this introduces a new failure mode for visualisation, where the visualisation code will now be sometimes presented with tasks that have no submit time.

Allow monitoring db task_time_submitted to be NULL

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py

As @TomGlanzman suggested, we should log the exception for each retry of a task to monitoring.
This PR adds the exceptions to `monitoring.db` as a column, in the format of `exception 1; exception 2; exception 3 ...`
Related to #1104 .
Fix #1105 .

Catch exception for retries in monitoring

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/monitoring/db_manager.py
parsl/monitoring/message_type.py
parsl/monitoring/monitoring.py
parsl/tests/manual_tests/test_fan_in_out_htex_remote.py

This PR is a major breaking down of PR #1024 . It tries to add a node table to monitoring.db, which logs the node information including resource capacity, reg_time, python version, etc.
1. The node info is first collected by the interchange.
2. The interchange send data to the Hub (then send to db_manager). The db_manager logs all the data then.
To allow interchange to connect to the Hub, we need dfk to pass the hub address and hub port to executor and interchange.

Add node resource monitoring

---

.flake8
parsl/executors/high_throughput/process_worker_pool.py
parsl/launchers/__init__.py
parsl/tests/integration/latency.py
parsl/tests/integration/test_channels/test_ssh_errors.py

Where two functions with the same name are defined differently, the second
one is used as that seems to reflect how python actually does things.

Fix flake8 F811 violations and remove F811 exemption

---

.flake8
parsl/app/futures.py
parsl/channels/local/local.py
parsl/channels/ssh/ssh.py
parsl/dataflow/dflow.py
parsl/executors/extreme_scale/executor.py
parsl/executors/high_throughput/executor.py
parsl/executors/ipp.py
parsl/executors/ipp_controller.py
parsl/executors/low_latency/executor.py
parsl/monitoring/visualization/views.py
parsl/providers/kubernetes/kube.py
parsl/tests/configs/local_threads_monitoring.py
parsl/tests/integration/test_apps/HEDM_processlayer/process_layer.py
parsl/tests/integration/test_apps/vasp/vasp_example.py
parsl/tests/integration/test_channels/test_ssh_errors.py
parsl/tests/integration/test_early_attach_bug.py
parsl/tests/integration/test_monitoring_config.py
parsl/tests/integration/test_parsl_load_default_config.py
parsl/tests/integration/test_stress/test_bash_apps.py
parsl/tests/integration/test_stress/test_python_ipp.py
parsl/tests/integration/test_stress/test_python_simple.py
parsl/tests/integration/test_stress/test_python_threads.py
parsl/tests/manual_tests/test_udp_simple.py
parsl/tests/test_swift.py

When a source file contains an `import *`, flake8 cannot
check that source file for use of symbols which are
not defined.
This commit also fixes some problems that were covered
over by the F403 exemption.
A couple of files have other problems which can have a
tighter per-file exemption applied.

Remove flake8 exemption for F403 undefined name detection

---

docs/userguide/apps.rst
parsl/app/app.py
parsl/app/python.py
parsl/tests/test_error_handling/test_python_walltime.py

This PR adds python app time limits. As noted in #1118, there is currently a 'walltime' keyword arg to both the python and bash app decorators and classes-- all of which do nothing. I chose to match what is currently implemented for bash apps-- a reserved `walltime` keyword arg to the app. I'll remove the unused args in a separate PR.

Add Python app time limits.

---

.flake8
parsl/providers/aws/template.py
parsl/tests/test_error_handling/test_rand_fail.py
parsl/tests/test_python_apps/test_rand_fail.py

The violations were all in commented out / docstring text.
This commit removes dead code to fix one violation, and
changes a literal string into #-comments, which may use
\ symbols without them forming an escape.

Remove violations of flake8 W605 (invalid escape sequences)

---

parsl/providers/aws/aws.py

Before this patch, the provider would initialize and then later fail when
attempting to allocate a resource, with:
2019-07-10 23:02:00 parsl.providers.aws.aws:495 [ERROR]  Request for EC2 resources failed : Parameter validation failed:
Invalid type for parameter KeyName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
After this patch, the initializer will fail when intializing the
AWSProvider, before the DFK is even loaded, and with an error message
that better reflects the missing mandatory parameter.

Rearrange AWS initializer params to reflect that key_name is mandatory

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

A small PR breaking down from #1024.
1. Using `dataframe`'s built-in `max()` method
2. Break a loop earlier for speed

minor code enhancement in workflow_resource_plot

---

.gitignore
mypy.ini
parsl/tests/configs/user_opts.py

This is intended to facilitate putting secrets into a
user configuration file while reducing the chances of
those secrets being published as part of version
control history

Add non-version-controlled user opts override

---

parsl/providers/aws/aws.py

Previous to this commit: if the boto client initialization
throws an exception, then the exception handling of that
throws another exception from __repr__() from
RepresentationMixin, as it cannot list out all of the
initializer fields.
This commit moves self.statefile to earlier in the
initializer, before the above boto client initialization.

Move AWS self.state_file to make RepresentationMixin happier

---

parsl/data_provider/data_manager.py

A data manager always belongs to a DFK, and there can be multiple
DFKs in existence - so the notion of getting a data manager globally
outside the context of a specific DFK does not make sense.
The last call to this was removed in PR #885 (b7c14695)

Remove get_data_manager and the concept of a global data manager

---

parsl/app/futures.py

No need for super() - invoking set_result or set_exception
on self will pick the correct method.
No need to check if parent future is done in done callback.

Minor tidying to DataFuture result handling

---

parsl/tests/configs/ec2_single_node.py
parsl/tests/sites/test_ec2.py

Awkwardnesses:
i) `template.py` needs to be adjusted to install the same version of parsl as is being submitted from, rather than whatever the most recent release is - as needs to happen with any non-trivial development version of parsl submitting to EC2.
ii) This will not run inside pytest - as with a bunch of other tests, some apps run inside pytest cause more modules to be loaded than run outside pytest, the reason for which I don't understand. In this case, that means the workers try to import the test script, which causes several problems - at least, that `PARSL_TESTING` is not installed, that the test-requirements dependency stack is not installed, that `user_opts` is not set correctly on the remote side.
Nevertheless, this is maybe worth merging to master as being better than not …

Add a site test for ec2

---

parsl/tests/test_error_handling/test_fail.py

I can't find where this is explicitly tested in the test suite at the moment, but maybe it is already?

Test that exceptions from apps are delivered to caller

---

parsl/executors/workqueue/executor.py
parsl/executors/workqueue/workqueue_worker.py
parsl/tests/workqueue_tests/test_scale.py
parsl/tests/workqueue_tests/wqex_local.py

This pull request makes many small changes to the `parsl/executors/workqueue/executor.py` and `parsl/executors/workqueue/workqueue_worker.py` script. These changes changes primarily deal with adding additional commenting and more verbose logging messages to help better describe the script. It additionally adds error messages to handle more Work Queue system failures, which were previously  not handled.
This PR contains all the tidyup changes that were originally submitted in PR #1152. If these changes are merged, then PR #1152 should only contain feature changes, i.e., changes that affect the serialization and deserialization of the Python functions and exceptions.

Work Queue Executor Tidy Up Changes

---

parsl/channels/oauth_ssh/oauth_ssh.py

This avoids this error when custom port is set:
AttributeError: class OAuthSSHChannel uses port in the constructor, but does not define it as an attribute

Set optional port as proper Channel attribute.

---

parsl/tests/test_python_apps/test_basic.py

This was disabled in #652 because it was failing. It doesn't fail for me now on my laptop, and it gives a bit more coverage of exception handling.

Re-enable disabled exception handling test

---

.travis.yml
test-requirements.txt

This attempts to reduce the optional dependencies installed before the majority of tests, and installs those dependencies later on only for mechanism-specific testing.
This addresses a problem encountered a few times in CI, where missing dependencies  in the core `requirements.txt` were not discovered because of the more exciting dependency options installed in CI.

Re-order extreme scale and workqueue for better dependency validation

---

parsl/launchers/launchers.py

This will affect parsl users who have implemented their own launcher.
Addresses part 2/2 of #1176

Remove unused walltime parameter from launcher API

---

parsl/executors/high_throughput/executor.py
parsl/executors/ipp.py
parsl/executors/low_latency/executor.py
parsl/providers/aws/aws.py
parsl/providers/azure/azure.py
parsl/providers/cluster_provider.py
parsl/providers/cobalt/cobalt.py
parsl/providers/condor/condor.py
parsl/providers/googlecloud/googlecloud.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/kubernetes/kube.py
parsl/providers/local/local.py
parsl/providers/pbspro/pbspro.py
parsl/providers/provider_base.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

This API change will affect parsl users who have implemented their own providers.
Addresses part 1/2 of #1176
Method:
I've been through all of the providers grepping for 'blocksize', and removed
the code that uses those. Generally it didn't do much.
The docstrings of those providers are a bit weird and I haven't attempted to
rewrite them - instead I have just removed blocksize references, replacing/folding
in a constant '1' in where necessary.
I've also gone through the whole codebase using
`git grep -C 3 provider.submit`
to find hopefully all of the places where a provider submit call is made,
and removed the blocksize parameter from those.
Two tests make provider.submit calls, but look like they are very dated
as they use dictionary based parsl configs, not class based configs:
``` …
```

Removes barely used/implemented blocksize parameter from provider.submit API

---

parsl/executors/workqueue/executor.py

In some situations that I've encountered (working on PR#1181),
t.output is None and so error reporting breaks with:
```
...
File "/home/benc/parsl/src/parsl/parsl/executors/workqueue/executor.py", line 244, in WorkQueueSubmitThread
reason += "\nTrace:\n" + t.output
TypeError: Can't convert 'NoneType' object to str implicitly
```
This PR also logs the numerical value of WQ task return status when it does not have a corresponding text description.
When the above error happens, apps hang rather than return an error. With this PR applied, those apps fail rather than hang.

Improve wrapper script error handling for workqueue

---

parsl/dataflow/dflow.py
parsl/dataflow/futures.py

Prior to this, AppFuture properties were copies provided at construction time,
which was fragile in the presence of these properties being modified - specifically,
the handling of parsl.AUTO_LOGNAME.
This PR makes the task_def structure the only place where these values
live, and makes the corresponding AppFuture properties a view into that
task_def structure.

Make AppFuture task-related properties be view of task_def struct

---

parsl/data_provider/data_manager.py
parsl/data_provider/globus.py
parsl/dataflow/dflow.py
parsl/dataflow/futures.py

This facilitates a few things which will appear in future PRs:
* pluggable app replacement stage-out, where the submitted app
task needs to know about stage outs at the time that it is submitted,
rather than the DFK managing this separately after the task
has completed.
* a fix for issue #778, so that DataFutures completion can
indicate successful stageout
* a fix for issue #1173, where the stage-out code must be given a chance
to set the localpath on a File before the main app task runs
Stage out tasks cannot run immediately upon submission now, as they are
submitted before their corresponding main task has completed. This PR
adds an extra parameter to stage out tasks to allow them to depend on the
main task.
That extra dependency means that stageout tasks depend on a task (the main …

Move output staging task submission to before task launch

---

parsl/data_provider/data_manager.py
parsl/data_provider/globus.py

This makes Globus stageout localpath behaviour the same as stagein behaviour:
if staging will be happening to some non-default working directory, then
localpath will be set to point to that actual location of staging.
Because stageout completion is not tested at the moment, the behavioural change is:
Before this PR, if user_opts['globus']['path'] is not equal to the current working directory:
globus stageout test would complete with a successful exit code before
stageout happens (see issue #778); but a transfer job would be left in globus
stalled with a file-not-found error (forever, or at least for a day)
After this PR: globus stageout test will complete with a successful exit code before
stageout happens; a globus transfer job will be made and this will successfully
stage out the file. …

Give Globus stageout code the chance to set File.localpath

---

.flake8

I think this became unnecessary after the fixes in #1117 which removed F403

Remove unnecessary flake8 F405

---

parsl/data_provider/data_manager.py
parsl/data_provider/ftp.py
parsl/data_provider/globus.py
parsl/data_provider/http.py
parsl/dataflow/dflow.py

Prior to this PR, DataFutures were treated, dependency-wise, like
any other input value, and did not cause any deferral of execution.
This meant that output DataFutures from one app passed as inputs
to a second app would not cause the second app to wait for the
first app to complete.
Fixes issue #1125

Treat DataFuture inputs as dependencies

---

README.rst

The static tutorial was removed in PR #429.
The live tutorial has moved.

Update tutorial links in README

---

parsl/dataflow/futures.py

The behaviour shouldn't change over this commit as the self methods should
be the same as the super methods at present, but super() calls
should be avoided unless something specific is being done with inheritence.

Replace super references with self references in AppFuture

---

parsl/app/bash.py
parsl/app/python.py
parsl/dataflow/dflow.py

Prior to this, DataFutures were marked as complete when the main app
task completed, prior to any staging happening.
This meant that DataFutures completing were not an indication that
Globus stage-out had completed (or even been started).
This commit causes DataFutures to complete when the relevant
staging task has completed.
Prior to this commit, DataFutures were created by bash/python
app decorators. This commit creates the DataFutures as part
of stageout setup.
When stageout is inhibited, we still need to create the
DataFutures; in such case, a DataFuture will be marked as complete
as soon as its app future is complete (the existing behaviour).
The key difference here is that the call to 
> self.data_manager.stage_out(f, executor, app_fu)
can now return a future, rather than not …

Make DataFutures complete after stageout (issue #778)

---

parsl/data_provider/data_manager.py

Remove doctring for executor parameter which was removed in PR #805, commit
66b423066b199296bd9ba0d19ece22bd73192470
Remove data manager globus reference, which was moved into GlobusScheme in PR #1165, commit
73c1909d95f2a0ab2062002745421bdc0fc8e0d873c1909d95f2a0ab2062002745421bdc0fc8e0d8

Remove outdated bits from data manager initialization

---

parsl/app/futures.py

There might be better phrasing for the warning text, as likely a user will encounter this when using `outputs=[]` as they should not be constructing DataFutures themselves.
This manifests in the test suite when app outputs are specified with strings
rather than File objects; and for those strings, File objects are constructed.
However:
* these Files are not staged out properly according to staging rules;
* the behaviour of strings on inputs is to be passed through unmodified to
apps, rather than being wrapped as files.
The longer term behaviour should be to remove this special casing, but it will
break user code that relies on specifying local unstaged files as strings.

Add a deprecation warning when DataFutures are constructed with strings

---

docs/reference.rst
docs/stubs/parsl.data_provider.staging.Staging.rst
docs/userguide/data.rst
parsl/configs/local_threads_globus.py
parsl/configs/stampede2_htex_multinode.py
parsl/data_provider/data_manager.py
parsl/data_provider/file_noop.py
parsl/data_provider/files.py
parsl/data_provider/ftp.py
parsl/data_provider/globus.py
parsl/data_provider/http.py
parsl/data_provider/staging.py
parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/ipp.py
parsl/executors/swift_t.py
parsl/executors/threads.py
parsl/tests/configs/local_threads_globus.py

Instead of dispatching inside the DFK explicitly based on a
hard-coded map between URI schemes and staging implementations,
go through each staging scheme in sequence, giving that scheme the chance
to handle staging
The concept of 'is_remote' being a property of files defined
by the URL scheme is also superceded by this, and so
is_remote is removed. For behaviour of "file:" URLs to mean
'no staging', then a no-op staging scheme is implemented
in this PR. Other  staging providers can implement different
semantics for `file:` URLs.
There's a user-facing API change here: if a configuration specifies
`storage_access=[]` rather than omitting it or specifying `storage_access=None`,
then the default staging mechanisms will be removed and
even no-op file access won't work; and the way to …

Implement file staging provider API

---

parsl/tests/test_python_apps/test_arg_input_types.py

This behaviour has been much debated, but the consensus on
expected existing behaviour is that any object can be passed into
inputs=[], and that if it is not a File, it should be passed
through unmodified to the app code.

Add a test that checks that inputs=[] can take a variety of types

---

.travis.yml

In testing on my laptop, this takes the mypy step of CI from 48 seconds to 0.9 seconds.

Use faster mypy invocations in CI

---

parsl/executors/extreme_scale/executor.py

Prior to this commit, attempting to construct a Config involving
the extreme scale executor would fail if mpi4py was not installed
with an exception message informing the user about that requirement.
After this commit, that exception will be thrown later, at the point
that a user attempt to load a DFK with that config.
This allows unused extreme scale executor configs to be imported
safely - most immediately, for test rearrangements in PR #1210

Move extreme scale executor mpi4py import requirement into start

---

parsl/tests/test_data/test_file_ipp.py

Previously this test could not be run on a pristine checkout on its
own; it relied on a previous execution of a test with the setup_data
annotation (in CI, parsl/tests/test_data/test_file_apps.py) to pass.

Add missing setup_data annotation to test that uses data/

---

.travis.yml
parsl/tests/conftest.py
parsl/tests/integration/test_apps/HEDM_processlayer/process_layer.py
parsl/tests/integration/test_channels/test_channels.py
parsl/tests/integration/test_channels/test_scp_1.py
parsl/tests/integration/test_channels/test_ssh_1.py
parsl/tests/integration/test_channels/test_ssh_errors.py
parsl/tests/integration/test_channels/test_ssh_file_transport.py
parsl/tests/integration/test_channels/test_ssh_interactive.py
parsl/tests/integration/test_early_attach_bug.py
parsl/tests/integration/test_parsl_load_default_config.py
parsl/tests/integration/test_retries.py
parsl/tests/integration/test_stress/test_python_ipp.py
parsl/tests/integration/test_stress/test_python_simple.py
parsl/tests/integration/test_stress/test_python_threads.py
parsl/tests/manual_tests/test_basic.py
parsl/tests/manual_tests/test_memory_limits.py
parsl/tests/manual_tests/test_oauth_ssh.py
parsl/tests/manual_tests/test_worker_count.py
parsl/tests/pytest.ini
parsl/tests/sites/test_ec2.py
parsl/tests/workqueue_tests/test_scale.py

This leaves the marker implementation in case it is needed in the
future, but removes its use in favor of implementing a
`pytest_ignore_collect` function in `conftest.py`. The advantage of this
is it removes the need to append each pytest invocation with `-k not
noci`, which is needed by definition. The disadvantage is that, since we
mix pytest and non-pytest tests in the testing directory, this
obfuscates which tests will be ignored by pytest.

Remove use of 'noci' pytest marker

---

parsl/providers/cobalt/cobalt.py
parsl/providers/condor/condor.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

This shouldn't change parsl behaviour when using the providers directly, but
would affect any subclasses which attempt override the affected methods. (I am not
aware of any such subclasses)
Prior to this commit, subclasses could not override the affected methods.
Now they can.
This commit is more about tidying away unnecessarily complicated uses of
super() from the codebase, rather than fixing an immediate bug.
It looks like the many references to super() came from copy-paste of some
original code.

Remove calls to super() which probably should be self, in providers/

---

parsl/app/app.py

If this message fires, the user should be aware that it is happening
in more than debug level logging

Elevate a warning message about appcaching to warning level

---

parsl/dataflow/dflow.py
parsl/dataflow/flow_control.py
parsl/dataflow/usage_tracking/usage.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/utils.py

Prior to this, the threads touched in this PR were named with
sequential numbers.
Thread exceptions will now look like this:
```
Exception in thread FlowControl-Thread:
```

Give processes/threads human readable names to aid debugging

---

parsl/dataflow/flow_control.py

Prior to this, exceptions raised by the flow control
callback caused the flow control thread to die.
After this, exceptions raised by the flow control
callback are logged with a stack trace, but flow
control continues.

Catch and log errors in flow control callback

---

parsl/executors/high_throughput/executor.py

Setting the daemon flag causes a process which has encountered some
error condition such as a provider timeout to exit rather than hang.
I think what was going on before was that the interchange would not
shut down, so no atexit behaviour would fire that would cause the
interchange to shut down.
It is, I think, more proper that the interchange be killed at
process shutdown.
In a test on cori using a cmd_timeout deliberately set low to 2
seconds, using LocalChannel and HighThroughputExecutor, runs go
from hanging 4 out of 5 tests, to hanging 0 out of 5 tests.

Flag interchange process as daemon to reduce shutdown hangs

---

docs/userguide/apps.rst
parsl/tests/test_bash_apps/test_error_codes.py

This PR changes the user guide to describe the actual behaviour of the code wrt bash_app unix exit codes.
Two previously broken tests are fixed to test that behaviour.
Fixes issue #802

Fix userguide and test for @bash_app exit codes

---

parsl/providers/cluster_provider.py

ExecutionProvider has submit and cancel methods which are labelled
as @abstractmethods.  Prior to this PR, ClusterProvider implemented
those with stubs that always failed; this removes some of the
benefit of using @abstractmethods. This PR removes those stubs, so
that ABC behaviour will still happen for those methods.
ClusterProvider introduces a new method which must be overridden
by subclasses, _submit. As with submit and cancel, this was implemented
as a non-functioning stub. This PR replaces that with an
`@abstractmethod`.

Tidy cluster provider 'abstract base class' behaviour

---

.travis.yml

Previously, mypy only checked main parsl code which was imported
through any of the tests or test configs. This PR extends that to
any code in any of the enumerated main parsl code directories.
Not all of the parsl source tree passes mypy at the moment, which
is why there is an explicity whitelist of directories, rather than
a single `mypy parsl/`.
Notably, the following directories do not pass `mypy` checking at
the moment and are excluded from the list:
parsl/executors/
parsl/configs/
as well as the remaining parts of:
parsl/test/
that are not already checked.
This PR does not attempt to fix up any of the mypy problems in
those directories.

Extend mypy checking to more of the codebase

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py

This was a bad use (IMO) of __del__ and frequently threw
exceptions at python shutdown.
Fixes #1044

Remove use of __del__ in monitoring

---

parsl/dataflow/dflow.py

I think this broke in PR #1183
This causes workflows that attempt to recording monitoring information to hang instead.

Fix bad reference in monitoring to internal AppFuture tid

---

parsl/data_provider/data_manager.py
parsl/dataflow/dflow.py

This is intended to support a later PR which will attempt to address #1197
by duplicating File objects inside the newly refactored function.
This present PR, however, should not change behaviour.

Rearrange stage-in to facilitate upcoming duplication of Files

---

parsl/tests/test_bash_apps/test_pipeline.py

In practice, the presence of working files from previous runs
has made this test pass incorrectly.

Make pipeline test delete its working files before and after

---

parsl/dataflow/dflow.py

Callbacks on executor futures are executed in the order
they were added, so PR1200 should properly have made the
AppFuture callback at the end, rather than at the start,
of DFK executor callback processing.
This PR restores that order.
The new (and original) order means that the DFK will
record jobs as finished before setting the AppFuture,
which in turn means that the DFK will record jobs as
finished before the main workflow becomes aware of
the AppFuture completing, which further in turn means
that the DFK will have done that recording before
the main workflow falls of the end and exits.
The different there seems to be that in the 
post-PR1200 pre-this-PR case, workflows end with tasks
not recorded as finished:
2019-09-09 08:19:26.454 parsl.dataflow.dflow:747 [INFO]  Summary of tasks in …

Restore PR1200 executor future callback order

---

parsl/tests/sites/test_local_ipp_multisite.py

This test should run. If it doesn't, parsl needs fixing...

Re-enable ipp multisite test previously skipped for being broken

---

parsl/tests/test_checkpointing/test_task_exit.py
parsl/utils.py

* Fix incorrect attribute name for DFK run directory
* Fix time_limited_open incorrectly using wait_for_file context manager
* Add some notes on race conditions
* Re-enable test

Fixup checkpoint 'task_exit' test

---

parsl/tests/test_bash_apps/test_memoize.py
parsl/tests/test_python_apps/test_memoize_1.py

* Remove use of sleep:
* Remove a likely race condition coming from using sleep
* Removing use of sleep makes this test fail faster
* Assertions are based on the expected errors, not based on
timing
* Move into own file in bash directory - this is not a test of
python_apps, as the previous location implied.

Fixup and re-enable bash memoization test

---

parsl/app/futures.py
parsl/data_provider/data_manager.py
parsl/data_provider/files.py
parsl/data_provider/ftp.py
parsl/data_provider/globus.py
parsl/data_provider/http.py
parsl/dataflow/dflow.py
parsl/tests/test_bash_apps/test_pipeline.py
parsl/tests/test_staging/test_implicit_staging_globus.py

This addresses issue #1197
Prior to this PR, File objects were shared or not-shared between
different pieces of parsl code based on the nature of the
executor.
For example, modifying a File object inside a stage-in task
running in the local thread executor would modify the original
File object passed into the app (because the thread executor passes
around the original object), but modifying a File object inside
a stage-in task running in the htex executor would not modify
the original File object, as File objects are copied (implicitly
by serialization of app arguments).
Also, the local_path attribute which was sometimes set to provide
an execution-side filesystem path did not always propagate properly.
This was generally disguised by the presence of a vestigial
enumeration of …

Make explicit copies of File objects per execution

---

parsl/providers/condor/condor.py

Add resource hints for Condor provider

---

parsl/executors/high_throughput/errors.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/configs/htex_local.py
parsl/tests/test_error_handling/test_htex_worker_failure.py

This commit makes two main changes:
1) A shared dictionary is added which the workers can access. They now
put their in-progress tasks there.
2) A worker watchdog thread is added which monitors the worker
processes. If it finds a dead worker, it checks for any in-progress
tasks in the shared dictionary and sends it back to the DFK with a
WorkerLost error, and restarts the worker.
Fixes #1245.

Add a worker watchdog thread

---

parsl/tests/test_checkpointing/test_regression_233.py

The test previously made the incorrect assumption that
future.result() returning meant that the checkpoint for
the corresponding app had been written out.
The assumption made by the test after this commit is:
If future.result() has returned, and then *after that*
dfk.cleanup() has been invoked and returned, then
the checkpoint for the corresponding app has been
written out.
This test was previously skipped because of this race
condition, but is re-enabled in this PR.

Fix race condition in checkpoint test (issue #681)

---

.travis.yml
CONTRIBUTING.rst
parsl/tests/__init__.py
parsl/tests/integration/test_apps/__init__.py
parsl/tests/integration/test_stress/__init__.py
parsl/tests/pytest.ini
parsl/tests/sites/__init__.py
parsl/tests/test_checkpointing/__init__.py
parsl/tests/test_data/__init__.py
parsl/tests/test_error_handling/__init__.py
parsl/tests/test_flowcontrol/__init__.py

This commit removes most of PARSL_TESTING environment handling from the
test suite in order to make pytests easier to run. Since usage tracking
became opt-in, there has been less need for this environment variable.
The reporting of PARSL_TESTING in usage tracking code is left in place.

Remove PARSL_TESTING requirement from test suite

---

parsl/executors/high_throughput/executor.py

@typeguard forces provider to be not-None at the moment
so these if statements always take the true path.

Remove provider=None codepaths

---

parsl/executors/extreme_scale/executor.py
parsl/executors/high_throughput/executor.py
parsl/executors/ipp.py
parsl/executors/low_latency/executor.py
parsl/providers/aws/aws.py
parsl/providers/azure/azure.py
parsl/providers/cluster_provider.py
parsl/providers/condor/condor.py
parsl/providers/googlecloud/googlecloud.py
parsl/providers/kubernetes/kube.py
parsl/providers/local/local.py
parsl/providers/provider_base.py

This code path is not used, and providers have a more nuanced
ability to control their own scaling, because they are allowed
to not launch a block when asked.
This does not remove the ability for executors (rather
than providers) to be marked as scalable or not. Executors which
previously sometimes inherited their scalability from their
provider now also report themselves as scalable when given a
provider.
Fixes #1304

Remove ability for providers to be not-scalable

---

parsl/tests/test_bash_apps/test_pipeline.py

In some cases when developing staging providers, the pipeline
test fails due to a buggy provider, but giving an error that is
not immediately clear - rather than indicating that an input
file is missing, the test instead starts counting from 0 again.
This patch adds in an explicit test for expected input files to
aid in detecting that particular failure mode.
This patch also adds checks to ensure that returned outputs are
DataFutures - this catches the case that file stage-out code is
incorrectly returning a File rather than DataFuture for that
File.

Tighten pipeline tests to assert more.

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py
parsl/monitoring/visualization/templates/resource_usage.html
parsl/monitoring/visualization/views.py

This PR adds a worker efficiency plot to the resource page of workflow.
The worker efficiency is computed by `total_running_tasks/total_workers`.
`total_running_tasks` is to count the total number of running tasks every one second (by checking if the `task_time_running` and `task_time_returned` include that timestamp).
`total_workers` is computed by adding up the `worker_count` in the `node` table (current assumption is that there is no scaling. If we want to have scaling, we need to add more info to the `node` table)

Add worker plot monitoring #1278

---

parsl/utils.py

Fixes #1124
Two issues are fixed:
When there are no defaults, None is used instead of an empty tuple,
which breaks the zip of args and defaults.
When defaults is an empty dict, the sub-section of the args list
is taken with -0, which does not have the intended effect of dropping
no args. This is replaced with a special case `if`.

Make RepresentationMixin work on classes with no default initializer args

---

parsl/dataflow/dflow.py

Prior to this, staging providers were given the opportunity to
replace the app function with a staging wrapper for stageout,
but that staging wrapper was then discarded.

Pay attention to function substitution done by output staging

---

parsl/data_provider/globus.py

Current globus transfer error checking mechanism assumes  `task_event_list()` to return non-empty iterable and fails it is it empty. If the transfer is still running, then function call `task_event_list(task['task_id'], num_results=1, filter='is_error:1')` returns empty list and causes the code to fail in the next line when it attempts to access the first element of the result from the function `event = events.data[0]`. This change checks `events` and continues if the result is None
Fixes #1170 and #1317 by checking the size of globus event
list before accessing the first element since it can be empty

Prevent globus transfers to fail after 60 seconds 

---

parsl/dataflow/dflow.py

This is a bit broken because it assumes Futures have parsl specific
properties.
The code path removed is not used - similar functionality comes
from _count_deps instead.

Remove unused (and a bit broken) codepath from gather_all_deps

---

.travis.yml

Adds Python 3.7 to the Travis matrix (Python 3.8 is due out soon). Unlikely to cause feature conflicts due to your upgrade cycle, but they do occasional make tweaks to `concurrent.futures`.

Adds Python 3.7 testing

---

docs/devguide/dev_docs.rst

In the API reference to the ExtremeScaleExecutor it accidentally referenced the HighThroughputExecutor resulting in the former actually being missing.

Fixed reference to ExtremeScaleExecutor in docs.

---

parsl/config.py
parsl/dataflow/dflow.py

The use case for this is when parsl is used as a library
as part of a bigger system which wants to configure logging
in a way that makes sense for that bigger system as a whole.
In such a situation, parsl should step out of the way
and let that system do what it wants.

Make DFK optionally not initialize any logging

---

parsl/executors/high_throughput/zmq_pipes.py
parsl/version.py

Reproducing #1146 is hard. Assuming that the ZMQError is coming out of a REQ/REP pipe deadlocking, destroying and recreating the context should be a reasonable fix.
Once this is reviewed, @Lnaden and @dgasmith, it would be very useful to get this tested over on your infrastructure.
Fixes #1146

Adding retry mechanism for when command channel fails with ZMQErrors

---

parsl/executors/workqueue/executor.py

This PR organizes and adds docstrings to the WQExecutor to better specify the documentation for its use. This attempts to fulfill issue #1326, and if there are other files that need to be updated with the Work Queue documentation, they can be included in this PR.

Update Documentation for WorkQueueExecutor

---

parsl/executors/high_throughput/executor.py

In most production settings, `suppress_failure=True` is the expected behavior. Without this being set to True, we see issues like #1188.

Setting suppress_failure=True as default

---

test-requirements.txt

This commit does not change any of core parsl. It changes the dependencies
that will be installed for testing, giving an older more tolerant mypy.
PR #1370 is a better but riskier fix.

Pin mypy to 0.730 pending more invasive fixes in #1370

---

parsl/configs/theta.py

This PR
(1) renames the Theta config path
(2) adds `min_blocks` and `max_blocks` to show how users can configure the scaling on Theta
(3) add `overrides="-d 64"` to AprunLauncher, which can deploy the workers across all the 64 cores on compute nodes.

change the theta config path and add an option to AprunLauncher

---

docs/devguide/changelog.rst

Current says release on Oct 23, can be updated if there's a change.
Do we want to add a link to our release checklist on the changelog ?

Changelog updates for 0.9.0

---

parsl/providers/azure/azure.py

* capitalisation of JSON
* long exception string literal contained long strings of
whitespace due to indentation - change string literal
syntax to one which avoids that
* make markup and articles consistent
* remove a duplicate comment

Fix human-readable text in Azure provider

---

parsl/executors/high_throughput/executor.py

There is more description in the docstring for
HighThroughputExecutor, which is also available
via parsl.HighThroughputExecutor.

Remove outdated HTEX module docstring

---

parsl/tests/test_bash_apps/test_apptimeout.py

Prior to this commit, this test did not check that timeout
behaviour actually happened. After this commit, the test
checks for an AppTimeout, in the style of the python_app
test in parsl/tests/test_error_handling/test_python_walltime.py
This commit also adds a test that apps will pass without
an exception if they run within the specified walltime.

Fix bash_app walltime test

---

parsl/app/bash.py

Fixes UnboundLocalError from #1435 
Minor wording update in the exception message to clarify that the return code is in the string.

Fix undefined returncode bug in exception handling code

---

parsl/providers/local/local.py

Prior to this commit, the pid to inspect was not properly
passed in, and the status check always returned that a
remote process was not running.
When strategy was enabled, this meant that the strategy
would keep launching blocks, even when they were starting
and running successfully.
Part of plan in issue #1448

Fix status checking in LocalProvider non-LocalChannel path

---

parsl/monitoring/monitoring.py

As reported in #1438 , with monitoring enabled, it took 31s for a very short workflow.
This is because we recently changed the monitoring closing mechanism in PR #1403 .
But it took a long time for the `Hub` process to join because of the long zmq context termination.
This PR sets the zmq lingering option to 0, so the context will terminate immediately.
Fixes #1438

set monitoring zmq channel linger options to 0 to prevent shutdown delay

---

parsl/providers/ad_hoc/ad_hoc.py
parsl/providers/local/local.py

This is to support using these code paths with the LocalChannel which will
run the commands inside /bin/sh rather than bash - and that /bin/sh
sometimes will not know &> bashisms.
This is part of the plan described in #1448

Replace bashisms with Bourne shell redirects in Local and AdHoc providers

---

docs/userguide/app_caching.rst

The previous hyperlinks expected bash_app and python_app to be in the
parsl.app module; but they are actually in parsl.app.app.

Fix hyperlink in app cache userguide

---

.flake8

D203 is now disabled by default in flake8, so a parsl
level exclusion isn't necessary any more.
See https://github.com/PyCQA/pydocstyle/issues/141

Remove unused flake8 D203 exclusion

---

parsl/channels/base.py
parsl/channels/local/local.py

execute_no_wait sets the process group of launched commands so that
local and ad-hoc providers can kill those launched commands later by
killing the whole process group.
Before this commit, execute_wait did not do that, so execute_wait could
not be used in the same way - instead, processes were left in the same
process group as the parent, and local/adhoc providers kill the entire
parent process group (for example, the entire containing workflow).
This commit also amends the documentation for the Channel base class to
clarify this requirement.
This is part of the plan in issue #1448

Make LocalChannel execute_wait set pgid like execute_no_wait

---

parsl/executors/high_throughput/probe.py

Prior to this commit, the probe will run for the entire timeout
period. This results in slow worker startup if the timeout is
manually changed to something much longer.

Exit htex probe loop with first working address

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

Prior to this, colours and labels for jobs in the two DAG graphs were
jumbled up.
The code incorrectly assumed that iterating over a dict would iterate in
the order that the entries appear in a hard-coded literal dict in the
source tree.
For example:
The code assumed that the first element added to the node_traces list, and
thus the element referred to by node_traces[0], would be the element in
groups_list with value (0,...)
This incorrect assumption led to adding DAG nodes to the wrong Scatter
object.
This patch changes the way that the node_traces list is constructed by
populating it with marker places and then using index notation to set the
appropriate entry in the list based on hard-coded index.
Further, that wrong scatter object then had its colour mutated. This patch
sets the …

Fix jumbled legends and colors in workflow dags

---

parsl/dataflow/strategy.py
parsl/executors/high_throughput/executor.py
parsl/executors/ipp.py
parsl/executors/low_latency/executor.py
parsl/providers/aws/aws.py
parsl/providers/azure/azure.py
parsl/providers/cobalt/cobalt.py
parsl/providers/condor/condor.py
parsl/providers/googlecloud/googlecloud.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/kubernetes/kube.py
parsl/providers/lsf/lsf.py
parsl/providers/pbspro/pbspro.py
parsl/providers/provider_base.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

Wrap provider task status into a class. Has two purposes:
- formalize the possible states to a set defined by the JobState enum
- allow additional information to be stored, such as the cause of a failure

Job status class

---

parsl/providers/ad_hoc/ad_hoc.py
parsl/providers/local/local.py

Boubou was committed earlier. The job_status_class branch/PR was missing changes to the local and ad_hoc provider. Somehow it passed tests, review, and whatnot. We should merge this.
You can check that there are no more relevant occurrences of 'PENDING', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED' with:
egrep -r "'PENDING'|'RUNNING'|'FAILED'|'COMPLETED'|'CANCELLED'" .
There are a few in comments, which we should fix, but this is more urgent.

These should have been part of the job_status_class PR, but weren't.

---

parsl/providers/slurm/slurm.py
parsl/providers/slurm/template.py

Some slurm configurations do not use a partition parameter, but instead
take a --qos parameter.
This change is intended to allow the partition parameter to be
suppressed (with the user then supplying a --qos parameter in
scheduler_options.
Fixes #518

Allow slurm partition to be optional

---

test-requirements.txt

Coverage 5.0.0 just appeared which appears to not work with pytest
properly. This patch pins coverage to 4.5.4 which is a version
which has worked successfully previously.
Coverage 5.0.0 + pytest fails with:
INTERNALERROR> coverage.misc.CoverageException: Couldn't use data file '/home/travis/build/Parsl/parsl/.coverage': UNIQUE constraint failed: meta.key
when run when no .coverage file exists. Subsequent runs do not raise
this error.

Pin `coverage` version in CI.

---

parsl/executors/ipp.py
parsl/providers/ad_hoc/ad_hoc.py
parsl/providers/cluster_provider.py
parsl/providers/googlecloud/googlecloud.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/kubernetes/kube.py
parsl/providers/provider_base.py

Fixes docstrings for executor.status() methods and an occurrence of "RUNNING" in the IPP executor

Fix rest of job status stuff

---

parsl/executors/high_throughput/process_worker_pool.py

This commit adds an addition block level to htex worker log paths,
like this:
.../runinfo/004/worker-nodes/block-0/627785a8965e/manager.log
This has been useful during a run with multiple large blocks to
discern which logs belong to which block.

Separate htex worker log directories by block id

---

parsl/dataflow/dflow.py

This is initialized to None. I cannot see it used anywhere else in
the codebase.

Remove unused 'callback' entry from DFK task record

---

parsl/launchers/launchers.py

Makes SingleNodeLauncher fail if all launched commands exit with a non-zero exit code.

Single node launcher error propagation

---

parsl/app/app.py
parsl/app/bash.py
parsl/app/python.py
parsl/tests/test_error_handling/test_python_walltime.py

`walltime` kwarg is now removed from the app decorator base and will not be supported by `@bash_app` or  `@python_app`. 
Adds a test that checks whether python_app walltime kwarg works correctly. The walltime works in second level granularity, so this test will take at least a second to trigger. 
Fixes #1527

Fix walltime bug #1527

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

Prior to this, the worker efficiency plot assumed that it got
ints from the database but it actually gets numpy.float64s.

Fix worker efficiency plot for CI runs

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

Prior to this commit, the gantt chart appeared to default to the year 2000 for some of the times
used. This mean that the default scale of the gantt chart was useless (decades, rather than
seconds) for a CI test run.
After this commit, if either the submitted or running times are None, then the return time is used.

Infer submitted and running times in gantt chart

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

Before this patch, the tasks_per_app plot could not be displayed when
viewing a CI test run monitoring.db. This patch fixes the plot so
that a CI run can be visualized.
i) the plot was expecting ints, but was getting numpy.float64
from the underlying database.
ii) the plot was expecting ints, but the time_running fields are
None/NaN because checkpointed tasks never start running.

Fix tasks_per_app plot enough to visualise a CI run

---

parsl/monitoring/monitoring.py

There isn't anything particularly special about main process monitoring
logs that should be treated differently from any other parsl component.

Put main process monitoring into main log file, not own separate log

---

parsl/app/python.py
parsl/tests/test_error_handling/test_python_walltime.py

Prior to this, the default/definition-time walltime was always
used, and this could not be overridden at invocation time.
This commit adds a test case for this, which fails prior to the
changes introduced by this PR.

Respect invocation-time python app walltime

---

.travis.yml
bors.toml

This should enable the bors merge-bot. It follows the vanilla recommendations [here](https://bors.tech/documentation/getting-started/), and further specifies that PRs should be squashed before merging.

Enable the bors merge-bot

---

bors.toml

I believe that if this isn't enabled, someone could merge a PR via bors without it having been approved.

Require PR approval before allowing bors merge

---

parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_dep_standard_futures.py

By ensuring that plain Futures can be used as dependencies, we can be more sure that dependency code does not want to know about the parsl-internal state of dependencies, but instead only relies on what it can observe with the Future interface.
This should be useful in garbage collection work.

Allow plain Futures to be used as dependencies

---

parsl/tests/test_threads/test_lazy_errors.py

Previously this test checked that 'done' was defined on an
AppFuture, rather than checking that the result of invoking done()
was True. This commit adds the necessary '()'.
This commit also removes some unnecessary complexity in the test.

Fix lazy error handling test

---

parsl/tests/test_regression/test_854.py

This test sometimes chose to put 0 items in a queue, which then
caused the not-empty-queue assertion to fail.
This commit makes the test always put a positive number of items
in the queue under test.
Prior to this commit, this test would fail usually after about
50 loops. After this commit, it has run for 2286 loops without
fail:
while pytest --config local parsl/tests/test_regression/test_854.py ; do echo LOOP ; done

Fix broken MacSafeQueue test that failed 1 in 100 times

---

parsl/providers/grid_engine/grid_engine.py

GridEngine takes an `h_rt` attribute that expects HH:MM:SS format or seconds. 
Previously we incorrectly passed it walltime in minutes resulting in jobs terminating early.
Unfortunately the GridEngine scheduler did not give any warnings on hitting the walltime, and allowed this bug to go on undetected.
@benhg I'd appreciate it if you can test this out on your cluster.
Fixes #1556

Fixes walltime format for GridEngineProvider

---

parsl/dataflow/dflow.py

Summary now only lists a total count of tasks in each state. Code is
updated to rely task_count, tasks_completed_count and tasks_failed_count
rather than iterate over the tasks table.
Fixes #1559.
Must merge into master before #1560

Updates to summary method to account for task getting garbage collected.

---

parsl/tests/test_summary.py

This is a test that would detect the regression #1559 (missing summary info) introduced in #1543 (garbage collection).
The test passes with the parent commit of #1543 (92a4bbc06c6cd5e46cdc307212caebd546f2db9b) but fails with #1543 applied.
I expect it to fail in CI until #1559 is fixed.

Add a test that DFK cleanup summary is output

---

parsl/dataflow/dflow.py

Before this commit, the message was awkwardly phrases as "waiting on" and then nothing further.
Task 35 submitted for App echo_to_streams, waiting on
Now the message looks like:
Task 35 submitted for App echo_to_streams, not waiting on any dependency

Fix "Task N waiting on" message when task isn't waiting on anything

---

parsl/dataflow/memoization.py

This case was occuring when a task set for memoization fails due to a
dependency failure. In this situation, the inputs of the task have not
been hashed and stored in hashsum (and do not even exist because the
task that produces them failed).
Previously, a key error was thrown, propagating up to handle_app_update.
Now, the memo table is silently not updated.

Handle the case where a task does not have a hashsum for memoization

---

parsl/app/bash.py
parsl/tests/test_regression/test_226.py

I'm a little unsure if it is safe to use parameter.empty here... I think so but it is a different
inequality to the one being tested before.
see https://github.com/Parsl/parsl/issues/226

Fix bash_app vs empty parameters, and expand #226 regression test

---

parsl/app/bash.py
parsl/app/python.py
parsl/dataflow/dflow.py
parsl/tests/test_bash_apps/test_keyword_overlaps.py

Before this commit, app invocation kwargs and dfk.submit kwargs were unnecessarily
tangled: keyword parameters such as `cache` couldn't be used as app parameters because they conflicted with keyword parameters passed to submit.
This commit keeps app invocation kwargs more cleanly separated.

Untangle app invocation and dfk.submit parameter namespaces

---

parsl/providers/torque/torque.py

This is a simple naive fix to a critical issue with the Torque provider.
The implementation of the Torque provider keeps track of running jobs using the output it got from the `qsub` command which gives a full hostname. But the status method runs `qstat` whose output typically provides truncated job_id values.
In my case (on Purdue's Brown cluster):
```
$ qsub ...
6058223.brown-adm.rcac.purdue.edu
```
```
$ qstat 6058223.brown-adm.rcac.purdue.edu ...
Job ID                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
6058223.brown-adm         ...96831.6737266 glentner               0 Q debug
```
This results in an almost immediate `KeyError` being raised on startup and a full panic.
All this fix does to …

Fix Torque job_id truncation

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py

This allows retries/checkpoint reuse of the "same" task across runs
to be identified.
A use case is where a large run takes multiple parsl runs to complete,
but information about all tasks no matter which run they happened in
is needed.

Store memoization hashsum in monitoring database

---

parsl/dataflow/dflow.py

Recent versions of typeguard place typeguard/__init__.py in the stack instead
of typeguard.py, so the code which skipped typeguard.py in workflow name
detection didn't skip typeguard and was picking __init__.py as the workflow
name.
Probably in general __init__.py is never the right name for a workflow in
monitoring - so this PR skips that name in all circumstances.
If the code runs out of names to try, then the code now defaults to a
specific value rather than leaving the workflow name un-set.

Make monitoring workflow name work with recent typeguard and ignore __init.py__

---

parsl/monitoring/db_manager.py

This was introduced to monitoring in PR #1584 but the
schema required it to be NOT NULL.
This field is NULL when a task fails before its hashsum is created:
specifically in testing, when a task ends with status dep_fail.
In such a case, data is not stored properly to the monitoring database.
This failure is logged in database_manager.log but is not made
obvious to the user/CI.

Allow task_hashsum to be null in monitoring

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/tests/test_python_apps/test_depfail_propagation.py

This should not change behaviour in usual operation, but moves
the retries_left information to the task record along with other
task related information.
It also makes type-checking with mypy easier for the Futures returned
by executors as there is no longer an expectation that arbitrary
Futures will have retries_left attributes.

Move retries_left to task record, instead of on the executor Futures

---

parsl/executors/high_throughput/interchange.py

Decode away the b'' wrapping around manager ID
Change Manager case to match other error message "Task failure due to loss of worker"
Rephrase docstring
Previously:
parsl.executors.high_throughput.interchange.ManagerLost: Task failure due to loss of Manager
b'6f2dab838843' on host parsl-dev-3-5-4032
Now:
parsl.executors.high_throughput.interchange.ManagerLost: Task failure due to loss of manager
05fc46e83367 on host parsl-dev-3-5-4032

Tidy loss of manager exception text

---

test-requirements.txt

This stops spurious CI errors caused by mypy releases making mypy stricter.
After this PR, mypy can be upgraded by:
* changing the test-requirements.txt mypy version
* fixing whatever breaks because of that upgrade

Pin mypy version

---

parsl/dataflow/task_status_poller.py

Calling logging.debug adds handler when it shouldn't. logger.debug should be user instead

Replacing logging.debug with logger.debug

---

parsl/dataflow/dflow.py
parsl/dataflow/error.py

This looks like it came as a cut-and-paste from another
exception class when DependencyError was initially
implemented.

Remove unused outputs attribute from DependencyError

---

parsl/app/errors.py

str is supposed to be more human readable than repr, but it
contains less information

Remove less-readable __str__ from MissingOutputs

---

docs/devguide/dev_docs.rst
docs/reference.rst
docs/stubs/parsl.dataflow.error.MissingFutError.rst
parsl/dataflow/error.py

This has been unused since commit
4cc6806ce74d91d39ba930bb1aa159643751e00b,
in March 2017

Remove unused MissingFutError implementation

---

parsl/providers/slurm/slurm.py

On cori, a number of interesting slurm behaviours have been
revealed by these log lines. (eg #1588)
They will probably be useful in general in understanding slurm behaviour.

Add progress logs for debugging slurm problems

---

docs/devguide/dev_docs.rst
docs/stubs/parsl.channels.LocalChannel.rst
docs/stubs/parsl.channels.OAuthSSHChannel.rst
docs/stubs/parsl.channels.SSHChannel.rst
docs/stubs/parsl.channels.SSHInteractiveLoginChannel.rst
parsl/channels/base.py
parsl/channels/local/local.py
parsl/channels/oauth_ssh/oauth_ssh.py
parsl/channels/ssh/ssh.py

This was previously used in a special case for
Local and AdHoc providers, but that special case
has been removed in previous commits.
This is the last patch in the series described in #1448. Resolves #1448.

Remove unused execute_no_wait from Channels

---

parsl/providers/cluster_provider.py

Previous to this, trying to throw this exception would have resulted
in a different exception being thrown as sitename would not be found.
This comes from benc-mypy branch

Use label rather than (missing) sitename in ClusterProvider exception

---

parsl/dataflow/dflow.py

This case happens harmlessly when multiple dependency callbacks
complete close together in time, with the task launching,
completing and being deleted before all of those depenency
callbacks have happened.
This log line is probably still useful to have in
place for debugging dependency behaviour.

Reduce log showing usually-harmless race from INFO to DEBUG

---

parsl/channels/local/local.py
parsl/channels/ssh/ssh.py
parsl/channels/ssh_il/ssh_il.py

This will catch more typos in channel keyword arguments rather
than silently condemning them to the ignored kwarg dict.

Remove **kwargs in various Channel inits

---

parsl/tests/test_bash_apps/test_memoize_ignore_args.py

Tests introduced in PR #1568 included definitions called test_*
that were not pytest tests. pytest issues a warning about these.
This commit renames those definitions to stop the warning.

Fix pytest warnings introduced in #1568

---

setup.py

The azure dependency broke when the latest released version moved to version 5.0.0. This
commit pins azure to major version 4, which is the major version
installed in my dev environment at the moment.
That breakage was blocking CI. This commit makes a minimal change
to unblock CI.
If azure is going to be used a lot, it would make sense to test
against azure version >=5, and move to correct dependencies with
a lower bound rather than an upper bound on older dependencies.

Pin azure dependency

---

docs/userguide/data.rst

Previously the config/auth subheadings for globus and
rsync providers were on the same level as the provider
name. This looked wrong in the table of contents.
This commit switches those subheadings to one level
lower (" is one level lower than ^)

Fix rsync/globus config/auth docs subheadings

---

parsl/app/bash.py
parsl/tests/__init__.py
parsl/tests/test_bash_apps/test_basic.py
parsl/tests/test_bash_apps/test_memoize.py
parsl/tests/test_bash_apps/test_multiline.py
parsl/tests/test_data/test_file_ipp.py

Previously this code assumed that a output was either:
* a string
or
* something with a .filepath attribute
and would fail if an output was anything else.
Presently, outputs of a bash app are always File objects
(with a .filepath attribute, and never anything else).
This commit tidies that codepath.

Rearrange bash app output checking codepath

---

parsl/channels/base.py

This will change channel implementations behaviour, so that subclasses
without a pull_file will error rather than silently skip file transfer.
I think this does not affect any existing channel.

Make channel.pull_file an @abstractmethod like other channel methods

---

parsl/dataflow/dflow.py
parsl/dataflow/memoization.py

There is no need to separately indicate if the memo
result is present and return that memo result.
A memo result is always a Future, so usual
Future or None protocol can be used.
This should not change the behaviour of memoization.
This comes from work on benc-mypy branch.

Simplify return type of check_memo

---

parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_memoize_bad_id_for_memo.py

Prior to this PR, an exception raised by launch() propagates upwards, in at least two
different ways:
* If a task has no pending dependencies, then the exception propages to the user's code which
invoked the relevant app. An example of testing this can be seen in
parsl/tests/test_python_apps/test_memoize_bad_id_for_memo.py
which expects such an exception.
* If a task has pending dependencies, then the exception propagates into the dependency Future's
callback handler, and then out of the top of that into nowhere. The user is never informed. This
behaviour was not tested in the test suite.
In both cases, anything which waits on such tasks completing (for example, via AppFuture.result()
or downstream dependencies) will hang forever as the tasks never reach a final state.
This PR places …

Mark task as failed if launch() raises an exception

---

parsl/dataflow/dflow.py

This adds stderr and stdout to ignore_for_cache automatically if
parsl.AUTO_LOGNAME is set. Fixes #1293.

Ignore AUTO_LOGNAME for caching

---

docs/devguide/dev_docs.rst
docs/reference.rst
docs/stubs/parsl.app.errors.AppFailure.rst
docs/stubs/parsl.app.errors.BashExitFailure.rst
docs/userguide/apps.rst
parsl/app/bash.py
parsl/app/errors.py
parsl/executors/workqueue/executor.py
parsl/tests/test_bash_apps/test_error_codes.py

This allows the bash app unix exit code case to have better formatting.

Split AppFailure into two cases: bash unix exit and workqueue failures

---

parsl/tests/test_flowcontrol/test_one_block.py

Once a block has been launched, the simple scaling strategy will not
see that it exists until after one executor poll period.
This test subclasses LocalProvider to:
* provide an extremely long polling period
* ensure that only one block is submitted through this provider
The test fails at the moment, showing that many blocks are
launched through the provider.
Blocks are launched every strategy period (5s) but based on status
information that comes only after each executor poll period.
I have experienced this in real use on cori using slurm.

Add a test to exhibit a scaling bug

---

parsl/providers/torque/torque.py

This bug and fix was found by @ravihansa3000 and confirmed by @benclifford.
Because array jobs report a `B` instead of `R` by the scheduler, these
jobs are seen by parsl with unknown job state. Fixes #1649.

Add batch jobs to PBS/torque job status table

---

parsl/executors/high_throughput/interchange.py

Catching the case of results being received from a manager that is marked dead due to missing heartbeats.
In the new mode, we will ignore results from a zombie manager. This is done since the assumption is that at the point where a manager is called dead, we send back notifications of the tasks being lost. Those tasks will then be relaunched. We should not send conflicting results back to the interchange.

Results from zombie managers

---

parsl/executors/workqueue/executor.py

The log messages should print the parsl_id, not the wq id (which does
not exist at that point in time anyway).

wq: log message incorrectly printed wq task id.

---

parsl/executors/workqueue/executor.py

The logic to find the reason of failure was moved to the function explain_task_exit_status.
This function also uses the symbolic names from the errors, rather than the hard-coded numbers.

wq executor cleanup: move reasons of failure outside WorkQueueSubmitThread

---

parsl/executors/workqueue/executor.py

Adds default values to the docstrings of WorkQueueExecutor's _init__method.

Specify doc defaults for the wq executor.

---

parsl/dataflow/dflow.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py

* `dfk`  does not call `shutdown` or `scale_in`, if the executor is in a bad_state to avoid hangs.
* `suppress_failures` option is now removed, this used to cover the following situations:
* manager registration fails dues to version mismatch -> Now a critical failure
* manager registration fails due to bad message -> logged and ignored
* interchange received a spurious message -> logged and ignored 
* `address_probe_timeout` is not specified to the manager if user does not specify explicitly for better backward compatibility.
The last item can be separated to a different PR.

Remove suppress failures #1669

---

parsl/executors/workqueue/executor.py

This PR adds options to the Work Queue executor to turn on automatic resource labeling for submitted tasks. WQ can collect stats from running tasks to automatically determine resource requirements. Another PR (#1675) is adding explicit resource labels. This feature is useful if the resource requirements aren't known in advance or the user doesn't want to worry about it, but still wants to subdivide large workers.
This PR also introduces a complementary option to automatically assign categories to functions, with each defined function placed in its own category. WQ manages resources separately for different categories, so this complements the auto-labeling feature. If different functions have different resource requirements, WQ will measure and label each function category separately.

Add support for Work Queue auto labeling resources

---

parsl/executors/workqueue/executor.py

When not using autocategory, the category of the task is set to
'parsl-default' before sending it to work queue. The work queue code
then can treat parsl-default as any other category. This simplifies the
logic a little bit, as the category of a task is set once and never
changed.
@trshaffer: I am consolidating the msgs sent between parsl and wq. This pr is just to make those changes easier.

wq excutor: treat parsl-default as any other category

---

parsl/executors/high_throughput/process_worker_pool.py

Other configuration is logged here already.

Log heartbeat configuration at start of process worker pool

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py

This is a mechanism to enable python2 new-style classes which
is unnecessary noise now.
This change should not affect behaviour.

Remove python2 object superclass idiom from monitoring.

---

parsl/dataflow/task_status_poller.py
parsl/executors/base.py

Prior to this, I was seeing 38 lines of executor configuration sent to the
parsl log file every 5 seconds.
This commit adds python 3.5 compatible code to declare the type of label,
so that `make mypy` will pass. This code is a bit ugly but can be replaced
once we drop support for Python 3.5

Replace executor __repr__ with executor label in periodic state report

---

parsl/__init__.py
parsl/log_utils.py

This is intended to allow cleaner-looking imports of logging
helper code in monitoring components.

Move parsl/__init__.py log helpers to separate file

---

parsl/executors/workqueue/executor.py

I found a bug in the WQ executor that prevents any tasks from starting when `source=True`.
The steps to actually write out the serialized function were under the default non-source branch, so configuring the executor with `source=True` resulted in no function info being written. Work Queue of course failed with missing inputs before actually running anything.
Also, the error message was kind of confusing (`unable to process wrapper script failure with status = -1`). I think the worker wrapper is in flux, would it be better to say something here to the effect of "this is probably a bug in Parsl" in case a user happens get into an invalid state?
cc @btovar  @yadudoc

Fix source mode in Work Queue executor

---

parsl/monitoring/db_manager.py

Using a module-global 'logger' allows log messages to be made even when
database manager object has failed to initialise properly.
This also removes some almost-duplicate code from the database manager,
replacing it with parsl's main set_file_logger.

Make monitoring database manager log with same style as rest of parsl

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py
parsl/monitoring/visualization/models.py

Times between different task state transitions are better computed
as needed by monitoring database readers.
This field was not used by the visualization UI.

Remove denormalized/unused monitoring db elapsed time field

---

parsl/monitoring/db_manager.py
parsl/monitoring/message_type.py
parsl/monitoring/monitoring.py

Resource messages are delivered via their own queue
and do not need a tag.

Remove unused RESOURCE_INFO message tag

---

parsl/monitoring/db_manager.py

Before this commit, if an exception happened in the Database __init__ call,
then the database thread would exit, and parsl would hang at shutdown.
After this commit, exceptions in database creation are handed with the
existing database exception queue.

Catch exceptions in database init (for example, DB schema errors)

---

.travis.yml
Makefile

This PR rearranges the Makefile to:
- allow use of the Makefile in an existing python environment rather than forcing a new `venv`. This allows `make test` to be used to test against development environments
- removes the use of a venv in CI. CI provides a container environment for the entire system, so a python level virtual environment is unnecessary
- removes a duplicate execution of module linting and flake8
- makes mypy be executed the same as lint/flake8
- installs optional dependencies in the targets that need them - prior to this, optional dependencies were sometimes installed in a different target that happens to execute in the correct order in `make test`

Rearrange Makefile and CI

---

parsl/monitoring/monitoring.py

There is now a MonitoringHub, containing a component called MonitoringRouter

Rename Hub class because it clashes cognitively with MonitoringHub

---

parsl/providers/cobalt/cobalt.py
parsl/providers/condor/condor.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/lsf/lsf.py
parsl/providers/pbspro/pbspro.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

This only touches the default config values for max_blocks.
This is added to avoid the situation of Parsl provisioning multiple jobs when the strategy assumes conservatively that each node will give one worker when doesn't know the number of workers that a node can support.

Updating all cluster providers with max_blocks default of 1 from 10

---

parsl/tests/conftest.py
parsl/tests/site_tests/README.rst
parsl/tests/test_bash_apps/test_memoize.py
parsl/tests/test_bash_apps/test_pipeline.py
parsl/tests/test_data/test_file_apps.py
parsl/tests/test_data/test_file_ipp.py
parsl/tests/test_docs/test_workflow1.py
parsl/tests/test_python_apps/test_futures.py
parsl/tests/test_regression/test_69b.py

This differentiates tests that fail due to issue363 (stdout/stderr staging issue), from tests that could pass if a staging provider is available in cases where the system doesn't have a shared-FS. 
Adds markers into the site_testing branch.

Adding a staging_required marker

---

parsl/__init__.py

This is required to get HTEX working on Mac. Related to #1659.
Warning note in FAQ/HTEX pending.
@danielskatz  Could you install this from this branch and test please ?

Disable fork safety on mac

---

.travis.yml

PR #1711 renamed the Hub component of monitoring to
MonitoringRouter and renamed the log file accordingly, but
did not make this change to CI.

Check for errors in renamed hub.log, now monitoring_router.log

---

parsl/dataflow/dflow.py

The first and second parts of handle_exec_update used to be in separate callbacks,
They were merged by #1431 to happen in the same callback, one after the other,
without more fine grained merging of behaviour.
This commit merges some of the if statements to make retry behaviour clearer.
Previously the retry behaviour was split between the two sections described aboe.
This commit will peturb the order in which post-task completion events happening.
This means that task garbage collection can happen earlier on, and so looking up
a task_id in self.tasks cannot happen so much. _create_task_log_info is modified
to take a task record, rather than a task_id, to accomodate this.

Merge two sections in handle_exec_update that have distinct ancestry

---

parsl/providers/cluster_provider.py
parsl/providers/cobalt/cobalt.py
parsl/providers/condor/condor.py
parsl/providers/googlecloud/googlecloud.py
parsl/providers/local/local.py
parsl/providers/lsf/lsf.py
parsl/providers/pbspro/pbspro.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

See #921.
Block status information comes from provider.status() now

Remove broken/unused provisioned_blocks attribute of providers

---

parsl/monitoring/visualization/plots/default/workflow_plots.py
parsl/monitoring/visualization/views.py

The status table captures richer state information than the task
table timestamp columns.
The chart will now show: retries, the initial period when a task is in
pending state, and continue to the end of the workflow showing final
(success or failure) state.
Previous:
New:

Generate Gantt chart from status table rather than task table timestamps

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a template for pull requests similar to the templates we have for issues. The goal is to make sure the PR nudges contributors to write cleaner PR descriptions that can go into our changelog.

New PR template

---

parsl/monitoring/visualization/templates/app.html

What you are clicking on/choosing is a task, not an app - you are already on the page for an app.
This is already how dependencies are represented in the same table: clickable task IDs

Hyperlinks for app page to task pages should be on the task ID, not app name

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py
parsl/monitoring/visualization/models.py
parsl/monitoring/visualization/templates/app.html
parsl/monitoring/visualization/templates/dag.html
parsl/monitoring/visualization/templates/resource_usage.html
parsl/monitoring/visualization/templates/task.html
parsl/monitoring/visualization/templates/workflow.html
parsl/monitoring/visualization/templates/workflows_summary.html
parsl/monitoring/visualization/views.py

This value be computed from other fields in the database,
so should not be stored in the DB:
duration = time_completed - time_began
Previously, the workflow duration was reported as None/NULL
when a workflow was not finished. This PR adds a helper
which provides NULL-aware subtraction for cases where
time_completed is null.

Remove denormalised workflow duration from monitoring db

---

Makefile

Remove a spurious } symbol in a debugging log line in the Makefile. This wasn't breaking anything, but was noise in CI output.
Please check the options below:

Remove spurious } in Makefile

---

parsl/dataflow/dflow.py

A previous commit replaced its use with fail_count

Remove task record retries_left because it is no longer used

---

parsl/tests/test_providers/test_local_provider.py

The provider tests in `parsl/tests/test_providers/test_local_provider.py` do not need a DFK configured, so should run in `pytest --config local` test mode, rather than with a configured DFK.
Before this PR, these tests were run multiple times without any difference (once per configuration); after this PR, they are run once (in the local tests run).
Code maintentance/cleanup

Make provider tests run in local mode

---

.github/PULL_REQUEST_TEMPLATE.md

Prior to this PR, the type of PR was presented as a series of checkboxes
with the intention that applicable ones are checked.
Github interprets checkboxes in PRs as todo lists, and renders a summary of them as "n of m
completed" progess bars on the PR summary page. This is wrong and confusing.
This PR moves formatting away from that style to prevent spurious github progress bars.

Remove markup checkboxes that conflict with github's interpretation

---

parsl/dataflow/dflow.py

The removed fragment of pseudocode does not reflect the current behaviour of DFK task submission.

Remove outdated/wrong pseudocode in dfk.submit docstring

---

docs/userguide/configuring.rst

This PR corrects the package for workqueue executor in Documentations from cctools to ndcctools

Correct the package for workqueue executor in Docs from cctools to ndcctools

---

parsl/launchers/launchers.py

The single node launcher introduced by PR #1724 uses "wait -n". The "-n" flag was introduced in bash v5. This PR rewrites that piece of code to not use said flag.
Fixes #1797 

Do not use "wait -n" in order to support bash versions older than 5.0.

---

codemeta.json
parsl/providers/slurm/slurm.py

Added an account option to the Slurm provider to optionally provide an account to which to charge the batch job.
Fixes #519

Add account config option to Slurm provider (#519)

---

parsl/dataflow/dflow.py
parsl/dataflow/error.py

When there is a long chain of dependencies, then an early one failing generates verbose and
awkward to read exception text.
DependencyErrors are now rendered like this:
Dependency failure for task 8 with failed dependencies from tasks [6]

Make dependency exceptions only report task ID, not full exception tree

---

parsl/tests/conftest.py

Treating KeyError to mean "skip this test" rather than as a test failure only makes sense for
local tests, where some configurations do not work unless user options are supplied.
KeyErrors raised by specified-config tests should be treated as regular test failures; such
exceptions can be raised by failing test cases, and so should cause the test suite to fail.
This commit removes special casing for KeyErrors in the specified-config case, leaving it in place
for local tests.

Tighten pytest KeyError test skipping

---

docs/conf.py
docs/index.rst
docs/quickstart.rst

The link to the Parsl tutorial notebook in the Parsl docs was broken as per #1787. This was because the name of the notebook was changed in the `parsl-tutorial` repo. Simple fix.
Fixes #1787

Fix broken link to Parsl tutorial (#1787)

---

CONTRIBUTING.rst

Updates link to point at CODE_OF_CONDUCT.md on master instead of the now deleted CoC.md.

Updating link to point to the updated CODE_OF_CONDUCT.md

---

docs/userguide/data.rst

Previously the configuration section was at the same level as
the globus introduction; now it is at the same level as the
globus authorization section.

Correct globus configuration doc subheading level

---

docs/devguide/contributing.rst

The removed text was largely a dupe of CONTRIBUTING.md, which is
better maintained.

Link from dev guide to CONTRIBUTING.md

---

parsl/serialize/facade.py

The parsl.serialize module, tries a sequence of serializations methods and whenever a serialization method failed, existing behavior is to log the exception to the parsl.log which can be confusing to users since this was added only for debug. This PR
removes these logging lines completely. The module reports the exception from the last serialization method if all serialization
methods fail.

Removing serialization exception logging for every attempt

---

parsl/configs/Azure.py
parsl/configs/ad_hoc.py
parsl/configs/bluewaters.py
parsl/configs/cc_in2p3.py
parsl/configs/comet.py
parsl/configs/cooley.py
parsl/configs/ec2.py
parsl/configs/frontera.py
parsl/configs/midway.py
parsl/configs/osg.py
parsl/configs/stampede2.py
parsl/configs/theta.py
parsl/tests/configs/ad_hoc_cluster_htex.py
parsl/tests/configs/bluewaters.py
parsl/tests/configs/comet.py
parsl/tests/configs/cooley_htex.py
parsl/tests/configs/frontera.py
parsl/tests/configs/midway.py
parsl/tests/configs/osg_htex.py
parsl/tests/configs/theta.py
parsl/tests/manual_tests/test_ad_hoc_htex.py
parsl/tests/manual_tests/test_dynamic_executor.py
parsl/tests/manual_tests/test_fan_in_out_htex_remote.py

Pertaining to issue #1754. I made sure to remove all instances of `address_by_hostname` and `address_by_query` from code base. This is an amendment to a previous pull request, but I couldn't figure out how to fix the old one so I closed it and made a new one. :)
Let me know if there are any remaining issues and I will update accordingly.

Removed all instances of "address_by_hostname" and "address_by_query" in config examples

---

docs/userguide/configuring.rst
parsl/executors/workqueue/executor.py
parsl/tests/test_error_handling/test_resource_spec.py

This PR allows users to specify the resource usage for each task in workqueue executor.
Users can define an app as:
```
@python_app
def double(x, parsl_resource_specification={}):
return x * 2
```
Then when the app is submitted, the resource specification is like:
```
spec = {'cores': 2, 'memory': 1000, 'disk': 1000}
fut = double(n, parsl_resource_specification=spec)
```

Allow user to specify the resource for each task with workqueue executor

---

parsl/monitoring/db_manager.py

The status table talks about AppFuture states. Hostnames are related to tries.

Remove hostname from status table

---

parsl/providers/local/local.py

Unlike the other providers, LocalProvider does not set a JOBNAME environment variable. This causes havoc with some launchers that use the JOBNAME variable.

Add JOBNAME to local provider 

---

parsl/monitoring/db_manager.py

PR #1727 tries to insert task info into task table when task is created. But that PR failed to update the `task_hashsum` in the task table. This PR fixes the bug and update `task_hashsum` in task table.
Fix #1850 

fix a bug that task_hashsum is missing in monitoring task table

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/sites/test_affinity.py

This PR introduces an option for HTEX workers to set their CPU affinity on launch. Setting CPU affinity can prevent multithreaded tasks from interfering with each other (e.g., Tensorflow tasks). 
Fixes #1344 

Allow HTEX to set CPU affinity

---

parsl/data_provider/ftp.py
parsl/data_provider/globus.py
parsl/data_provider/http.py
parsl/dataflow/dflow.py

When a task has input or output files, then file staging elaboration
may add in new tasks to perform that input or output staging.
Those new tasks should not themselves be further elaborated by
the staging mechanism, otherwise inappropriate staging behaviour
might be added in around the staging tasks themselves.
Prior to this inhibition, this inhibition of staging happens in
two ways, differently for stage-in and stage-out.
If the task is assigned to the 'data_manager' executor,
then no staging-in elaboration is performed on that task.
If a task has a 'staging_inhibit_output=True' keyword argument,
then no staging-out elaboration is performed on that task.
It turns out that check for the 'data_manager' executor is
not a very good test, for a couple of reasons:
Stage-out tasks can run on …

Generalise staging inhibiting to work in more cases

---

parsl/config.py
parsl/data_provider/globus.py
parsl/dataflow/dflow.py
parsl/tests/test_error_handling/test_resource_spec.py

An upcoming PR to implement monad-like joins needs to execute tasks locally inside the submitting
process, just like the data_manager local executor is used for when performing some staging tasks
(globus ones).
This PR renames that local executor from data_manager to _parsl_internal to reflect that intended
broader use.
- Breaking change:  any external file staging providers which expect to use `data_manager` as an executor name need to change to use `_parsl_internal`

Rename data_manager executor for more general use

---

docs/userguide/monitoring.rst

It was not mentioned in the docs that `parsl-visualize` has some more dependencies and hot to install them.

Add note on installation of parsl-visualize dependencies

---

parsl/app/bash.py
parsl/tests/configs/local_threads.py
parsl/tests/test_bash_apps/test_basic.py

Manually set `func.__name__` to fix Parsl stdout log filename issue when `parsl.AUTO_LOGNAME` is set in bash_apps
Added a test case to validate the stdout format when `parsl.AUTO_LOGNAME` is set
Fixes #1857 

Fixes #1857 by setting remote func.__name__ manually

---

parsl/executors/workqueue/executor.py

Fixes #1842.
Before, the WQ resource monitor would be enabled if debugging was enabled. We only want it enabled if `autolabel=True`.

Don't enable WQ resource monitor if autolabel=False

---

parsl/executors/high_throughput/zmq_pipes.py

Prior to this PR, the zmq_pipe would try to send every message three times regardless of whether it is sent successfully or not.
So for example, I saw three `hold_worker` logs in `interchange.log`  when dfk was exiting,
```
2020-09-24 17:24:15.871 interchange:329 [INFO]  [CMD] Received HOLD_WORKER for b'f924c9740a62'
2020-09-24 17:24:15.872 interchange:329 [INFO]  [CMD] Received HOLD_WORKER for b'f924c9740a62'
2020-09-24 17:24:15.872 interchange:329 [INFO]  [CMD] Received HOLD_WORKER for b'f924c9740a62'
```
while `parsl.log` indicated that only one `hold_worker` command was sent via the command channel
```
2020-09-24 17:24:15.871 parsl.executors.high_throughput.executor:517 [DEBUG]  [HOLD_BLOCK]: Sending hold to manager: f924c9740a62
2020-09-24 17:24:15.873 …
```

breaking out the max_retries loop in zmq_pipe after message is successfully sent

---

parsl/app/app.py
parsl/app/python.py

Prior to this PR, if you declare a python app with the default kwarg `parsl_resource_specification` and invoke the app without using this kwarg, parsl disregards the resource specification. This PR fixes the issue.

Fix the correct reference of kwargs in python apps dfk.submit and include parsl_resource_specification by default

---

parsl/executors/workqueue/executor.py

The function qualname is getting lost when the function is
wrapped for error propagation; `__name__` is updated explicitly and safe
to use here.
Fixes #1867. 

Set WQ category to func name, not qualname

---

parsl/monitoring/monitoring.py

In PR #1839 , we changed the mechanism for monitoring's first message (used to infer the running time of a task). However, that PR silently ignores the exception for monitoring first message.
This PR lets the worker handle monitoring first message exception directly and reports back the exception to the user along with the task.

Let worker handle monitoring first message exception directly and raise the exception to task exception

---

parsl/__init__.py

This PR makes some more common parsl symbols re-exported at the top level, meaning that users can write more concise imports.

Refresh the list of useful top level re-exports for usability

---

parsl/dataflow/dflow.py

This is useful when examining long running tasks which did not complete,
for example because the workflow process crashed or was killed.

Log stdout/err paths at task start as well as at completion

---

parsl/tests/test_python_apps/test_memoize_5.py

This test attempts to check that caching does not happen when
a function is redefined, but it was not enabling caching at all
because cache=True was in the wrong place.
This PR puts cache=True into the right place, and adds another
assertion that checks that caching *is* working when the function
is not redefined.

Fix memo test that did not correctly enable caching

---

parsl/executors/high_throughput/executor.py

Changes HTEX to remove references to a task after it completes. Could otherwise lead to memory issue if task outputs are large.
Fixes # (issue) [Would you like me to open one?]

Remove task future from executor once completed

---

Makefile
test-requirements.txt

PR #1638 added several packages to test-requirements that were already
listed in requirements.txt - probably as part of an attempt to avoid
performing a parsl installation (which would lead to the requirements.txt
requirements being installed) before running tests.
This PR removes those duplicates and explicitly installs requirements.txt
alongside test-requirements.txt.
This removes some of the need to manually maintain the image of
requirements.txt inside test-requirements.txt

Dedupe requirements between requirements and test-requirements.txt

---

parsl/monitoring/db_manager.py

self._get_messages_in_batch was always called with batching parameters
coming from self, so invocations look cleaner if that method looks up
the batching parameters directly.

Take _get_messages_in_batch parameters from self implicitly

---

parsl/providers/aws/aws.py

This pull request will fix a mismatch of state_file names in the AWS provider config. 
Context:
1. When someone initialises a AWS Provider Object, the code looks for a file named 'ec2_{name}.json' to see if a VPC has already been created or not. 
2. If it doesn't find a file of that name, it'll create a new VPC and save the information in a file called 'awsproviderstate.json'.
The problem here is that, the code looks for a state file name ('ec2_{name}.json') that is never created because a new VPC is always stored in 'awsproviderstate.json'. This means that the code will NEVER find the json file by default and it always ends up creating a new VPC. This means that the user will hit their VPC limit very quickly.
Fixes: By making the state_file name consistent between the 'code that creates …

Fixed mismatch in state_file name

---

parsl/tests/test_callables.py

These new casese reflect a different way that importlib is now used in the
LSST DRP workflow, based on the ongoing discovery of problems related to
the new serialisation mechanism in PR #1806.

Add more serialisation vs importlib testcases

---

parsl/dataflow/dflow.py

Previously this was not logged until after the task had been
successfully submitted.

Log choice of executor for a task as soon as it is chosen

---

parsl/dataflow/strategy.py

Unused fields are removed, and _general_strategy now requires
an explicit strategy type (which was already the case in all
invocations)

Tidy strategy parameters

---

parsl/tests/test_bash_apps/test_error_codes.py

This was disabled in a great testpocalypse, 7ee597bcf51ae432a82dabe9fc2bec00e5abc456
which was pretty free in disabling anything that seemed to not be passing.
- Testing

Re-enable test which appears to work now

---

docs/stubs/parsl.providers.AWSProvider.rst
parsl/providers/aws/aws.py

Adds a name tag of the form "parsl.aws.123456.789" for the newly created VPC. The same is done for associated security groups and subnets.
Fixes https://github.com/Parsl/parsl/issues/1135

Add name tags to AWS VPCs

---

parsl/dataflow/dflow.py
parsl/dataflow/task_status_poller.py
parsl/executors/base.py
parsl/executors/status_handling.py

`create_monitoring_info` has a block_id_type parameter, but that isn't the case for ParslExecutor.
This PR corrects the issue.

Correct create_monitoring_info args in ParslExecutor

---

parsl/configs/wqex_local.py

The current WQ example configuration does not work out of the box.
This fixes it:
- project_name should not have spaces
- shared_fs should be false by default for robustness
- see_worker_output is not a valid flag.

Fix Example WQ Configuration

---

parsl/executors/high_throughput/interchange.py

Instances of hub_channel aren't threadsafe. This PR moves away from having
one magic self.* channel, and another as a local in a thread, to creating
all channels as locals in threads.
monitoring_enabled is replaced by hub_channel becoming an optional, with
None signalling the same as !monitoring_enabled.
_send_monitoring_info gets a new parameter, hub_channel, which means it can
now be used in more places, reducing some code duplication.
This is in preparation for some upcoming PRs which allow the htex messaging
connections to be used for sending monitoring messages from the worker
side, instead of the monitoring system running its own monitoring
network connections.
This PR should not affect monitoring behaviour.

Rework hub_channel usage to be more obviously thread safe

---

parsl/monitoring/monitoring.py

Prior to this patch, monitor() performed two functions, selected by a boolean
parameter:
i) It sends a task running message, which is used to populate the task_try_running
database field.
ii) It performs periodic monitoring of the process tree that is executing the
task.
These two code paths are fairly clearly separate, and do not need to both be in
monitor.
This PR is preparation for future PRs which allow worker-side monitoring to
report task start time without forking a resource monitoring process.

Split worker-side monitoring message code based on purpose

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/process_loggers.py
parsl/tests/test_error_handling/test_wrap_with_logs.py

When a thread or process raises an exception out of its top level function,
that exception does not get logged automatically. This sometimes results in
the threads appearing to silently stop without any reported error.
This patch adds a @wrap_with_logs decorator which can be used on
thread/process top level functions (or any other function) and which logs
such exceptions as they propagate upwards.
This won't catch cases where logging is sent to a logger name where
logging has not been configured for that name yet - for example, exceptions
happening before interchange or monitoring database manager have
configured their logging.

Add decorator to catch exceptions coming out of threads and processes

---

parsl/app/app.py
parsl/app/bash.py
parsl/app/python.py
parsl/dataflow/dflow.py
parsl/dataflow/memoization.py

Prior to this PR, inputs for memo hashes are generated in two places:
* in app construction, producing a func_hash by attempting to get the
function source code
* id_for_memo hashes various things, including arguments and the app name
When the function is wrapped by some pieces of parsl, such as
remote_side_bash_executor or some file staging code, then the function is
replaced by a new function, and the original function is passed as an
additional argument.
This has the effect of id_for_memo hashing also hashing the function, in
addition to the app construction hash, and this time hashing it in a
different way - by using serialisation of the function object.
This hash-by-serialisation method was extremely fragile and would change for
probably undesirable reasons, such as source code …

Memoize functions like any other value

---

parsl/app/bash.py

The `remote_side_bash_executor` wraps bash commands in a python function. This function currently adds a new logger per function execution to direct log lines from each bash_app execution to its own log file, and does not close the logger file handles. This could result in the worker side running out of filehandles as we run more apps. However, we currently only report logs that are redundant given reporting we do elsewhere. This PR removes the loglines and the code that sets up the logger.
Fixes #1950 
Reported by Andrzej Novak.

Remove logging from remote_side_bash_executor

---

docs/stubs/parsl.executors.ExtremeScaleExecutor.rst
docs/stubs/parsl.executors.HighThroughputExecutor.rst
docs/stubs/parsl.executors.LowLatencyExecutor.rst
docs/stubs/parsl.executors.ThreadPoolExecutor.rst
docs/stubs/parsl.executors.WorkQueueExecutor.rst
docs/stubs/parsl.executors.base.ParslExecutor.rst
docs/stubs/parsl.executors.swift_t.TurbineExecutor.rst
parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/threads.py
parsl/monitoring/monitoring.py

This allows an executor implementor (not a user) to indicate
that parsl resource monitoring is not compatible with that
executor - this incompatibility arises with the
ThreadPoolExecutor as process spawning and thread spawning
do not play nicely together in python.
With this PR, ThreadPoolExecutor can be used in a configuration
with monitoring enabled.
ThreadPoolExecutor is needed for a couple of features
even when most work is done through some other executor such
as HTEX:
* the existing globus data provider
* still unmerged @join_app functionality
- Bug fix (non-breaking …

Add per-executor resource monitoring toggle

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/tests/test_monitoring/test_fuzz_zmq.py

In practice on cori.nersc.gov on large runs, some unexpected network
traffic arrived at monitoring ports. This would sometimes crash
the monitoring system. This PR makes monitoring more likely to ignore
such traffic rather than crashing.
This PR adds some tests to generate spurious traffic.
Notes to reviewers:
I'm a little unclear about the correct way to report that
exceptions happened in the database loop: at the moment, this
ignores such exceptions and then reports a final exception
when monitoring finishes.
Another of my concerns is that there are other causes of exceptions,
not only spurious messages, and this may not be the right
handling for such messages. (for example, does a particular
socket closed exception result in the loop going into a 100%
CPU loop?)
This change most makes …

Make monitoring more resilient to spurious network traffic

---

parsl/executors/errors.py

str should be more informal/human readable, and repr should be more
python syntax
see:
https://docs.python.org/3/reference/datamodel.html#object.__str__
https://docs.python.org/3/reference/datamodel.html#object.__repr__
Before this PR (eg for a ScalingFailed error, which inherits its
str/repr behaviour from executorerror):
>>> str(ex)
('local', 'Attempts to provision nodes via provider has failed')
>>> repr(ex)
Executor local failed due to Attempts to provision nodes via provider has failed
After this, the object default repr is used instead of overriding,
and where repr() was previously overridden to provide human readable text,
that is changed to be the str() representation.
So, the example ScalingFailed error looks like:
>>> str(ex)
'Executor local failed due to: Attempts to provision …

Fix executor error repr vs str wrong-way-round-ness

---

docs/reference.rst
docs/stubs/parsl.executors.errors.ControllerError.rst
docs/stubs/parsl.executors.errors.InsufficientMPIRanks.rst
parsl/executors/errors.py

Looks like ControllerError is a leftover from IPP,
and InsufficientMPIRanks is from some now discarded
MPI work.

Remove unused executor errors

---

parsl/executors/errors.py
parsl/executors/high_throughput/executor.py

In one place, the constructor was called with the wrong number of args,
which would result in a different exception when trying to raise this.
This PR makes provider label optional to support that use, where there
is no provider available.
This PR adds type annotations on the ScalingFailed __init__()

Fix bad args for ScalingFailed constructor

---

parsl/providers/grid_engine/grid_engine.py

Hi. @Lanyavikins at UCSF has been getting our Parsl pipeline working with a Grid Engine scheduler. However, the job submission on Wynton requires a "queue" command line argument. Her fix is to add "queue" as an optional parameter to GridEngineProvider.

Add optional queue flag to Grid Engine submissions

---

parsl/dataflow/dflow.py

repr is a better format for this field. For example, it usually
contains more context such as the exception class name:
```
>>> str(v)
'3'
>>> repr(v)
'KeyError(3)'
```
Anything expecting specific content for monitoring errors in the monitoring db will break as the format is changed.

Use repr instead of str for monitoring fail history

---

parsl/monitoring/monitoring.py

Previously after receiving a UDP message, there was a potential block on subsequent delivery to a queue before the log happened.

Log UDP received message as soon as it is received.

---

parsl/providers/grid_engine/grid_engine.py

The GridEngineProvider doesn't currently support the `cmd_timeout` kwarg that's used to configure the duration for which the provider would wait for commands. This PR adds that.
Requested by @marinerhemant

Adding cmd_timeout option to GridEngineProvider

---

docs/reference.rst
docs/stubs/parsl.errors.OptionalModuleMissing.rst
docs/stubs/parsl.providers.error.OptionalModuleMissing.rst
parsl/executors/workqueue/executor.py
parsl/monitoring/db_manager.py
parsl/providers/aws/aws.py
parsl/providers/azure/azure.py
parsl/providers/error.py
parsl/providers/kubernetes/kube.py

There was one at the parsl top level, and one in providers, but
these were not used uniformly:
* the monitoring system used the provider version even though
it is nothing to do with the provider system.
* the top level error was not listed in the API documentation
This will break any code that was expecting specific classes for these errors, but I've never seen any in real life.

Unify two impls of OptionalModuleMissing exception class

---

parsl/executors/workqueue/executor.py

Update WQ executor to allow specifying GPUs.
CCTools just released version 7.2.0, which improves handling for GPUs. This PR allows Parsl apps to specify GPUs in their resource requirements, which will be passed down to WQ.

Allow passing GPU requirements to WQ executor

---

parsl/addresses.py

Some linux distros do not come with /sbin/ip command and thus a workaround is needed for the function address_by_route.
Code

Workaround for missing /sbin/ip command

---

parsl/dataflow/usage_tracking/usage.py

This PR fixes a race-condition in usagetracking by using task counters in the DFK instead of the current mechanism of iterating on the DFK.tasks table. This avoid any issues arising from the tasks table's keys changing while it's being iterated on.
Fixes #1986 

Fix for racecondition in usage tracking at cleanup

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py

This PR tries to set an env variable `PARSL_WORKER_BLOCK_ID` for every HTEX worker. When a task runs on a worker, monitoring extracts the block id info and logs the `block_id` into `try` table.
Fixes #1969 
- Breaking change (fix or feature that would cause existing functionality to not work as expected) --- this breaks old monitoring db schema

Log block id in monitoring try table

---

README.rst
setup.py

A recent release (1.4.0, 1.4.1) of sqlalchemy breaks the parsl[monitoring] install. This branch constraints sqlalchemy to the 1.3.x series.

Tighten SQLAlchemy version constraints after incompatible SQLAlchemy 1.4 release

---

parsl/tests/site_tests/site_config_selector.py
parsl/tests/test_bash_apps/test_error_codes.py
parsl/tests/test_docs/test_workflow4.py

Some tests currently failed on sites without a shared file system (e.g., k8s). This PR marks those tests to exclude them when doing site tests.

Mark some tests that do not work for sites without a shared file system

---

parsl/app/app.py
parsl/data_provider/ftp.py
parsl/data_provider/http.py

This PR changes imports in file staging providers to prevent an import loop introduced by the import of DataFlowKernel into the decorator module.
`import M` is more robust against import loops than `from M import x`

Add typeguard to user-facing app decorators

---

requirements.txt

This is needed because PR #1963 introduced code that uses this dependency.
Users get an error when installing parsl without this dependency when trying to do anything with parsl. See #2008 
It didn't break in CI, probably because the test-requirements
dependencies, such as mypy, make it be installed.

Add typing-extensions dependency

---

docs/quickstart.rst
docs/userguide/configuring.rst
docs/userguide/monitoring.rst
parsl/monitoring/db_manager.py

Without '-marks, zsh tries to resolve our given example installer
commandlines as wildcards, resulting in errors like this:
$ pip install parsl[monitoring]
zsh: no matches found: parsl[monitoring]

Use zsh compatible install syntax

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

PR 1876 removed the reg_time field from the monitoring database but did not remove attempts to use it from the visualization code, or code that initialises it on the sending side.
Visualization was broken because of this.

Fix use of previously removed reg_time monitoring field

---

setup.py

Python 3.9 has been supported by parsl since #1720

Reflect python 3.9 support in setup.py metadata

---

parsl/executors/workqueue/executor.py

This is useful when launching workqueue workers inside
some other environment - for example, when the workers
are installed inside a singularity/shifter image.

Make WorkQueue worker command configurable

---

parsl/channels/local/local.py
parsl/channels/ssh/ssh.py

This change was originally added by @rantahar to a fork of `libsubmit` which means it has to be reintroduced again due to all the structural changes. 
I've found this [PR](https://github.com/Parsl/libsubmit/pull/88) a bit later and it was created not long before the project assimilation so it didn't have a chance to be merged. I'm not sure about line endings though, it looks like a reasonable thing since there is going to be Linux running on the other side.
Rather than stacking strings together it's much better to use `os` module to make it work on Windows as well.

Fix os independent paths

---

parsl/providers/grid_engine/grid_engine.py

PR #1964 introduces a queue constructor parameter and a use elsewhere of `self.queue`, but omits any code to join one to the other.
That means that at least all GridEngine configurations appear to be unusable when passed to parsl.load() whether they use the `queue` parameter or not - they raise the below exception.
```
python sgetets.py 
File "sgetets.py", line 30, in <module>
parsl.load(config)
File "/home/benc/parsl/virtualenv-3.7/lib/python3.7/site-packages/typeguard/__init__.py", line 891, in wrapper
retval = func(*args, **kwargs)
File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 1280, in load
cls._dfk = DataFlowKernel(config)
File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 84, in __init__
logger.debug("Starting …
```

Fix GridEngine unable to initialise due to missing self.queue

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

Prior to this PR, this plot would crash. After this PR, this plot regards task without an end time as still in progress and occupying a worker.

Fix worker efficiency plot when tasks are still in progress

---

parsl/executors/workqueue/executor.py

Prior to this PR, config dumps using the WorkqueueExecutor would show only the class name and object id:
```
executors=[<parsl.executors.workqueue.executor.WorkQueueExecutor object at 0x7f29216f7400>
], 
```
Now they show a more elaborate representation of the configuration in line with the rest of parsl.
```
WorkQueueExecutor(
address='parsl-dev-3-7-257', 
autocategory=True, 
autolabel=False, 
autolabel_window=1, 
env=None, 
extra_pkgs=[], 
full_debug=True, 
init_command='', 
label='WorkQueueExecutor', 
managed=True, 
max_retries=1, 
pack=False, 
port=9000, 
project_name=None, 
project_password_file=None, 
provider=LocalProvider(
channel=LocalChannel(envs={}, script_dir=None, userhome='/home/benc/parsl/src/parsl'), 
cmd_timeout=30, 
init_blocks=1, 
launcher=SingleNodeLauncher(debug=True, …
```

Make WorkqueueExecutor show itself with RepresentationMixin

---

.travis.yml

This was introduced in PR 1391 to test that all targets could be installed.
That target has never really installed properly though - different parts of
parsl optional dependencies conflict with each other and this test has
previously only passed because pip didn't actually error out when dependencies
conflicted.
More recently this has become a problem where pip is not trying hard to
resolve a dependency that quite likely is not resolveable, and appears
to get stuck trying to install msazure and jeepney.
INFO: pip is looking at multiple versions of jeepney to determine which version is compatible with other requirements. This could take a while.
Collecting jeepney>=0.4.2
Downloading jeepney-0.5.0-py3-none-any.whl (45 kB)
Downloading jeepney-0.4.3-py3-none-any.whl (21 kB)
Downloading …

Remove breaking .[all] install target

---

Makefile

In CI this was not revealed because of the order in which tests are run there.

Add monitoring dependency to local tests

---

parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_join.py

prior to this, returning the wrong type was resulting in a
hang.
after this, returning the wrong type gives a TypeError - for
example:
TypeError: join_app body must return a Future, got <class 'list'>

Fix and test wrong type handling for joinapp returns

---

parsl/monitoring/db_manager.py

Practical experience with wstat has shown this index
to give great speedup when making queries which match
up tasks between runs based on their checkpointing
hashsum.

Index task_hashsum to give cross-run query speedup

---

parsl/executors/threads.py

Remove python <3.6 handling from threadpoolexecutor

---

parsl/dataflow/dflow.py

An AppFuture will always present its exception as a future.exception(),
not as a RemoteWrapper. RemoteWrappers are used at the executor future
layer.

Do not unwrap joinapp future exceptions unnecessarily

---

parsl/errors.py

__repr__ should be quasi-machine-readable, and __str__ human readable
See PR #1966, commit a423955f4a9e03cf6986a6e21d285cf46fa3bc88, for further context.
Before:
>>> str(e)
"(['mymod'], 'this test needs demonstrating')"
>>> repr(e)
"The functionality requested requires a missing optional module:['mymod'],  Reason:this test needs demonstrating"
After:
>>> str(e)
"The functionality requested requires missing optional modules ['mymod'], because: this test needs demonstrating"
>>> repr(e)
"OptionalModuleMissing(['mymod'], 'this test needs demonstrating')"

Rework __repr__ and __str__ for OptionalModuleMissing

---

parsl/dataflow/dflow.py
parsl/dataflow/memoization.py

When these functions need the task id, they can extract it from
the task record.
see #2014 

Remove task_id param from memo functions, as whole task record is available

---

parsl/configs/wqex_local.py
parsl/executors/workqueue/executor.py

This PR causes the WQ executor to use a project name of "parsl-wq-{UUID}" by default, unless the user picks another one.  This allow the standard WQ reporting infrastructure to uniquely identify each worklfow separately.

Document WorkqueueExecutor project_name remote reporting better

---

docs/userguide/configuring.rst

Remove untrue claim that parsl_resource_specification keys are case insensitive

---

parsl/monitoring/monitoring.py

Previously, this message wouldn't be logged until after the message was
sent to the resource_msgs queue; if that queue blocked, the message would
not be logged at the right time.

Reorder debug message so it happens when the message is received

---

docs/conf.py
parsl/data_provider/data_manager.py
parsl/executors/base.py
parsl/executors/flux/executor.py
parsl/executors/high_throughput/executor.py
parsl/executors/swift_t.py
parsl/providers/kubernetes/kube.py
parsl/providers/provider_base.py

Before this, only a small table of summary information was given for each
class, and per-method docstrings were not presented.
This PR also fixes several errors in docstring text that were previously
not a problem, because those pieces of docstring were not used.
Attached are before/after screenshots showing the extra information:

Configure sphinx to put in full documentation for each method

---

docs/userguide/configuring.rst
parsl/configs/toss3_llnl.py

Updates the documentation to add a config for LLNL TOSS3 machines. TOSS3 machines are commodity machines with no GPUs (with one or two exceptions). They all run Slurm.

docs: add Flux/LLNL TOSS3 configuration

---

.coveragerc
README.rst
test-requirements.txt

Recently (since the PR #2078) something has changed in dependency packages which made `pip` unable to find a valid set of package versions to install.
The version pin on `coverage` that is removed by this PR was conflicting with
pytest-cov > 2.10. Previously pip was able to easily find a solution
to that by using an earlier pytest-cov, but as of some recent
ecosystem change, it was unable to find a solution.
When manually trying to install pytest-cov 2.11.0 on my laptop
with a working parsl dependency stack already installed:
```
The conflict is caused by:
The user requested coverage==4.5.4
pytest-cov 2.11.0 depends on coverage>=5.2.1
```
When building in CI, this resulted in pip spending "forever" (i.e. longer
than the test timeout) trying to find a solution.
This PR removes that pin of …

Fix CI broken by dependency package changes

---

parsl/addresses.py

Changes made in my efforts to get Parsl working minimally on Windows.
- Do not crash when fcntl is not found.
Addresses #1878, though I would not claim I will fix it completely.

Improve support for Windows

---

parsl/channels/local/local.py

This was showing up as a hang when the qstat command launched by
the grid_engine provider returned a very large output: the process
would not exit until stdout had been read enough to empty buffers,
but stdout would not be read until the process had been exited.
Python provides `communicate` to deal with exactly this sort of
complexity, so this PR switches to using that.
Found by Quentin Le Boulc'h
Fixes #2102 

Fix a race condition in the local channel

---

parsl/monitoring/db_manager.py
parsl/monitoring/message_type.py
parsl/monitoring/monitoring.py

This PR makes RESOURCE_INFO messages be in the same format as other
monitoring messages:  ( ( tag, message ), address)
This is part of ongoing rationalisation of monitoring messaging that
will allow any kind of message to be sent over any monitoring channel,
from any location.

Regularise monitoring RESOURCE_INFO messages

---

parsl/providers/slurm/slurm.py

This adds a default to the partition parameter of None, to make it
behave like the account parameter.
The documentation for partition and account parameters is made a
bit more verbose to distinguish between omitting a parameter and
specifying a python None value.
See issue #2125 

Improve docs and defaults for slurm partition and account parameters.

---

parsl/executors/high_throughput/interchange.py

PR #2104 introduced a result channel heartbeat. However, this heartbeat
resulted in the idle time of managers being updated on each heartbeat.
Because of this, no manager ever appears to be idling for very long.
And because of this, the scale down code will not select any manager
for scaling down.
This PR makes result channel messages not update the idle time if
a manager already has an idle time: a result channel message (either
a result or a heartbeat) now means:
"I am (still) idle", rather than "I am idle starting from now".
There is no CI test for this (before or after). See issue #1885 

Fix htex scale down breakage due to overly aggressive result heartbeat

---

parsl/executors/high_throughput/interchange.py

Poller registration for task_incoming happens in
migrate_tasks_to_internal

Remove a commented out line of dead code in htex

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py

Prior to this PR, the monitoring hub decided it was time to exit
by relying on the absence of a python version string in WORKFLOW_INFO
messages that it was sent.
This PR replaces that with an explicit exit field, which makes
the shutdown logic easier to read. It should not change any other
behaviour.
This is part of an ongoing sequence of PRs attempting to simplify monitoring message flow.

Make monitoring hub exit condition more explicit

---

README.rst

when viewing the readme on github, the link did not work

trying to fix broken link in GitHub

---

CONTRIBUTING.rst

I tested this using anonymous mode in my browser: the old links tell me they are expired. The new one invites me to sign up.
Fixes #2145

Update slack join links to currently unexpired link

---

parsl/tests/test_bash_apps/test_error_codes.py

The bash formatting test is removed, as that implicit formatting was
removed in PR #1034
Re-enable div_0 bash error code test. This was disabled as part of the
large set of tests disabled in the PR #652 testpocalypse. But on review
it should be a valid test that we expect to pass.

Tidy bash error codes tests

---

docs/userguide/checkpoints.rst
parsl/launchers/launchers.py
parsl/providers/lsf/lsf.py
parsl/providers/lsf/template.py

The current LSF provider is used only on Summit, but can't be used on some other computers that use a slightly different LSF.
For example, the SUSTech LSF-based HPC cluster differs in the following aspects.
(1) It requests resources based on `the number of cores`, rather than the number of nodes `#BSUB -nnodes ${nodes}` on Summit. 
```
#BSUB -n 80 ##number of total cores
#BSUB -R "span[ptile=40]" ##40 cores per node
```
(2) The job submission requires to specify the queue `#BSUB -q short ##queue name`.
(3) It does not have a project specification `#BSUB -P project`.
(4) `Bsub` command requires a redirection symbol `<`, i.e., `bsub < job_script`.
This PR updates the LSF provider to make it more friendly to general LSF providers.
The PR also adds an override option to mpirun launcher to …

Update LSF provider to make it more friendly for different LSF-based computers

---

parsl/executors/status_handling.py

Prior to this, the error message would be reported with no
in-context exception, and so would emit a line like this:
```
2021-11-26 18:21:10.761 parsl.executors.status_handling:111 [ERROR]  Exception:         STDOUT: /home/benc/parsl/src/parsl/runinfo/018/submit_scripts/parsl.localprovider.1637950869.7853742.sh: line 3: executable_that_hopefully_does_not_exist_1030509.py: command not found
NoneType: None
```
The NoneType: None happens there because no exception is in
scope at the moment.
After this change, the log reports:
```
2021-11-26 18:09:51.235 parsl.executors.status_handling:111 [ERROR]  Setting bad state due to exception
Exception:      STDOUT: /home/benc/parsl/src/parsl/runinfo/008/submit_scripts/parsl.localprovider.1637950190.2711153.sh: line 3: …
```

Make executor bad state exception log use the exception

---

parsl/tests/test_error_handling/test_htex_missing_worker.py

Without this, that DFK continues to exist and emit logs while other tests are happening.

Make missing worker test cleanup DFK at end

---

parsl/dataflow/futures.py

A long time ago there was a lot of complexity in AppFuture. This has
basically all been moved elsewhere, so there is nothing AppFuture
specific that is being represented any more.
This PR removes the almost-empty AppFuture repr, in favour of the superclass
repr.
This makes repr of AppFuture change from this:
<AppFuture super=<AppFuture at 0x7f4bfe06a730 state=finished returned int>>
to this:
<AppFuture at 0x7f2ce1aa6f70 state=finished returned int>

Remove AppFuture.__repr__, because superclass Future repr is sufficient

---

parsl/executors/workqueue/executor.py

WQ recently introduced an additional resource constraint: workers can be aware of their remaining wall time, and tasks can be constrained to only go to workers with sufficient remaining time.
This has been used with success on the `desc` parsl branch for a few months.
cc. @dthain 

Allow use of WorkQueue running_time_min resource constraint

---

codemeta.json
parsl/providers/condor/condor.py

This commit ensures the condor provider doesn't throw an error for
pilot jobs it doesn't know about. It also adds the ability to make
calls to the scheduler in chunks of pilot jobs to help them timeout
less.
Fixes #2160 
Fixes #2159 

BUG fixed bug in condor provider for unknown pilot jobs

---

parsl/providers/provider_base.py

When job status output is large, parsl tries to create an abbreviated
summary.
Before this PR, when that code path runs, this error happens:
head = f.read(JobStatus.SUMMARY_TRUNCATION_THRESHOLD / 2)
TypeError: argument should be integer or None, not 'float'
There is a cross-python behaviour change here: in python 2,
/ 2 returns an int, but in python3 it returns a float.
python 2: 1/2 gives 0
>>> type(1/2)
<type 'int'>
python 3:  1/2 gives 0.5
>>> type(1/2)
<class 'float'>
This PR makes the code round-down to an int.

Fix type error when job status output is large

---

parsl/tests/test_channels/test_large_output.py

Regression test for #2210.
The local channel was hanging if the specified command gave too
much output, due to a race condition between process exiting and
pipes filling up.

Test large channel data

---

parsl/executors/status_handling.py
parsl/utils.py

Previously the code around block ID allocation was a bit fuzzy and
it looks like it could sometimes allocate the same block ID several
times in the presence of failure.
This is at least causing confusion in debugging frequent hangs in
CI.
A second ID allocator was used when a block ID had not already been
allocated, for simulating failures. This ID allocation code is changed
in this PR to use the same sequence counter.
Fixes #2181 

Allocate block ids uniquely

---

docs/userguide/monitoring.rst
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/monitoring/visualization/app.py
parsl/tests/test-viz.sh
parsl/tests/test_monitoring/test_basic.py
parsl/tests/test_monitoring/test_db_locks.py
parsl/tests/test_monitoring/test_fuzz_zmq.py
parsl/tests/test_monitoring/test_memoization_representation.py

This change was made to keep all parsl files in runinfo and to maintain a sense of tidiness.
Fixes #2136

Move monitoring.db to runinfo

---

.github/workflows/ci.yaml
Makefile
README.rst
parsl/dataflow/dflow.py
parsl/executors/errors.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/tests/site_tests/test_provider.py
parsl/tests/site_tests/test_site.py
parsl/tests/sites/test_dynamic_executor.py
parsl/tests/test-viz.sh
parsl/tests/test_checkpointing/test_python_checkpoint_1.py
parsl/tests/test_checkpointing/test_python_checkpoint_2.py
parsl/tests/test_checkpointing/test_python_checkpoint_3.py
parsl/tests/test_checkpointing/test_task_exit.py
parsl/tests/test_error_handling/test_htex_basic.py
parsl/tests/test_error_handling/test_htex_missing_worker.py
parsl/tests/test_error_handling/test_htex_worker_failure.py
parsl/tests/test_error_handling/test_retries.py
parsl/tests/test_flowcontrol/test_one_block.py
parsl/tests/test_flowcontrol/test_python_diamond.py
parsl/tests/test_staging/test_1316.py
parsl/tests/test_threads/test_lazy_errors.py
setup.py

CI was down to less than 50% of builds passing, and then to 100% failure with a new release of pandas.
This PR contains a number of distinct changes which I have tried for fixing and debugging CI, none on which were in themselves completely reliable.
This PR has passed 6 times in a row with no code changes, so the reliability looks like it is massively increased. I still think there is some broken behaviour, as the reason that 6 is only 6 is because the 7th to last test hung, and all that's changed since then is addition of some logging around the suspicious area.

CI fixing megablast

---

parsl/dataflow/strategy.py

For htex_auto_scale instead of removing only 1 block at most in case there are more slots than tasks, remove try to remove many blocks so that the number of slots matches the number of tasks. This is of course still limited by how many blocks have reached the configured max_idletime.
Fixes #2195

Make scale in of htex_auto_scale more effective

---

.gitignore
parsl/tests/conftest.py
test-requirements.txt

Older pytest was causing problems in a couple of places: python 3.10 support, exaworks development
Newer pytest changes/removes how it deals with `nose` test compatibility; but parsl stopped doing nose tests in #272 in 2018, so this PR removes those vestiges.

Eliminate pytest nose and upgrade pytest version

---

setup.py

This allows source code which uses Parsl to take advantage of the
currently very limited type annotations that are present on Parsl
code if/when they are checked with mypy.
Prior to this, those type annotations were used for:
- internal self consistency with mypy
- runtime checking with typeguard
I've been seeing increasing use of type annotations on user code
recently so I think it makes sense to export our declarations for
use by downstream users.
This work is driven most immediately by integration with exaworks,
where the psij code is heavily type checked and I would like the
interface code to be as type-checked as possible given what exists
already.

Export type annotations using PEP561 convention

---

parsl/errors.py

This error can be raised when an optional module failed to import
for any reason, not just because the optional module is missing.
A recent example is that sqlalchemy released a new incompatible
version which parsl's requirements spec was not protecting against.
This was fixed in PR #1994.

Rephrase optional module missing error

---

parsl/dataflow/dflow.py

This value is a surrogate key generated by parsl. Reuse of runids will break lots of assumptions about runid uniqueness. It shouldn't be user configurable.
There are other  fields for identifying run identity according to the users identity rules (workflow name and version), as well as the ability to use the generated runid as a key into a different user-controlled data structure.

Remove a TODO about runid configuration

---

.github/workflows/ci.yaml
README.rst
codemeta.json
docs/quickstart.rst
setup.py

Python 3.10 was released 2021-10-04  (see https://www.python.org/dev/peps/pep-0619/)
Python 3.6 was end-of-lifed 2021-12-23 (see https://www.python.org/dev/peps/pep-0494/#lifespan)

Add python 3.10, drop python 3.6

---

parsl/monitoring/monitoring.py

Although the naming and previous docstring suggest that the two parameters
work together to define a single port which either is specified explicitly
or comes from the supplied range, this is not true.
Two listening ports are used:
* one for the UDP receiver for message from workers
and
* one for ZMQ queue from from the htex interchange (or any other executor
that wants it)
The UDP port is either `hub_port` or an arbitrary system-allocated port,
ignoring hub_port_range.
The ZMQ queue port is always chosen from `hub_port_range`, which has a
default value so a user is not required to specify it. `hub_port` is never used
for this port.

Correct misleading docstring on confusing hub port vs hub port range

---

parsl/monitoring/monitoring.py

Callables lose their name attributes when monitoring is turned on as the wrapper function for monitoring doesn't wrap callables correctly. More details can be found in this [issue](https://github.com/cooperative-computing-lab/cctools/issues/2813). Issue is now fixed using wrap decorator from functools module.

adds wraps to monitoring so functions have their names back

---

parsl/executors/workqueue/executor.py

Before callables when submitted to WorkQueue (WQ) executor are categorized using their name attribute. Now callables can explicitly set their categories before submitted to WQ.
Fixes [this issue](https://github.com/cooperative-computing-lab/cctools/issues/2813).

Adds support for specifying callables' categories in WorkQueue executor

---

mypy.ini
parsl/providers/provider_base.py

Most of these annotations have been brewing in the `benc-mypy` branch for a while. My recent work on exaworks psij, which has much stronger type-checking, has pushed me to want these annotations in mainstream parsl while implementing a parsl provider which interfaces with psij.
Implementing this interface with psij and using these type annotations has revealed a bug when a job status is created with a `None` stdout or stderr: a default None stdout or stderr path causes an exception when accessing the `stdout` or `stderr` property. This is fixed to return `None` in that case.
~~This PR uses some python >=3.7 syntax, so probably can't be merged unless Python 3.6 support is dropped - see PR #2208 - keeping this PR as draft until then~~
- Bugfix
- New feature (non-breaking change that adds …

Add type annotations for provider_base.py and fix some bugs there

---

parsl/dataflow/dflow.py
parsl/dataflow/usage_tracking/usage.py

This replaces unsafe use of self.tasks[] in shutdown along with a handful of ad-hoc state counting variables with a more regular counting mechanism for all task states that never references self.tasks.
see issues #2178 for this particular report, 
and #2014 for overview of tasks[id] elimination.

Eliminate tasks[id] when reporting final status counts

---

parsl/dataflow/dflow.py

task_record stores data as dictionary entries, not as attributes,
and PR #2192 used the wrong membership test for that.
Because of that, old task states were not being decremented ever.
Prior to this commit:
2022-02-17 15:51:50.231 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.unsched: 298
2022-02-17 15:51:50.231 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.pending: 298
2022-02-17 15:51:50.231 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.running: 0
2022-02-17 15:51:50.231 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.exec_done: 238
2022-02-17 15:51:50.232 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.failed: 36
2022-02-17 15:51:50.232 parsl.dataflow.dflow:956 [INFO]  Tasks in state States.dep_fail: 11
2022-02-17 15:51:50.232 …

Fix broken PR #2192 task state counting

---

parsl/executors/workqueue/executor.py

WorkQueueExecutor status reporting did not properly lock the task status
dictionary. This commit adds that lock.
When task submission happens at the same time as flow control, for example
when a very large number of tasks are submitted, this exception can occur:
2022-02-23 14:42:14 parsl.dataflow.flow_control:114 MainProcess(112424) FlowControl-Thread [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
File "/home/ir-shir1/rds/rds-iris-ip005/ras81/wq_env/lib/python3.8/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
self.callback(tasks=self._event_buffer, kind=kind)
File "/home/ir-shir1/rds/rds-iris-ip005/ras81/wq_env/lib/python3.8/site-packages/parsl/dataflow/task_status_poller.py", line 104, in …

Fix race condition between WorkQueue task submission and scaling

---

parsl/tests/test_error_handling/test_retries.py

Without this, the tasks continue to run while subsequent local
tests happen. This is at the least confusing in logs - I haven't
checked if it introduces any actual testing problems.

Make retry tests wait for all launched tasks before finishing

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py

This means monitoring messages are handled based on their
declared tag type, rather than how they are received by the
database manager.
Specifically, RESOURCE_INFO messages are now handled more
like other messages.
This is groundwork for future PRs which will, for example,
allow remote tasks to deliver their resource messages over
htex's existing channels, rather than via UDP.

Dispatch monitoring messages on tag type, instead of queue name

---

parsl/app/bash.py

Workaround for #2233. Provides a fake name for functions that got serialized w/o a __name__ attribute

Workaround for BashApps with partial.functools

---

parsl/data_provider/files.py

now:
<File at 0x7f5259991940 url=/home/benc/parsl/src/parsl/outputs/test_parallel/out.0.txt scheme=file netloc= path=/home/benc/parsl/src/parsl/outputs/test_parallel/out.0.txt filename=out.0.txt>
before:
<<class 'parsl.data_provider.files.File'> at 0x7fce53e9d8e0 url=/home/benc/parsl/src/parsl/outputs/test_parallel/out.0.txt scheme=file netloc= path=/home/benc/parsl/src/parsl/outputs/test_parallel/out.0.txt filename=out.0.txt>

Tidy representation of File class

---

parsl/app/errors.py

Before:
('calibrate', 1)
After:
'bash_app calibrate failed with unix exit code 1'

Make str of BashExitFailure be clearer about fields

---

parsl/executors/errors.py
parsl/executors/flux/executor.py
parsl/executors/high_throughput/executor.py
parsl/executors/low_latency/executor.py
parsl/executors/status_handling.py

I've seen the ambiguity that lead to this in the wild with LSST - naming a provider when an executor should have been named, in a ScalingFailed error.

Fix type ambiguity between executor object and executor label in scaling failed, along with TODOs

---

parsl/dataflow/dflow.py

Remove logger.warn (replace with warning) - this is causing pytest warnings that .warn is deprecated

---

docs/userguide/configuring.rst
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/sites/test_affinity.py

Adds an option to HTEx for pinning each worker to a different GPU. Needed for systems that include multiple GPUs per node when tasks do not scale to >1 GPU and there is no mechanism in the scheduler for partitioning GPUs.

Add support for pinning workers to an accelerator

---

parsl/providers/slurm/slurm.py

When squeue is called with at least one job ID which is active, it returns successfully. If it is called with only jobs that have already completed, it returns an error. This situation happens if no blocks are currently running.
The same logic (checking if the existing status is terminal) is used in the [local](https://github.com/Parsl/parsl/blob/master/parsl/providers/local/local.py#L77) and [kubernetes](https://github.com/Parsl/parsl/blob/master/parsl/providers/kubernetes/kube.py#L208) providers.
Fixes #1588

only query active slurm jobs

---

parsl/providers/slurm/slurm.py

PR #2259 introduced a type error which was not found by CI as we have no slurm testing in CI.
cc @aclowes 

Fix slurm provider type error broken by PR #2259

---

parsl/providers/slurm/slurm.py

Fix misspelled 'squeue' in log message

---

parsl/providers/slurm/slurm.py

This PR tries to make logging clearer when SlurmProvider receives unknown statuses. Most immediately this is driven by #2255.
JobState enums are now output using `str()` which renders their symbolic name, instead of numerical state value.
old:
2022-05-11 03:30:24.572 parsl.providers.slurm.slurm:158 [DEBUG]  Updating job 58928398 with slurm status R to parsl status 2
vs
new:
2022-05-11 03:37:51.814 parsl.providers.slurm.slurm:158 [DEBUG]  Updating job 58928492 with slurm status R to parsl state JobState.RUNNING
If a state does not exist in the translation table, a warning is logged:
2022-05-11 04:05:21.818 parsl.providers.slurm.slurm:159 [WARNING]  Slurm status XXX is not known

Clarify log messages when SlurmProvider gets unknown statuses

---

parsl/monitoring/monitoring.py

These logs were generally inaccessible on workers, and mostly useless. The log statements themselves are left in place in case someone wants to hack worker logs back on again.

Stop per-task wrapper logging to /tmp

---

parsl/executors/high_throughput/zmq_pipes.py

this warning is not due to a full pipe, but due to an unresponsive pipe - eg if the interchange has gone away.
rephrasing to make less confusing.

broaden error message text for htex zmq pipe errors

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/monitoring_info.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/monitoring/monitoring.py

This will be used by the high thoughput executor to
send monitoring messages over its existing channels,
rather than using UDP.

Add an HTEXRadio monitoring radio mode

---

parsl/dataflow/job_error_handler.py

This is unused -- it would affect how __init__ is called in the presence of subclasses, but this class is not designed for subclassing/multiple inheritence

remove object/init boilerplate

---

parsl/monitoring/monitoring.py

This comes from some outdated terminology to go along with
UDPRadio.

Remove the only reference to 'dish' in the monitoring code

---

parsl/executors/workqueue/executor.py
parsl/monitoring/monitoring.py

This is intended to replace UDP based monitoring for work queue when a shared file system is available.

Add a filesystem based monitoring radio

---

mypy.ini
parsl/dataflow/usage_tracking/usage.py
parsl/executors/high_throughput/interchange.py
parsl/executors/workqueue/executor.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/utils.py
requirements.txt

Previously, in `ps`, all processes appeared with the same commandline,
that of the process which which was used to launch parsl (for example,
python3 ..., or pytest ..., or bps ... in one LSST project).
This commit gives more interesting names.
Perhaps the process name should include some kind of workflow identifier so as to
disambiguate? That's an issue for users running multiple workflows, most likely spread
across time when leftover processes are left behind. Although the regular process
three would show relationships.
This patch deals with processes forked with multiprocessing, in:
* monitoring
* high throughput executor
* work queue executor

Set forked process names for debugging memory/cpu usage

---

parsl/tests/conftest.py

Use __name__ for conftest.py logging so logs appear under its own name

---

README.rst
setup.py

A recent networkx release, 2.8.4, does not work with parsl-visualize. The previously working version was 2.5.x, and this PR adds a constraint for that.
Fixed errors look like this:
```
File "/home/benc/parsl/src/parsl/parsl/monitoring/visualization/plots/default/workflow_plots.py", line 251, in workflow_dag_plot
name = dic['task_status_name'][node]
KeyError: '0'
```

Add constraints for networkx for parsl-visualize

---

parsl/monitoring/monitoring.py

There is a significant cost to waiting for zmq messages in the way that it is
implemented in the monitoring router, because of timeouts when there is no
traffic on a particular channel.  That imposes a maximum reception rate
(eg the reciprocal of the sum of all timeouts in the receive loop) which can
cause massive queueing and memeory bloat.
Using a single ZMQ socket instead of several reduces this bloat.

Use a single ZMQ socket in monitoring router.

---

parsl/executors/extreme_scale/mpi_worker_pool.py
parsl/log_utils.py

Adds a `stream` keyword argument to `set_stream_logger` function so that the user can specify whether the `StreamHandler` directs to `sys.stderr` or `sys.stdout`.
For my work on a TACC Frontera project, I want this stream to be directed to `sys.stdout` instead of the default `sys.stderr` for the instantiated `StreamHandler`.

Add option to specify stream for stream logger

---

parsl/executors/high_throughput/interchange.py
parsl/monitoring/monitoring.py

Prior to this, the monitoring router reformatted NODE_INFO messages.
This PR regularises the format of NODE_INFO messages at the point
that they are initially sent, so that the router does not have to
reformat them.
The router still adds a run_id field to the NODE_INFO message, as
before, as this information is not available in the interchange where
the messages are generated
This moves around these non-routing behaviours in MonitoringRouter:
* reformatting an htex last_heartbeat time into a more suitable type
* putting the message timestamp into the message dictionary

Regularise NODE_INFO message format

---

parsl/tests/test_python_apps/test_fibonacci_iterative.py

Previously, some tasks were not waited for, which make debugging
in the test suite hard as they would run over into the next test
run.
This PR removes some intermediate value complexity from the test
and uses previous values/futures from results[]
Specifically, every launched app now goes into results[] which
means each will now be waited for by the end of the test.
The potentially-unrecorded second call to get_num in the loop is
removed.

Make the interactive fibonacci test wait for all of its tasks

---

parsl/executors/high_throughput/interchange.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py

Components such as the interchange and monitoring router
log to their own files.
However, log messages from those components are also passed
up to the root logger. In more complicated environments,
that root logger may also log those messages, which is
undesirable.
This commit turns off upwards propagation of log messages
from those separate components to the root logger.

Do not propagate logs for components with own log files

---

parsl/dataflow/dflow.py

Part of #2014 tasks[id] elimination project

Use task records instead of task IDs in checkpoint queue.

---

mypy.ini
parsl/monitoring/monitoring.py

Instead of killing the monitor process using terminate,
use a multiprocessing event, as process terminate can
sometimes corrupt shared queues, according to documentation.
Send the final resource message after resource monitoring
has completed - otherwise, the "last" message is not
necessarily before the final resource monitoring message.

Rework resource monitoring termination

---

parsl/monitoring/monitoring.py

This calculates the total of chld user/system time
by summing the total for each child on each
monitoring report, rather than calculating a
delta for each child and accumulating that.
This should also reduce floating point rounding
errors, but is possibly more expensive: linear
in number of children ever, rather than in
current number of children.

Accumulate child user/system time more accurately

---

parsl/dataflow/job_error_handler.py
parsl/executors/base.py
parsl/executors/status_handling.py

Prior to this commit, job error handling failures
were dealt with in two places - a "default" with 3 retries,
and for all status handling executors, in handle errors,
with an "init blocks" limit which overrode that.
This removes the default handling -- 3 is an unconfigured
arbitrary value at the moment, and in practice this code
path isn't used because our error handling executors are
all status handling executors.
Handling errors at the executor level is now mandatory,
but can still be delegated to simple_error_handler.
This is part of an ongoing move towards BlockProviderExecutor
holding the relevant code (which can then be overridden
if desired) rather than having a second non-inheritence-based
default path.

Put default job error handling in one place

---

parsl/executors/high_throughput/process_worker_pool.py

The return code of the send is always None - errors are
indicated by exceptions.
This message has confused me for years.

Do not log None return of heartbeat send

---

parsl/monitoring/visualization/models.py

I addressed the issue described in https://github.com/Parsl/parsl/issues/2266#issuecomment-1142077440 and https://github.com/Parsl/parsl/issues/2266#issuecomment-1150712877, by adding the missing entry `task_time_invoked` to the `Task` class in `parsl/monitoring/visualization/models.py`. Unless I'm missing something, this should close the corresponding issue.
Fixes #2266 

Fix Task class in models.py, adding task_time_invoked column (ref #2266)

---

parsl/executors/high_throughput/executor.py

Using two names for the interchange process/queue process makes the code a
bit harder to read.

Refer to the interchange process rather than queue process

---

parsl/log_utils.py
parsl/tests/test_checkpointing/test_periodic.py

This is useful when trying to understand which components are writing which logs, when their logging overlaps in time.
It should replace the less accurate manual style of annotating some log messages with [TOPIC] prefixes
This PR also adds a unix timestamp, which is accurate to microsecond resolution, which is also useful when trying to correlate between components.

Log process, thread, function metadata in parsl.log

---

parsl/executors/high_throughput/interchange.py

Previously, the manager field was logged, even though the log
claimed it was the (JSON) message. This PR corrects that.

Fix bad message logging on interchange deserialization failure

---

parsl/executors/workqueue/executor.py

This includes: renaming processes, adding wrap_with_logs
to log exceptions will escape the two worker processes,
and rephrasing the initial scaling out failure message.

Improve assorted debugging information for work queue

---

parsl/executors/high_throughput/process_worker_pool.py

Log that workers were started, rather than synced

---

parsl/dataflow/dflow.py

This is part of ungoing debugging of parsl shutdown,
especially tied to cleanup running inside a python
process that has a lot of other stuff going on,
eg BPS in lsst/desc

Add wrap_with_logs around cleanup calls

---

parsl/tests/conftest.py

In general when re-using config files in the test suite,
fresh_config() is a cleaner choice than using config, as
it generates a whole new structure each time.
Individual configs can't, in general, be loaded using
parsl.load() more than once due to mutability of the
component objects (although in many cases this might work).
Generating a config at import time is also sometimes
expensive - for example, it often requires a network lookup
to determine IP address. Using fresh_config() defers
that activity until a particular config is actually
needed.

Use fresh_config() in pytest if config is not available

---

parsl/tests/test_scaling/test_scale_down.py

This was disabled due to frequent failure (see issue #1885) but this test
has been re-enabled in the `desc` branch for a while and has not caused
trouble, so this commit should re-enabled it in master.
Issue #1885 also notes the utility of this test in discovering scaling-in
breakage - which gives some pressure to re-enable this test.

Re-enabled scale down test

---

parsl/providers/provider_base.py

mem and cores per node are used by htex and the slurm
provider, not by the strategy code.

Correct documentation for mem/cores per node

---

parsl/executors/threads.py

When parsl shuts down at the end of a python process, previously it would
not wait for thread pool tasks to complete.
However, the underlying thread pool executor (from the concurrent.* library)
would then cause the python process exit to stall until thread-local tasks
are complete.
This PR makes parsl also wait, so that it is clearer when debugging slow
or hanging shutdown that thread-local tasks are involved.
In the case of shutting down a DFK at process exit, this should not
significantly delay shutdown any futher.
In the case of shutting down a DFK in the middle of a process, this will
cause longer delay, but in the absence of the ability to cancel tasks
in the thread local executor, this maybe the best thing to do (rather than
claiming that shutdown has actually completed when tasks …

Make parsl wait for ThreadPoolExecutor tasks to complete during shutdown

---

parsl/executors/status_handling.py

Elaborate on x->y notation to be clear what the
x and y values are in the log message

Disambiguate which executor blocks are launched on

---

parsl/executors/high_throughput/executor.py

If this case is firing, then something is wrong.

Make log about queue management duplicate thread be an error

---

parsl/monitoring/monitoring.py

This allows accumulation to run more frequently, to
give more accuracy, without generating monitoring
message traffic load.
This PR also adds a final send when the monitoring
loop terminates, to capture the final resource usage
which in the DESC case was especially interesting.

Separate accumulation and sending of resource info

---

parsl/monitoring/monitoring.py

This is an unintuitive API difference:
> write_chars (Linux): the amount of bytes which this process
> passed to write() and pwrite() syscalls (cumulative).
> Differently from write_bytes it doesn’t care whether
> or not actual physical disk I/O occurred.
from the python psutil pages.
I think _chars is the one that is most relevant - especially
in an environment using network filesystems in preference to
local disk.

Use more useful counter for IO read/write in resource monitor

---

parsl/executors/high_throughput/interchange.py

Prior to this, it was logged for each outstanding task.

Send only log manager failure report once per manager

---

parsl/config.py

Executors and checkpoints only need to be Sequences, not Lists -- they don't need to be edited, although parsl.config has an option to replace the entire executor list.
This can help with covariance in type checking elsewhere.

Update parsl.config type annotations

---

parsl/tests/test_bash_apps/test_error_codes.py

Tighten exception catching in bash error code test, because e.exitcode is not defined for arbitrary exceptions

---

parsl/dataflow/memoization.py

Being clear about which entry is being replaced (identified by
hash sum) is important.
function name is not so relevant when debugging - that info is
available via task id - so is removed from message

Include hashsum in app cache update logs, remove function name

---

parsl/executors/high_throughput/interchange.py

This poll period is specified as an argument to the
Interchange() constructor, and doesn't also need to
be settable by start()

Remove never-used interchange.start poll_period arg

---

parsl/dataflow/task_status_poller.py

Sending every block on every iteration is extremely expensive when runs
are made with very many blocks (for example, some HTC configurations).
This PR reduces the amount of network traffic and the number of rows
recorded in the monitoring database block table.

Only send block monitoring status on change

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

When all tasks are the same app, the total task line was plotting over the top of the per-app tasks.
I think it is better to see the per-app tasks rather than the total tasks.

Move total tasks to back of plot so that doesn't override tasks

---

parsl/dataflow/strategy.py

In one particular test in CI, no blocks were started and the logs look like
this, as if after one execution attempt, the executor is not strategised over
any more.
```
1652440511.041642 2022-05-13 11:15:11 INFO MainProcess-9443 MainThread-139718497531712 parsl.dataflow.dflow:685 launch_task Parsl task 0 try 0 launched on executor htex_Local with executor id 1
1652440511.301012 2022-05-13 11:15:11 DEBUG MainProcess-9443 FlowControl-Thread-139713557300992 parsl.dataflow.strategy:163 _general_strategy general strategy starting
1652440511.942638 2022-05-13 11:15:11 DEBUG MainProcess-9443 FlowControl-Thread-139713372706560 parsl.dataflow.task_status_poller:52 send_monitoring_info Sending message [] to hub from task status poller
1652440511.944299 2022-05-13 11:15:11 DEBUG MainProcess-9443 …
```

Add debugging around strategy failures

---

parsl/executors/high_throughput/executor.py
parsl/executors/status_handling.py
parsl/executors/workqueue/executor.py
parsl/tests/configs/htex_local_alternate.py

This is motivated by two use cases:
* at in2p3 with htex submitting large numbers of blocks into
many queues results in expected block failure. Because this
failure is expected, it should not result in permanent executor
failure.
* the psi/j slurm provider reports failures differently (more
accurately?) which seems to trigger this behaviour

Allow bad block based permanent failure to be disabled

---

parsl/providers/pbspro/pbspro.py

PBSPro defaults to using the Torque qstat command which is limited in the number of characters used to represent a job id. This is a problem on the ALCF Polaris machine which has long job names (id.polaris.alcf....) which are shortened in qstat (e.g., 123.polaris.al*). These shorthand job ids do not resolve in the dictionary of resources, causing the provider to fail when scaling.
This PR provides a customized PBSPro status() function that uses `qstat -f -F json` to retrieve the full job description as json and then extracts the long job id from the dictionary of jobs.

Change pbs qstat to use json format

---

parsl/config.py

This makes the possible checkpoint mode strings explicit at the type level.

Tighten type specification for checkpoint_mode

---

docs/userguide/checkpoints.rst
parsl/config.py
parsl/dataflow/dflow.py
parsl/tests/test_checkpointing/test_python_checkpoint_1.py

initially these did not need to be different, but
since #1512 introduced garbage collection, there is
now a distinction:
* with no checkpointing, tasks can be garbage collected
immediately.
* with manual checkpointing, tasks should not be garbage
collected until they are checkpointed.

Introduce separate None and manual checkpoint modes

---

parsl/executors/high_throughput/interchange.py

This situation causes the interchange to shut down,
so it is more than a warning.

Log manager/interchange version mismatch as errors

---

parsl/dataflow/dflow.py

Correct docstring: a parsl config is not a dict

---

parsl/dataflow/futures.py

This comes from the benc-mypy branch

Add type annotations to parsl.dataflow.futures

---

parsl/monitoring/monitoring.py

This is inherited from copy-paste of a different radio implementation
where serialisation happened at this point. In the HTEX radio case,
serialisation happens inside the htext implementation so doesn't
happen here.

Remove unused try block around assignment

---

parsl/executors/high_throughput/interchange.py

This is for consistency with parsl.log which got
function names in PR #2328

Log python function name in interchange log lines

---

parsl/executors/high_throughput/interchange.py

This is never used - or at least, there is no other
SHUTDOWN literal in the parsl codebase.

Remove unused interchange SHUTDOWN codepath

---

parsl/executors/high_throughput/interchange.py

This loop was to check the kill event, which is
no longer used by this thread (see PR #2423), so there
is no need to loop repeatedly in the absence of
messages.

Remove periodic timeout in interchange task pull loop

---

parsl/executors/high_throughput/interchange.py

The interchange is shut down by process termination, so
this code path is not needed.

Ignore kill event in interchange command server

---

parsl/executors/high_throughput/zmq_pipes.py

This reduces the logging associated with a queue full event as the
delay period will get large rapidly.
In exchange this probably makes message delivery during task submission
a bit slower when a queue full event happens, although I have not benchmarked
that.

Use exponential, rather than linear, backoff when interchange task full

---

parsl/executors/high_throughput/interchange.py

Use only symbolic log level, not number constant, in interchange docstring

---

test-requirements.txt

See issue https://github.com/python/mypy/issues/13627
CI builds were failing due to this incompatibility which is fixed in mypy 0.981

Upgrade mypy to address bug in mypy 0.961 vs python 3.10.7

---

Makefile
tag_and_release.sh

This PR adds a new option to `tag_and_release.sh` script to help with weekly releases.
The steps to doing the weekly release would go like this:
1. Run tests and confirm all green
2. Run the github action here -> `https://github.com/Parsl/parsl/pull/2441` 
* This action will run `version_update` on master bumping the version to "YYYY.MM.DD"
* The action will do `python -m build` instead of our current `setup.py` calls
* Action will deploy now to testpypi, and later to pypi.

Adding an update_version option to tag_and_release

---

.github/workflows/python-publish-to-testpypi.yml

GIthub action that publishes to testpypi. Plan is to test this over there and then update to push to pypi.
This PR is missing changes to `tag_and_release.sh` that will come separately.

Github action to publish to testpypi

---

.github/workflows/python-publish-to-testpypi.yml

Minor mod to fix syntax error in `workflow_dispatch` trigger.

Attempt to fix syntax error in publish action

---

parsl/dataflow/dflow.py

The removed parameters (func, args and kwargs) are already contained in the TaskRecord so do not need duplicating.

Remove redundant parameters from launch_task

---

parsl/monitoring/monitoring.py

See PEP257: "Multi-line docstrings consist of a summary line [...]"

Remove "internal" prefix on monitoring docstrings

---

.github/workflows/python-publish-to-testpypi.yml
setup.py
tag_and_release.sh

This PR brings in 4 changes:
* Changes to the github action to allow a configurable `suffix` to be passed from the manual `workflow_dispatch` option.
This allows you to push `dev` or `alphas` 
* Github release action now points at test.pypi and will need to be reverted to point at pypi in a later PR.
* The optional package `psi-j-python` is now removed since pointing to github repos for modules are not allowed by pypi.
* Update version no longer checks if the version exists on pypi, but instead relies on pypi to raise an error on version name collision.

Tweaking release automation

---

.github/workflows/python-publish-to-testpypi.yml

* Point at pypi instead of test.pypi
* Do scheduled push to pypi at 09:42 on Wednesdays from main.

Follow up to get release automation point at Pypi

---

parsl/dataflow/dflow.py

See issue #2014 for overview of tasks[id] elimination.

Eliminate self.tasks[id] from wait_for_current_tasks

---

parsl/executors/high_throughput/interchange.py

This thread does not poll kill_event any more, so does not need to loop fast for polling

Remove unneeded RCVTIMEO from interchange command channel

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios.py

This is part of splitting up the large parsl.monitoring.monitoring module (933 lines). Radios need to live somewhere they can be accessed by a soon-to-be moved remote monitoring wrapper, without importing the full monitoring module.

Move monitoring radios into their own module

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/launchers/launchers.py
parsl/multiprocessing.py
parsl/tests/sites/test_mpi/mpi_hello
parsl/tests/sites/test_start_method.py

Polaris, in particular, has an interaction between MPI and fork which makes HTEx worker pools fail to function when used with an MPILauncher. This PR adds the ability for HTEx to launch workers by spawning a new process rather than forking.

Support using spawn instead of fork for HTEx

---

parsl/app/python.py
parsl/tests/test_error_handling/test_python_walltime.py

python_app walltime is implemented as a wrapper. That wrapper did not use `@wraps`, unlike many other parsl function wrappers.
This resulted in the app name being "wrapped", the name of the wrapper.
This PR adds `@wraps` so that the app name is preserved.
This PR also adds a test that fails before this change, and passes afterwards.
Fixes #2449

Add wrapper renaming to python app walltime. Fixes #2449

---

parsl/executors/workqueue/executor.py

Previously Work Queue Executor working files were placed under the rundir top level. This resulted in conflicts when more than one Work Queue Executor is used in a run.
This moves those files down one level into a per-executor directory.
Fixes issue #2453

Fix conflicting paths in multiple WQ executors.

---

parsl/dataflow/flow_control.py
parsl/dataflow/job_error_handler.py
parsl/dataflow/job_status_poller.py

This aligns with the JobStatus and JobState classes.

Rename task_status_poller because it polls jobs not tasks

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

Previously, the CPU usage plot looked at resource reports grouped by task. This meant that when several tries happened for a task, the plots did not accurately reflect what happened, because they incorrectly compared cumulative CPU time counters from multiple tries.
This would result in CPU usage from second and further tries not being properly accounted for, and sometimes in the graph showing negative CPU usage.
This PR makes that plot reference resource usage records by both task_id and try_id together, instead of only the task_id.
Fixes #2477
Fixes #1494

Make resource usage plots try-aware

---

README.rst
setup.py

doc build is failing with
```
Warning, treated as error:
/home/runner/work/parsl/parsl/docs/1-parsl-introduction.ipynb::Pygments lexer name 'ipython3' is not known
make: *** [Makefile:52: html] Error 2
```

Add ipython3 version constraints to cope with newly release ipython 8.7.0

---

parsl/monitoring/visualization/templates/resource_usage.html
parsl/monitoring/visualization/views.py

This removed plot measures the mean CPU time across all resource readings for each task, and then makes a histogram of how many tasks fall into each bucket.
However, the mean cumulative CPU time across all resource readings (for a given task) doesn't really have a lot of meaning. The maximum value plot, which makes more sense, is retained by this PR.

Remove histogram of mean CPU time

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

Prior to this PR, the plot was generated by computing a histogram of one-second buckets, and each task contributed 1 second to each bucket that it overlapped, even when the task was only running for part of that second (the first and last seconds).
After this PR, a task only contributes a fraction of a second to the start and end buckets, based on the fractional part of the start/end timestamp.
For a workflow with many short running tasks, this will show a large decrease in worker usage: for example, the pytest test suite running with --config htex_local_alternate.py on my laptop goes from a peak of 50 workers in use (more workers than actually exist!) to a peak of 3.
See issue #2474 for more discussion and example plots.

More accurately record worker usage in efficiency plot

---

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py

The previous label, "total online workers", suggests that this line might vary over time as workers come online and go offline. This is not the case.
See issue #2474 

Relabel worker efficiency plot to show that total workers is constant

---

docs/faq.rst
docs/userguide/apps.rst
docs/userguide/data.rst
mypy.ini

Remove references to cloudpickle, sometimes replacing with dill

---

parsl/serialize/facade.py

It is unlikely that this will detect any problems serialization problems, and it is expensive under heavy loads - roughly doubling the cost of serializing complex objects, if they are not already in the cache.

Don't deserialize during serialization

---

docs/userguide/execution.rst

Flow control / scaling strategy choices are hard coded into the parsl source code in self.strategies in Strategy.__init__ and require patching the parsl source code to add more.

Remove documentation references to user-extensible flow control

---

parsl/executors/workqueue/executor.py

This is part of a fix for task #2473, but not all of it.
Prior to this PR, when Parsl decides that a work queue executor is permanently failed, it will attempt to set an exeception on all task futures, even tasks which already have received a result.
This results in an incorrect state exception, which then stops the rest of executor permanent failure handling.
This change to use .pop makes the Work Queue Executor behave more like the High Throughput Executor: completed task futures will not be stored in the list of tasks, and so (race conditions aside) will not get an exception set on them.

Make work queue executor pop tasks so failure handler does not see them

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py
parsl/monitoring/remote.py

Monitor wrapper closures are not cacheable by parsl.serialize, because they are created on invocation of an app. parsl.serialize code caching expects that repeated invocations of a function will use the same function code, which is not true in this case.
The main reason that this closure is generated on each invocation is because it contains invocation specific values: task_id and try_id.
This PR re-arranges the invocation of the monitor wrapper so that those two values are passed as additional parameters - effectively making a manual closure that is more amenable to parsl.serialize.
This PR introduces a new cache inside the montoring code, keyed by:
(run_id, f, radio_mode)
which is then used to cache wrapped app functions.

Move per-task params out of monitoring closure for cacheability
