Parsl/parsl

parsl/executors/high_throughput/process_worker_pool.py

This PR changes the SYCL environment variable for gpu discovery from SYCL_DEVICE_FILTER to ZE_AFFINITY_MASK.  I've been doing tests with SYCL devices and I found that setting both caused conflicts in some programs.  I was told in private communications that SYCL_DEVICE_FILTER has never been used or tested.  I removed it and added ZE_AFFINITY_MASK.

Changing environment variables for SYCL devices

---

parsl/providers/kubernetes/kube.py

If the `user_id` and `group_id` are specified in the Kubernetes provider configuration, the following error is thrown:
```
File "/src/main.py", line 101, in <module>
print(f'''[{cur_time()}] python replica {idx} result: {replicas[idx].result()}''')
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
raise self._exception
File "/usr/local/lib/python3.8/dist-packages/parsl/dataflow/dflow.py", line 288, in handle_exec_update
res = self._unwrap_remote_exception_wrapper(future)
File "/usr/local/lib/python3.8/dist-packages/parsl/dataflow/dflow.py", line 481, in _unwrap_remote_exception_wrapper
result = future.result()
File …
```

Fix bug in securityContext user_id and group_id

---

Makefile
parsl/monitoring/queries/pandas.py
parsl/monitoring/visualization/views.py

This is intended to allow other users to get the same pandas dataframe view of monitoring data as is used in parsl-visualize.
A couple of more complex SQL queries are left behind in monitoring, as they don't seem so generalisable.

Factor many queries used in parsl-visualize into reusable library

---

docs/reference.rst
parsl/app/errors.py
parsl/app/futures.py

This performs stronger runtime type checking on the initializer, removes code paths where a DataFuture is constructed with a string (which was turned into an error case in PR #1412)
and removes NotFutureError, as that type error is now handled by the typeguard.typechecked decorator.
This comes from work on the benc-mypy branch.

Tidy DataFuture initialisation

---

mypy.ini
parsl/executors/threads.py

This comes from the benc-mypy branch.
See mypy issue https://github.com/python/mypy/issues/9091 for a bit more discussion about this option.

Enable no-implicit-optional and fix the one error that occurs

---

mypy.ini

This gives motivation to remove casts that can become redundant as more type information becomes available as type annotations are added later.
This comes from benc-mypy branch.

Switch on mypy warn-redundant-casts

---

mypy.ini
parsl/dataflow/job_error_handler.py

This means that names need to be defined in the modules that they are imported from, rather than being transitively imported.
This is probably good for code clarity.
This flag was already used on some parts of the tree, but after this PR, applies everywhere.

Enable mypy no-implicit-reexport and fix single arising error

---

parsl/dataflow/dflow.py

Remove redundant test - replace_task_stage_out always returns a function

---

parsl/tests/test_scaling/test_scale_down.py

Sometimes the scale happens one 5-second period longer than usual (because the idle time is 5 seconds minus tiny amount) and so the workers have not timed out by the time the final assert fires.

Allow one extra 5s period in scale in test

---

parsl/channels/local/local.py
parsl/channels/ssh/ssh.py

Previously parsl created directories with mode 0o777. Mode 0o777 allows arbitrary other users to write into the working directories, including modifying files created by channels which are then subsequently executed.
This PR replaces that mode by 0o700 which allows user access but excludes group and world access.
Partially addresses #836

Tighten channel permissions so working directories are not world writable

---

codemeta.json
setup.py

This should have happened with the 1.0.0 release in PR #1748

Label parsl as production in metadata

---

parsl/executors/high_throughput/process_worker_pool.py

Htex uses different task IDs to parsl core.
They are, however, close enough to cause confusion - for example, parsl task 7 and htex task 7 will often be running around the same time even though they may be unrelated.
This PR uses the phrase "executor task" to refer to task identifiers from the executor layer in log messages.

Label htext (vs parsl) task IDs more explicitly

---

parsl/tests/configs/workqueue_ex.py

This allows use of the WQ config in locally-marked tests.

Switch WQ test config to fresh_config style

---

parsl/monitoring/monitoring.py

This happens often when multiple DFKs run on the same host sharing a configuration, and this PR should make the problem more obvious.

Explain a common monitoring port in use exception

---

parsl/monitoring/monitoring.py

This was leading to exceptions about undefined 'router' when the initial try/except block encountered an error.

Don't try to start the router if it doesn't exist

---

parsl/dataflow/dflow.py
parsl/dataflow/usage_tracking/usage.py
parsl/executors/extreme_scale/executor.py
parsl/executors/flux/executor.py
parsl/executors/high_throughput/executor.py
parsl/executors/low_latency/executor.py
parsl/executors/swift_t.py
parsl/executors/threads.py
parsl/executors/workqueue/executor.py

Unmanaged executors are poorly defined and not tested, and reading the few codepaths involved can be a bit confusing when trying to understand scaling logic.

Remove unmanaged/managed executor concept

---

parsl/providers/ad_hoc/ad_hoc.py

scaling_enabled usually lives on executors, not on providers, and this method never seems to be invoked.

Remove unused scaling_enabled method from adhoc provider

---

docs/userguide/configuring.rst
parsl/executors/high_throughput/process_worker_pool.py

Sets the thread affinity for subprocesses that use OpenMP launched by a Parsl worker by setting the environment variables.
Fixes #2528. Though, as discussed, we're unsure if this can be done a better way.

Set OpenMP environment variables when imposing affinity

---

setup.py

The current parsl code (at least in the test suite) is incompatible with >=2 which was released in the last few days.

Add upper bound to SQLAlchemy

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/manager_record.py
parsl/executors/high_throughput/process_worker_pool.py

[single-latency.py.txt](https://github.com/Parsl/parsl/files/10582032/single-latency.py.txt)
Prior to this PR, the interchange calculated how many tasks to send to a manager based on the minimum of: how many tasks the manager most recently requested (minus sent tasks); how many tasks the manager has total capacity for, minus the number of tasks in flight.
The most recently requested count is made on an exponential backoff, which continues to backoff when a manager is saturated with long tasks. That means that the requested task count is sometimes not updated for quite a long time.
This PR removes that clause entirely, and the code that delivers that information. Now the interchange relies only on the computed maximum capacity minus the number of tasks in flight - this code was added in PR …

Remove manager to interchange work requests to speedup sequential task distribution

---

Makefile

Previously, only explicitly named subtrees were checked. Previous PRs have tidied up typechecking problems so that this PR can apply mypy to all of parsl/

run mypy on all of parsl/ tree

---

parsl/providers/cobalt/cobalt.py
parsl/providers/lsf/lsf.py
parsl/providers/pbspro/pbspro.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py

The presence of _ on _status indicates it is internal.
The method is expected to be called - that's why it exists. This PR removes exhortions to the contrary.

Prune unnecessary warnings in provider docstrings

---

.flake8

parsl/executors/serialize was removed in PR #1806 in 2020 which introduced the current serialization system.

Remove an unused path from flake8 exclude line

---

.github/workflows/python-publish-to-testpypi.yml
tag_and_release.sh

This PR updates our weekly release pipeline to mint a release tag.
* GH action now passes `VERSION` env var to `tag_and_release.sh`
* GH action will now mint a new tag matching the version pushed to pypi
Fixes #2451 and #2462 

Update gh actions to push tags

---

.github/workflows/python-publish-to-testpypi.yml

Setting perms to write, since the previous line from docs apparently doesn't work.

Limiting action perms to contents:write

---

.github/workflows/python-publish-to-testpypi.yml

The test releases and tagging worked in the last iteration. Logs are here: https://github.com/Parsl/parsl/actions/runs/4285181155/jobs/7463141066
With that, I'm pointing the action to push releases to Pypi instead of test.pypi.

Point release target from test.pypi to pypi on Github Actions

---

.flake8
parsl/log_utils.py

Reducing the line length here reduces the longest line in the codebase now, so this PR reconfigures flake8 slightly towards the PEP8 line length limit.

Add return type annotation for log utils, reformat, reconfigure flake8

---

parsl/tests/test_bash_apps/test_memoize_ignore_args.py

If the test output file happens to exist, the test will fail even though there is nothing wrong.

Remove test output file before running test

---

parsl/dataflow/dflow.py
parsl/tests/test_bash_apps/test_memoize_ignore_args_regr.py

When using AUTO_LOGNAME, stderr/stdout are added to ignore_for_cache, because this parameter is different on each invocation, and so invocations will not be cached.
However, what is modified is the ignore_for_cache structure in the function itself, not a local variable inside the invocation, which means that it is modified for all subsequent calls, including calls which do not use AUTO_LOGNAME.
This was found by mypy on the benc-mypy branch.
Fixes #1655 

Fix modification of ignore_for_cache when using AUTO_LOGNAME

---

parsl/executors/flux/executor.py

Problem: Currently, the launch_cmd is not set if provided to the FluxExecutor directly. Many jobs are likely to start already with access to a flux instance, in which case the launch command should use flux submit instead of flux start.
Solution: Ensure the launch_cmd is set.
Fixes #2633 

fix: launch_cmd not set when provided to FluxExecutor

---

parsl/providers/slurm/slurm.py

On the HPC I'm working (VSC clusters in Flemish universities, Belgium), the output of the `sbatch` command is slightly different from the default and therefore not processed correctly. The consequence is that submitted jobs for workers are not terminated when Parsl shuts down. This error did not result in an error message in `parsl.log`.
This is an example of the output of `sbatch` on one of the VSC clusters:
```
Submitted batch job 60060368 on cluster slaking
```
The fix proposed in this PR introduces a minimal customization with a more robust default than the current implementation. The proposed default is consistent with the current behavior and works for us too.
I'm happy to address any concerns. Thank you for considering this change and for making Parls in the first place!
- Bug fix …

Improved extraction of the job ID from sbatch stdout

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_scaling/test_scale_down.py

Prior to this PR, htex.connected_managers was a `@property`, which makes reasoning about the effect behaviour of code using this property harder to reason about:
For example, in htex scaling down code, when the interchange code is gone away, the value of executor.connected_managers is a silent hang, not a value.
Two other IPC @property values are not changed by this PR, connected_workers and outstanding, because they are exposed outside of the executor, to core scaling code, and I would like to think about that a bit more.

Make htex.connected_managers IPC call into a function

---

parsl/executors/high_throughput/interchange.py

When the interchange is killed by SIGINT/Ctrl-C, the main thread exits (due to a SIGINT generated KeyboardInterrupt exception) but the other two interchange threads do not. This means that the interchange process hangs without exiting.
With the behaviour introduced by this PR, the main thread ending will now cause the (now daemon) threads to end too.
This behaviour is different from the SIGTERM behaviour (which is how a clean parsl shutdown happens) - a SIGTERM kills all threads without opportunity for catching the exit, in the current signal handler configuration.
To recreate:
run:
```
pytest parsl/tests/ --config parsl/tests/configs/htex_local_alternate.py  -k 'not cleannet'
```
press ctrl-C after a while
observe a hang and that the interchange process is still alive.
After this PR, …

Make interchange threads daemons for less-hangy exit

---

parsl/executors/workqueue/executor.py

This PR makes all arguments into mandatory keyword arguments, and adds type annotations.
The default values are removed because they're always specified at the call site, and some defaults are dangerous: it is not valid to share a multiprocessing.Queue between multiple instances of the submit/wait thread.
The env parameter appears to be never specified, and so this PR removes that parameter entirely.
To typecheck task.env_pkg usage, the package_run_script parameter needs to not be None when that is used, and so this PR extends the existing task submission failure error handling to include a new exception that can be raised there.
This was driven by work in the benc-mypy branch

Rework _work_queue_submit_wait arguments

---

mypy.ini
parsl/executors/workqueue/exec_parsl_function.py
parsl/tests/test_bash_apps/test_stdout.py
parsl/utils.py

This PR removes some manual type checks in favour of typeguard, which will use the same annotations as mypy.

Strengthen type annotations in parsl.utils

---

parsl/executors/high_throughput/executor.py

This is part of issue #2343, to remove/reduce the use of the unsafe fork multiprocessing start method throughout Parsl.

Deprecate unsafe fork multiprocess in process_worker_pool

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/process_worker_pool.py

Polaris has low-rank CPUs sharing memory with high rank GPUs. This PR creates a CPU affinity mapping to ensure workers use CPUs near their associated GPUs
https://docs.alcf.anl.gov/running-jobs/example-job-scripts/#single-node-ensemble-calculations-example

Add a reverse block for CPU affinity mapping mapping

---

parsl/app/errors.py
parsl/errors.py
parsl/executors/errors.py
parsl/executors/workqueue/errors.py

This error is not specifically dataflow related, and could be used as a base exception in a bunch of other places, once this move is done.

Move ParslError to top level error module

---

parsl/monitoring/db_manager.py

This is driven by a desire to run on top of other database engines, especially PostgreSQL.
See issue #2073, https://github.com/Parsl/parsl/issues/2073
These schema bugs fixed in this PR are not a problem when running on sqlite3, because sqlite3 does not enforce the broken foreign keys or care about integer size in the same way as postgres.
Changes are:
* Remove foreign keys from status and resource tables into the task and try tables. These key relationships are troublesome in two ways:
i) by the time a resource or status message is processed, the task/try might not have been created in the task/try tables.
ii) A task_id or try_id is not a unique identifier of an entry in the task/try tables, because those IDs are re-used across runs, so cannot be used as a foreign key, even if the …

Fix some schema problems for other database engines

---

mypy.ini
parsl/monitoring/db_manager.py
parsl/tests/test_monitoring/test_basic.py
parsl/tests/test_monitoring/test_db_locks.py
parsl/tests/test_monitoring/test_fuzz_zmq.py
parsl/tests/test_monitoring/test_memoization_representation.py
test-requirements.txt

This PR makes the code able to run with SQLAlchemy 2.0, but does not change the version constraint, as the way that type annotations are handled has changed, and mypy can't be configured in a way which works with both SQLAlchemy 1.4 and 2.0

Make changes towards supporting SQLAlchemy 2.0

---

mypy.ini
parsl/executors/high_throughput/process_worker_pool.py
parsl/serialize/base.py
parsl/serialize/concretes.py
parsl/serialize/facade.py

This PR switches __init_subclass__  to using only kwargs, as shown in PEP487.
A few docstrings are also corrected and some of the logic is rearranged to make type checking easier.
This is from benc-mypy branch.

Strengthen type checking on serialization code

---

parsl/dataflow/flow_control.py

This removes a lot of duplicated code between those two classes.
My intention is to make the non-timer functionality of FlowControl be more visible, to help with ongoing FlowControl simplification.

Make FlowControl be a subclass of parsl.utils.Timer

---

parsl/executors/base.py

Correct docstring on ParslExecutor to not claim it is a metaclass

---

docs/quickstart.rst

The link target is implicitly defined by the heading "Execution Providers" as #execution-providers
This broken link was introduced in PR #2499 but was not caught by CI until some not-version-controlled changes in environment.

Fix broken link in quickstart

---

parsl/monitoring/visualization/plots/default/workflow_plots.py
parsl/tests/test_monitoring/test_viz_colouring.py

This is a regression test for PR #2708, issue #2681, that will also detect other new states added to the states enumeration without being added to the coloring tables.
In order to be able to test this way, this PR moves the two coloring tables to be module scope, instead of local scope inside a method.

Add test that visualization coloring tables color each known state

---

requirements.txt

Parsl PR #2678 breaks with typing-extensions==4.5.0. See that PR for some further information. This PR adds a lower bound to be later than 4.5.0, and also a major version upper bound to work with typing-extensions Semantic Versioning.

Add version constraints on typing-extensions

---

parsl/executors/workqueue/executor.py

Prior to this, Work Queue staged the relevant function files in (and attempted to stage the missing result files out), but the coprocess worker code was given the original (non-staged) paths.
This worked in shared-fs environments: the staged files were ignored, and the original files were used, but broke in non-shared-fs environments.
This PR uses the staged filename (the basename), as already happens with non-coprocess mode.
Fixes #2728

Rewrite file paths in WorkQueue coprocess mode, for non shared-fs

---

parsl/benchmark/perf.py

Prior to this PR, if the first iteration takes longer than the target time (120s by default) due to warmup, rather than due to raw task throughput, the task rate from the first iteration will be used.
This PR forces two iterations, so that the first iteration forces warmup and a second iteration always to make a meaurement in warmed-up state.

Force two iterations in parsl-perf for proper warmup

---

parsl/executors/workqueue/executor.py

This comment was introduced in commit 525641f16c68f7ac2415fe577a7d20951c0ce86a in 2019

Remove a comment that became irrelevant a long time ago

---

docs/userguide/apps.rst
docs/userguide/execution.rst
docs/userguide/index.rst
docs/userguide/mpi_apps.rst

Adds a documentation page which explains how to launch MPI apps from Parsl.
See #2723 

Add a documentation page on MPI apps

---

docs/devguide/design.rst
docs/devguide/roadmap.rst

This is intended to help new readers understand the context of why these sections of been kept, rather than deleted.

Add notes justifying why historical sections of docs have been made historical

---

parsl/tests/test_python_apps/test_type5.py

Based on analysis by BenC with WorkQueue, noted that the parametrization of this test hits WQ's weakspot: depth.  So, reduce it's depth for our tests. 

Reduce depth to work with WQ for delayed tests

---

parsl/tests/conftest.py
parsl/tests/test_data/test_file_apps.py
parsl/tests/test_data/test_file_staging.py

- Use the well-known `tmp_path` fixture.
- Remove duplicated tests

Cleanup some test file detritus

---

parsl/dataflow/memoization.py

Biggest detail is to not rebuild the memoization list every statement, instead opting for the usual `.append()` and `.extend()` methods.  While here, also remove some unnecessarily forced string interpolation for non-debug logs.

Mild memoize method cleanup

---

docs/userguide/joins.rst
docs/userguide/plugins.rst

This description focuses on Globus Compute, but it can apply to other components with a Futures driven API.
Fixes #2786 

Document calling other systems using @join_app and Futures

---

parsl/serialize/base.py
parsl/serialize/concretes.py
parsl/serialize/facade.py

Prior to this PR, the serialization header was parsed twice during deserialization, and in two different ways, leading to an awkward header format: the header must be exactly three bytes long for one (length based) parser, and the third byte must be a \n for the other (new-line based) parser.
This PR removes the length based parser, instead allowing an arbitrary length \n-terminated header.
Backwards/forwards compatibility:
The parsl serialization wire format is not a user exposed interface, as parsl requires the same version of parsl to be installed at all locations in a parsl deployment.
This PR does not change any on the wire byte sequences when used with the two existing de*serializers, but opens the opportunity for future implementations to use more than two bytes for identifiers. …

Parse serialization headers only once

---

parsl/serialize/facade.py

This mirrors a removal in Globus Compute, which originally contributed this code as a fork of the funcX serializer:
PR https://github.com/funcx-faas/funcX/pull/1153
commit (in funcX) 955e666fe6279571bf6024c239fc789595d8e206

Remove unused internal serializer _list_methods method

---

parsl/serialize/base.py

This ambiguity in serializer ID use is the root of issue #2555 where parsl.serialize ends up with two different serializers sharing the same ID, and both able to deserialize (in different ways) the same serialized data.

Clarify that serializer ID selects a deserializer

---

docs/userguide/apps.rst

The documentation does not explain that you can create Apps outside of the decorator-based mechanism. 
It's a convenient route when you just want to make a "Parsl version" of a function already in a module,
and create Parsl functions programatically.
Was reviewing code from a user and saw functions similar to:
```python
@python_app
def f(x): 
from m import f
return f(x)
```
I suggested they replace with
```python
from m import f
f = python_app(f)
```
to make the code more succinct.
It wasn't apparent in the docs that you could do this. I know you can because I'm familiar with function serialization.

Explain how to use functions from libraries

---

parsl/tests/test_python_apps/test_fail.py
parsl/tests/test_python_apps/test_garbage_collect.py
parsl/tests/test_python_apps/test_join.py
parsl/tests/test_python_apps/test_mapred.py
parsl/tests/test_python_apps/test_memoize_bad_id_for_memo.py
parsl/tests/test_python_apps/test_overview.py
parsl/tests/test_python_apps/test_pipeline.py

- Make some test code more Pythonic (e.g., generators, list comprehension)
- Remove a number of unnecessary sleep calls (or vastly reduce)
- Teach some tests to `assert`
- Remove more `print()`s

Remove or reduce some test sleeps

---

parsl/tests/conftest.py
parsl/tests/test_bash_apps/test_basic.py
parsl/tests/test_bash_apps/test_kwarg_storage.py
parsl/tests/test_bash_apps/test_memoize.py
parsl/tests/test_bash_apps/test_multiline.py
parsl/tests/test_bash_apps/test_pipeline.py
parsl/tests/test_bash_apps/test_stdout.py
parsl/tests/test_data/test_output_chain_filenames.py
parsl/tests/test_docs/test_workflow4.py
parsl/tests/test_python_apps/test_outputs.py

Take advantage of pytest fixtures and update all errant tests accordingly.  In particular, noting that many tests rely on shared fs, use a temporary directory structure rooted inside of the CWD (typically the root Git directory), rather than `tmp_path`'s native use of `TMPDIR`.
The only leftover detritus I didn't engineer removal of was the `runinfo/` directory, which is where Parsl places logs if `parsl.AUTO_LOGNAME` is in play. Given the potential to interplay with a developer's "live" data, I opted to leave this for now.

Remove a number of leftover test files

---

parsl/serialize/base.py
parsl/serialize/concretes.py
parsl/serialize/facade.py
parsl/tests/test_serialization/test_2555_caching_deserializer.py

Prior to this PR:
parsl.serialize.facade monkeypatches some serializer objects to create new serializers, but does not generate new identifiers for those new serializers, so two serializers exist in the serializer globals with the same identifier.
This patching is done to make some new serializers that have caching behaviour.
This leads to issue #2555, where data from one serializer is deserialized using one of the these dynamically defined serializers, incorrectly.
This PR removes that monkeypatching and moves caching behaviour into two new serializers explicitly defined for the type of objects that should be cached.
This adds two new serializer identifiers, which means there is an incompatible wire protocol change: older versions of parsl will not be able to deserialize callables …

Rearrange serializer caching to fix issue #2555

---

parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_join.py

Prior to this PR, a join app returning an empty list, rather than a list with at least one Future, would hang at the joining stage. This is because join completion code was only invoked when Futures in the return list complete: with an empty list, that would be invoked 0 times.
There's no conceptual reason why a join app shouldn't return an empty list: (an example application, imagine, when processing n regions with n subtasks, identified by an earlier step, but that step identified n=0 regions, so there would be n=0 subtasks, and a list of length n=0 inner Futures to wait on.
This PR makes join completion code happen in the empty list case immediately, rather than indirecting it via completion callbacks on inner futures which do not exist.
This PR includes a regression test which, before …

Allow join_apps to return []

---

parsl/dataflow/memoization.py

Some memoisation functions are implemented by serializing values to generate hash material: this is done under the weak assumption that serializing the same value will always give the same hash material.
This PR tries to make that assumption stronger by forcing a particular serialization method for those memoization functions, as the serialization code moves towards allowing arbitrary user pluggable serialization functions that are much less likely to have that property.
This aligns with the explicit use of pickle to store checkpoints to disk, rather than parsl.serialize: memo/checkpointing is now entirely pickle based for serialization, leaving parsl.serialize only for moving objects to/from workers. This behaviour might be revisited later, with more awareness in parsl.serialize about …

Use pickle instead of parsl.serialize for memo hashes

---

parsl/providers/local/local.py

PR #1471 removed the special casing that gave a remote mode and a local mode, distinct from LocalChannel and the various SSH channels, and since then the code has always followed the code path that used to be "remote mode".

Remove log reference to "remote mode"

---

.readthedocs.yaml

Prior to this PR, readthedocs was using Python 3.7 by default to build the docs. This became unsupported in parsl in PR #2749 and broken in Parsl in PR #2744.
This PR adds a configuration file to use Python 3.11, the latest supported version of Parsl, to build on readthedocs.
This configuration file will become mandatory in readthedocs in September 2023, according to their own documentation, so this file would need adding soon anyway.
See https://readthedocs.org/projects/parsl/builds/21218011/ for evidence that this builds correctly.

Add a readthedocs config, to fix bad python version and because it will soon be mandatory

---

parsl/tests/conftest.py
parsl/tests/test_regression/test_1606_wait_for_current_tasks.py

This tests internal DFK data structures; only necessary to run locally.  This means we can use `threading.Event()` to enact this test, rather than sleeping the day away.

Remove test_1606 sleep

---

parsl/serialize/concretes.py

This serializer, in current practical parsl cases, will raise an exception every time and fall through to the dill callable serializer, because it cannot serialize the wrappers that Parsl user functions are wrapped in.
Were it actually able to serialize, it would in many usecases generate invalid serializations, rather than raising an exception: in any case where an app was defined in a main file rather than in an importable file (eg. simple workflow scripts, REPLs like Jupyter notebooks)
- New feature (non-breaking change that adds(removes) functionality)

Remove pickle serializer for callables

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_scaling/test_regression_1621.py

The key change is to abuse the `JobStatusPoller.poll()` to ping the scale-out logic more often than the hard-coded 5s.  Ping it every tenth of a second for the second it takes the app() to complete.  Nominally, if the scaling logic is correct, then with a single app it won't matter that it's spammed: we'll only scale out a single block total.

Reduce test delay from 45s to 1

---

parsl/tests/test_error_handling/test_htex_worker_failure.py

No sense in waiting 30s for the test to fail.  I would have gone smaller, but we force it to an integer in `process_worker_pool.py`.  Will save that potential change (fractional HB period) for a future date.

Reduce htex test HB period to 1s

---

parsl/executors/high_throughput/process_worker_pool.py

Prior to this, a dead process in a pool of N processes would take, on average, (N * heartbeat) / 2 seconds to be restarted.

Check *all* child process for liveness every HB

---

parsl/tests/test_error_handling/test_python_walltime.py

`timeout()` utilizes `threading.Timer` under the hood, which accepts floats -- so use values less than 1 to remove more wasted waiting time.

Reduce timeout test delays; rework test to allow timeout decorator to interrupt

---

test-requirements.txt

This is needed as a pre-requisite for upgrading typeguard, part of LSST driven packaging upgrades (PR#2812)

Upgrade pytest to latest

---

parsl/executors/taskvine/install-taskvine.sh

No need to scroll past the progress bar in the CI -- use of the logs there is almost always a retrospective, so save some bits.
- remove `wget`'s progress output
- remove `tar`'s verbose flag

Remove unnecessary log output in CI

---

parsl/monitoring/monitoring.py

This wasn't detected by flake8, but moving the line above the type for _db_manager_excepts caused flake8 to detect it, so perhaps it is the presence of intervening code between the imports that causes that.

Remove duplicate import not detected by flake8

---

parsl/serialize/base.py
parsl/serialize/concretes.py
parsl/serialize/facade.py

Previously registration was implicit in the class definition, using a subclass hook. This makes it a bit awkward to work with the set of registered serializers:
* serializers would be registered at definition time (which because of non-deterministic import order) makes the order awkward to understand if serialisers are defined in more than one module.
* serializers could not be defined without being registered
This PR makes the set of serializers more explicit, with the defaults registered at import of the facade module. Definitions of serializers in concretes.py (or anywhere else) now do not result in a registration.
This is part of a move towards user-pluggable serializers, although this PR does not actually support adding more user serializers (as they will not be imported on the …

Make serializer registration explicit

---

parsl/executors/high_throughput/interchange.py

See PR #1966 and linked PRs for similar work, separating formal __repr__ from informal __str__
See https://docs.python.org/3/reference/datamodel.html#object.__repr__

Use default repr for interchange exceptions

---

parsl/tests/test_python_apps/test_timeout.py

As seen in CI at least once, it's possible that the noop() function takes too long to complete.  Address by:
- increasing the timeout
- removing the now-deemed-extraneous other parameterizations
- and verifying the test pre-condition first.  ("We expect to get a result!")
Reference problem observed: https://github.com/Parsl/parsl/pull/2812#issuecomment-1645072179

Verify a test pre-condition

---

docs/reference.rst
parsl/executors/errors.py
parsl/executors/flux/executor.py
parsl/executors/high_throughput/executor.py
parsl/serialize/errors.py
parsl/tests/test_error_handling/test_serialization_fail.py

This is in expectation of at least one more exception being added related to serialization as part of ongoing serializer plugin work.

Move serialization error definitions into parsl.serialize

---

parsl/monitoring/monitoring.py

This PR moves most log messages in the filesystem radio to debug level, and sets the log level for the monitoring to INFO level. This gives one log message per monitoring message, without per-poll logging. This is more in line with log level styles in Parsl, logging at INFO when something happens.
Output of DEBUG logs is not user-configurable, but I left those log lines there for debug hacking.
Fixes #2845

Reduce monitoring filesystem radio log volume

---

parsl/executors/high_throughput/executor.py

This PR only adds some typing info for these methods/properties on the `HighThroughputExecutor`:
* `HTEX.outstanding`
* `HTEX.connected_workers`
* `HTEX.connected_managers`

Adding typing info for HTEX

---

parsl/addresses.py

Logging an exception for every missed address resolution has these issues:
* Even when there are no faults, users stumble on these and we receive spurious fault reports over slack. It makes for a bad first impression
* These non-critical errors act as a diversion from real faults for users attempting to debug on their own.
PR only changes the log level for these non-critical errors from `logging.exception` to `logging.info`, but we'll not have a traceback.
Before:
```
1690831678.348826 2023-07-31 14:27:58 MainProcess-2772 MainThread-8640217792 parsl.addresses:113 get_all_addresses ERROR: Ignoring failure to fetch address from interface lo0
File "/Users/yadu/src/parsl/parsl/addresses.py", line 111, in get_all_addresses …
```

Change log level for get_all_addresses and get_any_address

---

parsl/executors/taskvine/exec_parsl_function.py
parsl/executors/taskvine/executor.py
parsl/executors/taskvine/factory.py
parsl/executors/taskvine/manager.py
parsl/executors/taskvine/manager_config.py
parsl/executors/taskvine/utils.py
parsl/tests/configs/taskvine_ex.py
parsl/tests/scaling_tests/vineex_local.py

This PR is a follow-up to PR https://github.com/Parsl/parsl/pull/2809 with the following changes:
- Add support for serverless execution mode for tasks. Users can now declare serverless tasks like this:
```
@python_app
def f(x, parsl_resource_specification={'exec_mode': 'serverless'}):
...
```
Under the hood, a library task is deployed to each worker and forks itself to execute an actual task/function call.
- Add support for full conda environment replication on worker nodes for both serverless and regular tasks. Given a conda environment, TaskVine will distribute and cache it efficiently, so a shared filesystem is not required. The benefit mainly lies in the assumption that the conda environment can be huge in size and thousands of tasks asking the shared filesystem for the same …

TaskVineExecutor: add serverless execution mode for tasks

---

parsl/executors/base.py
parsl/executors/status_handling.py
parsl/jobs/job_error_handler.py
parsl/jobs/job_status_poller.py
parsl/jobs/simple_error_handler.py

Before this PR: The JobErrorHandler class had no state and was used effectively as a repository of stateless library functions, which are called from two distinct pieces of code.
This PR removes the JobErrorHandler class, moving the code into two locations:
`JobErrorHandler.run` (and its helper method `__check_irrecoverable_executor`) are called by `JobStatusPoller` to give each executor a chance to run its own error handler. This code is moved into JobStatusPoller.
`simple_error_handler` (and its helper methods `count_jobs` and `get_error`) are called by the `BlockProviderExecutor` implementation of error handling. They are moved into a new file, `simple_error_handler.py` directly inside that module (rather than inside a class).
After these changes, instances of `JobErrorHandler` are no …

Split and remove JobErrorHandler

---

parsl/executors/status_handling.py
parsl/jobs/job_status_poller.py

After this PR, calls to handle_errors are always enabled, and it is the responsibility of the handle_errors implementation to ignore errors if the user has so chosen.
The BlockProviderExecutor handle_errors implementation already has a test for that (duplicating the test in the now removed error_management_enabled code) so nothing needs to change there: this code only removes the redundant code path.

Remove executor-level error management enable/disable

---

parsl/dataflow/memoization.py
parsl/tests/integration/test_channels/test_ssh_errors.py
parsl/tests/test_bash_apps/test_keyword_overlaps.py
test-requirements.txt

Upcoming Python 3.12 (at least in python 3.12-rc1) requires a newer version of flake8 as flake8 6.0.0 gets confused by things happening inside format strings with Python 3.12-rc1.
This PR makes that upgrade.
Flake8 6.1.0 introduces a new rule to use is-equality, rather than ==-equality, when comparing types, and so this PR fixes violations of that rule too. In theory this shouldn't change behaviour.

Switch type comparisons from == to is, and upgrade flake8, in preparation for Python 3.12

---

mypy.ini

ExecutorStatus and its containing module were removed in PR #2835.

Remove mypy configuration for removed ExecutorStatus

---

parsl/jobs/strategy.py

This was not causing an error in master because no uses of the incorrectly annotated attribute (self.executors) were type checked.
This PR introduces a typed dict to represent the (single element) dictionary used for strategy state.
(A futher tidyup could be to remove that typed dict entirely and replace with the single value it contains, but this PR is trying to be descriptive of existing code)
The incorrect type annotation was added in #2712

Correct incorrect type annotation inside strategy code

---

parsl/app/python.py

The rest of the codebase already accepts `None` as a default here (for example, the corresponding parameter to bash_app) so there aren't any further code changes needed to deal with this.
This comes from working through flake8-bugbear errors in draft PR #2832

Fix mutable ignore_for_cache default in python apps

---

parsl/app/app.py

PR #2621 didn't remove the user facing join parameter it was intended to, instead just ignoring it.
That PR #2621 also added a new executors parameter to the join_app decorator, which is then ignored (as it should be - because join_apps should be forced to run in the _parsl_internal executor). This PR removes that spurious parameter.
This will be a breaking change for anyone explicitly specifying the _parsl_internal decorator to join_app, or for anyone explicitly specifying join=False to python_app. (Other uses of those parameters are already broken because those parameters are ignored, and they will now be broken in different ways)

Tidyup messy join app refactoring PR #2621

---

parsl/dataflow/dflow.py

This comes from a flake8-bugbear warning.

Remove unused key in iteration of task dictionary

---

parsl/monitoring/remote.py

Issue #2840 reports that the process monitor does not always exit if the workflow process exits unexpectedly, and looking at the cpython implementation, it looks like these processes will only be terminated at worker shutdown if the worker shuts down normally. If it is surprise terminated/killed, it will not shut down its dependent daemons such as any resource monitors it has launched.
This PR adds a liveness check for the process that it is monitoring, which is the parent worker process; so that if that process goes away without telling the resource monitor to exit, then the resource monitor will exit anyway.
Fixes #2840

Make resource monitor exit when monitored process has gone away

---

parsl/jobs/errors.py
parsl/jobs/simple_error_handler.py

Before (in pytest output, with htex launch_cmd="/bin/false"):
```
Exception: 	STDOUT: Found cores : 8
Launching worker: 1
```
After:
```
parsl.jobs.errors.TooManyJobFailuresError: Error 1:
EXIT CODE: 1
STDOUT: Found cores : 8
Launching worker: 1
```
* Fix counting so it counts even when js.message is None
* Add exit code
* Use a new error subclass rather than Exception
* Pluralise messages in for no-messages string and remove brackets
'[No error message received]' vs 'No error messages received'
- New feature (non-breaking …

Rework _get_error in simple_error_handler to give more information

---

parsl/dataflow/dflow.py

The default configuration actually comes from `DataFlowKernelLoader.load()` and the `Config()` object specified in the `DataFlowKernel.__init__` default parameters is never used, as all constructions of DataFlowKernel in the codebase specify a config.
This comes from flake8-bugbear

Remove unused re-used DFK default configuration object

---

parsl/dataflow/dflow.py

All of these parameters are specified by invocations in the relevant app decorators and so these defaults are never used.
Removing the default app_kwargs = {} is especially interesting for mutability safety.
This comes from flake8-bugbear

Remove unused defaults from dfk.submit

---

parsl/dataflow/dflow.py
parsl/errors.py

Make RuntimeErrors in DFK into custom error classes

---

parsl/app/app.py

Add ignore_for_cache docstring to decorators. Fixes #2875

---

parsl/app/errors.py

Outputs must be Files - although early on in Parsl, it was possible to specify them as string pathnames. This now-removed string-or-File dual annotation is probably a holdover from that.

Tighten MissingOutputs file type

---

parsl/dataflow/dflow.py

The task record entry app_fu is never None:
it is either missing (during construction) or a Future.
So, this None check will never fire.
Discovered by mypy 0.5.1 warn_unreachable

Remove unreachable code when app_fu is None

---

parsl/executors/high_throughput/executor.py

The removed text looks like it was written as if for an abstract base class, not for a concrete implementation like htex.

Remove spurious docstring in htex initialize_scaling

---

parsl/executors/base.py
parsl/executors/flux/executor.py
parsl/executors/status_handling.py
parsl/executors/threads.py

Scale in/out behaviour is only for BlockProviderExecutors. Other fairly recent PRs have been consolidating that behaviour, and this PR is another one in that direction.
The non-BlockProviderExecutors (threads and flux) had meaningless stub methods to make ABCMeta allow them to be instantiated. This PR removes those stubs.

Move scale_{in,out} from ParslExecutor to BlockProviderExecutor

---

parsl/channels/base.py

No in-codebase channels return None for stdout or stderr, and some cluster providers (at least pbspro and slurm) do not handle the case when stdout is None, instead assuming it will be a str.
This PR makes those assumptions concrete.
This PR will introduce API breakage for any externally implemented channels which return None here, although in practice because of the above, it's likely that use of those channels woudl already be broken.
However, I am not aware of any externally implemented channels.

Remove execute_wait stdout, stderr optionality

---

parsl/channels/local/local.py

These initial values will never be used and in the stdout/err case, can give the impression that stdout, stderr might be returned as None. There is no code path which uses these initial assignments as the function will raise an exception in the case that they are not all re-assigned later on.

Remove three dead assignments from local channel

---

docs/userguide/index.rst
docs/userguide/parsl_perf.rst

Document parsl-perf

---

parsl/dataflow/dflow.py

This is in support of
https://github.com/Parsl/parsl/issues/2873#issuecomment-1726540856
This will break anyone relying on particular exception classes coming from this call.

Switch empty dfk() error from ConfigurationError to NoDataFlowKernelError

---

parsl/benchmark/perf.py

Prior to this PR: In some startup situations, the estimated number of tasks for the next iteration can round down to 0, and then parsl-perf can sometimes enter an infinite loop without increasing the loop size:
==== Iteration 29463 ====
Will run 0 tasks to target 20.0 seconds runtime
Submitting tasks / invoking apps
All 0 tasks submitted ... waiting for completion
Submission took 2.1457672119140625e-06 seconds = 0.0 tasks/second Runtime: 1.049041748046875e-05s vs target 20.0
Tasks per second: 0.0

Make parsl-perf iterations have at least 1 task

---

parsl/benchmark/perf.py

In Python 3.12, f-strings vs flake8 has more whitespace checking, in line with whitespace checking in other Python expressions, as part of a broader rationalisation of f-string implementation:
https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep701

Fix flake8 error from upcoming Python 3.12

---

parsl/tests/test_bash_apps/test_error_codes.py

This fixes this pytest warning:
PytestReturnNotNoneWarning: Expected None, but
test_bash_apps/test_error_codes.py::test_div_0 returned True, which
will be an error in a future version of pytest.
Did you mean to use `assert` instead of `return`?

Do not return a value from a pytest case, to fix a deprecation warning

---

parsl/executors/threads.py

The `ThreadPoolExecutor` forces the `max_threads` kwarg to be of type `int`. However, since `max_threads` inevitably makes its way into `concurrent.futures.ThreadPoolExecutor`, [which can take `max_workers=None`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor), I have modified the type hint to be `Optional[int]`. 
Happy to add a test if you feel it warrants one.

Make `max_threads` type `Optional[int]` in `ThreadPoolExecutor`

---

parsl/executors/workqueue/parsl_coprocess.py

I applied [ruff](https://github.com/astral-sh/ruff) autofixes (i.e. `ruff . --fix`) to the source code, which found... precisely one unused import. 😅 

Remove unused import (from `ruff . --fix`)

---

parsl/dataflow/dflow.py
parsl/dataflow/futures.py
parsl/tests/test_error_handling/test_python_walltime.py
parsl/tests/test_monitoring/test_memoization_representation.py

This will be a breaking change for any user that references the (now renamed) `task_def` attribute of an AppFuture.

Use the term "task record" instead of "task def(inition)" more consistently

---

Makefile
docs/userguide/monitoring.rst
setup.py

This reflects a difference in code maturity and maintenance between the two: monitoring core is much more maintained and stable than visualization at the moment.
Work with LSST has repeatedly encountered dependency problems caused by the visualization dependencies, even though those dependencies are not need by LSST, and this separation allows the visualization dependencies to be skipped.
Breaking change:
If you are using visualization you will now need to:
pip install parsl[monitoring,visualization]
to get all of the dependencies previously installed by [monitoring]

Separate monitoring core and visualization dependencies

---

parsl/executors/workqueue/errors.py
parsl/executors/workqueue/executor.py

This will add exception chaining when an underlying exception is available, so that reporting of a WorkQueueTaskError will include before the WorkQueueTaskError. This means, in the case of a FileNotFoundError, that the filename that could not be found will now be reported.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/parsl/parsl/runinfo/003/WorkQueueExecutor/function_data/0011/result'
parsl/executors/workqueue/executor.py:1059: FileNotFoundError
The above exception was the direct cause of the following exception:
```

Chain exceptions on WorkQueueTaskFailure when a cause is available

---

parsl/executors/taskvine/executor.py

This PR chains exceptions generated by either the function execution or the taskvine executor, and is a similar enhancement to workqueue in PR #2916.

TaskVineExecutor: Enable exception chaining when functions are executed to provide detailed error messages.

---

mypy.ini
parsl/executors/high_throughput/interchange.py

These changes are all in the interchange. In most cases, this error is found when a manager id (a byte sequence) is used in a string substitution, and to make happy, the format string is modified to indicate that we really do want to represent that byte sequence as a repr.
The only other place is one rendering of a binary message into a log string, and the fix is the same.
from benc-mypy branch

Re-enable str-bytes-safe mypy error, and fix uses

---

parsl/dataflow/dflow.py

There's no reason for it to be omitted and added later, and this style is more defensive.

Move task_launch_lock into initial TaskRecord

---

mypy.ini

This executor was removed in PR #2747

Remove mypy reference to Extreme Scale Executor

---

parsl/tests/conftest.py
parsl/tests/test_python_apps/test_lifted.py

When pressing ctrl-c in pytest, prior to this PR, it would hang as wait_for_task_completion would be called in the unwinding of the fixture stack. However, because ctrl-c was pressed, tasks wouldn't be expected to all complete.
This PR changes that to assert that all tasks are completed, rather than *waiting* for all tasks to complete.
A non-finished task now gives a test error - which is arguably better anyway because it more aggressively flushes out tests that do not perform a complete shutdown.
This means that pressing ctrl-C in a pytest leads to an assertion error; when previously it led to a hang.
One recently introduced test is fixed to conform to this new requirement.
This is part of safe-shutdown work.
- Code …

Make pytest fail when tasks are running after a test

---

.flake8
parsl/configs/ad_hoc.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/executors/taskvine/factory.py
parsl/monitoring/monitoring.py
parsl/monitoring/remote.py
parsl/monitoring/visualization/plots/default/workflow_plots.py
parsl/monitoring/visualization/plots/default/workflow_resource_plots.py
parsl/tests/configs/ad_hoc_cluster_htex.py
parsl/tests/configs/htex_ad_hoc_cluster.py
parsl/tests/configs/local_threads_monitoring.py
parsl/tests/scaling_tests/vineex_condor.py
parsl/tests/scaling_tests/vineex_local.py
parsl/tests/scaling_tests/wqex_condor.py
parsl/tests/scaling_tests/wqex_local.py

Fix all instances of flake8 E124 indentation warnings and re-enable

---

parsl/channels/base.py

This removes many uses of the word "simple" and makes the first sentence summarise the class (see PEP-257).

Refresh docstring for base Channel class

---

mypy.ini
parsl/executors/high_throughput/interchange.py

Require type annotations throughout the interchange

---

mypy.ini
parsl/dataflow/dflow.py

The only exception comes from multi-stage initialization of channels which is not properly represented in the type system.
"Globally" here means for code that is being type-checked - so not (by default) including code with no type annotations.

Enable mypy warn_unreachable globally; Describe the only exception

---

.github/workflows/python-publish-to-testpypi.yml

The release process previously used whichever environment the actions/setup-python action chose to use in the 3.x range. Python 3.12 and the current release process are incompatible, and auto-releases broke when actions/setup-python chose to supply Python 3.12. This PR pins the release to Python 3.11, which will remain in a supported state until October 2027. Beyond that, this release process will probably need some re-engineering to work.
Attempts to fix #2934

Pin release process to Python 3.11

---

.github/workflows/ci.yaml

This is motivated by upcoming PR #2923 which adds a RADICAL-Pilot executor: that executor is able to re-use a submit side virtualenv, but not able to re-use `--user` level installs.
This should not change any other behaviour of the CI: packages will be installed at different paths, but anything that was reliant on those paths being a specific values is suspicious.

Install into virtualenv inside CI

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a "mandatory" breaking changes section.
Rather than the previous assumption that bug fixes and new features would not break anything, this now assumes that all code changes might break something and encourages the pull-requester to think about this more seriously.
This PR also expands "Documentation update" to refer to anything involving human readable text.

Update PR template based on my recent experiences

---

parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/radical/executor.py
parsl/executors/status_handling.py
parsl/jobs/job_status_poller.py
parsl/tests/test_python_apps/test_garbage_collect.py
parsl/tests/test_regression/test_1606_wait_for_current_tasks.py

Remove one unused import of `parsl` entirely. This is probably good for import loop untangling generally anyway.
Remove some F401s that come from older type-checking code not being able to see imports used inside type annotations.
Remove some test-suite noqas that are defined for the entire test suite in .flake8
This PR leaves three # noqa statements in place because removing them is more complicated.
Developers using non-test-suite static checkers might find their checker is angry now.
Removal of `import parsl` in the executor base might cause changes to import order.

Eliminate trivially unnecessary # noqa statements

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/test_error_handling/test_htex_worker_failure.py

The HTEX worker watchdog was missing a worker argument and not starting any processes. This PR standardizes the initiation of worker processes to ensure consistency and fix the watchdog.
I also expanded the worker failure tests to cover restarts by the worker watchdog. 
Fixes #2972
- Bug fix

Standardize HTEX worker process initiation

---

parsl/executors/high_throughput/process_worker_pool.py

This code path seems to be unused, so should not change anything.

Remove unused STOP message exit path in htex worker pool

---

docs/reference.rst
parsl/jobs/states.py

This was driven by a desire to document the difference between TIMEOUT and FAILED in the API guide.

Add job-related docs to API guide, with more detail on JobStates

---

.github/workflows/ci.yaml

This is while investigating suspicious behaviour where runinfo directories from multiple jobs are becoming jumbled into the same runinfo zip files. I haven't seen anything that specifically says this will fix behaviour, but I'd like to see what happens with latest version before opening an upload-artifact issue.
This changes CI so should not change anything exposed to a user. upload-artifact crashes fairly often in CI, and this PR will perhaps change the frequency of that.

Bump CI upload-artifact to latest version

---

parsl/tests/sites/test_concurrent.py

I don't think there is any need for this test to put the run directory somewhere different, vs the other tests which all use the default runinfo/ directory.
Putting the logs in a different location means they are not available in CI runinfo/ archives.
This should not change anything for end users because it is a change to the test suite.

Use usual runinfo for ParslExecutor tests

---

parsl/executors/high_throughput/process_worker_pool.py

In normal usage a user wouldn't see this changed help text - only if they were trying to start their own htex worker pool outside of parsl's scaling mechanism

Correct process_worker_pool --debug arg help

---

parsl/executors/high_throughput/monitoring_info.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/multiprocessing.py

To avoid issues with forked processes and threads (see #2343), we will use spawn calls to start HTEX workers.
- Created spawn and fork multiprocessing context objects that we can use throughout the codebase to increase clarity on how we start processes.
- Migrated away from using the `MacSafeQueue` in the process worker pool since it was only needed to get the sizes of two queues for a single debug log statement.
- Replaced `ready_worker_queue` with `ready_worker_count`. The former was a multiprocessing `Queue` that we only used to track the number of workers that are ready to receive tasks. The latter is a multiprocessing `Value`, which is a more appropriate data structure.
- Created an HTEX manager thread to transfer monitoring messages from a managed queue, which we can utilize across …

Use spawn for process worker pool

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/test_error_handling/test_htex_manager_failure.py

If the manager terminates for any reason, its associated workers will shut themselves down. This ensures that workers do not remain active indefinitely without a manager.
Fixes #2956 
- Bug fix
- New feature

Shut down HTEX workers when Manager dies

---

parsl/executors/high_throughput/process_worker_pool.py

Prior to this PR:
In practice, the --cpu-affinity parameter was always specified, and when a user does not specify any value in the HighThroughputExecutor, the default value of `'none'` will be passed in to this parameter. So in practice, throughout process_worker_pool, all cpu_affinity variables will be a string, 'none' by default, or as specified by users.
The commandline args code allows --cpu-affinity to be omitted. This results in cpu-affinity having the value `None`. This is not handled properly by the worker code, which assumes that one of the explicit string values will be supplied, and will (I think - I haven't tested) raise:
> raise ValueError("Affinity strategy {} is not supported".format(cpu_affinity))
in this case.
The type annotations for the worker allow cpu_affinity to be …

Tidy types around CPU affinity

---

parsl/dataflow/dflow.py
parsl/dataflow/errors.py
parsl/tests/test_python_apps/test_dep_standard_futures.py
parsl/tests/test_python_apps/test_depfail_propagation.py

In some situations, a dependency in a dependency error does not have a task ID (becuase it is not an AppFuture) (case 1), or has a task ID from a different DFK (case 2)
Previously:
Case 1: the dependency error listed a task ID as `None`.
Case 2: the dependency error listed a task ID as if it was that task in the same DFK as the dependent task.
In both those cases now, the error message renders those "foreign" Futures using repr.
This PR also tidies up list formatting to remove []-brackets around the list of dependencies.
Now:
Dependency failure for task 0 with failed dependencies from <Future at 0x7f8ca335ef90 state=finished raised ValueError>
Previously:
Dependency failure for task 0 with failed dependencies from [None]
The task ID entry of `DependencyError.dependency_exceptions_tids` …

Add more info to DependencyError for non-task Futures

---

parsl/providers/slurm/slurm.py

Adds new options for `SlurmProvider` as attributes to fix #2994
Fixes # 2994
- Bug fix

Fix missing qos and constraint attributes that broke SlurmProvider in #2986

---

parsl/tests/test_providers/test_slurm_instantiate.py

This test checks that repr runs ok for SlurmProvider. That's a method that one might expect would always work, but RepresentationMixin has been a source of exceptions in the past (although with #2996, it would hopefully be less aggressive).
It might be useful to make this sort of repr test for more classes that are not otherwise tested.
This test does not need a slurm installation, as it does not test any interactions with slurm itself.

Add a regression test for broken SlurmProvider repr(), issue #2994

---

parsl/executors/workqueue/executor.py

The Work Queue executor was attempting to wait for tasks when there were none in the queue, causing the timeout period to be observed in the task throughput. 
Now the executor re-checks whether the queue is empty before attempting to wait on another task retrieval.
#2801 
- Bug fix

Fix blocking Work Queue executor send/retrieve loop

---

parsl/dataflow/dflow.py

The list of dependencies is always a sequence of futures, so there is no need to check the type of each element.
none

Remove unused type-check in dfk._count_deps

---

parsl/tests/test_radical/test_mpi_funcs.py

A temporary measure to allow testing locally on dev setups that don't have `radical.pilot` installed and/or working.  Use with:
```console
$ pytest parsl/tests/ -k "not radical" ...
```
For now, this is not _implemented_ anywhere (e.g., not in `Makefile`) so it's strictly a manual usage.  At some point, the tests are due for an overhaul to clean up the testing situation.  I won't enumerate the specifics here, but suffice to say that this is a on-going conversation.

Mark radical MPI test

---

parsl/tests/test_radical/test_mpi_funcs.py

Pytest looks for test functions with the word `test` in them.  But this is _not_ a test, per se, but rather a kernel for testing.  Odd distinction I suppose ...
Renaming to remove a (correct) Pytest warning

Rename test python_app

---

parsl/tests/test_checkpointing/test_python_checkpoint_1.py

An older test; the only detail of interest for the tests is the checkpoint files, so update accordingly: `assert` the interesting bits (no change), and remove the return.  While here, update test to use the `conftest` infrastructure (`local_config()`).

Address pytest warning for checkpoint

---

parsl/tests/test_checkpointing/test_python_checkpoint_2.py

Factor out the boilerplate DFK startup and shutdown to a contextmanager; the key bits of the test&nbsp;&mdash;&nbsp;is the checkpoint *utilized* (i.e., random numbers match second time)&nbsp;&mdash;&nbsp;are more apparent.
Meanwhile, use `tmpd_cwd` to remove another test detritus item.

Refactor test for readability

---

docs/userguide/checkpoints.rst

Simple code-block addition to the checkpoints documentation page.

Correct code-formatting oversight in docs

---

.github/workflows/ci.yaml
.gitignore
parsl/tests/conftest.py

Recent efforts to clean up the test detritus left in the developer's source directory were unaware of the fact that the `runinfo/` directory is saved in CI.  To accommodate both goals, refactor the `tmpd_cwd_session` fixture to preserve the last `N` test runs.  If not specified, default to keeping the last 3 runs.
Meanwhile, tell the upload-artifact step to preserve both directories for the time being.
(In response to [observation in PR #3003](https://github.com/Parsl/parsl/pull/3003#issuecomment-1875746026).).

Add .pytest/ to runinfo artifact collection

---

parsl/dataflow/dflow.py
parsl/jobs/job_status_poller.py

Currently, the `JobStatusPoller` and `PollItem` both take the `DataFlowKernel` as an argument, when in reality there's very little dependence for these on the `DFK`. `PollItem` uses the DKF to get to the monitoring component, which is again optional. This PR converts the DFK to an optional argument. 
This PR is primarily to simplify integrating Parsl scaling logic directly with individual executors without involving the DFK which is the direction globus-compute is taking with it's execution engines.
No user-facing changes are expected.

Update JobStatusPoller to not require DFK

---

parsl/executors/high_throughput/executor.py

Slightly more esoterically, help mypy know that `self.launch_cmd` is a `str` and never `None`, despite `__init__`'s signature.

No sense in setting launch_cmd twice

---

parsl/executors/workqueue/executor.py

After #2984 was merged it was observed that the work queue send/retrieve loop consumes CPU when there is no work to be done. This PR suspends execution waiting on the task input queue when both queues are empty. 
- Bug fix

Reduce WorkQueue CPU time at expense of more latency in complex submission patterns

---

parsl/tests/conftest.py

The pytest node names encapsulate test parameters in square brackets, which can be problematic when used in a dir name. To avoid issues, we ensure that the test dir name only includes word characters, whitespace, hyphens and underscores.

Replace problematic chars in test dir name

---

setup.py

Prior to this PR, pandas is constrained with a SemVer-like major-only constraint, `<3`. This aligns with Pandas declared policy of approximate-SemVer: https://pandas.pydata.org/docs/development/policies.html
On 20th January 2024, the latest version of Pandas went from 2.1.4 to 2.2.0 and looks like it introduced changes which break our usage of pandas.
I have not investigated in any depth what those changes are, but CI began to fail with the below stack trace.
This PR introduces a stronger minor-level upper bound, based on the above situation. This is likely to cause some conflict with users wanting to use recent pandas, and some effort should be made to fix it [by whom?].
The stack trace:
```
2024-01-22T16:48:24.7427770Z + wget http://127.0.0.1:8080/ --recursive --no-verbose …
```

Constrain pandas to exclude new v2.2

---

parsl/monitoring/monitoring.py
parsl/monitoring/remote.py

Two kinds of monitoring message originate from workers:
1. task start and end messages which are relatively lightweight, sent by the task thread at the beginning and end of a task.
2. periodic resource usage message which happen periodically while a task is running. These are sent from a forked process which monitors the task process and its descendants. This can be substantially more resource intensive and degrade workflow performance.
Previously configuration only allow disabling both of this kind of message. This PR allows the type 1 messages to continue to be sent, allowing users to see when a task starts executing, without running a per-task periodic monitoring process.
This only affects behaviour when `resource_monitoring_interval` was set to zero. In that case, previously the …

Only monitor processes when resource_monitoring_interval > 0

---

parsl/tests/conftest.py

A conflation of OS's internally initially led to use of `lchmod`.  It's still the correct call "for robustness" on platforms that support it, but for those that don't, fallback to regular `chmod`.

Address flaky tmp test dir cleanup

---

parsl/app/errors.py
requirements.txt
test-requirements.txt

https://wiki.debian.org/Python3-six-removal

Remove last usage of `six` Python 2 compatibility layer

---

parsl/tests/sites/test_concurrent.py
parsl/tests/test_data/test_file_apps.py
parsl/tests/test_data/test_file_staging.py
parsl/tests/test_docs/test_kwargs.py
parsl/tests/test_python_apps/test_futures.py

PR #2764 introduced `tmp_path` without understanding of the shared FS expectation for some tests (i.e., those run on site-specific hosts).  PR #2803 fixed this with `tmpd_cwd` which is a temporary directory created inside of the current working directory&nbsp;&mdash;&nbsp;which is assumed to be on a shared FS.
Fixes: #3039
- Bug fix (in tests)

Remove use of tmp_path fixture.

---

docs/userguide/configuring.rst

Fixed cpu_affinity docs that had the alternating option listed as `alternate` not `alternating`.

Fixed cpu_affinity docs that had the alternating option listed as alternate not alternating

---

parsl/providers/errors.py
parsl/providers/slurm/slurm.py

This PR moves the SLURM provider towards the tighter provider.submit API described in issue #2949 which requires that submission failures are indicated by an exception, rather than by a `None` value.
In this PR, instead of a relatively uninformative `None` value, a richer SubmitException is returned with more information about the submission failure.
I tested this on perlmutter by setting scheduler_options=`#SBATCH --nonsense`.
Before this PR, execution fails with this exception:
```
parsl.executors.errors.BadStateException: Executor PM_HTEX_multinode failed due to: Error 1:
Failed to start block 0: Executor PM_HTEX_multinode failed to scale due to: Attempt to provision nodes did not return a job ID
```
After this PR, the same failure results in this exception:
``` …
```

Propagate SLURM submission errors as exceptions, not `None`

---

parsl/dataflow/dflow.py
parsl/tests/configs/htex_local_alternate.py

This arises from a user interaction where it was unclear that some tasks were failing and retrying due to an application error; and others were failing due to lost managers.
The exception is recorded in the monitoring database, if that is used, and when retries have run out, is returned to the user in the relevant AppFuture but the exception class was not previously recorded in the log file for live investigation while a run is still proceeding.
Before:
1706696631.320572 2024-01-31 10:23:51 MainProcess-4072 HTEX-Queue-Management-Thread-139622759765696 parsl.dataflow.dflow:305 handle_exec_update DEBUG: Task 9 try 0 failed
After:
1706696578.454484 2024-01-31 10:22:58 MainProcess-3792 HTEX-Queue-Management-Thread-140175535478464 parsl.dataflow.dflow:305 handle_exec_update INFO: Task 9 try 0 …

Add exception type to task failed log messages

---

parsl/monitoring/monitoring.py
parsl/tests/test_bash_apps/test_stdout.py
requirements.txt

This PR loosens some type checking to accomodate both typeguard 2.x and 4.x as large parsl users (eg. LSST DESC) still package version 2.x but other users want the latest - 4.x
In typeguard 4.x, local variables are instrumented for type-checking, which is incompatible with using multiprocessing.Queue: multiprocessing.Queue is not a type as far as typeguard is concerned, so a single use of that, in MonitoringHub, is commented out by this PR.
Typeguard 2.x and 4.x have different type error classes, so explicit type checking of exception classes cannot happen in tests as the typeguard 4.x TypeCheckError class does not exist when typeguard 2.x is installed. This PR makes that type-check of type-checking errors happen using string matching of the name of the type-check error class in …

Permit both typeguard 2.x and 4.x

---

parsl/executors/taskvine/manager.py

Forwarding changes in Work Queue #2984 and #3018 to the TaskVine executor
Will increase general task throughput and the performance of serialized tasks
- Bug fix

TaskVine Send/Retrieve Loop Updates

---

parsl/executors/high_throughput/executor.py

scale_in returns block IDs, not provider job ids - that was changed in PR #1952
scale_in does not mark blocks for termination - it uses the provider mechanism to terminate blocks directly.

Rewrite htex scale_in docstring

---

parsl/executors/high_throughput/executor.py

Before this PR, there was a code path where HighThroughputExecutor.scale_in could be invoked with an explicit list of block IDs to scale in, rather than allowing HTEX to choose its own blocks to scale in.
This codepath is not used in the codebase, and I think has never been used since it was introduced in #1563
none

Remove unused codepath in htex scale_in for explicit blocks

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/jobs/error_handlers.py
parsl/jobs/states.py
parsl/tests/test_htex/test_connected_blocks.py
parsl/tests/test_htex/test_disconnected_blocks.py
parsl/tests/test_htex/test_multiple_disconnected_blocks.py

When it comes to an executor using a provider like SlurmProvider to provision resources, there are a few different failure modes that are not well supported.
1. Job fails to submit -> Reported as a provider failure
2. Job starts, workers fail to start with an non-zero exit code reported (LocalProvider) -> Reported as a provider failure
3. Job starts, but workers fail to start (bad env/network config) -> Silently ignored
4. Job starts, but terminates later due to reaching walltime -> Not a failure. 
In case3, when the batch system deems a task as completed/failed, the provider may not see further info reported from the queue. In such a situation the provider marks the job as `JobState.COMPLETED` instead of `JobState.FAILED`. However, this leads to a situation where Parsl would repeatedly …

Better support in HTEX for reporting jobs that fail without connecting

---

parsl/executors/high_throughput/executor.py

This supports the use case where a user wants to launch the regular launch command but inside some kind of wrapper: they can now write
```
HighThroughputExecutor(
launch_cmd = "some_wrapper " + HighThroughputExecutor.DEFAULT_LAUNCH_CMD,
...
)
```
which will use the launch command from the current Parsl version.
The alternative is to cut-and-paste the launch command out of the Parsl source code, which is more fragile.
- New feature

Make HTEX default launch_cmd available as a global

---

.github/workflows/ci.yaml

This is masked on master because of test execution order, but breaks on desc branch at the moment because of re-ordered tests
This broke in PR #2911 which split montoring dependencies into two in setup.py
Tests should be more resilient to makefile re-ordering.
- Bug fix

Add visualization as a dependency for test-viz part of the tests

---

parsl/executors/high_throughput/executor.py

This `if` statement had its inequality the wrong way round and would only truncate arguments when the effective log level was DEBUG or higher:
If the effective log level was exactly DEBUG, then the = part of the inequality fired, and the log message was truncated correctly.
If the effective log level was less than DEBUG (for example, imagine a user-defined TRACE level) then the log message was not truncated, and an unrestricted length log message was output.
If the effective log level was more than DEBUG (for example, WARNING, the default if initialize_logging=False), then the expense of truncation would be incurred, but the result would be discarded by being logged at DEBUG level.
This PR flips that inequality round to correct the behaviour.
It moves all of the log message processing …

Fix and tighten large argument debug line

---

parsl/utils.py

- Make a more informed use of the `threading.Event()`,
- Wait for the defined interval.  Don't calculate the interval, just use it.
- Remove unnecessary class variable

Simplify the Timer class

---

docs/userguide/mpi_apps.rst
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/mpi_prefix_composer.py
parsl/executors/high_throughput/mpi_resource_management.py
parsl/tests/test_mpi_apps/test_mpi_mode_disabled.py
parsl/tests/test_mpi_apps/test_mpi_mode_enabled.py
parsl/tests/test_mpi_apps/test_mpi_prefix.py
parsl/tests/test_mpi_apps/test_mpi_scheduler.py
parsl/tests/test_mpi_apps/test_resource_spec.py

This PR adds the following renaming changes to the `parsl_resource_specification` options defined in the #3016 
* `NUM_NODES` -> `num_nodes`
* `LAUNCHER_OPTIONS` -> `launcher_options`
* `RANKS_PER_NODE` -> `ranks_per_node`
* New kwarg `num_tasks`
Which existing user workflows or functionality will behave differently after this PR?

Renaming parsl_resource_spefication options for MPI Mode

---

parsl/tests/test_scaling/test_scale_down.py

In this particular test configuration, this doesn't really matter: all that is being passed around is a path wrapped in an object; no staging happens; and if staging was configured, this test would usually not work... so it's arguable even that File shouldn't be used here at all and just pass around paths.
It is also not necessary to cast an os.PathLike to a str before constructing a File around it.
Neither of these changes should change the behaviour of this test, but its probably better that they are in the right style in case someone looks at them.

Update style of scaling test File usage

---

Makefile
parsl/tests/test_radical/test_mpi_funcs.py

These tests are highlighting issues raised in issue #3029 and #3089, and should be re-instated as part of resolving those issues.
Between them, the hangs of these tests meant that it was becoming hard, and in some cases apparently impossible, to merge new PRs.
This PR reduces test coverage, which leads to increased unreliability in the codebase.

Skip two tests that are blocking CI with hangs

---

parsl/executors/high_throughput/executor.py
parsl/multiprocessing.py
parsl/tests/test_htex/test_htex.py

We give the Interchange process 10 seconds to terminate when calling the HTEX `shutdown()` method. If it doesn't terminate after 10 seconds, we'll add an informative log to notify the user of the stuck process, and then continue.
I've also updated the tests in `test_htex.py` to ensure we call `htex.shutdown()` at the end of each test.
Fixes #3080 
- Bug fix

Verify Interchange terminates on HTEX shutdown

---

parsl/dataflow/dflow.py

TaskRecord refers to this as "func", an abbreviation of function, for example, and executable brings fake unix process vibes with it.
local variable relabelling, shouldn't affect anyone except people poking in the source code

Use the word "function" not "executable" in DFK for consistency

---

parsl/tests/test_mpi_apps/test_mpi_scheduler.py
test-requirements.txt

https://github.com/testing-cabal/mock says:
> mock is now part of the Python standard library,
> available as unittest.mock in Python 3.3 onwards.

Remove old reference to "mock"

---

parsl/usage_tracking/usage.py

Before this PR, the end message process was terminated immediately, which mean that end messages (in all of my tests) were not sent.
This PR waits 10 seconds for termination before forcing a (now stronger) kill, which in practice is enough for the end message to be sent.
Reasons for making that timeout any larger are primarily DNS-resolution-time related - the tracking DNS record has a TTL of only a few hundred seconds, so it's likely to need re-resolving at end time in any non-trivial run.
In practice on a small pytest run on my laptop, with DNS cached, this new close procedure takes 20ms.
More information is delivered to the usage tracking server - the end message contains different information to the start message
Fixes issue #2532 
- Bug fix

Allow a few seconds for the end message usage process to work

---

parsl/jobs/states.py

Meanwhile, while in the file, move a couple of other instances to f-strings

No sense in formatting the already-formatted

---

parsl/providers/slurm/slurm.py
parsl/providers/slurm/template.py
parsl/tests/test_providers/test_slurm_template.py

This PR updates the stdout/err paths specified in the Slurm templates and updates the reporting of `JobStatus` at terminal states to include the stdout/err paths. I have tested these changes on Expanse by setting the address to `127.0.0.1`.
```
parsl.executors.errors.BadStateException: Executor Expanse failed due to: Error 1:
Job is marked as MISSING since the workers failed to register to the executor. Check the stdout/stderr logs in the submit_scripts directory for more debug information
STDOUT: Found cores : 128
Found nodes : 1
0: Failed to find a viable address to connect to interchange. Exiting
STDERR: srun: error: exp-9-55: task 0: Exited with exit code 5
```
Fixes #3058
- Bug fix

SlurmProvider to report stdout/err when job reaches terminal state

---

docs/userguide/configuring.rst
parsl/configs/expanse.py

Comet@SDSC is retired and is now replaced by Expanse. This PR adds expanse to the configuration section.
PS. I'm not deleting the comet from the configs. 

Replace Comet with Expanse@SDSC in configuration section

---

parsl/providers/pbspro/pbspro.py
parsl/providers/pbspro/template.py
parsl/tests/test_providers/test_pbspro_template.py

This PR adds better support for reporting stdout/err summary when jobs reach a terminal state with the `PBSProvider`.
This is the PBSPro version of the fixes that went in with PR #3091.
* Updated PBSProvider to report job stdout/err via JobStatus when job reaches terminal state
* Adding a simple test to confirm that stdout/err paths are included in internal table
* Removing config for Comet@SDSC which is now retired
When jobs silently fail, for eg, workers are not able to connect to the login node or workers are unable to start due to bad worker environments, the failure information captured in the job stdout/err is summarized in an exception.
Example error from testing on Polaris@ALCF :
```
(gce) rchard@polaris-login-01:~/src/Parsl/tests/failures> python yadu1.py
Launched task.. waiting …
```

PBSProvider to report stdout/err paths when jobs fails

---

README.rst
docs/userguide/usage_tracking.rst

While this and similar words have been used repeatedly in sellling usage tracking to end users, the user's IP address (regarded as at least possibly identifying information under e.g. GDPR, CCPA and HIPAA) is clearly logged on the receiving side, and for at least that reason it is likely incorrect to be calling this information collection anonymous.
https://github.com/Parsl/parsl_tracking/blob/2c9e11e991e38100126d28b18a57f52a0cc01aa0/tracking_listener.py#L38
Until PR #2666, an easily reversible encoding of username was also transmitted, suggesting a general culture of insincerity or naivety around anonymisation, and the onus should now be on the Parsl team to demonstrate a more serious approach before using this kind of phrasing again.
- Update to human readable text: Documentation/error …

Remove "anonymous" in relation to usage tracking

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py

Prior to this PR, the default was hard-coded to "runinfo/" (in PR #2136) which works most of the time, as most of the time, users do not change the Config run_dir.
However, PR #3003 sets Config.run_dir for most tests, resulting in a (mostly silent) monitoring database manager failure. This PR fixes that by allowing monitoring to see that new path, as well as fixing it for all other run_dir changing users.
Note that in Config/DFK there are two uses of the "run_dir" : in Config, that name refers to the root in which .../000/... /NNN/ directories will be created. In the DFK, that name refers to the numbered config.DFK/NNN/ directory.
Since #3003 (which I bisected back to), monitoring has been mostly silently failing with a database opening error appearing in database_manager.log and a …

Use run_dir from Config for monitoring path

---

parsl/channels/errors.py

See PR #1966 for more context
Channel error messages which report via repr rather than str will look different - now using repr-style syntax. Error messages which use str will remain the same.

Remove ChannelError.__repr__ in favor of __str__

---

parsl/providers/cobalt/cobalt.py
parsl/tests/test_providers/test_cobalt_deprecation_warning.py

Cobalt scheduler is no longer in use in any of the major ALCF machines. At this point only JLSE uses Cobalt. 
Since we don't know for sure if there are any parsl users on JLSE, I'm adding a deprecation notice with intent to remove the `CobaltProvider` by 2024-04. 

Add deprecation warning for the CobaltProvider

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

This is to permit imminent changes to this protocol to allow quenching of task delivery as part of work to drain workers near the end of their walltime.
Prior to this PR, the protocol used two formats: the first message in the worker->interchange task_output pipe was a JSON object, the "registration message".
Subsequent messages were not JSON, but an integer encoded as a byte sequence. This integer was historically used for two purposes: as a heartbeat (with value HEARTBEAT_CODE = (2 ** 32) - 1) and as a count of tasks to request from the interchange.
This latter use was removed in PRs #2588 and #3062, leaving only the heartbeat use case.
To allow this channel to be used for richer messages, this PR switches the messages on this stream to always be JSON object, with a 'type' entry: …

Make manager->interchange tasks_output protocol always JSON objects

---

parsl/executors/high_throughput/process_worker_pool.py

The start time is needed as part of upcoming work on walltime-based worker draining (so this PR makes it into an instance attribute)...
... and it can be made more accurate than the previous implementation by measuring it earlier (most especially, prior to invoking the often expensive probe_addresses call)
This PR rephrases a nearby log line which uses the word "starting" despite being not in the start() procedure of the manager, to reduce ambiguity when reading the code vs logs.
Users who pay attention to this log line:
>         logger.info("process_worker_pool ran for {} seconds".format(delta))
might notice a slight increase in the seconds count for "the same" duration runs.

Tidy up htex worker pool start time recording

---

parsl/tests/test_scaling/test_scale_down.py

PR #3097 introduced a more comprehensive test for the htex_auto_scale strategy, based on this test, and prior to this PR, test_scale_down only tested the 'simple' strategy parts of htex_auto_scale.
So, this PR leaves the #3097 test to test the `htex_auto_scale` strategy, and adds coverage for the `simple` strategy.

Repurpose test_scaling/test_scale_down.py for simple strategy

---

parsl/dataflow/future_resolution.py
parsl/tests/test_python_apps/test_pluggable_future_resolution.py

@benclifford: This PR into #3111 is to augment support for shallow-level `AppFuture` resolution.
A few comments:
1. The newly added tests pass on Python 3.11 for me, but I can't figure out the typing syntax for Python 3.8/3.9. I tried replacing `tuple`, `list`, and `set` with `typing.Tuple`, `typing.List`, and `typing.Set`, but that didn't help matters.
2. I tried to generalize [this line](https://github.com/Parsl/parsl/pull/3118/files#diff-d95e44771f15076748fffdf10ae0a92f25b3aeed06a61c26b4488b0103220b20R44) as being of type `Sequence` or `Iterable` instead of `Union[tuple, list, set]`, but when doing the former, the output of the test has `Path(<mapping>)` objects instead of the expected normal `pathlib.Path("str")` kind of result. So, I stuck with the explicit `Union`.
3. This does not …

Adding onto #3111: shallow resolution of lists, sets, and tuples

---

.flake8
parsl/executors/high_throughput/process_worker_pool.py
parsl/executors/workqueue/executor.py

Reduced  flake-8 maximum length and changed some lines which violate the new configuation
This pr wont change any behaviour of the project
Fixes #3105 

Reduce flake8 max-line-length

---

docs/userguide/execution.rst

Added a deprecation notice for the CobaltProvider and updated the list of supported providers in the `execution.rst` file.
- Users will now see a deprecation notice for the CobaltProvider in the `execution.rst` file.
- Updated the list of supported providers to include all available options.
N/A
- Update to human-readable text: Documentation

Update provider list in execution guide

---

.flake8
parsl/dataflow/taskrecord.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/jobs/strategy.py
parsl/providers/slurm/slurm.py

Reduced flake8 max-line-length 151 to 150 and ensured to fix the errors I got when I ran `make flake8`
Which existing user workflows or functionality will behave differently after this PR?
- Bug fix
- New feature

Reduce flake8 max-line-lenght 

---

parsl/dataflow/dflow.py
parsl/usage_tracking/usage.py

Previously the message format was driven by a small "invoke me repeatedly, I'll change my behaviour based on how many times you've invoked me" state machine.
This PR removes that state machine and relies on the DFK knowing whether it is starting up or shutting down - that information is available statically inside the DFK code.
This should not change any behaviour

Change API usage to explict start/end style

---

parsl/executors/taskvine/manager.py

Before this PR, output files and data futures using the taskvine executor were being duplicated, omitting the benefits of caching and peer transfers
taskvine workflows will be able to effectively cache and manage output file data
- Bug fix

taskvine: fix tracking of output files/data futures

---

parsl/jobs/job_status_poller.py

Making the parameters mandatory and without defaults helps in debuggability and in code understanding.
Defaults come from closer to the user, and so the defaults removed here are never used.
To support Parsl users using JobStatusPoller as part of a DFK-free environment (for example, Globus Compute), this PR leaves the dfk parameter to have a meaningful default.
Runtime behaviour should not be changed, as this only removes unused defaults and requires parameters that were already supplied.

Make JobStatusPoller parameters mandatory and remove defaults

---

parsl/monitoring/monitoring.py

This could go through a deprecation cycle, but I'm not aware of anyone specifying them rather than leaving them at their unused defaults, so this PR avoids that deprecation workload.
Anyone specifying these parameters will have to remove them. Monitoring network behaviour should be unchanged because these parameters aren't used.

Remove unused monitoring configuration parameters

---

parsl/log_utils.py
parsl/monitoring/monitoring.py

This PR removes start_file_logger which was similar, but not the same as parsl.utils.set_file_logger. It makes set_file_logger return the chosen root logger, which was the main difference between start_file_logger and set_file_logger.
After this PR, monitoring logs will now use the verbose log format used by parsl.log, instead of their own more terse format.

Use parsl.utils log helpers for monitoring, rather than own variant

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

Prior to this PR, visualizing a workflow with no tasks in it would cause an HTTP 500 server error, caused by an exception raised in the gantt generation code.
However, a workflow with no tasks is a legitimate workflow.
This PR makes task_gantt_plot return None, rather than attempting a plot, which then places no Gantt chart in workflow visualization, rather than breaking.
This bug was exposed through PR #3121 which sometimes (as a legitimate part of that test) results in a monitoring DB with a workflow with no tasks (but not always - that test is testing shutdown behaviour, not database contents).
- Bug fix

Return None rather than raise an exception for Gantt chart of 0 tasks

---

parsl/providers/cluster_provider.py

I fixed the issue "parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True." I changed return True to having a placeholder of nothing. I also edited it inside of the docstring. 
With this new change, the return type of _write_submit_script becomes nothing or falls off the end of the method without a return statement at all.
Fixes #3234 
- Bug fix

Return None rather than constant True from cluster provider _write_submit_script

---

parsl/launchers/launchers.py

As of now, when nodes per block requested is greater than 1 in simpleLauncher , warning log with indicating to set permit multiple nodes to be True for multiple nodes per block, but it is not simpleLauncher supports at the moment even if permit multiple nodes set to be true on call. So it gives the user a false promise.
After this pr, whenever there is a request of multiple nodes per block , we just simply log a warning stating simpleLauncher only supports single node per block
. 
Fixes #3161

removing permit_multiple_nodes argument in simpleLauncher 

---

parsl/dataflow/dflow.py
parsl/jobs/job_status_poller.py
parsl/monitoring/monitoring.py
parsl/monitoring/router.py
parsl/tests/test_monitoring/test_fuzz_zmq.py

The naming of the interchange port suggests that is for the interchange to send monitoring messages, but it is a general ZMQ listening port used by at least the DFK too.
There is another general listening port, listening on UDP, used by the UDPRadio on remote workers.
This PR renames most variables referencing the above connections to have zmq_ and udp_ prefixes, instead of a mix of hub_ and ic_ prefixes, to clarify which variables and parameters apply to which of those two ports.
This clarifies in most of the codebase, for example, that the former hub_port and hub_port_range variables do not control the same thing in different ways, but that one is for ZMQ and ones is for UDP.
This PR avoids changing user-facing parameters, so some ambiguosly named parameters still exist: those should be …

Rename monitoring port variables to reflect use

---

parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

Previously these executors don't exit on their own but wait for the DFK to call their shutdown methods from the DFK's atexit handler. Now the call is removed so these executors add their own atexit handlers to clean themselves up, otherwise a Parsl program using these executors will hang at the end of the program.
These handlers never spawn new threads or processes so they should be safe according to Python3.12's atexit standard.
TaskVineExecutor and WorkQueueExecutor.
- Bug fix
- New feature

WQExecutor + TVExecutor: Automatic cleanup by adding their own atexit handlers.

---

parsl/monitoring/monitoring.py

This message previously talking about initializing ZMQ, but other stuff is happening here too.

Rephrase and move MonitoringHub init log

---

parsl/jobs/job_status_poller.py

These types align with the scale_in and scale_out types defined on BlockProviderExecutor.

Annotate scale_in and scale_out with types in JobStatusPoller

---

parsl/executors/status_handling.py

This dates from 2017, bfd4045b05f3ae9abd554a841e2ab73fb1213a5a and reflects a possible scaling model that is not what ended up being implemented in the subsequent 7 years.

Remove docstring talk of scaling coroutines

---

README.rst

The link in the Readme file's code of conduct section was not redirecting properly.
The link now correctly redirects to the code of conduct.

fix code of conduct link

---

parsl/tests/test_monitoring/test_htex_init_blocks_vs_monitoring.py

This is a test for an uncoming rearrangement of init_blocks handling.

Test that init_blocks blocks are recorded in the monitoring database

---

parsl/dataflow/dflow.py
parsl/executors/base.py

This PR adds type signatures directly on add_executors, and adds an explicit typed property onto the executor base class that is references from add_executors.

Add type signatures related to add_executors

---

setup.py

A recently released version, 1.48, doesn't work with this executor, so this PR aggressively constrains the version to what was passing in Parsl GitHub Actions over the last few weeks.
For further contex, see
https://github.com/radical-cybertools/radical.saga/issues/885#issuecomment-2017520999

Pin radical-pilot to version 1.47

---

parsl/dataflow/errors.py
parsl/dataflow/future_resolution.py
parsl/tests/test_python_apps/test_pluggable_future_resolution.py

Adds support for shallow resolution of Futures in `dict` types for #3111.
Thoughts, @benclifford? This takes care of key futures. It also takes care of value futures, but in this spirit of "shallow" future resolution, it only does so if it `isinstance(value, Future)` and won't (yet) handle more complex cases like a dictionary where the value is a `list` containing a future.

Add support for dicts in future-resolution-plugin (#3111)

---

parsl/dataflow/future_resolution.py

I made sure to use `dict` instead of `Mapping` in the `@traverse_to_gather.register(dict)` and `@traverse_to_unwrap.register(dict)` since we are specifically returning a `dict` in the wrap function. In principle, this could likely be made more general to `Mapping`, but let's start simple for now.

Use `dict` instead of `Mapping` in #3111

---

parsl/tests/test_monitoring/test_htex_init_blocks_vs_monitoring.py

A more principled fix of #3287 looks to be much more deeply invasive, and involves a big rework of how ZMQ is used.
- Bug fix

Tighten database access in htex/monitoring test to avoid issue #3287

---

parsl/executors/high_throughput/process_worker_pool.py

Before this PR, sometimes draining would fail with this error message:
```python
File ".../lib/python3.10/site-packages/parsl/process_loggers.py", line 27, in wrapped
r = func(*args, **kwargs)
File ".../bin/process_worker_pool.py", line 322, in pull_tasks
next_interesting_event_time = min(last_beat + self.heartbeat_period,
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```
because the code incorrectly sets drain time to `None` to indicate that further draining messages should not be sent.  An earlier version of the drain code used `None` in that situation, but this was changed to +inf in the version that was actually merged.
This error is statically detectable by mypy, if you turn on mypy checking for pull_tasks, although it …

Fix TypeError race condition in htex draining code

---

parsl/dataflow/dflow.py

Previously this message said an executor was not being shut down when it is in a bad state. This `if` statement is actually about scaling in the executors blocks. Shutdown always happens, a few lines later.

Correct not-scaling-in log message

---

parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

Previously, WQ and TV Executors can be shut down twice, one by the registration of `shutdown` to atexit, one by the user explicitly calling `parsl.dfk().cleanup()`. This PR makes the effect of these executors shutdown happen only once. Note that previously the shutdown methods don't create bugs as they only call process joins and a python process can be joined many times, but future bugs might come.
WQ and TV Executors

WQ + TV Executors: Making their shutdown methods idempotent

---

README.rst

Added instruction to README: "To prevent errors when running the 'make' command immediately after cloning, remind users to navigate to the root directory by using the command 'cd Parsl' first."

Add `cd` command to README

---

parsl/dataflow/dflow.py
setup.py

When attempting to use the with statement with `parsl.load()` to manage a DataFlowKernel object (dfk). Currently, the context manager protocol does not correctly assign the loaded DataFlowKernel to dfk, resulting in dfk being `None`. The desired solution is to ensure that `with parsl.load() as dfk`: That assigns the loaded DataFlowKernel object to dfk
now the DFK context manager should return DFK
Fixes # (https://github.com/Parsl/parsl/issues/3292)
- New feature

Return DFK in context manager

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py
parsl/jobs/job_status_poller.py
parsl/jobs/strategy.py
parsl/tests/test_htex/test_drain.py

This is part of issue #3278 tidying up job and block management.
Now init_blocks scale out happens on the first strategy poll, not at executor start - that will often delay init_blocks scaling by one strategy poll period compared to before this PR.

Handle init_blocks in scaling strategy, rather than special-casing it

---

docs/reference.rst

Remove duplicated `parsl.providers.GridEngineProvider`from docs
N.A.
N.A.
- Update to human readable text: Documentation

Remove duplicated parsl.providers.GridEngineProvider

---

parsl/dataflow/dflow.py
parsl/jobs/job_status_poller.py
parsl/jobs/strategy.py

This should not change behaviour, but should make the behaviour of this class a bit more understandable for human readers.
The history here was PollItem used to be two classes, PollItem and ExecutorStatus. Those two classes were merged, leaving only PollItem; and the combo gained more facade-like behaviour, rather than being a only status cache.
none

Rename PollItem to reflect its current role as a facade on executor

---

parsl/executors/high_throughput/executor.py
parsl/executors/status_handling.py
parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py
parsl/tests/site_tests/test_provider.py

This PR makes it more obvious what they are maps for, and that they are/should be inverses of each other.
none

Rename self.blocks and self.block_mapping for human clarity

---

parsl/dataflow/dflow.py
parsl/monitoring/remote.py

This function has a lot of parameters, and long sequences of positional parameters are hard to align. See #2973 for similar work elsewhere.
none

Force kwargs for monitor wrapper for reduced maintenance fragility

---

parsl/dataflow/dflow.py
parsl/jobs/job_status_poller.py

Changed behaviour: this will now happen slightly before it used to, but the differences are only changed place in the call stack, and log messages will appear in a different order now - so the actual scaling-in behaviour should be unchanged.

Move scale in at exit code into close method of job status poller

---

parsl/executors/status_handling.py

The call happens only in one place, and it only modifies a block-related data structure, right next to code that more directly modifies block-related data strucutres.
This PR makes all of those block-related data structure changes happen at the same level.
This call is not asynchronous, and this PR also removes that confusing use of the term async.
This should not change any behaviour.

Inline fail_job_async

---

parsl/jobs/job_status_poller.py
parsl/jobs/strategy.py

This is part of work to move JobStatusPoller facade state into other classes, as part of job handling rearrangements in PR #3293
This should not change behaviour: each executor has a single PolledExecutorFacade and a single strategy.ExecutorState, and this PR moves the 'first' field from one to the other.
parsl/tests/test_monitoring/test_htex_init_blocks_vs_monitoring.py tests that init_blocks handling still fires properly - that's what is switched by this 'first' field.
none

Move 'first' field into strategy state

---

parsl/jobs/job_status_poller.py

The DFK is only used to initialise monitoring, in `__init__`, and is not used after that. The object that lives beyond `__init__` is `self.hub_channel`.
This is part of work to move `JobStatusPoller` facade state into other classes, as part of job handling rearrangements in PR #3293
This PR should not change behaviour.

Do not store DFK in PolledExecutorFacade

---

parsl/jobs/job_status_poller.py

This is part of work to move JobStatusPoller facade state into other classes, as part of job handling rearrangements in PR #3293
This value is constant, in both executors and in PollingExecutorFacade.
This PR should not change behaviour

Do not duplicate executor polling interval in PollingExecutorFacade

---

.flake8
parsl/executors/high_throughput/process_worker_pool.py
parsl/jobs/strategy.py

Reduced the max-line-length in flake8 from 146 to 145. Fixed the subsequent errors due to files exceeding the max-line-length.
Fixes #3105 

Reduce flake8 max-line-length from 146 to 145

---

parsl/data_provider/data_manager.py
parsl/data_provider/zip.py
parsl/tests/test_staging/test_zip_out.py
requirements.txt

This output file staging mechanism provides a zip: URL scheme, naming
a file inside a zip file; output files from apps can be staged out into
this location. Input staging is not supported.
The use-case for this is as part of a sequence of PRs separating
PR #3306, leading to stdout staging into zipfiles.
This is new functionality only activated by use of the `zip:` URL scheme, which previously would have raised an error.
- New feature

Add ZipFileStaging to archive outputs into a zip file

---

parsl/tests/conftest.py

Not-running-tests-in-CI is achieved by more subtle means, such as topic and issue specific test markers.

Remove unused 'noci' pytest marker.

---

Makefile

These tests all pass with Work Queue and Task Vine in CI and on my laptop.
Some of these used to fail, but PR #2803 changed the stdout/stderr paths from relative paths to absolute paths (to move files into a per-test working directory). This then causes a different codepath for std* behaviour to be followed in Task Vine and Work Queue: when give absolute paths, those executors assume a shared file system without staging.
For example, test_stdout_truncate in parsl/tests/test_bash_apps/test_stdout.py work as currently written, but fails if this change from PR #2803 is reverted:
```
def test_stdout_append(tmpd_cwd):
-    out = str('t1.out')
+    out = str(tmpd_cwd / 't1.out')
```
Making a more formal model of how Work Queue and Task Vine should handle relative vs absolute paths as a signal …

Remove 'not issue363' markers from Work Queue and Task Vine tests

---

parsl/jobs/job_status_poller.py

This PR removes the notion of a shared current time among all polls.
Instead each facade poll looks up the current time individually.
Although executor polls are all launched from the same loop, there's no need for them to act as if they are being polled at the same moment in time, which in the case of multiple executors, will be some time in the past.
This means there is one less variable shared between polls of different executors, which is part of work pushing executor polling deeper into each executor away from the per-DFK JobStatusPoller.
This will change the cadence of polling: `now` may be measured a bit later, especially in the presence of multiple executors, causing meaning a poll that might have previously skipped to now run, and as a knock on, all subsequent skips/updates will …

Unshare "now" timestamp across executor polls

---

parsl/jobs/job_status_poller.py

`self.monitoring_enabled = True` is equivalent to `self.hub_channel` being assigned.
This PR uses a more type-driven style of a single Optional for `hub_channel`, removing `monitoring_enabled`.
This PR should not change behaviour.

Merge PollingExecutorFacade monitoring_enabled and hub_channel

---

parsl/jobs/job_status_poller.py

It was used once, a couple of lines below.
This PR should not change behaviour.

Inline PolledExecutorFacade._should_poll_now

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py
parsl/monitoring/router.py

Prior to this PR, the monitoring router exited due to receiving a WORKFLOW_INFO message with an exit_now field set to True, but only if that message was received through a specific path.
This PR removes that exit_now field, and makes the monitoring router exit on a multiprocessing event. This removes the need for the exit message to arrive through that specific path into the router, which makes message handling more consistent, and opens up opportunities to feed messages into monitoring through different paths.
Slowly ongoing work has been trying to make all the different monitoring message paths behave the same with a goal of eliminating some of them, and this change also works towards that.
Exiting might behave slightly differently: before this PR, the exit message was sent a bit before …

Exit monitoring router exit on multiprocessing event, not exit message

---

parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

Before this PR, the scale in methods for those executors returned None, in violation of the type specification in `BlockProviderExecutor`. This PR adds type annotations to cause those methods to be type checked.
This PR adds handling for return value based on the HTEX implementation of scale_in to both Work Queue and Task Vine executors.
This PR adds a few debug logs around behaviour there.
These return values are not used anywhere (which is why this has not been a problem) but an upcoming PR will both make use of them (in monitoring) and test that something is returned.
none in current code - pre-emptive bugfix for broken monitoring in upcoming PR.
- Bug fix

Fix scale_in return values for Work Queue and Task Vine

---

parsl/providers/local/local.py

Before this PR, `proc_id` was used in log messages as if its a symbol such as a local variable or function parameter. It is not.
This PR replaces `proc_id` with human words.

Replace proc_id with human words in LocalProvider debug log

---

Makefile

This is needed for PR #3339 to make Work Queue and Task Vine tests in --config local mode
- New feature

Make CCTOOLS environment available to --config local tests

---

parsl/jobs/job_status_poller.py

I can't find anywhere this is used: I think PolledExecutorFacades are never referenced outside of job_status_poller.py and strategy.py; and in both of those files, I cannot see anywhere that a PolledExecutorFacade is repr'd.
This PR should not change any behaviour.

Remove (unused?) PolledExecutorFacade __repr__

---

mypy.ini
parsl/jobs/job_status_poller.py

This reveals one type error, that JobStatusPoller does not properly implement the .close() method signature. This PR fixes that and passes the new timeout parameter to the superclass which can make use of it.
should be none - JobStatusPoller.close() is only called in the codebase without this new parameter.

Turn on type checking for all of parsl.jobs.*

---

parsl/dataflow/futures.py

This refers to DataFutures which do not live in this module. AppFutures are already described in the AppFuture docstring.

Remove outdated parsl.dataflow.futures docstring

---

parsl/dataflow/dflow.py
parsl/jobs/job_status_poller.py
parsl/monitoring/monitoring.py
parsl/monitoring/radios.py
parsl/tests/test_monitoring/test_fuzz_zmq.py

Before this PR, the DataFlowKernel and each JobStatusPoller PolledExecutorFacade each opened a ZMQ connection to the monitoring router. These connections are not threadsafe, but (especially in the DFK case) no reasoning or checking stops the DFK's connection being used in multiple threads.
Before this PR, the MonitoringHub presented a 'send' method and stored the DFK's ZMQ connection in self._dfk_channel, and each PolledExecutorFacade contained a copy of the ZMQ channel code to open its own channel, configured using parameters from the DFK passed in at construction.
This PR:
* moves the above uses to use the MonitoringRadio interface (which was originally designed for remote workers to send monitoring information, but seems ok here too)
* has MonitoringHub construct an appropriate …

Replace DFK and JobStatusPoller monitoring zmq channels with Queue radio

---

parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/status_handling.py
parsl/tests/test_monitoring/test_basic.py

This method makes sense for `BlockProviderExecutors`, where it is used by the `JobStatusPoller`. It does not make sense for Parsl Executors in general and is not otherwise used. So remove from the `ParslExecutor` base class, which removes the dependency of `parsl.executors.base` on `parsl.jobs.*`, a cleaner separation of concerns.
This method is implemented in `HighThroughputExecutor`, but the information generated only uses `BlockProviderExecutor` information and would make sense for other BlockProviderExecutors (Work Queue, Task Vine and the erstwhile IPP and Extreme Scale executors). Using this implementation has been prototyped in the desc branch of parsl since 2021. So move that implementation out of `HighThroughputExecutor` and into `BlockProviderExecutor`.
This should not change …

Unabstract executor.create_monitoring_info

---

parsl/dataflow/dflow.py
parsl/tests/test_bash_apps/test_basic.py
parsl/tests/test_bash_apps/test_stdout.py

Before this PR, an invalid stdout/err stream was logged at WARNING level and the filename as recorded in the monitoring database was set to the exception message.
This PR elevates that log to an ERROR, because this is an error, including the exception message to give a debugging hint.
In this error case, a blank stdout or stderr will be recorded in the monitoring database. Generally the task will fail later due to other parts of the code being unable to interpret the specification.
less confusing stuff in the monitoring database. more noise in logs.

Rework monitoring recording of invalid stdout/err streams

---

parsl/dataflow/dflow.py

Previously, stdout/err logs no output if the streams were not set (i.e. defaulting to None) and logged with the entire stream target if set.
This PR adds more cases here with case specific logging: if stdout/err is not redirected, that is now logged. If tuple mode is used, the tuple is unpacked and logged as separate fields. If an unknown format is specified an error is logged (but no exception is raised - it is not the job of this code to validate the stdout/err specifications)
This PR is in preparation for a new case to be added in an upcoming PR which requires more serious formatting that was not accomodated by the previous implementation.
log messages - including a new error log

Add more cases for std stream logging

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/jobs/job_status_poller.py

This is a step in consolidating responsibility for BLOCK monitoring into the BlockProviderExecutor.
Before this PR, executors were already configured ad-hoc with a lot of monitoring information. This PR adds another attribute to that collection for the local monitoring radio.
This PR removes some more state from the PolledExecutorFacade class.
This PR should not change behaviour - it changes the code path by which the job poller's monitoring radio is found.

Move monitoring radio reference from JobStatusPoller to BlockProviderExecutor

---

parsl/jobs/job_status_poller.py
parsl/jobs/strategy.py

This is in preparation for moving all the `PolledExecutorFacade` code into `BlockProviderExecutor`, in an upcoming PR.
There should now be no intersection in the attributes or methods of `PolledExecutorFacade` and `BlockProviderExecutor`, in the methods that will move. `__init__` is an exception because it will merge with the `__init__` of `BlockProviderException`.
The renamed methods are slightly awkwardly named because there isn't a short adjective that I have found that adequately describes the difference between `BlockProviderExecutor` and `PolledExecutorFacade` behaviours.
Future untangling work in this area will necessarily involve quite a lot of rearranging and picking appropriate names for whatever remains is part of that future work - so no bikeshedding over adjectives.
This PR …

Rename PolledExecutorFacade methods that overlap BlockProviderExecutor

---

parsl/executors/status_handling.py
parsl/jobs/job_status_poller.py
parsl/jobs/strategy.py

This should be code movement only and should not change functionality.
This consolidates scale in/out and status functionality in BlockProviderExecutor, which hopefully makes future work rearranging the three sources of block status information easier.
none

Move PolledExecutorFacade functionality into BlockProviderExecutor

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_scaling/test_scale_down_htex_unregistered.py

Prior to this PR, the scale_in code for the `HighThroughputExecutor` will not scale in any block that has not had at least one manager register with the interchange, because it retrieves the list of blocks from the interchange. This is documented in issue #3232 
This PR makes the htex scale in code also pay attention to blocks in the status_facade list - which includes blocks that have been submitted, and blocks which have been reported by the provider mechanism.
Scaling in will now scale in more blocks.
Fixes #3232 
- Bug fix

Make HTEX scale-down be aware of unstarted blocks

---

parsl/tests/test_htex/test_zmq_binding.py
setup.py

Two simultaneous CI-rot breakages have happened and this PR fixes them simultaneously - they cannot be fixed individually because neither fix is sufficient to pass CI.
RADICAL-Pilot installation broke recently in CI, through some change outside of the Parsl repository, and even with a pinned RADICAL-Pilot version. More recent radical-pilot will install OK, and this PR advances the pin to that more recent version. This might be something to do with this fix introduced in https://github.com/radical-cybertools/radical.pilot/pull/3169 but I'm not completely clear.
Issue #3037 started happening in CI. That issue is that a test checks a property that it might not actually be reasonable to expect to hold. This PR skips that issue, leaving further work for whoever adopts issue #3037.
- Bug fix

Fix two CI-rot breakages

---

parsl/app/bash.py
parsl/app/errors.py
parsl/utils.py

Prior to this PR, this exception class had a mandatory nested exception attibute.
This PR removes that exception, because Python already has some nesting mechanisms for exceptions which would serve well enough here: https://docs.python.org/3/tutorial/errors.html#exception-chaining
This change allows exceptions to be optionally chained like any other Python exception; or not chained at all, simplifying one use of BadStdStreamFile where a contrived TypeError was constructed to fill the slot.
Any user code catching BadStdStreamFile exceptions and extracting the chained exception will have to be adapted to live without that chained exception.

Remove nested exception from BadStdStreamFile exception

---

parsl/addresses.py

Currently `get_all_addresses` presents every single missing address from say `address_by_interface` to info when realistically, this is not useful at all. Any single method failing is not worth presenting to the user, and is useful only in a debug context.
`get_all_addresses` will report missing interface lines to debug rather than info.

`get_all_addresses` to log at debug level instead of info

---

parsl/dataflow/dflow.py
parsl/executors/base.py

Setting these attributes in the constructor makes reasoning about later use less complicated.  If an Executor is instantiated these exist.  Whether or not they've been set to a non-default value is another question.
Functionally for users, this should represent no change.  These attributes are nominally already set by the rest of Parsl's infrastructure.  For developers, this change simply makes reasoning about the state of Executors a little easier.

Set Executor attributes in super class constructor

---

parsl/tests/test_monitoring/test_stdouterr.py
parsl/utils.py

Prior to this PR, an arbitrary os.PathLike was rendered to monitoring using that PathLike's str method. What should be appearing in the monitoring database should be a string representation of the path. This is an issue in (rare in practice?) cases where `__str__` and `__fspath__` return different things. This PR changes rendering to use `fspath` rather than `str`.
os.PathLike objects can also render as `bytes`, not `str`. This PR decodes those bytes using `.decode()`.
This PR adds tests for various valid data types going from app stdout/err parameters to the corresponding column in the monitoring database, including test cases that drove the above fixes.
This will change how some stdout/stderr paths are rendered to the monitoring database, hopefully for the better.
- Bug fix

Fix broken stdstream handling for bytes and arbitrary os.PathLike objects; test harder.

---

parsl/app/bash.py
parsl/dataflow/dflow.py
parsl/dataflow/futures.py
parsl/tests/test_bash_apps/test_basic.py
parsl/tests/test_monitoring/test_stdouterr.py
parsl/tests/test_staging/test_staging_stdout.py

Prior to this PR, stdout and stderr were treated as string pathnames interpreted in an executor specific context: for example, htex treats them as paths on the worker filesystem; Task Vine treats these paths as names of files that should be staged to the submitting system.
This is/was different to the treatment of files placed in the outputs kwarg of an app using File objects. Those file objects can be staged out arbitrarily using Parsl file staging.
This PR allows File objects to be specified for bash_app stdout and stderr kwargs, and stages those files out in the same way as outputs-kwarg files are staged.
This PR preserves the previous str-based behaviour without staging. This is inconsistent with the data staging mechanism, which only accepts Files, but preserves backwards …

Treat stdout and stderr as stageable Files

---

parsl/dataflow/dflow.py
parsl/tests/test_monitoring/test_stdouterr.py

PR #3347 attempted to do case-based logging of all the different kinds of stdout/err specification.
It failed to capture some of the cases involving os.PathLike, and so after PR #3347, those cases would log an ERROR that the specification was unknown. This new behavior is only a new ERROR logging message - PR #3347 did not change other behaviour.
This PR also amends a rich test of stdout/err specification types introduced in PR #3363 to check that no ERROR messages are logged during these tests.
- Bug fix

Fix stdout/err log errors introduced by PR #3347

---

parsl/monitoring/monitoring.py

This frees up some threads and file descriptors.

Shutdown multiprocessing queues at monitoring shutdown

---

parsl/executors/workqueue/executor.py

This frees up some threads and file descriptors.

Shutdown multiprocessing queues at Work Queue shutdown

---

parsl/executors/taskvine/executor.py

This frees up some threads and file descriptors.
cc @tphung3 @colinthomas-z80 etc

Shutdown multiprocessing queues at TaskVine shutdown

---

parsl/tests/test_python_apps/test_context_manager.py

This test used to re-use a temporary intermediate file by appending to it. When run multiple times, it failed with errors like this as the results from previous runs are also observed by the test:
```
E               AssertionError: assert '2\n2\n2\n2\n' == '2\n'
```
This PR uses `tmpd_cwd` to avoid that behaviour.

Fix broken test that cannot be run multiple times in same environment.

---

parsl/tests/test_scaling/test_regression_1621.py

PR #2816 introduced a workaround in the polling API by adding a new thread to call job status poller poll() method more frequently than the JobStatusPoller invokes that method.
PR #3246 introduced general configurability of the JobStatusPoller poll period.
This PR replaces the thread from #2816 with the configuration option from #3246.
This PR removes one thread left running at the end of this test case, in --config local tests.

Use strategy_period in test, instead of custom thread

---

parsl/tests/configs/local_threads_checkpoint_periodic.py
parsl/tests/conftest.py
parsl/tests/test_checkpointing/test_periodic.py

The checkpoint is the threshold of interest, so rather than waiting for an inordinate amount of time, dynamically ascertain what the checkpoint wait time is.  Add 1 second to that value for good measure.
Test time reduced from ~20s locally to ~4s.

Reduce test sleep()

---

parsl/dataflow/dflow.py

Parsl shutdown logs are deliberately rich at shutdown time because this is an incredibly hang prone part of the code-base.
See https://github.com/Parsl/parsl/labels/safe-exit
This PR adds logs bracketing the shutdown of the usage tracker, in line with later shutdowns of the job status poller, executors and monitoring.
two more log lines at shutdown

Add logs around usage tracker shutdown

---

parsl/dataflow/dflow.py

Prior to this PR, the closure stageout_one_file is redecorated by typeguard on every invocation, so once per task that is using files, and instruments that closure each time with internal type checking code. This was introduced incidentally as part of PR #3348.
This PR removes that runtime type-checking. In general, parsl-internal calls should be checked statically by mypy if possible, not by typeguard, which should be reserved for the interface with users.
Prior to this PR, parsl-perf modified to use a File stdout on my laptop ran at median 2176 tasks per second. After this PR, median 2627 tasks per second.
@svandenhaute experienced a much starker difference on a psiflow test case, with one test case that takes 40 seconds reduced to 9 seconds by this PR, the same performance as before PR …

Remove expensive typeguard call from file staging closure

---

parsl/tests/conftest.py
parsl/tests/unit/test_file.py

We may have other UTs littered among the other tests, but this file now sets the stage (via the new `unit/` directory) for where to place them.  A not-complete metric for UTs: do they they run _fast_?  If not, or if the test includes `.sleep()`, it's probably not a UT.

Add first unit test for File

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_htex/test_missing_worker.py

This releases two fds in the workflow process used to communicate with the interchange process, and is part of work to release more resources explicitly at shutdown rather than leaving them until process end.
One test was making an out-of-API shutdown of HTEX on the basis that the DFK would not shutdown this executor when a bad state was set. That used to be true, but PR #2855, which re-arranged some shutdown behaviour, (accidentally?) changed shutdown to always happen. That is, I think, the right shutdown behaviour: if an executor wants to suppress parts of its own shutdown based on internal state, that's the business of the executor, not the DFK.
This PR removes that out-of-API shutdown.
As exposed by the changed test, shutdown behaviour is a bit peturbed: for example, situations where …

.close() interchange process to release more fds

---

CONTRIBUTING.rst

The previous description of putting `--config local` tests into /sites/ and /integration/ does not reflect the reality of current Parsl development. cc @khk-globus who has put some thought into test organisation, but for now remove that advice.

Rework description of --config local tests

---

parsl/tests/test_mpi_apps/test_resource_spec.py

Use local config for htex MPI test, instead of setup/teardown fixutre

---

docs/userguide/plugins.rst
parsl/config.py
parsl/dataflow/dflow.py
parsl/tests/test_bash_apps/test_std_uri.py

A generation function can now be specified at configuration time, with the previous behaviour invoked as default.
None: If this parameter is not specified, parsl.AUTO_LOGNAME should generate the same names as before this PR.
- New feature

Make parsl.AUTO_LOGNAME generation pluggable

---

parsl/providers/kubernetes/kube.py

This PR supersedes https://github.com/Parsl/parsl/pull/2503
See https://github.com/kubernetes-client/python/issues/1005 for a good description of the issue.  
The `KubernetesProvider` now falls back to loading config in-cluster if a kube-config file is not found. This allows in-cluster submission of parsl jobs.
- Bug fix

Use incluster config fallback for KubernetesProvider

---

README.rst

This functionality was introduced in #3260 and we should be encouraging people to use it in order to clean up nicely, after PR #3165 took away atexit handler cleanup.

Use DFK in a `with` block in README

---

parsl/executors/workqueue/executor.py

This PR removes the atexit handler of WorkQueueExecutor as discussed in https://github.com/Parsl/parsl/issues/3334.
WorkQueueExecutor
Fixes #3334
- Bug fix

WorkQueueExecutor: remove atexit handler

---

parsl/executors/taskvine/executor.py

This PR removes the atexit handler of TaskVineExecutor as discussed in https://github.com/Parsl/parsl/issues/3334.
TaskVineExecutor
Fixes #3334
- Bug fix

TaskVineExecutor: remove atexit handler

---

parsl/monitoring/monitoring.py

Before this PR, pytest parsl/tests/test_monitoring/ leaves 1093 fds open (which is too much for the test suite to complete in some default configurations of max fds 1024)
After this PR, that test run leaves 895 fds open.

Close monitoring processes at shutdown, freeing some fds

---

parsl/executors/status_handling.py

This TODO was implemented in PR #2858

Remove a TODO for pluggable block error handling

---

parsl/dataflow/dflow.py

This hook is only to deal with reminder the user about cleanup and is otherwise unnecessary.
The exit warning about cleanup state is now switched based on the presence of the atexit handler or not, rather than the cleanup called variable.
Effects of this PR:
* removed log noise
* one less garbage collector reference to the DFK - although that won't directly lead to the DFK being collected earlier, it might in combination with other future work.
peturbed exit behaviour, hopefully for the better

Unregister atexit hook at cleanup

---

setup.py

On 10th May 2024, a new version of radical.utils was released, which does not work with the pinned radical.pilot==1.52.1 used by Parsl.
I also tried upgrading radical.pilot to 1.60, released alongside the new radical.utils, but that does not work for other reasons documented in the below issue.
See Parsl issue #3429
cc @AymenFJA @andre-merzky
radical.utils will no longer follow the latest (or at least, the latest under whatever radical.pilot constrains things to) - that's a good thing from this PR's perspective.
Fixes #3429
- Bug fix

Pin radical.utils version, to work with pinned radical.pilot

---

parsl/executors/high_throughput/executor.py

These have been initialised in the ParslExecutor base class since #3361
none

Remove double init of some HTEX/monitoring attributes

---

README.rst
docs/index.rst
parsl/executors/status_handling.py

It bothers me that there is no parallelism in the README.
N/A
N/A

Use concurrency in the README

---

parsl/channels/base.py
parsl/channels/local/local.py
parsl/channels/oauth_ssh/oauth_ssh.py
parsl/channels/ssh/ssh.py

Theres was no defined meaning to the return bool either in the code or in the human text:
- no code calls close to give an example of interpretation
- it's not success/fail because local channel returns False to indicate that it didn't need to do anything, not that there was a failure.
Other .close() style methods return None and raise an exception if there is a problem. This PR pushes Channel.close() in this direction.
A separate PR will actually invoke this .close() method.
This is an apparently unused return value so should not affect anything.

Remove return bool from Channel.close()

---

parsl/monitoring/remote.py

Factor radio selection in monitoring worker-side code

---

parsl/executors/high_throughput/interchange.py

The interchange command protocol is tied to the submit side closely, and it is generally a programmer or deployment error rather than intentional cross-version compatibility that would result in this unknown command code path firing.
more logging in error situations

Log commands that the interchange does not recognise, as an error

---

parsl/providers/local/local.py

Fixes #3437, a problem which was created by me in the first place.
Does not remove the `parsl.` prefix from the hostfile written when using localprovider.
Fixes #3437 
- Bug fix

Remove $ when writing job name

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py

This follows a rename in PR #3266 which focused on making the same change inside parsl/monitoring/
A final use of hub_port is left in place in the MonitoringHub constructor because it is user-facing - future work on monitoring radio plugins might change this significantly (or not) so I am leaving it as is for now.
none

Rename hub_port in executors to clarify it is for ZMQ

---

parsl/dataflow/dflow.py

PR #2989 made dependency errors look nicer, but only did it for positional 
parameters. This PR extends that to kwarg and inputs=... dependencies.
PR #2989 describes these changes in more depth.
This PR adds a type annotation onto DFK._unwrap_futures that drives this
change - preventing _unwrap_futures from returning None task ids for failed
dependencies and instead requiring the task IDs to be strings.

Extend dependency error change in #2989 to remaining two dependency types

---

CONTRIBUTING.rst

Prior to this PR, there were not enough `-` symbols so GitHub's RST renderer did not recognise this as a heading.

Fix misformatted 'Credits and Contributions' section heading

---

CONTRIBUTING.rst

Remove incorrect historical reference to Parsl semantic versioning

---

CONTRIBUTING.rst

Branch names are largely irrelevant in the squash PR model: PR text provides much richer context; branch names do not find their way into permanent history; and we have been successfully operating with arbitrary branch name choices without trouble for a long time.

Remove issue number recommendation from CONTRIBUTING branch names

---

README.rst

Updating the CoC link in the README's [Code of Conduct](https://github.com/Parsl/parsl/blob/master/README.rst#code-of-conduct) section reflects recent updates. I've linked it to the CoC tab in parsl/parsl so users aren't unnecessarily routed to the .github repo.
N/A
N/A

Update CoC link in README

---

parsl/dataflow/dependency_resolvers.py
parsl/tests/test_python_apps/test_pluggable_future_resolution.py

Prior to this PR, the `dict` part of `DEEP_DEPENDENCY_RESOLVER` did not extract all futures that it should in the gather stage, meaning that sometimes the unwrap stage would happen too early. Prior to this PR, only keys and values of a `dict` that were directly `Future` objects would be waited for by the DFK, rather than deep-recursing into those key/value objects. This would result in `Future.result()` happening too early (and blocking, potentially forever).
This PR switches out that behaviour to call deep_traverse_to_gather recursively, instead of using an `if`.
This PR adds a test case which demonstrates this change. That test case will hang without the above change, but pass with this change.
This PR adds asserts to the code that unwraps `Future` objects, to assert that the future …

Fix delay/hang when resolving deep dictionary dependencies

---

parsl/dataflow/dependency_resolvers.py

deep_traverse_to_gather (and any traverse_to_gather) always returns only Futures in its return list, so this if statement will always fire (or at least, if it doesn't, it is a bug, not something to be ignored by this `if`)

Remove redundant `if` statement in dependency resolver deep traversal

---

parsl/dataflow/dependency_resolvers.py

Add type annotations to DependencyResolver fields

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/zmq_pipes.py
parsl/tests/test_htex/test_command_client_timeout.py

This clarifies our intention to use a separate ZMQ context for each ZMQ pipe, which simplifies the handling of ZMQ pipe objects.
Fixes #3457 

Make ZMQ context per pipe explicit

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py

Before this PR, the interchange used a multiprocessing.Queue to send a single message containing the ports it is listening on back to the submitting process. This ties the interchange into being forked via multiprocessing, even though the rest of the interchange is architected to be forked anyhow, as part of earlier remote-interchange work.
After this PR, the CommandClient used for other submit-side to interchange communication is used to retrieve this information, removing that reliance on multiprocessing and reducing the number of different communication channels used between the interchange and submit side by one.
See issue #3373 for more context on launching the interchange via fork/exec rather than using multiprocessing.
The CommandClient is not threadsafe - see #3376 - and it is …

Use CommandClient for interchange port reporting instead of Queue

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/test_htex/test_cpu_affinity_explicit.py

This PR makes two changes:
1. `os.sched_(get/set)affinity` is not supported on MacOS. This PR ignores mypy errors from code blocks that touch on affinity that are not used in MacOS.
2. Skip tests that touch on affinity that are not expected to work on MacOS.
- Bug fix

Ignore mypy errors and skip tests that don't work on MacOS

---

docs/quickstart.rst
docs/userguide/usage_tracking.rst
parsl/usage_tracking/usage.py

This PR removes the use of `$PARSL_TRACKING` env variable to setup usage tracking configuration. Parsl will now only take usage tracking configuration from the `config`
Anyone using only the env variable `PARSL_TRACKING` to enable usage tracking will need to set `usage_tracking = True` within the `config` to enable usage tracking.
Fixes #3456 
- Update documentation

Remove environment variable configuration for usage tracking

---

Makefile

This shoudn't change user-facing behaviour, but will enforce sorting on fewer files than before this PR when testing.

isort only parsl/ for consistency with flake8, mypy, lint-inits

---

docs/faq.rst

Add FAQ on surviving end of a batch job

---

parsl/config.py
parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_context_manager.py

Most important is a ``wait`` exit mode which will make the context manager wait for tasks to complete at exit, unless an exception is raised. This addresses a common usability problem where users forget to wait for their tasks and are then confused by their workflow exiting immediately, but does not defer exceptions - this block-on-exception behaviour was the main usability problem when attempting this before in PR #610.
The default mode should preserve existing behaviour - so none.
- New feature

Add exit choices for the DFK context manager

---

parsl/tests/conftest.py
parsl/tests/test_bash_apps/test_stdout.py

I've encountered a bunch of situations in the last few months where people were running the test suite in environments where filesystem permissions were not enforced - various container/virtual machine situations running as root.
In such a situation, some tests are not expected to pass, as those tests test that a (not-happening) OS-level filesystem permission error is correctly passed back to the Parsl user.
- Bug fix

Add a marker for tests which test errors caused by unix filesystem permisions

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/tests/test_htex/test_zmq_binding.py

This PR makes all parameters to the Interchange class into mandatory keyword-only arguments.
The removed defaults were not used in production use, because they were all specified explicitly in parsl/executors/high_throughput/executor.py too.
The single exception to this was client_address, which was defaulted in the interchange and never specified by the exeuctor. This PR moves that default into executor.py too, to work like all the other defaults.
See similar changes to the process worker pool, PR #2973, for more detailed justification.
test_zmq_binding.py is the only test which instantiates Interchange objects directly (rather than testing the executor as a whole) and this PR modifies that test to explicitly specify all interchange parameters rather than relying on the otherwise-unused …

Remove unused-in-production HTEX interchange default values

---

parsl/app/app.py

Testing to see if `AppBase` needs `outputs` and `inputs` fields or the lines changed are necessary.
Removed the last 2 lines of `AppBase.__init__` which set `AppBase.inputs` and `AppBase.outputs` to default values if they exist.

Remove unused inputs and outputs fields for AppBase

---

parsl/providers/kubernetes/kube.py

The launch command is formatted with a newline at the end so when the trailing semicolon is added here, it causes the semicolon to be run as a separate bash command by the worker. A single semicolon is a syntax error in bash and produces an error in container logs when the container tries to run it. Removing it is safe since it's at the end of the command and nothing is concatenated after it.
Remove an error in the Kubernetes worker container logs.
Fixes # n/a - minor issue
- Bug fix

Fixed Kubernetes worker container launch command to remove trailing semicolon.

---

parsl/providers/kubernetes/kube.py

Switch the Kubernetes client call to read_namespaced_pod_status() to read_namespaced_pod(), which is functionally the same but requires fewer permissions
This change is based on the comment from https://github.com/kubernetes-client/python/issues/993#issuecomment-547566592 . Similar to the user in the reporter of that issue, I was seeing forbidden permission when making the read_namespaced_pod_status() call, and according to the discussion there, this can be fixed by using read_namespaced_pod() instead which is almost exactly the same request/response (except the metadata.selfLink field, which is not used by the parsl code). It seems that the read_namespaced_pod_status() call requires an additional permission on "pods/status", while read_namespaced_pod() does not (I didn't check but I can …

Switch Kubernetes client to read_namespaced_pod() which requires fewer permissions

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/tests/test_htex/test_htex.py
parsl/tests/test_htex/test_zmq_binding.py
setup.py

This PR removes a use of multiprocessing fork-without-exec.
At heart, this is how the interchange has wanted to be launched for some time (because of earlier remote interchange work).
Launching multiprocessing fork caused a bunch of problems related to inheriteing state from from the parent submitting process that go away with this (jumbled logging topics, race conditions around at least logging-while-forking, inherited signal handlers).
The configuration dictionary, previously passed in memory over a fork, is now sent in pickled form over `stdin`. Using pickle here rather than (eg.) JSON keeps the path open for sending richer configuration objects, beyond what can be encoded in JSON. This isn't something needed right now, but at least configurable monitoring radios (the immediate driving …

Launch interchange as a fresh process

---

parsl/channels/local/local.py

This is driven by a case where it is unclear when the Parsl scaling code is launching processes to monitor batch queue status.
This will add 4 debug lines per block started, block cancelled, and per poll (limited by provider.status_polling_interval() and config.strategy_period)
- New feature

Add debug logging around local channel process launch

---

parsl/app/bash.py

tl;dr bash_app unexpectedly mutates the global remote_side_bash_executor function, which is bad. This PR makes it not do that.
This addresses behaviour subtle enough we've gone years without noticing but is now causing problems for a test introduced in apparently-unrelated PR #3489.
What was happening before this PR, in the removed line is that update_wrapper is being used in two ways:
i) Deliberately, a functional style: return a remote_side_bash_executor
that looks like self.func
and
ii) Accidentally, modify the global remote_side_bash_executor to look
like self.func
That second step is problematic: it modifies a global object (the remote_side_bash_executor callable object) on every bash_app decoration, and so leaves it finally looking like the most recent bash_app decoration.
For …

Remove incorrectly-global-mutating update_wrapper in bash_app

---

parsl/configs/ASPIRE1.py
parsl/configs/Azure.py
parsl/configs/ad_hoc.py
parsl/configs/bridges.py
parsl/configs/cc_in2p3.py
parsl/configs/ec2.py
parsl/configs/expanse.py
parsl/configs/frontera.py
parsl/configs/htex_local.py
parsl/configs/illinoiscluster.py
parsl/configs/kubernetes.py
parsl/configs/local_threads.py
parsl/configs/midway.py
parsl/configs/osg.py
parsl/configs/polaris.py
parsl/configs/stampede2.py
parsl/configs/summit.py
parsl/configs/toss3_llnl.py
parsl/configs/vineex_local.py
parsl/configs/wqex_local.py

Enable usage tracking with level 1 in the configs
Example configs will have `usage_tracking` set to the lowest level and share the following user data: `python-version`, `parsl-version` and `platform`
- New feature

enable usage tracking in example configs

---

parsl/tests/test_bash_apps/test_memoize_ignore_args.py
parsl/tests/test_bash_apps/test_memoize_ignore_args_regr.py
parsl/tests/test_error_handling/test_retries.py
parsl/tests/test_staging/test_file.py

Remove some local-dev test detritus

---

parsl/executors/high_throughput/errors.py
parsl/executors/high_throughput/interchange.py
parsl/tests/test_serialization/test_3495_deserialize_managerlost.py

Per the analysis in #3495, defining the `ManagerLost` and `VersionMismatch` errors in the `interchange.py` became a problem in #3463, where the interchange now runs as `__main__`.  This makes it difficult for Dill to get the serde correct.
The organizational fix is simply to move these classes to an importable location, which follows the expectation that classes are available in both local and remote locations, which defining in `__main__` can't easily guarantee.
Fixes: #3495
- Bug fix

Move ManagerLost and VersionMismatch to errors.py

---

docs/index.rst

I'm trying to get my head around Parsl, but the first example in the documentation already lost me.  I believe the example was broken by #3428.  CC: @WardLT
`g` was defined as a single-argument function, but called with two.
First example in the documentation now actually works.  With this change, the example is now consistent with the README (also changed in #3428): https://github.com/Parsl/parsl/blob/2fc20d8da76198db13145bd4341d8ad9db1c6a37/README.rst#L24-L26
N/A

Fix definition of `g` in very first example in docs

---

parsl/executors/high_throughput/executor.py

This was introduced in PR #3463 and at the time I incorrectly assumed that interchange exit would close both ends of the pipe. That is untrue.
For example: pytest parsl/tests/test_htex/ --config local ends with 341 fds open before this PR,
and 327 file descriptors open after this PR.
nothing should be user visible, but less file descriptor usage
- Bug fix

Close stdin used to send config to Interchange

---

parsl/providers/kubernetes/kube.py

Fix spacing in KubernetesProvider debug log and use deferred formatting

---

parsl/providers/kubernetes/kube.py

Correct KubernetesProvider.submit docstring, to not return None

---

parsl/providers/kubernetes/kube.py

The job_name is uniquified with a timestamp inside the submit method, and the default job_name is "parsl", which is not unique wrt other invocations using the default.

Remove documentation that KubernetesProvider job_name must be unique

---

parsl/tests/test_providers/test_local_provider.py

This stops that thread being left still running over the end of the test - which is needed in work in PR #3397 to ensure that no threads are left running at the end of a test.
If that shutdown hangs, this test will now hang rather than leave the thread behind.
Along with PR #3504, this eliminates any threads left behind after parsl/tests/test_providers/test_local_provider.py

Join on stopped thread at end of LocalProvider+ssh test

---

parsl/channels/ssh/ssh.py
parsl/tests/test_providers/test_local_provider.py

This is paired with DFK behaviour introduced in PR #3503 which closes channels in the DFK.
This PR makes SSHChannel.close (soft) wait until its worker thread is shut down. This is initially driven by the desire for threads to be shut down before test cases end, but more generally is part of a goal of shutting everything down *before* the relevant close/cleanup operation completes.
"soft" in this sense means that after 30 seconds, a warning will be emitted, rather than hanging longer than that.
This PR modifies a test which does not use the DFK to also perform that shutdown - with parsl/tests/test_providers/test_local_provider.py, this reduces the number of threads remaining at the end of execution from 3 to 2.

Better closing of SSH channel

---

parsl/executors/flux/flux_instance_manager.py

Problem: flux_instance_manager.py runs as a script and creates a ZMQ context and socket but never cleans them up.
None, it's just cleanup.
N/A, but tag-on to #3517 and #3484 .

flux: cleanup zmq context and socket

---

parsl/executors/high_throughput/executor.py

This worker manages a queue of *results*, not of other things that might be queued.
none

Rename htex queue management worker to reflect purpose

---

parsl/executors/high_throughput/executor.py

This reduces the number of file descriptors left open at the end of pytest parsl/tests/test_htex --config local from 372 fds to 131 fds.
This PR does not close the incoming_q ZMQ pipe. A companion PR will close that pipe as part of bigger work to shut down the result management thread, which otherwise continues to use the incoming_q pipe even after shutdown.
this peturbs what happens at shutdown - I think always for the better

Close two of the zmq pipes at HighThroughputExecutor shutdown

---

parsl/executors/status_handling.py

See PEP-8 https://peps.python.org/pep-0008/#descriptive-naming-styles
This should not change any behaviour.

Mark scale_out method as internal to BlockProviderExecutor

---

parsl/executors/flux/executor.py

Prior to this PR, there were frequent hangs in CI at cleanup of the ZMQ objects used by the FluxExecutor. See issue #3484 for some more information.
This PR attempts to remove some dangerous behaviour there:
i) creation of ZMQ context and socket is moved into the thread which makes use of them - before this PR, the socket was created on the main thread and passed into the submission thread which uses it. This removes some thread safety issues where a socket cannot be safely moved between threads.
ii) ZMQ context and socket are more explicitly closed (using with-blocks) rather than leaving that to the garbage collector. In the hung tests, the ZMQ context was being garbage collected in the main thread, which is documented as being unsafe when sockets are open belonging to another thread …

Move FluxExecutor ZMQ into thread and explicitly clean it up

---

parsl/dataflow/dflow.py

This attribute is initialised sometimes, but not always, and is never read from. There's a similarly named attribute in Memoizer, so I think this was mistakenly introduced in commit
307b419dbcc847aeaf021f04c45b5149aa81d190.
none

Remove unused dfk.memo_lookup_table attribute

---

parsl/executors/high_throughput/executor.py

This code path looks like it was originally intended to cause the thread to exit, but is never used - this PR removes the entire if statement and re-indents so that the else case is the only code path that happens now.

Remove unused None message codepath from htex result queue thread

---

parsl/executors/base.py
parsl/monitoring/monitoring.py
parsl/monitoring/radios.py
parsl/monitoring/remote.py

Ongoing monitoring radio work (see PR #3315) introduces per-radio configuration classes using *Radio names.
This PR frees up the *Radio namespace for that use, by renaming non-user-exposed internal classes out of the way.
none
- New feature

Free up the *Radio namespace for future config structures

---

parsl/executors/status_handling.py

* This monitoring message is not coming from the job status poller - this moved in PR #3349.
* This monitoring message is not being sent to the hub, but rather to the monitoring router on the far end of the monitoring radio.
* Debug messages should be formatted with deferred logger formatting.

Update block monitoring log message

---

docs/userguide/mpi_apps.rst

Parsl providers assume a pilot job model, where a single manager runs per node. This model conflicts with the model that `MPIExecutor` uses where the scheduler starts a single manager on the entire job which then launches MPI apps. This PR adds a warning to documentation cautioning use of `cores_per_node` in the SlurmProvider and similar options.  
This PR comes Christopher Harrop from NOAA reported on the help channel. 

Adding warning about provider options in MPI context

---

parsl/executors/status_handling.py
parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

The intended behaviour of this scale in code, which is only for scaling in all blocks (for example at the end of a workflow) makes sense as a default for all BlockProviderExecutors. This PR makes that refactor.
This code is buggy (before and after) - see issue #3471. This PR does not attempt to fix that, but moves code into a better place for bugfixing, and a subsequent PR will fix it.
This PR should not change any behaviour for any of the executors in the Parsl source tree. It might change behaviour for any out-of-tree executors.
- New feature

Refactor naive scale in behaviour for Work Queue and Task Vine

---

docs/userguide/checkpoints.rst

Fix broken markup for hyperlink

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py
parsl/tests/test_monitoring/test_fuzz_zmq.py

Prior to this PR, monitoring hub address and ZMQ port were stored as attributes of the DFK. The address also existed as an attribute on dfk.monitoring, and the ZMQ port was returned by dfk.monitoring.start
Afte this PR, those values are not added to the DFK, but instead are accessed via dfk.monitoring.
These two attributes are now only set on a new executor when monitoring is enabled, rather than always being intialised by the DFK. Default values now come from the executor __init__ method, which is a more usual style in Python for providing default values. See PR #3361
This is part of ongoing work to introduce more pluggable monitoring network connectivity - see PR #3315
none

Don't copy monitoring address/port parameters into the DFK.

---

README.rst

If one tries to follow step 3 after step 2, which I think is something somewhat reasonable to expect, they end up inside directory `parsl/parsl`, where there's no `setup.py` script.  Instead, the script is in the top-level directory, so if you already entered `parsl`, you don't need to go into `parsl/parsl`.  This adds a comment to clarify this possible point of confusion.
Make following installation instructions for developers less confusing.
N/A

Clarify dev instructions in README.rst

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/manager_record.py
parsl/executors/high_throughput/process_worker_pool.py

Managers now record their start time and forward this information to the interchange during registration. The ManagerRecord was updated to support this functionality. Adding this will allow for better manager selection by the interchange in the future.
No changes
Part of project outlined by [issue 3323](https://github.com/Parsl/parsl/issues/3323)
- New feature

Add Start Time Tracking for Managers and Update ManagerRecord on Registration

---

parsl/executors/status_handling.py

See PR #3530 which does this for status()
This is a buildup to some simplification and eventual merge of scale_out and scale_out_facade in upcoming PRs.
This PR should not change any behaviour

Move scale_out_facade next to scale_out

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_htex/test_htex.py

We now accept a string or a list of strings for `interchange_launch_cmd` to support multi-token commands.
We also no longer encode the interchange launch command before passing it to `subprocess.Popen()` because strings are sufficient.
- Bug fix

Accept multi-token interchange launch commands 

---

parsl/executors/status_handling.py

block_ids is populatd by _scale_out which always returns a list, according to its type signature. So the `None` codepath should not ever be reached.
mypy agrees: after adding an else clause (to act on the `None` case), mypy then marks the added clause as unreachable.

Remove unused codepath from executor scale-out

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/manager_selector.py
parsl/tests/test_htex/test_zmq_binding.py
parsl/tests/test_mpi_apps/test_mpiex.py

Added a Manager Selector interface which allows users to choose an algorithm to sort the interesting managers. This will allow for flexible testing and implementation of manager selection strategies to optimize efficiency of the interchange. 
When using defining a config for the HTEX, users can now optionally specify a ManagerSelector to change the strategy. Default algorithm is the original random shuffle.
Further development of project outlined by [issue 3323](https://github.com/Parsl/parsl/issues/3323)
- New feature

Add Modular Manager Selector Interface

---

parsl/executors/status_handling.py

Especially this log message is intended to help user understanding when Parsl is not scaling in as they expected - before this PR, any blocks marked as not-scaled-in were not reported to the user (perhaps on the assumption that it might work next time round?)
Slightly more logging in the case of providers not killing blocks.

Add type annotation and error log to _filter_scale_in_ids

---

parsl/tests/test_htex/test_htex.py

This replaces mock-captured call sequences which are over-testing the exact position of tested log calls in relation to any other log calls, which makes this test fragile when working on logs in the affected area of the code.
This is consistent with other parts of the test suite which test log messages using caplog.

Use caplog fixure rather than mock logging when testing HTEX shutdown

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/status_handling.py

A Parsl executor is configured with a submit-side monitoring radio sender, which is used by the BlockProviderExecutor to send block status messages to the monitoring subsystem.
Parsl executors also have a notion of a remote monitoring radio, used by remote workers to sending monitoring messages.
This can be confusing when both of these radio senders are referred to in the same piece of code, as happened in ongoing monitoring plugin development in draft PR #3315.
This PR is intended to make this sitution much less ambiguous by avoiding the mention of a monitoring radio in executor code without qualifying whether it is a submit-side or remote-worker-side radio definition. A future PR from the #3315 stack will introduce other monitoring radio references with the remote prefix, replacing the …

Rename submit-side monitoring radio for clarification

---

parsl/tests/test_monitoring/test_basic.py

Before this PR, this radio was omitted because all of executors in the basic monitoring test had over time been switched to different defaults.

Test UDP monitoring radio

---

parsl/executors/status_handling.py

This brings two related pieces of code together into a single method, removing the possibility of the _scale_out code being called in any other way than via scale_out_facade.
Future PRs will rearrange the now unified code and make a bugfix that will be more easily fixable now.
This PR should not change behaviour as it is only a code movement.

Inline _scale_out in BlockProviderExecutor

---

parsl/executors/status_handling.py

There are multiple structures that contain information about blocks and the status of those blocks. This PR is part of ongoing work to make the information contained in those blocks more consistent.
This PR brings updates to executor._status (before PR #3352, living in parsl.jobs.job_status_poller) together with updates to the block/job id mapping structures (which has existed in the executor layer under different names since commit
a1963bf36fa6bac5bb5b28757a2c5d4a1fbe0462 introduced self.engines in 2018).
This PR should not change behaviour: it moves code around in a way that should not affect how the various structures are left populated at the end of the method.
This PR makes the cause of issue #3235 clearer, without attempting to fix it: in the successful code path touched by this PR, …

Bring block table updates together in scale out

---

parsl/executors/status_handling.py
parsl/tests/test_htex/test_disconnected_blocks_failing_provider.py

_status stores the status of blocks. This structure is periodically updated by executor.status(), but any changes to block status that happen before such an update happens need to be done explicitly, to make them appear in _status immediately.
Before this PR, this was done for launched blocks, 6 lines before this change, but not for failed blocks. This is the cause of issue #3235 - scaling code does not become aware of failed blocks until executor.status() updates _status on a slow poll.
This PR makes _status be updated with that failed block information immediately (in addition to the existing code which places it in _simulated_status for when executor.status() rebuilds the entire _status structure).
This PR has a test case which fails before this PR's change to status_handling.py but …

Update _status cache on failed blocks

---

parsl/monitoring/errors.py
parsl/monitoring/monitoring.py

This is in line with the principle that Parsl exceptions should all be subclasses of ParslError.
Anyone catching this exception will have to catch it differently

Make monitoring hub start into its own Exception

---

parsl/executors/high_throughput/interchange.py
parsl/monitoring/radios.py

From an interchange perspective: this is a refactoring intended to clarify that the interchange isn't doing anything special wrt. monitoring messages and that it can send monitoring messages in the same way that remote workers can.
From a monitoring perspective: this pulls ZMQ sender code out of the interchange and puts it in a place that is more natural for ongoing development. For example, a potential future use with Work Queue and Task Vine is that workers would also benefit from using ZMQ to send monitoring messages.
In some potential use cases, it might be desirable to configure the radio used by the interchange instead of the hard-coded ZMQRadio. On-going work in draft PR #3315 addresses configuration of different types of radio and that work should be relevant here too.
This should …

Factor interchange monitoring code into a ZMQRadioSender

---

parsl/tests/test_htex/test_htex.py

Prior to this PR, this usage of caplog is dependent on the level of the root logger, which is not set by this test and so ends up being dependent on which tests have run before: sometimes the INFO logs output by htex.shutdown are not captured by caplog.
This PR explicitly tells caplog to get at least INFO level logs, to capture the expected messages.
eliminates a bug in test code
- Bug fix

Fix pytest caplog heisenbug introduced in PR #3559

---

parsl/monitoring/router.py

This is part of two ongoing strands of development:
* Preparation for arbitrary monitoring radio receivers, where UDP is not special compared to other methods. This code separates out the UDP specific code making it easier to move around later (see development in PR #3315)
* Avoiding poll-one-thing, poll-another-thing tight polling loops in favour of multiple blocking loops. The two router receiver sections used to run in a single tight non-blocking loop, each component waiting loop_freq (= 10 ms) for something to happen. After this PR, the separated loops are more amenable to longer blocking times - they only need to discover when exit event is set which probably can be more on the order of 1 second.
no functional changes - time of delivery of monitoring messages will be very slightly …

Split monitoring router into two radio-specific receiver threads

---

parsl/dataflow/dflow.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/monitoring/monitoring.py
parsl/monitoring/router.py
parsl/tests/test_htex/test_zmq_binding.py

Prior to this PR, the monitoring router would add a run_id field to every NODE_INFO message that it received. These are messages from the interchange describing worker pools.
The monitoring router does not modify any other messages.
This PR sets the run_id at the point of message origination inside the interchange (in _send_monitoring_info), and makes the router leave NODE_INFO messages unmodified (like the other message types).
This is part of work to make the router less aware of message types by removing a bunch of message-type specific handling.
This PR brings in a bunch of rewiring to get the run id into the interchange rather than into the monitoring router.
This should not change any worker-user-facing behaviour.
Globus Compute (or anyone else building a fake Parsl environment) …

Remove monitoring router modification of node message

---

parsl/executors/high_throughput/executor.py

Even if the subsequent SIGKILL works, this is an exceptional circumstance that should be logged.
more logging

Promote unable to terminate warning to logger.WARNING

---

docs/userguide/configuring.rst

Our current documentation on `available_accelerators` does not explain some of the nuances around specifying accelerators via a list of strings. This PR adds some additional information on the following:
* Notes on how to specify list of strings to available_accelerators
* Clarify how to bind multiple GPUs to workers
Based on questions from @msakarvadia. 
Only documentation changes.

Adding notes on `available_accelerators`

---

parsl/monitoring/db_manager.py
parsl/monitoring/remote.py

This is in preparation for future type work in the monitoring codebase (for example, see PR #3572).
This PR does not claim that the types it is moving around are correct (and PR #3572 contains some instances where the types are incorrect). It is a purely syntactic PR.
After this PR, $ git grep '# type:' parsl/monitoring/ returns two remaining comment style annotations, which are 'type: ignore' exclusions not specific types.
should be no changed behaviour

Convert monitoring type annotations to PEP-526 from comments

---

parsl/monitoring/db_manager.py
parsl/monitoring/router.py

Prior to this PR, the startup code for the monitoring router and database processes had type annotations on queues; but these types were not checked, and were incorrect - they were labelled process-local `Queue` instead of multiprocessing queues. This did not cause much trouble execution- and mypy-wise, as the interfaces of those two classes are similar enough, but it is confusing to read in a part of the codebase that is already confusing (that confusion is probably what lead to the incorrect annotations in the first place...)
They were not checked because the informal policy of "internal stuff is checked with mypy, external interfaces are checked with typeguard" works badly here:
The startup methods are launched using multiprocessing.Process, and function invocations are not …

Correct and check types on monitoring router and database processes

---

parsl/channels/oauth_ssh/oauth_ssh.py
parsl/channels/ssh/ssh.py
parsl/channels/ssh_il/ssh_il.py
requirements.txt
setup.py
test-requirements.txt

Removed paramiko from requirements.txt and added it as an optional module in setup.py. Added OptionalModuleMissing errors for the ssh channel files for when usage is attempted without the required paramiko module being installed.
If users have code that depends on the ssh channels, they may need to opt in to that module.
Prepares for #3515 

Made paramiko an optional dependency in preparation for #3515

---

parsl/monitoring/monitoring.py
parsl/monitoring/router.py

See PR #2973 for justification of mandatory keyword args.
none for users

Make router_starter parameters mandatory kwargs

---

parsl/monitoring/db_manager.py

The main goals of this PR is to make _migrate_logs_to_internal much more clearly a message forwarder, rather than a message interpreter.
This follows on from PR #2168 which introduces _dispatch_to_internal to dispatches messages based on their tag rather than on the queue the message was received on, and is part of an ongoing series to simplify the queue and routing structure inside the monitoring router and database code.
Further PRs in preparation (in draft PR #3315) contain further simplifications building on this PR.
After this PR:
* the database manager will respond to a STOP message on any incoming queue, vs previously only on the priority queue. This is a consequence of treating the queues all the same now.
* the database manager will not perform such strong validation of message …

Remove monitoring queue tag switch monitoring db pre-router

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/monitoring/router.py

Prior to this PR, there are four multiprocessing queues from the monitoring router process to the database manager process. (also used by the submit process via MultiprocessingQueueRadioSender but that is not so relevant for this PR)
Each message arriving at the router goes into `MonitoringRouter.start_zmq_listener` where it is dispatched based on tag type into one of these four queues towards the monitoring database. In the monitoring database code, no matter which queue the messages arrive on, they are all passed into `DatabaseManager._dispatch_to_internal`.
The four queues then don't provide much functionality - their effect is maybe some non-deterministic message order shuffling.
This PR collapses those four queues into a single queue.
Messages will arrive at the database manager in …

Collapse 4 monitoring router to db queues into 1 queue

---

parsl/executors/high_throughput/interchange.py

Mostly an exercise in calming my IDE and "while here" massaging a couple of `log.debug` calls to use printf-style arguments.
No changed behavior.

Non-functional change: minor log call-site updates

---

parsl/executors/high_throughput/executor.py
parsl/executors/status_handling.py
parsl/jobs/states.py
parsl/tests/test_htex/test_multiple_disconnected_blocks.py
parsl/tests/test_monitoring/test_htex_init_blocks_vs_monitoring.py
parsl/tests/test_scaling/test_regression_3568_scaledown_vs_MISSING.py

This PR adds a new terminal job state, SCALED_IN. None of the existing providers will return it, but the scaling layer will use it to mark a job as deliberately scaled in, so that error handling code will not regard it as failed.
Fixes #3568

Make deliberately scaled-in unstarted blocks not be failures

---

docs/userguide/configuring.rst

Both Polaris and Perlmutter have configuration documentation hosted by their respective facilities. This is great, but it makes it harder for users trying to match an undocumented machine to existing configs. This PR adds some hints to both Polaris and Perlmutter listing the provider and launcher combo used in the hopes that it might lead the user to configs from those machines.

Add breadcrumbs for users trying to match configs to their machines

---

docs/reference.rst
docs/userguide/configuring.rst
parsl/configs/improv.py

This PR adds a configuration example for Improv at Argonne's LCRC.

Adding configuration example for Improv@LCRC

---

parsl/executors/high_throughput/executor.py
parsl/tests/site_tests/README.rst
parsl/tests/test_htex/test_htex.py
parsl/tests/test_mpi_apps/test_mpiex.py
parsl/tests/test_scaling/test_scale_down_htex_auto_scale.py
parsl/tests/test_scaling/test_scale_down_htex_unregistered.py

Remove the deprecated `max_worker` argument to `HighThroughputExecutor`.
Any workflows that still use `max_worker` will no longer simply get a warning message but still work.  Users will need to change any scripts to use `max_workers_per_node`.  (But they've had six months of ~warnings~ education to do the deed!)

Remove deprecated max_worker

---

parsl/executors/taskvine/executor.py

This moves the working directory for TaskVine executor function data to a directory in /tmp
These files were previously written adjacent to the logging in the working directory. They may be written in excess when running a large number of tasks.
- New feature

TaskVineExecutor: write function data to temp directory

---

parsl/launchers/launchers.py

In current version, Some of the launchers have parameter called 'task_block' mentioned in the docstring of the `__call__` method but it is redundant and have no reflection on the code. This fix removes the mentioned parameter from the docstrings.
This doesnt change any behaviour and everything is expected to behave the same
Fixes #3612 

Removal of 'task_block' parameter from serveral launcher's docstring

---

README.rst

Currently Parsl has a status badge showing the status of the recent workflow runs. As Parsl has a strict PR check run before merging, if an arbritrary PR fails , the badge ends up with Parsl "failing" which is not true. As of now, there are no events that can target the status of PRs raised against master branch. This PR removes the status badge from the `README.rst`.
This change doesnt reflect on the functional behaviour of parsl and all programs are expected to work the same.
Fixes #3610 
- Bug fix

Remove Status Badge from README

---

parsl/config.py
parsl/tests/unit/test_usage_tracking.py
parsl/usage_tracking/usage.py

Add option to deanonymize usage tracking data by tagging it with a name using `parsl.Config.project_name`.
Usage Tracking messages will include `project_name` if set. 
Ex: 
```json
{
"correlator":"e578ad3e-dddb-465e-93df-2db42a097883",
"end":1727729064,
"execution_time":3,
"components":[
{
"c":"parsl.dataflow.dflow.DataFlowKernel",
"app_count":3,
"app_fails":0
},
{
"c":"parsl.config.Config",
"executors_len":1,
"dependency_resolver":false
},
"parsl.executors.threads.ThreadPoolExecutor"
],
"project_name":"my-test-project"
}
```
- New feature

Usage tracking project name

---

parsl/tests/configs/htex_local_alternate.py

This uses the project name feature introduced in PR #3624 in one of the standard Parsl tests that already had usage turned on.
More usage tracking on `pytest parsl/tests/ --config parsl/tests/configs/htex_local_alternate.py` which runs in CI and often on my laptop.
- New feature

Add more usage tracking to htex_local_alternate test

---

docs/quickstart.rst

Remove claim that Parsl is tested on macOS

---

.github/workflows/ci.yaml
.gitignore
parsl/tests/conftest.py

Prior to this PR, output from pytest was generally hidden by placing it in the .pytest directory.
After this PR, that .pytest directory is now pytest-parsl.
Most immediately, a breaking change in the GitHub actions artifact upload has started respecting that dotfile hiddenness, and so with that version of the artifact uploader, test runs prior to this PR are missing a bunch of output. https://github.com/actions/upload-artifact/issues/602
The uploader now has an option to enable hidden files...
but ...
.. before this most immediate motivation, I've run into a couple of developer experience cases that look like:
Q: I cannot find the output of pytest
A: We have deliberately made it hard for you to find
which is enough to make me rename the directory rather than turn on the artifact uploader …

Unhide pytest output by removing dotfile directory

---

parsl/executors/errors.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/mpi_prefix_composer.py
parsl/executors/threads.py
parsl/executors/workqueue/executor.py
parsl/tests/test_error_handling/test_resource_spec.py
parsl/tests/test_htex/test_resource_spec_validation.py
parsl/tests/test_mpi_apps/test_mpi_mode_enabled.py
parsl/tests/test_mpi_apps/test_resource_spec.py

There are three places where the executors raise the errors regarding resource specification.
1.  when passing the resource_specification parameter to the htex, it raises the mpi_prefix_composer InvalidResourceSpecification from validate_resource_spec method. https://github.com/Parsl/parsl/blob/master/parsl/executors/high_throughput/executor.py#L342
2.  ThreadPoolExecutor also raises the UnsupportedFeatureError when passing resource specification to it, https://github.com/Parsl/parsl/blob/master/parsl/executors/threads.py#L54
3.  WorkQueueExecutor raises two errors similar to this but as a Base ExecutorError, one when there is invalid resource_specification ; https://github.com/Parsl/parsl/blob/master/parsl/executors/workqueue/executor.py#L418 and another one when the autolabel is false …

Use a single exception class for all resource specification errors

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py

The count of outstanding tasks may now be higher:
A task will be counted when it enters the task submission ZMQ channel to the interchange, rather than when it reaches the end of the ZMQ channel (which could be a queue under load), and a task will be counted as complete when it arrives back on the submit side, rather than when the interchange places it into the results channel.
It's probably more desirable to count the tasks earlier like this and less desirable to count the results later like this, for scaling purposes - scaling load will be observed before it reaches the interchange, but reduction in load due to completion won't be observed until the result has got all the way through the result queue. I don't think this will affect users in real life - but I don't have any numbers for …

Count outstanding tasks on submit side rather than in interchange

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py

Prior to this PR, heartbeats sent from worker pools to the interchange on the results channel would be forwarded on to the submit side along the interchange to submit side results channel.
These heartbeat messages would then be discarded on the submit side.
I think these forwarded messages don't do anything, so this PR removes the forwarding.
The network path between interchange and submit side is on localhost and unlikely to need any TCP level keepalives. There is no handling for missing heartbeats, and indeed no expectation of heartbeats arriving: an interchange might exist for many hours with no connected workers, and so no forwarded heartbeats.
This PR should reduce message load on the submit side results channel by one message per work pool per heartbeat period.
See issue #3464 for …

Don't forward worker heartbeats to the submit side

---

parsl/executors/high_throughput/executor.py

Correct whitespace in InvalidResourceSpecification message

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_htex/test_resource_spec_validation.py

Adds the parameter  'priority' as a valid entry in the resource spec dict. Necessary for changing the pending_task_queue to a different structure than queue.Queue. Also passes resource spec to the interchange.
Users can now specify values for 'priority' within the resource spec of parsl apps. Currently doesn't do anything with that information. 
N/a
- New feature

Add resource specification fields to HTEX

---

parsl/tests/test_htex/test_drain.py

This PR reduces the load places on the interchange and on the whole test environment caused by repeatedly querying the interchange for connected managers. It does this by increasing the period between such requests, from the default, every 20ms, to every 100ms.
In the last few days, test_drain.py began failing often. I have seen it occasionally fail before. This was initially a problem in PR #3639 which is unrelated, but I recreated the problem in CI against master as of #3627.
I investigated and found this behaviour causing the failure:
* test_drain configures the drain period to be 1 second
* startup of a worker pool was taking more than 1 second
* the worker pool enters drain state, drains and terminates immediately on being fully started up.
* test_py fails its assumption that there …

Reduce load on drain integration test to reduce race-condition failures

---

Makefile
parsl/providers/kubernetes/kube.py
parsl/tests/test_providers/test_kubernetes_provider.py
parsl/tests/test_utils/test_sanitize_dns.py
parsl/utils.py

- Modified Kubernetes pod names and labels to conform to RFC 1123 for DNS subdomain names and labels, ensuring compliance with Kubernetes naming conventions.
- Modified `KubernetesProvider.submit()` to return an eight-character hex value as the job ID instead of the pod name.
- Replaced the trailing timestamp in the pod name with the job ID to improve collision avoidance.
- Replaced `app` pod label with `parsl-job-id`.
- Updated container name to use job ID.
- Bug fix
- New feature

Ensure k8s pod names/labels are RFC 1123 compliant

---

parsl/tests/test_serialization/test_3495_deserialize_managerlost.py

The threshold was the same as the heartbeat period, leading to races in CI where the manager would be expired before the heartbeat was received.
- Bug fix

Fix too-low heartbeat threshold in test

---

parsl/channels/base.py
parsl/channels/local/local.py
parsl/channels/ssh/ssh.py

Part of #3515 
none - this abstraction was never used

Remove Channels.abspath that is unused

---

docs/reference.rst
parsl/channels/errors.py
parsl/channels/ssh/ssh.py

This is part of staged removal of channels - see issue #3515 and PR #3650.
none

Remove FileExists channel exception that is unused

---

.github/workflows/ci.yaml

This won't directly make anything run more often, but is needed for experimenting with GitHub merge queues, where a new type of commit is automatically made that also needs to pass testing.
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
enables CI testing of merge queue candidate commits if Github merge queues are turned on (which they are not as of this PR)
- New feature

Enable main Github Actions test for merge queues

---

parsl/channels/local/local.py

walltime is used in LocalProvider
This is part of tidyups during implemention of #3515

Remove docstring saying used "walltime" parameter is unused

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/monitoring/radios.py
parsl/monitoring/router.py
parsl/monitoring/types.py

This was an extra protocol complication, the source address was never used beyond immediate logging, and the source address sometimes didn't exist with a few different filler values used instead.

Remove unused source address on some monitoring messages

---

parsl/monitoring/radios.py

PR #2439 split out radios from monitoring.py, but miscopied these lines from there. They also exist in real form in monitoring.py

Remove bad cut/paste from PR #2439

---

parsl/tests/conftest.py
parsl/tests/test_bash_apps/test_basic.py
parsl/tests/test_bash_apps/test_error_codes.py
parsl/tests/test_bash_apps/test_kwarg_storage.py
parsl/tests/test_bash_apps/test_memoize.py
parsl/tests/test_bash_apps/test_memoize_ignore_args.py
parsl/tests/test_bash_apps/test_memoize_ignore_args_regr.py
parsl/tests/test_bash_apps/test_multiline.py
parsl/tests/test_bash_apps/test_stdout.py
parsl/tests/test_docs/test_from_slides.py
parsl/tests/test_docs/test_kwargs.py
parsl/tests/test_docs/test_workflow1.py
parsl/tests/test_python_apps/test_outputs.py
parsl/tests/test_regression/test_226.py
parsl/tests/test_staging/test_docs_1.py
parsl/tests/test_staging/test_output_chain_filenames.py
parsl/tests/test_staging/test_staging_ftp.py
parsl/tests/test_staging/test_staging_https.py
parsl/tests/test_staging/test_staging_stdout.py

This PR adds a new `staging_required` marker and a marker to several tests that assume a shared filesystem to work. Similarly, a few tests that use staging are now marked with the `staging_required` marker.
This PR splits out changes from #3607.
These markers should not affect any test-behavior since none of the test entries in the Makefile make use of this.
These change will kick-in once they are used by `GlobusComputeExecutor` and potentially `KubernetesProvider`
for tests.
- New feature

Add `shared_fs` and `staging_required` test markers

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py

This is an API tidyup that works towards all monitoring message sends taking a TaggedMonitoringMessage: callers of send are responsible for forming a tagged tuple.

Make monitoring radio send() signature consistent with radio.send

---

parsl/monitoring/monitoring.py

The is based on a review comment from @khk-globus on PR #3672
logging formatting *should* come out the same but maybe not

Move all monitoring.py logging to lazy format style

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios.py

UDP and HTEX radios both use pickle, not parsl.serialize, and there is no reason for this inconsistency.

Make FilesystemRadio serialize monitoring messages the same as UDP and HTEX radios

---

parsl/channels/local/local.py

This is part of staged dissolution of LocalChannel as part of #3515 channel removal.
Removed (but I think generally unused) functionality and configuration option
- New feature

Remove LocalChannel userhome attribute

---

parsl/monitoring/monitoring.py

Prior to this PR, on Linux, this is already a fork process because of defaults.
But this process *must* be a fork process, for the same reason that other explicit ForkProcesses in Parsl must be fork processes: we cannot re-import the the unknown user workflow script again.
This PR makes that explicit and consistent with other forked processes.
Longer term, multiprocessing-forked processes need to go away throughout Parsl - see issue #2343, but this PR is not for that.
This should not change behaviour on Linux. On platforms that are not Linux, nothing is supported and is probably already broken here.

Be explicit about filesystem monitoring radio being ForkProcess

---

parsl/channels/base.py
parsl/channels/local/local.py
parsl/tests/test_channels/test_local_channel.py

Prior to this PR, Channel.execute_wait took a parameter to modify the unix environment of the newly executed process. This is unused in current Parsl. As part of the implementation of that, LocalChannel cached the unix environment at object initialization, and used that as the base to override with any supplied execute_wait environment parameter.
Post this PR:
The `env` parameter of execute_wait is removed.
LocalChannel does not cache the environment any more. The executed process will inherit the parent process environment as of the point of execution not object initialization.
This is a behaviour change: if the workflow process changes its unix environment after creating the configuration objects, then prior to this PR, executed processes would not observe that change. Post this PR, …

Remove Channel.execute_wait environment wait handling, part of #3515

---

docs/userguide/plugins.rst

Move Channel plugin documentation to a removed section

---

parsl/channels/local/local.py
parsl/tests/test_providers/test_pbspro_template.py
parsl/tests/test_providers/test_slurm_template.py

Prior to this PR, if the argument defaulted to None, then the DFK would set a script dir based on the workflow rundir.
Post this PR, this default behaviour is the only behaviour and the user cannot specify an overriding value.
Future PRs will remove channel level script directories entirely. This is part of issues #3515 removing channels,
This PR removes a little-used user configuration option.

Remove the opportunity to configure script_dir for LocalChannel

---

parsl/channels/base.py
parsl/channels/local/local.py

This is part of implementing #3515 channel removal code. These methods became unused in PR #3688.

Remove unused channel directory handling code

---

parsl/monitoring/monitoring.py

Prior to this PR, filesystem_receiver was annotated as taking queue.Queue. This was incorrect (but not detected or enforced by any tooling - because type annotations are not carried across the invoking Process constructor)
The receiver actually takes a multiprocessing.Queue, which is used without a namespace, like the rest of this source file.

Fix filesystem radio type annotation: the wrong kind of Queue

---

parsl/executors/taskvine/manager.py
parsl/executors/taskvine/manager_config.py

Make vine_tune config parameters accessible through the manager config while using the TaskVine executor
- New feature

TaskVine Executor: add vine tune to manager config

---

parsl/tests/conftest.py
test-requirements.txt

SSH channels were removed in #3677

Remove some SSH channel related test infrastructure

---

docs/quickstart.rst

Minor modifications to the Quickstart documentation. Fixes a typo in `retries`, adds the relevant import statements to the Polaris config, and changes the config to use the debug queue rather than prod.

Update quickstart example config

---

parsl/providers/slurm/slurm.py

Adds the `clusters` option from slurm for sites with [multi-cluster slurm](https://slurm.schedmd.com/multi_cluster.html) setups. 
Users on federated Slurm clusters will be able to schedule tasks between different clusters within the same slurm instance.
Fixes #3675 
- New feature

Adds clusters option for slurm

---

parsl/monitoring/monitoring.py
parsl/monitoring/router.py

This PR is intended to consolidate monitoring message sending in the monitoring radio code.
This is a step towards removing Python multiprocessing from the monitoring code base (see issue #2343) by making it clearer how to change to a different message send implementation (by swapping out the radio implementation and configuration)
Compare to how the interchange forwards HTEXRadio messages onwards via some other radio (which right now is always the ZMQRadioSender) -- rather than having its own ZMQ code.
none

Make ZMQ, UDP and filesystem monitoring routers send via radios

---

parsl/dataflow/dflow.py
parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/monitoring/router.py

Prior to this PR, MonitoringHub had a logdir parameter which let the log directory be set separately from the DFK-level run directory.
Other Parsl components generally don't let the user set this unless there is a specific reason.
So this PR removes that feature, reducing the amount of state to be threaded around.
When reading this patch, note that what the DFK calls the rundir is a different directory vs what a Config object calls the rundir.
This removes a parameter from user facing MonitoringHub configuration.

Remove ability to set monitoring log directory separate from rundir

---

parsl/executors/high_throughput/mpi_resource_management.py
parsl/executors/high_throughput/process_worker_pool.py

The `execute_task()` function is used by multiple executors, but the MPI code is specific to HTEX.

Extract MPI code from `execute_task()`

---

parsl/executors/execute_task.py
parsl/executors/flux/execute_parsl_task.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/executors/radical/rpex_worker.py
parsl/tests/test_execute_task.py

Multiple executors use the `execute_task()` function, so moving it to its own module improves code organization and reusability.
Also removed MPI-related code from `execute_task()`, as it's specific to the HTEX.

Move `execute_task()` to a dedicated module

---

parsl/executors/execute_task.py
parsl/executors/high_throughput/mpi_resource_management.py
parsl/executors/radical/rpex_worker.py
parsl/executors/workqueue/exec_parsl_function.py
parsl/serialize/facade.py

The `user_ns` and `copy` arguments from `unpack_apply_message()` and `unpack_res_spec_apply_message()` are not used.

Drop unused args from unpack functions

---

parsl/addresses.py
parsl/curvezmq.py
parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/mpi_executor.py
parsl/executors/high_throughput/probe.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/executors/high_throughput/zmq_pipes.py
parsl/tests/configs/htex_local.py
parsl/tests/test_htex/test_zmq_binding.py
parsl/tests/unit/test_address.py

This PR adds a new option: `HighThoughputExecutor(loopback_address: str = "127.0.0.1")` which can be used to specify the internal address used by HTEX for communication between the executor and the interchange. In addition, all ZMQ sockets are now are set to having IPv6 enabled.
The test config `htex_local` has been updated to use `loopback_address="::1"` for testing.
* IPv6 support is enabled on all HTEX ZMQ components.
* HTEX now supports a `loopback_address` which allows configuring the address used for internal communication
- New feature

Adding support for IPV6 addresses

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/zmq_pipes.py

This poll happens at the configured htex poll period, which defaults to 10ms.
Under heavy result load, this shoudn't result in much additional load: the poll loop will already be looping a lot to process the results.
Under lower result load, there is a slight observable increase in CPU usage: a 30second sleep task shows this before this PR:
before:
real    0m37.451s
user    0m2.160s
sys     0m0.376s
run 2, user 2.160s
run 3, user 2.116s
and this after this PR:
real    0m37.473s
user    0m2.400s
sys     0m0.557s
Run 2, 2.457s
Run 3, 2.452s
At shutdown, the ZMQ socket for incoming results is closed.
This reduces both the number of threads and number of file descriptors left behind by the `--config local` tests. For example:
$ pytest parsl/tests/test_monitoring/ --config local
Before this …

Make result queue poll for shutdown, and tidy up at shutdown

---

docs/userguide/monitoring.rst
parsl/configs/ASPIRE1.py
parsl/tests/configs/htex_local_alternate.py
parsl/tests/configs/local_threads_monitoring.py
parsl/tests/manual_tests/test_udp_simple.py
parsl/tests/test_monitoring/test_htex_init_blocks_vs_monitoring.py
parsl/tests/test_monitoring/test_stdouterr.py

This port will be chosen dynamically, and that is fine in test situations.
This is probably also better in environments where users run multiple Parsl instances at once: they cannot all use the removed port 55055 and will interfere with each other.
Ongoing work to refactor monitoring radios will remove this hub_port parameter, making it either unnecessary (when non-UDP monitoring radios are used) or specified as part of the radio selection.
This PR removes hub_port from tests and examples as preparation for that change.
The monitoring UDP port will be chosen dynamically in tests and examples.

Remove monitoring UDP hub_port from example/test configs

---

parsl/channels/base.py
parsl/channels/local/local.py
parsl/dataflow/dflow.py
parsl/providers/condor/condor.py
parsl/providers/grid_engine/grid_engine.py
parsl/providers/lsf/lsf.py
parsl/providers/pbspro/pbspro.py
parsl/providers/slurm/slurm.py
parsl/providers/torque/torque.py
parsl/tests/test_providers/test_pbspro_template.py
parsl/tests/test_providers/test_slurm_template.py

This leaves channels as a stateless (and useless) object that can be removed in a subsequent PR. That removal will change/break a lot of config files so I want it to keep it separate from this attribute removal.
Batch providers will now use their own script_dir attribute, rather than the channel script_dir attribute. Prior to PR #3688 these attributes were paths on different file systems: the submit side (for providers) and the batch job execution side (for channels). PR #3688 removed support for batch job commands to run somewhere that isn't the workflow submit side, and so since then, these two attributes have been roughly equivalent.
In some (obscure seeming cases) they might be different: if a channel is shared between DFKs, then the script_dir used by providers in one DFK will now no …

Remove script_dir state from channels

---

docs/index.rst
docs/userguide/glossary.rst
docs/userguide/index.rst

Makes the style of the glossary section for the documentation match the rest of the docs better.
- Only have it appear once in table of contents
- Remove bolding from section titles (Sphinx style already bolds them)
- Remove : from end of section title (to match other rst documents)
- Make underscores for titles match length (mismatch just bugs me)
N/A
Fixes #3426 (we've got the general prototype done)

Clean up glossary formatting

---

setup.py

This is a piece of PR #3646 to support Python 3.13
networkx 3.2 is the first version to support numpy 2. Later versions do not support Python 3.9.
This is a package upgrade that behaves the same in my testing

Upgrade networkx to support Numpy 2 to support Python 3.13

---

parsl/monitoring/db_manager.py
parsl/tests/configs/htex_local.py
parsl/tests/test_monitoring/test_app_names.py
parsl/tests/test_monitoring/test_stdouterr.py
setup.py
test-requirements.txt

This is part of supporting Python 3.13 (PR #3646), as a prereq to upgrading pandas.
Development environments (which have the requirements in `test-requirements.txt` installed) will break and need `pip uninstall sqlalchemy2-stubs` - sqlalchemy packaging does not express a negative/removal requirement against that transitional package.
non-parsl user code which happens to use the parsl-installed sqlalchemy might break - for example, see API changes in the test suite in this PR

Upgrade SQLAlchemy to version 2

---

parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

Block scaling is the responsibility of the job status poller, and end-of-run block scale-in happens in `job_status_poller.close()`
The code removed by this PR is buggy and breaks in some situations: it should not be using the `blocks_to_job_id` table to enumerate live blocks.
- Bug fix

Remove WorkQueue and TaskVine block scale-in code

---

setup.py

This is part of supporting Python 3.13 (PR #3646). The previous pandas constraints cannot install on Python 3.13.
none

Upgrade pandas to >=2.2

---

docs/reference.rst
parsl/executors/taskvine/factory_config.py
parsl/executors/taskvine/manager_config.py

Fix a handful of Task Vine docstring issues

---

parsl/tests/test_python_apps/test_fail.py

This test would pass if execution either succeeded or failed with a `DependencyError`. It did not assert any relationship between those two possibilities and whether earlier tasks actually succeeded or failed.
`test_fail_sequence` in the same file tests more strongly whether a failure is correctly propagated.

Remove a deliberately non-deterministic test

---

parsl/app/futures.py

The task ID is never optional: a DataFuture always comes from a Parsl task. (in the same way that an AppFuture always has a task record)
Long ago, Files could be specified as strings. This behaviour was removed slightly less long ago. Right now, typeguard should be detecting if a string is passed, because of the type signature, and so the explicit type check for strings should be unnecessary. This PR removes that explicit type check.
The future being tracked by the data future is not necessarily an AppFuture: it can be any kind of future that completes to indicate the represented file is now available. That is already reflected in the type annotations and code, but this PR fixes the docstring.
none

Tidy DataFuture argument types

---

parsl/dataflow/dflow.py
parsl/tests/test_python_apps/test_dep_standard_futures.py
parsl/tests/test_python_apps/test_fail.py
parsl/tests/test_python_apps/test_join.py

Prior to this PR, there were 4 variant ways to render a future (which is usually but not always a Parsl task) as a text string:
1. describing failure of inner future in a join_app with 1 future to join
- rendered task ID if the inner future has a task record attribute, without checking it is a parsl.dataflow.taskrecord.TaskRecord or that that attribute contains a task id entry.
- otherwise render as None
2. describing failure of inner future in a join_app with a list of futures to join
- is meant to do the same as case 1, but is buggy and always renders as None (the wrong object is checked for having a task_record attribute)
3. describing failure of a dependency future
- rendered task ID if there was a task_record, and the
future is from the same DFK as is rendering the code
(so that a …

Refactor 4 different renderings of task description

---

parsl/executors/high_throughput/zmq_pipes.py

This was introduced in PR #2965 to help debug ZMQ hangs.
PR #3709 changed this loop to run every poll period (by default, every 10ms) rather than every result message.
That turns this log line into a huge source of log noise/volume.
This PR removes that log line - ZMQ debugging must proceed without it.
parsl.log size from:
pytest parsl/tests/ --config parsl/tests/configs/htex_local.py
before this PR: 7 megabytes
after this PR: 2 megabytes
- Bug fix

Remove over-verbose debug message

---

parsl/dataflow/taskrecord.py

TaskRecord was merged in PR #2392 from a separate
development branch, and contained some cruft which this PR removes:
* a comment on checkpoint, that was a note on that development branch, not relevant to the main codebase
* retries_left was removed in #1773 and has never been used in TaskRecord
* fn_has was removed in #1945 and has never been used in TaskRecord

Tidy mess from initial TaskRecord implementation

---

CONTRIBUTING.rst

I noticed the Code of Conduct link was broken, so I updated it. While reading through the file, I made some minor grammatical updates for consistency and accuracy.
N/A
N/A

Update broken CoC link and minor grammar changes

---

.github/workflows/gce_test.yaml
Makefile
docs/reference.rst
docs/userguide/configuration/examples.rst
docs/userguide/configuration/execution.rst
mypy.ini
parsl/configs/gc_multisite.py
parsl/configs/gc_tutorial.py
parsl/executors/__init__.py
parsl/executors/globus_compute.py
parsl/tests/configs/globus_compute.py
parsl/tests/conftest.py
parsl/tests/test_error_handling/test_resource_spec.py
parsl/tests/unit/test_globus_compute_executor.py
setup.py
test-requirements.txt

This PR adds a new `GlobusComputeExecutor` that wraps the Globus Compute SDK to allow Parsl to execute tasks via Globus Compute. This mechanism supports remote execution of tasks similar to the functionality that `parsl.channels` enabled and is a potential replacement.
Since `GlobusCompute` often runs on remote machines that do not have a shared-filesystem with the parsl runtime, tests have been updated with a new `shared_fs` and `staging_required` pytest markers. I have not added tests and CI actions to enable executing these tests against our CI system, but you can run tests locally with these steps:
1. Install `globus-compute-sdk` with `pip install .[globus-compute]`
2. Configure and start a globus-compute-endpoint, `globus-compute-endpoint start <endpoint_name>`
3. Set an env var with …

Support for GlobusComputeExecutor

---

parsl/executors/high_throughput/executor.py
parsl/tests/test_htex/test_resource_spec_validation.py

PR #3638 introduced parameters and documentation for a task priority field which was never implemented in mainline Parsl. This PR leaves most of the infrastructure in place, as other code now depends on it, but removes `priority` as a valid resource specification field.
users trying to use the no-effect priority parameter will now get runtime errors rather than silent ignore.

Revert part of PR #3638 which is part of a now-abandoned task priority PR series

---

parsl/dataflow/dflow.py
parsl/usage_tracking/usage.py

Fix the bug where the DFK logs that it is entering usage tracking code in a way that suggests it is logging usage tracking data, even when turned off.
The DFK will only log messages about usage tracking data being sent when usage tracking is enabled.
Fixes #3740 
- Bug fix

Usage Tracking: Only log messages when tracking is enabled

---

parsl/executors/high_throughput/interchange.py

This removes one of two non-main threads in the interchange - the task puller thread - and moves the behaviour there (receive a message and put it in an in-process queue) into the main thread (where that in-process queue is ultimately dequeued, anyway)
This is aimed at helping with ZMQ-vs-threads issues within the interchange -- most immediately, clean shutdown #3697
performance notes:
parsl-perf -t 30, my laptop, no logging
before this PR, 2320 tasks/second
post this PR, 2344 tasks/second
cc @rjmello who expressed especial interest in this
Some performance difference, although the brief measurements above are not concerning.
- New feature

Move htex interchange tasks incoming thread into main thread

---

parsl/dataflow/dflow.py
parsl/tests/test_checkpointing/test_python_checkpoint_1.py

This file is saved alongside checkpoints, but stores an extremely light summary of DFK state rather than of checkpoints: the DFK's task count and run directory path.
That is information that falls into the space of monitoring, not of checkpointing - so this PR removes that file, in favour of the much richer monitoring database.
Checkpoints will no longer contain the light monitoring data that was previously in `dfk.pkl`.  Users will have to get that information some other way (for example, by looking at the location of the checkpoint directory to discover the run directory, and by using Parsl's monitoring facility for task counts)

Remove quasi-monitoring checkpoint file dfk.pkl

---

parsl/monitoring/visualization/plots/default/workflow_plots.py

Plotly released 6.0.0 a couple of weeks ago, and dropped a deprecated item we use.  Accordingly, alter usage to the updated API.
No changed behavior.

Update plotly usage

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/unit/executors/high_throughput/test_process_worker_pool.py

The only change of note is to move the `ArgumentParser` to a function to enable writing unit tests for it.
No user-functional change.

Add first unit tests for process_pool_worker

---

parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/unit/executors/high_throughput/test_process_worker_pool.py

`--addresses` is de facto expected to be specified, and breaks if not specified.  Formalize that expectation.
No changed behaviour.

Formalize required argument

---

parsl/executors/high_throughput/process_worker_pool.py

The IDE was complaining that syntactically, `logger` might not exist.  Satisfy the IDE.  While here, move to a single `.info()` call, and update to f-string syntax.
A slight log format modification for the beginning of this script to facilitate a single log call.

Guarantee logger exists

---

parsl/executors/high_throughput/process_worker_pool.py

There's no sense in delaying the creation of these instance variables.  Move them to init to allow typing to be able to reason about them slightly better.
No changed behaviour.

Specify instance attributes in init

---

parsl/executors/high_throughput/process_worker_pool.py

Silly to pass the variable when the class already has a reference to it.  While here, update name of event to stop, as "kill" implies, at least in Unix-signal-speak, something more drastic.
No changed behaviour.

Don't pass class variable

---

parsl/executors/high_throughput/process_worker_pool.py

The ZMQ documentation is quite clear about not sharing ZMQ sockets between threads.  This case wasn't so much shared as simply created on the main thread and _used_ in the child threads.  "Probably" okay, and hasn't appeared to have bitten us to date ... regardless, be cleaner, and in so doing recognize that these aren't actually class variables.
Slightly different logging output, as the result and task ZMQ pipes are now connecting in different threads.

Create and close ZMQ sockets on utilizing thread

---

parsl/executors/high_throughput/mpi_resource_management.py

`TaskScheduler` is a do-nothing shim over `mp.Queue`, only standing as hook-in point for `MPITaskScheduler`.  In both cases, there is no need to mask the `Queue`'s fundamentals semantics.
No changed behaviour.

Update signature to match underlying resource

---

parsl/executors/workqueue/executor.py

This is a small step in restricting global/broadly scoped state around multithread/multiprocess use - something which is an ongoing problem in Parsl in general.
This change should not change any behaviour as the changed variable was already only used in local scope.
none

Move WorkQueue._port_mailbox to be a local variable

---

parsl/executors/taskvine/factory.py

TaskVine Executor: make sure factory scratch dir exists

---

parsl/utils.py

Prior to PR #3282, initial block scaling happened at DFK startup.
PR #3282 moved initial scaling to happen inside the scaling strategy, alongside other scaling. This meant that initial block scaling only happens on the first poll cycle, by default 5 seconds after startup.
This PR makes a scaling strategy run happen at startup and then every subsequent poll cycle - removing that one-poll-cycle second delay.
parsl blocks will start up faster.
- Bug fix

Perform initial block scaling immediately

---

.github/workflows/parsl+flux.yaml
.github/workflows/parsl+slurm.yaml

In order to make more tests mandatory, those tests need to run in the merge queue. PR #3661 did this for the main CI tests. This PR does it for flux and slurm tests so that they can be made mandatory (in github non-versioned config)
more tests will run at merge time. nothing user-facing.

Run slurm and flux tests in merge queue

---

parsl/monitoring/router.py

This was introduced unused in PR #812 and I think has never been used since then.
none

Remove unused argument that only ever takes default value

---

parsl/tests/test_shutdown/test_kill_monitoring.py

This treats the filesystem router the same as the general router and DB process in this test.
more testing

Add another monitoring kill test, for filesystem router

---

parsl/executors/high_throughput/executor.py

The HighThroughputExecutor assumes that the submit process and the interchange are in the same host (in the sense that the configured loopback address will work to connect from one to the other).
This PR adds that assumption for connecting from the interchange to the monitoring router. Which is pretty much already a constraint: that router is launched from the submit process using Python multiprocessing and so will run on the same host as the submit process.
in-host network connections for monitoring will look a bit different, but shouldn't be a behaviour change

Make interchange monitoring ZMQ use loopback, like other connections

---

parsl/monitoring/radios/udp_router.py
parsl/monitoring/radios/zmq_router.py

Before this PR, the ZMQ/UDP router main threads only launched the receiver threads and then waiting for them to terminate. There is no need for separate threads for this.
none

Remove unneeded threads in ZMQ/UDP routers

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios/filesystem_router.py

This is consistent with ZMQ and UDP receivers being in their own files.
none

Move filesystem monitoring receiver to own file

---

parsl/monitoring/radios/zmq_router.py

This was used as part of the exit behaviour for UDP part of the monitoring router, from before PR #3796 router split.
none

Remove unused timeout parameter from ZMQ router

---

parsl/executors/high_throughput/mpi_resource_management.py
parsl/tests/test_mpi_apps/test_mpi_scheduler.py

The `MPITaskScheduler` uses Python's PriorityQueue to prioritize tasks based on the number of nodes requested.
When items with identical priorities are are submitted to the PriorityQueue, they attempt to sort based on the task dict which fails with TypeError unhashable type: dict. This PR adds a new `PrioritizedTask` dataclass that sets the task element to `field(compare=False)`.
I'm splitting changes in #3783 to keep the PR concise. This is split 1 of 3.
Fixes the bug described above.
- Bug fix

Fix bug in MPITaskScheduler where tasks with identical priorities fail with `TypeError`

---

README.md

Once I satisfy the first PR merge, I can create a specific "contributors" file to host all this info moving forward.
The all-contributors bot requires some initial code to be added to a README.md file to complete installation. I plan on creating a separate "contributors" markdown file to host contributor info without adding extra length to our current README.rst file. This README.md will be removed after installation is complete.
N/A
N/A
- New feature

Create temp README.md for all-contributors bot installation

---

parsl/executors/high_throughput/mpi_resource_management.py
parsl/executors/high_throughput/process_worker_pool.py

There is no need to iterate the loop to send a heartbeat.  Instead, use a dedicated thread (heartbeater), and no longer send messages to ZMQ in bulk.  ZMQ already handles messages messages performantly and `_multipart()` is for an _atomic_ send of multiple messages or message parts.
This reduces the complexity of the loop, and also reduces the idle CPU load.  On my local hardware, it reduces the idle load by about 40% (not scientific; just looking at htop).
In future work, can replace `result_outgoing.send_multipart()` with just `result_outgoing.send()`
No changed user-facing behavior.  Potentially visible is less idle CPU use.

Refactor result loop, remove timeout

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios/filesystem_router.py

The other routers exit using an exit flag, rather than being terminated.
This PR makes filesystem router consistent with that, without making an judgement about whether this is the right mechanism by which all these routers should exit.
none

Make filesystem monitoring router exit like the other routers

---

parsl/executors/high_throughput/process_worker_pool.py

Threads exiting normally is not unexpected -- the program is shutting down. Match the log level of the counterpart log message when starting the thread.
Mild changing of thread state log line levels.  For 99% of users, this could be considered a noop.

Reduce thread exit log level

---

parsl/monitoring/monitoring.py
parsl/tests/test_monitoring/test_exit_helper.py

Prior to this PR, the monitoring proceses were shut down in two ways:
* In the happy path, processes would be notified that it was shutdown time via a multiprocessing.Event(). They would be joined on, with no timeout, assuming that they would eventually shut down based on the Event. In the unhappy case that one does not shut down, DFK shutdown would hang here.
* In the unhappy path, processes each have an opportunity to notify that an exception has happened via the exception_q. This is used for two purposes: to transcribe the exception into the main Parsl log, and to change how shutdown happens: if any exception has been delivered this way by any of the monitoring processes, then shutdown will happen by calling .terminate() on each process, without event notification.
This PR changes that …

Make monitoring shutdown always event-terminate-kill-close

---

parsl/monitoring/db_manager.py
parsl/monitoring/monitoring.py
parsl/monitoring/radios/udp_router.py
parsl/monitoring/radios/zmq_router.py

After PR #3811 removed exeception_q's role in exit handling, this code remains only as a rudimentary distributed logging system to convey some specific error messages back to the main process for logging in parsl.log.
No other part of Parsl does this in this way, and instead each process logs to a file with the user expected to look in individual log files.
This PR makes monitoring consistent with that expectation.
Error messages from monitoring failures will appear in different places, compared to before this PR.

Remove exception_q from monitoring

---

parsl/multiprocessing.py
parsl/usage_tracking/usage.py

Prior to this PR, the usage tracking process was launched using the fork multiprocessing context, which interacts badly with threads.
This is part of a larger project to move Parsl away from the fork context. See https://github.com/Parsl/parsl/issues/3723 for more information.
This will require users invoking Parsl directly from workflow scripts to put `if __name__ == "__main__":` guards around their workflows, as described in the above issue.
- Bug fix

Move usage tracking to use spawn context multiprocessing

---

parsl/monitoring/monitoring.py
parsl/multiprocessing.py
parsl/tests/test_monitoring/test_exit_helper.py

This follows on from PR #3816 and is discussed in issue #3723
This PR makes one test timeout slightly longer: the spawn method is slower to start up new processes (mostly due to re-importing rather than copying from the parent process). On my laptop, that test starts failing with a timeout of 0.7s and github runners are definitely resource constrained and slower than my laptop, so I increased the previous 1s timeout to 2s.
Users will now require `if __name__ == "__main__"` protective sigil when using monitoring - see issue #3723 for more info.
- Bug fix

Move monitoring hub/router to use spawn context multiprocessing

---

parsl/monitoring/monitoring.py
parsl/multiprocessing.py
parsl/tests/test_monitoring/test_exit_helper.py

This is used within parsl.monitoring.monitoring, but upcoming code rearrangements to monitoring code want to use it in different places.
There is nothing monitoring specific about this - it should work with any SpawnProcess at least (and probably any multiprocessing Process) so this PR moves it to parsl.multiprocessing.
none

Move join_terminate_close_proc to parsl.utils

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/high_throughput/executor.py
parsl/monitoring/errors.py
parsl/monitoring/monitoring.py
parsl/monitoring/radios/zmq_router.py
parsl/tests/test_monitoring/test_fuzz_zmq.py
parsl/tests/test_monitoring/test_radio_zmq.py
parsl/tests/test_monitoring/test_stdouterr.py
parsl/tests/test_shutdown/test_kill_monitoring.py

This is part of an ongoing project to move monitoring message forwarding into relevant executors, with executors only initializing whichever routers are needed.
In this step of the project:
The ZMQ radio/router is only used by the high throughput executor to receive messages from the interchange. This PR makes the initialization of that look more like other interchange<->submit side ZMQ initialiation, rather than look like monitoring system initialization.
This does not stop other future components which want to use monitoring-over-ZMQ: those components would initialize ZMQ routing themselves.
API-wise:
Parsl executors lose the hub_zmq_port attribute which was configured by the DFK after initialising monitoring.
As a replacement, Parsl executors gain a monitoring_messages attribute, which …

Move ZMQ monitoring radio initialization into HTEX

---

parsl/dataflow/dflow.py
parsl/executors/base.py
parsl/executors/flux/executor.py
parsl/executors/globus_compute.py
parsl/executors/high_throughput/executor.py
parsl/executors/radical/executor.py
parsl/executors/status_handling.py
parsl/executors/taskvine/executor.py
parsl/executors/workqueue/executor.py

This attribute is now set by BlockProviderExecutor.start(), using executor.monitoring_messages.
This makes it so there is only be one path for monitoring messages from executor to the MonitoringHub.
Non-block-provider executors will now get no submit_monitoring_radio attributed injected, but I don't think any executors need that as it is only used for block reporting.

Remove DFK-set executor.submit_monitoring_radio

---

parsl/executors/high_throughput/interchange.py

The inner else condition was never utilized before, as the value of `real_capacity` never changed.  Calculate the value correctly by including the tasks that moved.
No user workflows should be changed; managers will be removed from the interesting_managers variable one iteration sooner.

Correctly calculate new manager real capacity

---

parsl/executors/taskvine/executor.py

Before:
```
1743168380.056636 2025-03-28 13:26:20 MainProcess-55205 TaskVine-Collector-Thread-140654853220032 parsl.executors.taskvine.executor:626 _collect_taskvine_results DEBUG: Updating Future for Parsl Task: 0.                                Task 0 has result_received set to True
```
After:
```
1743168797.042448 2025-03-28 13:33:17 MainProcess-56555 TaskVine-Collector-Thread-140356603016896 parsl.executors.taskvine.executor:626 _collect_taskvine_results DEBUG: Updating Future for Parsl Task: 0. Task 0 has result_received set to True
```
log formatting

Fix excessive whitespace in Task Vine log message

---

parsl/executors/high_throughput/interchange.py
parsl/tests/test_monitoring/test_basic.py

Update any interested listeners to the state of the manager when new tasks are assigned.  Based on `.start()`, this now covers most (all?) relevant changes to a manager's info block that will be shared.
Adds a monitoring message per manager in the interchange loop, for any outstanding tasks that move from the interchange to a worker manager.  I don't think any existing workflows will be impacted, but there will now be an extra NODEINFO record in the sqlite database per task.
- New feature

Add monitoring info for tasks given to a manager

---

parsl/dataflow/dflow.py
parsl/monitoring/monitoring.py

This consolidates the API that the MonitoringHub offers for sending a monitoring message to be via a multiprocessing Queue.
Prior to this PR, the MonitoringHub exposed both a multiprocessing Queue (since #3818) and a .send() method for use in the original process.
This is part of ongoing work to move external communication for monitoring out of the MonitoringHub, except via this multiprocessing.Queue.
This removes another constraint on what a replacement MonitoringHub looks like - something that is being partially driven by Globus Compute desire for some monitoring information via API, not via the existing database implementation.
This PR splits the DFK state for monitoring into two: a configured MonitoringHub (self.monitoring) which comes from the Config object as before, and a new …

Convert DFK/monitoring message.send() to multiprocessing Queue

---

parsl/executors/high_throughput/interchange.py
parsl/tests/test_monitoring/test_basic.py

This is a followup to #3833; had meant to add it in there after #3834, but miscommunicated so adding now.
Adds a result-side monitoring messages for managers that send results.  No workflows should be impacted, but there is now an additional NODEINFO record in the sqlite database.  This PR will bring the total up to 4 (as shown in the changed test).
- New feature

Add result-side monitoring update

---

.github/workflows/parsl+cctools.yaml
Makefile
parsl/executors/workqueue/executor.py
parsl/tests/test_monitoring/test_basic.py

This PR splits out the testing for WorkQueue and TaskVine into a separate Github action.
The current mechanism that relies on pulling binaries for cctools is broken in Ubuntu 24.04, and based on the discussion here: https://github.com/Parsl/parsl/issues/3544, the recommended solution is to switch to using binaries distributed through conda. 
* Split out TaskVine and WorkQueue test to a separate GH Action
* Update GH Action to use conda instead of virtualenv.
The default Parsl CI test action will no longer test WorkQueue and TaskVine. A new action is added for these tests.

Move WorkQueue and TaskVine tests to a separate GH Action

---

.github/workflows/parsl+radical.yaml
Makefile
parsl/tests/test_radical/test_mpi_funcs.py

This PR aims to separate the Radical executor test suite from the main parsl workflow. The current CI workflow encounters issues when installing MPI via system packages and pip when moving from Ubuntu 20.04 to 24.04. This new workflow fixes this by doing the following:
- Move radical tests to a separate GH action
- Use conda to install MPI and other external dependencies 
The main Parsl GH Action no longer tests radical executor tests. A new action has been added for radical specific tests.
Fixes #3844 
- Bug fix

Move Radical tests to a separate GH Action

---

parsl/executors/high_throughput/interchange.py

The interchange tight loops through several sections. Two of those sections log that they are doing nothing. Other sections only log when they do something.
This PR makes those two sections no longer log when they do nothing.
As an example, an interchange idle for 20 seconds in a test case on my laptop logs:
before this PR: 5699 lines
after this PR: 1925 lines
The bulk of the remaining 1925 lines is another per-iteration message that is interchange status summary information, rather than per-section activity logging. Rather than implement something specific for this message to log it less frequently, this is left for a future PR which will make the interchange loop only when something happens, rather than in a tight poll.
Please include a summary of the change and (optionally) which issue …

Remove interchange logging for sections where nothing happens

---

parsl/executors/high_throughput/mpi_resource_management.py
parsl/tests/test_mpi_apps/test_mpi_scheduler.py

The python `PriorityQueue` prioritizes items with smaller priority values, which leads us to our current `MPITaskScheduler` prioritizing MPI tasks with fewer nodes requested since the nodes requested is used as the priority. This PR changes the ordering to prefer larger jobs. 
MPI Tasks with larger node requests are prioritized by the manager. Please note that as @WardLT pointed out in the comments on #3783, the greedy scheduling that we use can lead to larger tasks getting delayed in favor of smaller tasks that can get scheduled immediately.
These are change split from https://github.com/Parsl/parsl/pull/3783 to keep the PR concise.
This is split 3 of 3.
- Update to human readable text: Documentation/error …

Make `MPITaskScheduler` prioritize large tasks

---

parsl/addresses.py
parsl/tests/test_htex/test_zmq_binding.py
parsl/tests/unit/test_address.py

Fixes the creation of the TCP url when the ports used by HTEx workers are fixed.
The `tcp_url` helper function from addresses.py was only appending the port number when the address was not "*".
HTEx works with the ports fixed. Not sure when it was broken
I added a unit test which shows that the current code fails when launching an HTEx interchange with user-set ports.
None (yet? should I make one?)
- Bug fix

Fix binding when user sets HTEx worker ports manually

---

.github/workflows/parsl+cctools.yaml
Makefile
parsl/tests/conftest.py
parsl/tests/test_monitoring/test_basic.py

PR #3844 removed those tests as part of CI rearragement.

Restore removed cctools monitoring tests

---

parsl/usage_tracking/usage.py

Occasionally usage tracking can fail to exit cleanly at the end of a parsl run and raise an error.
Call join() after kill() in usage.py.
Fixes # (#3859)
- Bug fix

Fix occasional error on exit with usage tracking enabled (#3859)

---

docs/faq.rst
docs/reference.rst

Updates references in the docs to ManagerLost which has been moved to errors.py instead of being within the Interchange. Theoretically, the original way of accessing ManagerLost via Interchange should be fine but doesn't work. Either way hopefully directly referencing errors.py should make it more clear in docs if nothing else. 
Docs CI should not fail due to missing references anymore.
N/a

Update ManagerLost references in docs

---

docs/userguide/advanced/monitoring.rst

Monitoring has been used for years with WorkQueueExecutor within DESC.

Remove "monitoring is htex only" statement

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios/udp_router.py

This stayed wired in when the ZMQ and UDP routers were split in PR #3796.
The UDP router does not use the hub address. It is only used by the ZMQ router.
As an alternative to remove this unused parameter, the UDP router could be modified to listen only on the supplied address - that remains as an option in future, but my work right now is about tidy up, not about adding new features.

Remove unused hub address parameter for UDP router

---

parsl/monitoring/radios/udp_router.py

PR #3791 removed an unused argument. PR #3796 was a source code move that was prepared around the same time, and did not do that move cleanly.
nothing was broken by the reversion, so nothing is fixed

Reapply PR #3791 accidentally unapplied in #3796

---

parsl/tests/conftest.py

Before this PR, a sequence of small random number choices could make doublings happen quite fast, pushing the delay time to be quite high faster than exponential rate and then causing later iterations to wait for longer than might be expected.
This PR makes the delay time increase according to the chosen delay for each iteration.
See issue #3350 for an example of where this happened and was part of a non-deterministic test failure.
This PR should make (by default) try_assert wait up to 2x as long as it takes for the assert condition to become true. This is now parameterised by `factor`, so that it might be set to 1.1 to make the assert wait for up to 1.1x the time it takes for the assert condition to become true.
Exponential backoff should now be more smoothly exponential.
- Bug fix

Make try_assert exponential backoff smoother

---

parsl/monitoring/monitoring.py
parsl/monitoring/radios/udp_router.py
parsl/tests/test_monitoring/test_radio_udp.py
parsl/tests/test_shutdown/test_kill_monitoring.py

This is part of making radios more pluggable.
After this PR, there is a UDPRadioReceiver, patterned after ZMQRadioReceiver which contains process state and can be asked to close.
One MonitoringHub shutdown test no longer tests the UDP receiver process being killed -- the MonitoringHub is no longer directly aware of that process because of the new UDPRadioReceiver class.
There is a new test that is more focused on the UDP code starting and exiting correctly, without involving the MonitoringHub, and which runs much faster.

Move more UDP receiver code to own class/file

---

.flake8

This is a continuation of #3715 which removed the tests.

Remove mention of Channel tests from .flake8

---

parsl/monitoring/radios/filesystem_router.py
parsl/monitoring/radios/udp_router.py
parsl/monitoring/radios/zmq_router.py

Prior to PR #3817, router processes were launched with multiprocessing fork-no-exec. This carried log configuration into the new process, and made the direction of logs to a log file for the new process vs the other process awkward and confusing.
Post-#3817, router processes start with a clean logging environment. So, this PR makes those processes log to `parsl.*`, following logging conventions, and directs all of `parsl.*` in those processes to the relevant per-process log file.
See issue #3723 for the overarching issue about moving away from fork-no-exec.
This will make log files longer per-entry because, like parsl.log, the fully qualified module name is now recorded.
This will allow parsl.* log lines from any helper functions to be recorded into the relevant process log - prior to …

Rationalise monitoring radio logging in a post-fork world

---

parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/process_worker_pool.py

As a follow-up to the just-landed ZMQ socket reduction, update a couple of variable names.  Even though we currently have `worker_port`, the _workers_ aren't talking to the interchange, the managers are.  Similarly, on the manager side, the connection is no longer task-only.  It's for general communication with the interchange.
None.

Update variable names to match concept

---

parsl/monitoring/radios/udp.py
parsl/monitoring/radios/udp_router.py
parsl/tests/test_monitoring/test_basic.py
parsl/tests/test_monitoring/test_radio_udp.py

This parameter wasn't wired through, but because there was a default deeper in the code, nothing detected that.
See #2973 for some context around this deep-default coding style: this PR removes the duplicated defaults and leaves the default only on the user facing UDPRadio class.
This PR uses the now-working parameter to make UDPRadioReceiver shutdown faster in tests: because in these test cases, we know that we have received all messages that we will process, there is no need to wait for any further outstanding messages. This saves around 9 seconds of test runtime - both theoretically (3 tests, each 3 second saving) and in practice on my laptop.
Now that this is wired through properly, a type mismatch between the original atexit_timeout (int) and the unwired UDPRadio parameter (float | …

Fix UDPRadio atexit_timeout and use it in tests

---

docs/reference.rst
parsl/dataflow/dflow.py
parsl/executors/threads.py
parsl/monitoring/radios/multiprocessing.py
parsl/tests/test_monitoring/test_radio_multiprocessing.py

Previously, it was not a proper RadioConfig style radio, but was used ad-hoc to send messages into a multiprocessing queue.
This PR makes it into a real radio which is then used by the ThreadPoolExecutor - allowing monitoring messages to be sent from there within process (rather than the previous UDPRadio default)
ThreadPoolExecutor will no longer open a UDP listening socket for monitoring. Monitoring messages should flow the same as before.
- New feature

Flesh out multiprocessing queue monitoring radio

---

parsl/log_utils.py

These return values are unused in the codebase.
Generally code uses a sub-logger of the logger used by these two set_*_logger functions, mirroring the module hierarchy.
So it would be unusual for this logger return value to be used ...
... but this value *was* used in PR #3254 as part of ongoing refactoring of logging helpers in other processes, until PR #3891, which rationalised those other process logging to also be module hierarchy based meaning the return value is not needed any more.
This is a tidyup to allow a future commit to return a different value as part of work to shut down parsl logging at DFK shutdown.
Users making use of this return value in their own code will have to acquire the relevant `logger` through some other means - for example, using the usual `logging.getLogger` …

Remove set_*_logger return values

---

parsl/dataflow/dflow.py
parsl/log_utils.py
parsl/tests/test_utils/test_logutils.py

Prior to this PR, the automatic parsl.log handlers for each DFK will accumulate on the "parsl" log topic as new DFKs in one process are created, so for example the first created parsl.log will contain the log messages for every parsl workflow run in that process.
This is especially noticeable in pytest tests, but real world users also occasionally want to run multiple DFKs in one process.
For multiple DFKs in a process that exist completely serially, with one being shut down completely before the next starts, this should separate the logs from the two DFKs (and components) entirely.
For DFKs that exist concurrently, this PR does not stop overlapping logs. The current approach of per-module loggers (rather than per-DFK/per-object) makes that hard and this PR does not attempt to solve that. …

Detach log handler at shutdown of DFK

---

parsl/executors/workqueue/executor.py

This is to help understand the connection between Work Queue and executor level tasks when looking through logs.
Awkardly this binding is only logged at the end of a task execution, but this is intended to be a minimal PR.
See for example #2313 for similar binding work in the DataFlowKernel.
one extra log line per task when running at INFO log level and using the Work Queue executor.

Increase log level for binding between WQ and executor ID namespaces

---

parsl/executors/high_throughput/executor.py
parsl/jobs/strategy.py
parsl/tests/manual_tests/test_memory_limits.py
parsl/tests/site_tests/test_site.py

See PR #3915 for related justification on the same change for executor.outstanding()
In the connected_workers case, for High Throughput Executor, an RPC to the interchange is made when this attribute is accessed, which is execptionally high failure risk and has personally caused me a lot of trouble in understanding previously.
User code that is accessing connected workers will have to switch to method syntax, from attribute syntax.

Make executor.connected_workers a regular method

---

parsl/monitoring/db_manager.py

This isn't type-checked by mypy on invocation because the invocation is via a Thread() object rather than a regular function call.
none

Correct type annotation on monitoring _migrate_logs_to_internal

---

parsl/monitoring/db_manager.py

Since PR #3817, the database manager has been started using multiprocessing spawn, rather than fork, as part of issue #3723, and since then, this special logger naming has been unnecessary.
See PR #3644 for the same change on the htex interchange, including more detailed explanation/justification.
This PR probably doesn't change which log lines are logged now. It does open up the opportunity for Parsl helper functions to log things into the database manager log now. And log lines are now longer, because their topic is now "parsl.monitoring.db_manager", not "database_manager".

Use usual __name__ idiom for monitoring DB manager logging

---

parsl/tests/test_utils/test_representation_mixin.py

Parameters with default values take a different path in RepresentationMixin and that path was previously not tested.
none

Test default value case for RepresentationMixin

---

parsl/tests/test_utils/test_representation_mixin.py
parsl/utils.py

Prior to this PR, keyword-only arguments (those appearing after a `*`) such as z in:
```python
def f(x, y, *, z):
```
would not be output by the representation mixin.
This PR makes `RepresentationMixin` output those.
- Bug fix

Fix RepresentationMixin PEP3102 keyword-only arguments

---

README.rst

The all-contributors badge link was still active at the top of our Readme file. Not all contirbutors have been added so waiting until that is complete before adding the badge back.
N/A
N/A

Remove all-contributors badge link until its updated

---

parsl/__init__.py

These were introduced a long time ago to support using `fork` multiprocessing on Macs, despite the Mac side of things pushing back on doing this. More recently, it became clear (issue #2343) that `fork` was a bad idea on all platforms, not just Mac, and subsequent work has happened in Parsl to move most processes to `spawn` multiprocessing explicitly labelled as `parsl.multiprocessing.SpawnProcess`, and label the remaining fork processes explicitly as `parsl.multiprocessing.ForkProcess`.
Because of that explicit labelling, the default multiprocessing set by this removed code now no longer affects how Parsl launches processes on macs, and can be removed.
Users who launch their own processes on a Mac and were relying implicitly on those being `fork` processes will have to make this global …

Remove Mac global fork process overrides

---

parsl/tests/test_htex/test_priority_queue.py

While working through a recent refactor, realized that I wasn't sure if the list was just reversed or if there was another bug.  Make it clearer for the next interaction that it starts life as an intentionally unsorted list, and the engine is supposed to deal with it correctly.
Only a test; no user-facing changes

Improve priorities test

---

parsl/executors/high_throughput/interchange.py

No practical difference, but remove one import for any library-approach uses of interchange.
No changed behavior

Move import to dunder main

---

parsl/executors/high_throughput/zmq_pipes.py

The effect of the loops was to wait forever until able to send the message, or ZMQ raises.  Just ... wait forever then.  No need for the loop.  Meanwhile, as there's only one socket involved, there's similarly no need for the Poller.
No changed behavior.

Remove unnecessary looping and ZMQ poller

---

parsl/executors/high_throughput/mpi_resource_management.py

The walrus operator (`:=`) entered [Python's syntax in v3.8](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions).
No changes.

Don't instantiate variable unless necessary

---

parsl/executors/high_throughput/executor.py
parsl/executors/high_throughput/interchange.py
parsl/executors/high_throughput/mpi_resource_management.py
parsl/executors/high_throughput/process_worker_pool.py
parsl/tests/test_mpi_apps/test_mpi_scheduler.py

Introduce a `context` side-along variable for HTEX tasks.  `resource_spec` is an entry within this new dictionary.  For the moment, they serve the same purpose, but I expect `context` to become a more general concept.
Functionally, the only difference currently is a one-layer-deeper nest of dictionaries:
```diff
- msg = {..., "resource_spec": {...}}
+ msg = {..., "context": {"resource_spec": {...}}}
```
None.
- (Infrastructure for a) new feature

Introduce a task context in HTEX

---

CITATION.cff
README.rst

This PR adds the conference proceedings paper on Parsl to the `CITATION.cff` file and also adds a badge to the project to make the paper more visible to others. I recognize there is also a `CITATION.md` with this information but thought it could be helpful to raise further awareness through more direct integration.
People can reference the `CIATION.cff` or the `README.rst` to find the paper.
Closes #3857 

Add conference proceedings paper references to `CITATION.cff` and `README.rst`

---

.github/workflows/parsl+slurm.yaml

As part of removing support for Python 3.9, the slurm test container was updated (not in this repo) to use a more recent OS/Python version. That more recent version is more aggressive about protecting against root-level global installation of software using `pip` rather than using the OS-native package manager.
This PR fixes that by using a virtualenv, which is consistent with the behaviour in the main CI environment.

Make slurm test container use virtualenv

---

mypy.ini
parsl/benchmark/perf.py

A couple of errors around config loading, which previously manifested as attribute-related errors, are now more explicitly checked and reported.

Add type annotations and stronger mypy for parsl-perf

---

parsl/dataflow/dflow.py
parsl/dataflow/memoization.py

update_memo is given the whole task record, which contains the relevant Future to be memoizing.
The memoizer should never be being updated with a future that is not coming from a coherent task record with aligned hash sum and future.
none

Remove redundant argument from update_memo

---

parsl/tests/test_checkpointing/test_regression_233.py

This was introduced in 2018 in commit
fd8ce2ed03f570952348b3150742ce160122d41b
already commented-out.
none

Remove commented dead code
