docs/userguide/overview.rst
clarify that we don't actually build a DAG
=> small text update

parsl/execution_provider/aws/aws.py, parsl/execution_provider/aws/providerconf.json
Added script to handle executing on AWS
=> initial commit for amazon aws provider

parsl/execution_provider/aws/aws.py, parsl/execution_provider/aws/awsprovider.log, parsl/execution_provider/aws/awsproviderstate.json, parsl/execution_provider/azure/azureDeployer.py, parsl/execution_provider/azure/azureProvider.py, parsl/execution_provider/azure/azureconf.json
=> submit now works

docs/userguide/faq.rst
Also:
We should define "picklable objects" in the FAQ, or link from it to a definition/example.
=> updating wording

docs/devguide/roadmap.rst
We should also try to add release numbers to the items that are bold that were done before 0.3 as well.
=> minor changes to show what has happened in 0.4 in roadmap

.github/CONTRIBUTING.rst
This reflects a short discussion I had with @yadudoc today. We want
to emphasize that testing should be done AFTER the feature branch
is up-to-date with master, to avoid unexpected issues from the
merge.
=> Tweak contributing doc

parsl/app/app.py, parsl/executors/threads.py
These should be `NotImplementedError`. Fixes #126.
=> Do not raise `NotImplemented`

parsl/executors/swift_t.py
=> Add missing `scaling_enabled` for `TurbineExecutor`

parsl/app/futures.py, parsl/tests/test_globus/test_explicit_staging.py
Adding an explicit check in DataFuture to find the topmost parent Future to get state.
=> Potential fix for issue #164

docker/Dockerfile, docker/app1/Dockerfile, docker/app1/app1.py, docker/app2/Dockerfile, docker/app2/app2.py, docs/userguide/containers.rst, docs/userguide/data.rst, docs/userguide/index.rst, parsl/dataflow/config_defaults.py, parsl/executors/ipp.py, parsl/tests/test_docker/localDockerIPP.py, parsl/tests/test_docker/test_docker.py, parsl/tests/test_docker/test_docker_multisite.py, parsl/tests/test_docker/test_without_containers.py, parsl/tests/test_sites/configs/midway.py
Adding support for containers. Fixes issue #45 
Contains:
*  Support for docker containers
* Test for single and multiple docker containers in the same wflow
* Documentation
@danielskatz Please review documentation
@kylechard or @annawoodard please review code and/or docs
=> Containerized #45

parsl/tests/test_ipp/bash_app.py, parsl/tests/test_ipp/test_bash_apps.py
This is partial (there are still other issues to be addressed, but I wanted to go ahead and merge what I've got so far).
=> Fix ipp tests

parsl/data_provider/files.py, parsl/tests/test_data/test_file_ipp.py, parsl/tests/test_sites/configs/cc_in2p3.py, parsl/tests/test_stress/test_python_simple.py
Adding some minimal code to support custom pickling for File objects such that they can be dispatched via IPP.
Added regression tests.
Fixes #200
=> File pickling #200

parsl/executors/ipp.py
=> Use bash 3-compliant syntax for append + redirect

CITATION.md
Hello :-)
would this be of interest as well? It's the same snippet that Zenodo exports.
Cheers!
=> Also offer BibTeX citation snippet

docs/faq.rst
Provides documentaion fix for #59
Adding troubleshooting for network issues with IPP.
=> Adding some troubleshooting info

docs/conf.py, docs/index.rst, requirements.txt
This is tested locally-- that's no guarantee it will work on readthedocs. At least everything is pointing at 'stable' instead of 'latest' now 😄.
=> Automatically convert the tutorial notebook

README.rst, docs/faq.rst, docs/quickstart.rst, docs/userguide/app_caching.rst, docs/userguide/checkpoints.rst, docs/userguide/data.rst, docs/userguide/exceptions.rst, docs/userguide/execution.rst, docs/userguide/overview.rst, parsl/app/bash_app.py, parsl/dataflow/dflow.py, parsl/dataflow/memoization.py, parsl/executors/base.py
This PR contains a collection of small fixes to human readable text: documentation, log
messages and exception messages.
=> Assorted tidying of human readable text

parsl/dataflow/dflow.py, parsl/dataflow/usage_tracking/usage.py, parsl/tests/test_checkpointing/checkpointed.py, parsl/tests/test_checkpointing/test_regression_232.py, parsl/tests/test_manual/test_regression_220.py
Moves the usage tracking piece off to a separate process.
=> Async usage track #220 and checkpoint testing

parsl/dataflow/usage_tracking/usage.py
This commit broadens exception handling to catch exceptions from
anywhere in the UDP sender.
It also validates the values of UDP IP and port.
The `done` variable did not exist, and was generating an exception
when used. This commit removes use of it.
When an error is encountered, a compact log message is generated,
and the error is propagated no further.
=> Add more error handling in usage tracker

parsl/dataflow/dflow.py, parsl/tests/conftest.py, parsl/tests/test_bash_apps/test_basic.py, parsl/tests/test_regression/test_221.py
=> Try harder to cleanup only once

parsl/dataflow/dflow.py, parsl/tests/test_swift.py
=> Creating a mock future set with exception as parent for appFutures that are dep_failed

parsl/dataflow/dflow.py
This has been useful when debugging hangs.
I'm not sure if it belongs on `master`, or if it should be optional. I can imagine it getting very big on runs with lots of tasks.
=> Implement a method to summarise all DFK tasks; and call it at shutdown

parsl/dataflow/strategy.py
The problem arises when a strategy thread calls status on IPP executor.
So, the strategy thread explicitly mutes the handler attached to the rootLogger
by setting the logLevel to ERROR.
=> Fixes #204. Duplicate log line bug

docs/userguide/data.rst, parsl/data_provider/data_manager.py, parsl/data_provider/files.py, parsl/dataflow/dflow.py
Adds implicit staging out for executors with shared file systems. Updates data.rst to reflect the latest changes:
- added 'ftp', 'http', https' schemes
- hidden explicit staging in/out (although still can be used)
- added implicit staging in/out
=> Implicit staging #169

parsl/dataflow/usage_tracking/usage.py
Minor changes to add reporting of OS platform to usage monitoring. Fixes #247
=> Adding platform info to usage stats

parsl/data_provider/data_manager.py, parsl/data_provider/files.py
This is more a request for discussion on error handling:
When a URL is used with an unknown URL scheme, what should happen staging-wise?
=> Add explicit errors for unknown url schemes

parsl/app/bash.py, parsl/app/errors.py
The reason for the AppBadFormatting error was not actually being
set. Fixes #433.
=> Clarify AppBadFormatting error

parsl/dataflow/dflow.py, parsl/dataflow/futures.py, parsl/dataflow/strategy.py
This has been tested with @djf604's workflow and is necessary to unblock him from using Parsl. Only 0a6eebb is relevant, the other commits are minor cleanup.
=> Retry dependency failures #473

parsl/dataflow/dflow.py
=> Adding a log line to clarify result reuse from cache

docs/reference.rst, docs/stubs/parsl.monitoring.db_logger.MonitoringConfig.rst, parsl/dataflow/dflow.py, parsl/monitoring/db_local.py, parsl/monitoring/db_logger.py
Addresses #506 and also the request to add the script name to the workflow tables. Also may want to move MonitoringConfig from inside parsl/monitoring/db_logger.py to something like parsl/monitoring/config.py to make import simpler?
=> Add doc stub for monitoring (also adds the workflow name to the monitoring tables)

parsl/app/app.py
=> Fix import error

parsl/providers/error.py
=> Remove duplicated ExecutionProviderException

parsl/monitoring/app_monitor.py, parsl/monitoring/logging_server.py
Remove some default main code that looks like it is unused and broken.
This makes mypy happier.
=> Tidy monitoring module __main__ behaviour

parsl/app/bash.py
This comes from work on the DESC imsim workflow.
=> Assorted fixes to bash app error handling

parsl/monitoring/db_logger.py, parsl/tests/integration/test_monitoring_config.py
Also included a test script to manually check monitoring behavior runs. This script is simply an example of monitoring usage and does not assert anything but should be expected to work. Addresses issue #559.
=> Added RepresentationMixin to monitoring config.

parsl/dataflow/dflow.py, parsl/dataflow/states.py, parsl/dataflow/usage_tracking/usage.py
NOT TESTED: the usage tracking change
=> put failure states into constants

parsl/dataflow/dflow.py
This branch contains small tidyups to dependency code. It should not affect functionality, but only remove unused parameters or rename human readable text.
Merge this non-squashed.
=> Minor tidying of dependency code

parsl/data_provider/globus.py
Not sure how to test if this was successful.
=> Changes the globus token path to the user's home dir. Closed #468.

parsl/dataflow/strategy.py, parsl/executors/high_throughput/executor.py, parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/process_worker_pool.py, parsl/executors/high_throughput/zmq_pipes.py, parsl/executors/ipp.py, parsl/tests/manual_tests/htex_local.py, parsl/tests/manual_tests/plain_executor.py
Fixes #574 : Writing logs to rundir by default
Fixes #566 : Adds command channels to request information from the interchange
=> Command channels #566

parsl/providers/kubernetes/kube.py
=> Update kube provider #478

requirements.txt
=> Updating pyzmq version requirement

setup.py
=> Add `sphinx_rtd_theme` to reqs

parsl/providers/aws/aws.py, parsl/providers/cobalt/cobalt.py, parsl/providers/condor/condor.py, parsl/providers/googlecloud/googlecloud.py, parsl/providers/grid_engine/grid_engine.py, parsl/providers/local/local.py, parsl/providers/slurm/slurm.py, parsl/providers/torque/torque.py
Removed the "label" kwarg from the provider classes. I took a simple approach which left the provider label property. If something different was hoped for I am happy to change it.
=> Remove provider label kwarg #440

docs/devguide/dev_docs.rst, docs/reference.rst, docs/stubs/parsl.channels.ssh_il.ssh_il.SSHInteractiveLoginChannel.rst, docs/userguide/execution.rst
Note that this only fixes the merge errors, it does not add new content beyond what was available before in the libsubmit docs (which was never really complete). We already have a number of issues open already to track those needed improvements.
=> Fix libsubmit docs which were badly merged

parsl/dataflow/dflow.py
There's a specific race condition that can happen
because checkpoint restore can call launch_task twice
at once (for a task being restored, and then in
handle_exec_update for its dependencies).
It's also desirable to have per-task locks to
potentially increase concurrency for performance
reasons (although this isn't quantified).
This commit also introduces a single submitter lock,
because at the moment, executors are not thread-safe.
=> Attempts to address #591

parsl/dataflow/dflow.py, parsl/executors/extreme_scale/executor.py, parsl/executors/extreme_scale/mpi_worker_pool.py, parsl/executors/high_throughput/executor.py, parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/process_worker_pool.py, parsl/tests/manual_tests/htex_local.py, parsl/tests/manual_tests/test_basic.py, parsl/tests/manual_tests/test_worker_count.py
=> Version mismatch #244

parsl/executors/extreme_scale/executor.py, parsl/executors/high_throughput/executor.py
=> Renaming public_ip->address and adding docs

parsl/executors/ipp_controller.py
=> Randomly select all IPP HubFactory listening port services from port_range

docs/devguide/changelog.rst, parsl/version.py
Bumping version to 0.7.1 to release fixes for #738
=> Adding docs for 0.7.1 upgrade

docs/quickstart.rst, setup.py
=> Adding kubernetes as optional extra, and docs to match

parsl/tests/test_staging/test_implicit_staging_https.py
Fixed a broken test that's blocking other PRs
=> Updating https file tests to use github.gist instead of petrel

parsl/providers/kubernetes/kube.py
There is no way to share data files between steps run on a kubernetes cluster.
Added a new parameter to the `KubernetesProvider`. It is called `persistent_volumes` and will be an optional list of tuples.
Each tuple is '(persistent volume claim name, mount directory)'
For example:
```python
[ (my-pvc,/data)]
```
The KubernetesProvider uses this list to create `volume` entries and associated `volume_mounts` in the `pod_template`.
Here are instructions on how to test this PR using a minikube.
1. Create a local host path folder inside the VM:
```bash
minikube ssh
sudo mkdir /mnt/data
sudo chmod o+rwx /mnt/data
```
2. Create the persistent volume in Kubernetes by pasting this into a file called `pv.yaml`
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
name: task-pv-volume
labels:
type: …
```
=> Add persistent volumes to Kubernetes provider

parsl/launchers/launchers.py
Code changes simply replicate the overrides mechanism used by AprunLauncher.
=> Adding overrides to srun launcher

README.rst, docs/userguide/usage_tracking.rst, parsl/config.py
=> Usage tracking opt in model #639

parsl/data_provider/data_manager.py
This should fix issue #809 introduced by #805
=> Make duck-typing stronger for executors in DataManager

docs/userguide/configuring.rst
=> Updating docs with rubric from HPDC paper

README.rst, docs/devguide/changelog.rst, parsl/dataflow/dflow.py, parsl/monitoring/db_manager.py, parsl/monitoring/message_type.py, parsl/monitoring/monitoring.py, parsl/version.py
There's still an issue with MonitoringHub importing classes that do so automatic initialization that is being fixed.
=> 0.7.2 release prep

parsl/dataflow/dflow.py, parsl/dataflow/futures.py
... because AppFuture always starts with no parent these days
=> Remove unused parent field in constructor

parsl/app/futures.py
This is basically the same change as PR #835 made to
AppFuture
=> Make DataFuture.cancel behaviour consistent with AppFuture

parsl/executors/high_throughput/interchange.py
Prior to this commit, sometimes the serialised data structure contained raw `Exception` objects, rather than the expected `RemoteExceptionWrapper`.
=> Wrap interchange exceptions in RemoteExceptionWrapper

docs/userguide/monitoring.rst
fixes #845 and modify docs for using visualization server
=> Fix docs for visualization -- fixes #845

parsl/providers/condor/condor.py
=> Add default channel for Condor provider

parsl/__init__.py
This cuts down on boilerplate imports
=> Expose newish app decorators through top level module

docs/userguide/monitoring.rst
fixes #882 
Please comment or modify if necessary.
=> add tunneling docs for viz_server

parsl/providers/__init__.py, parsl/providers/pbspro/pbspro.py, parsl/providers/pbspro/template.py, parsl/providers/torque/torque.py
This is needed because the template for PBS Pro is different from
Torque. Fixes #908.
=> Add dedicated PBS Pro provider

parsl/launchers/__init__.py, parsl/launchers/launchers.py
Add mpirun launcher for PBSPro provider. Fix #909
=> Add mpirun launcher

parsl/providers/local/local.py
Thanks for the report @TomGlanzman
=> Add worker_init to docstring

.travis.yml
=> Disable CI for doc changes

docs/faq.rst
=> Adding citation to faq

.travis.yml, parsl/executors/extreme_scale/mpi_worker_pool.py, parsl/tests/sites/test_local_exex.py
=> Fix #935 broken extreme scale executor, and add a regression test

docs/quickstart.rst
=> add doc for installation parsl from conda-forge

.travis.yml
=> Revert "Enforce policy that source dirs must have __init__.py"

.travis.yml, parsl/monitoring/visualization/plots/default/workflow_plots.py
Fixes:
* Code from prior effort to skip travis for doc only commits
* Minor flake8 issue
=> Disable travis doc skipper

setup.py
=> Fix typo in monitoring import

parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py
=> Add hostname to monitoring in TASK table

requirements.txt
=> Remove non-critical modules from requirements.txt

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py, parsl/monitoring/visualization/views.py
This PR fixes multiple minor issues.
1.  check if the resource table is empty, fixes #975 
2.  protect from zero division error, fixes #926 
3. add if to check whether min and max are the same --  new bugs just found.
=> Monitoring division by zero

requirements.txt, test-requirements.txt
=> Sqlalchemy version #997

parsl/monitoring/visualization/app.py
The makes the options more consistent with each other.
=> add short option for visualization port

docs/userguide/configuring.rst, docs/userguide/monitoring.rst, parsl/configs/ad_hoc_htex.py, parsl/configs/cc_in2p3_local_single_node.py, parsl/configs/comet_htex_multinode.py, parsl/configs/cori_htex_local_multinode.py, parsl/configs/ec2_htex_single_node.py, parsl/configs/midway_htex_multinode.py, parsl/configs/stampede2_htex_multinode.py, parsl/configs/theta_local_htex_multinode.py, test-requirements.txt
Updates configs for:
* Comet
* Cori
* Stampede2
* Theta
* CC-IN2P3
* AWS
=> 0.8.0 doc updates

parsl/providers/condor/condor.py
=> Add command timeout for Condor provider

parsl/monitoring/monitoring.py
Each worker will log to a file in /tmp, the same places that
bash per-task log files are sent. My intention is that this will
become customisable in a later PR.
Debug level messages are placed around steps that have the potential
to take a long time.
The log level is set to DEBUG, so potentially large amounts
of log information may be generated (several lines per monitoring
loop iteration per worker). This is because the monitoring code
generally needs debugging at the moment. This should also
become parameterisable in a future PR.
=> Add per-monitoring-worker logging

docs/userguide/monitoring.rst, parsl/monitoring/visualization/app.py
=> Use monitoring.db in the current directory as visualization default.

docs/quickstart.rst
Add a comment in quickstart docs about gcc
=> chore(quickstart): add note about gcc requirement

parsl/monitoring/monitoring.py
=> add a catch for monitoring wrapper loop

parsl/tests/integration/test_stress/test_python_simple.py
This PR updates the stress test to use the latest config paradigm and adds some minor cleanup.
=> Minor cleanup for stress test

parsl/executors/high_throughput/interchange.py
=> remove lost manager from interesting_managers

parsl/channels/ssh/ssh.py
Adding the ssh port parameter.
=> Configurable port on SSHChannel #1148

parsl/data_provider/data_manager.py, parsl/data_provider/ftp.py, parsl/data_provider/http.py
The intention here is to move the particular staging
mechanism out of the DM and into something configurable
along the lines of GlobusScheme
=> Move ftp and http staging into own files and out of DM

parsl/executors/workqueue/executor.py, setup.py
=> Setting WorkQueueExecutor as an optional extra

parsl/dataflow/dflow.py
This removes some repeated code. In a future PR,
that code will be a bit more complicated so it
is useful to have it not repeated.
Because an inner function is used, an integer
cannot be used as a count any more as it cannot
be modified from that inner function.
Instead, a new list, which is a mutable structure,
is used to accumulate the count instead.
=> Refactor _gather_all_deps

parsl/providers/kubernetes/kube.py
adding options for the user to specify cpu and memory for each pod
=> Add options for the user to specify cpu and memory for each kube pod

parsl/monitoring/monitoring.py
=> Hub in monitoring: bind to random port if hub_port is None

docs/userguide/configuring.rst, parsl/configs/kubernetes_htex.py
=> Add kubernetes config docs #1072

parsl/monitoring/monitoring.py
I tested with a small example, which reproduces the issue on #1108.
fix #1108
=> cumulate exited children cpu time

parsl/data_provider/files.py
This is hopefully useful in debugging new staging providers
=> Add a lot more debugging information to File __repr__

parsl/tests/configs/local_threads_checkpoint_periodic.py, parsl/tests/test_checkpointing/test_periodic.py
* Update to work with recent log line formats
* Change rounding-based time delta comparison to
floating point with a margin for error
=> Fixup checkpoint periodic test

parsl/config.py, parsl/dataflow/strategy.py
=> custom max_idletime in simple strategy

parsl/providers/condor/condor.py
=> Fix error parsing condor status output

docs/userguide/monitoring.rst, parsl/dataflow/dflow.py, parsl/monitoring/monitoring.py, parsl/tests/configs/local_threads_monitoring.py
This PR enables users to turn on/off monitoring debug logging.
Fix #1085
=> Fix monitoring logging level

parsl/executors/base.py
These were developed in the benc-mypy branch.
=> Add and tighten type signatures for executor abstract base class

parsl/dataflow/dflow.py, parsl/providers/condor/condor.py, parsl/tests/manual_tests/test_log_filter.py
Attempt at cleaning up some log lines for large production runs. There's a test in the manual_tests folder that show how to add filters to turn off certain log lines.
=> Reduce the log deluge #1309

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Removing auto-assign to yadudoc.
=> Removing auto-assign to yadudoc

parsl/configs/summit.py
Renaming summit config for consistency, and a note about paths on summit.
=> Add a note about summit paths

parsl/tests/configs/azure_single_node.py, parsl/tests/configs/user_opts.py
** NEEDS rsync PR #1378 to be merged **
=> Add a config for testing azure

parsl/addresses.py, parsl/executors/extreme_scale/executor.py, parsl/executors/high_throughput/executor.py, parsl/executors/high_throughput/probe.py, parsl/executors/high_throughput/process_worker_pool.py, requirements.txt
This PR will ignore the existing `HighThroughputExecutor(address=X)` option.
=> Add address heuristics

parsl/providers/slurm/slurm.py
=> Add type signatures for slurm initializer

docs/reference.rst, docs/stubs/parsl.executors.exceptions.ExecutorException.rst, docs/stubs/parsl.executors.exceptions.TaskExecException.rst, parsl/executors/exceptions.py
I think these have never been used in committed code.
=> Remove unused executor exceptions

docs/stubs/parsl.dataflow.futures.AppFuture.rst
This brings in a change for PR #1431
Generated by:
cd docs
rm -rfv stubs/
sphinx-autogen reference.rst
=> Commit latest stub compiler output

parsl/launchers/__init__.py, parsl/launchers/launchers.py, parsl/tests/sites/test_launchers.py
Designed to standardize launching tasks from within containers, etc
=> Added a WrappedLauncher

parsl/dataflow/strategy.py
=> Fix for #1530

parsl/app/python.py
Fixes #1533 
I've got a test case but in it's current form is too slow when running with the fixed code. Will fix once the slowness is addressed.
=> Fixing repeated timeout wrap bug in python_app code

parsl/executors/base.py, parsl/executors/status_handling.py
=> Use plain object as task ID type in more places

docs/userguide/configuring.rst, parsl/configs/ASPIRE1.py
=> Add ASPIRE1 config docs

parsl/dataflow/dflow.py
=> Stop storing file mode on the end of monitoring db stdout/stderr

parsl/dataflow/strategy.py, parsl/dataflow/task_status_poller.py, parsl/executors/base.py, parsl/executors/high_throughput/executor.py, parsl/executors/low_latency/executor.py, parsl/executors/status_handling.py
=> Client side poll item updates

parsl/executors/high_throughput/process_worker_pool.py
=> Use higher default buffer threshold for serialization

parsl/app/app.py, parsl/app/bash.py, parsl/dataflow/dflow.py, parsl/tests/test_bash_apps/test_stdout.py
=> Do not pass mutable default to ignore_for_cache

parsl/executors/high_throughput/executor.py, parsl/executors/high_throughput/process_worker_pool.py
* Updates the default address probe timeout from 2s to 30s
* Adds a configurable option for htex to specify the timeout.
=> Adding new configurable option address_probe_timeout to HTEX.

parsl/executors/workqueue/executor.py
Towards a solution to #1228.
The process that submits/waits for wq tasks now explicitely remembers
the name of the result file. Before this name was recomputed, making it
very fragile to changes to how files are named.
=> wq executor: map result filename to parsl task id

parsl/tests/integration/latency.py, parsl/tests/integration/test_apps/HEDM_processlayer/process_layer.py, parsl/tests/integration/test_apps/vasp/vasp_example.py, parsl/tests/integration/test_channels/test_local_channel.py, parsl/tests/test_docs/test_workflow4.py, parsl/utils.py, test-requirements.txt
* Fixes new complaints for flake8==3.8.0
* Pins flake8 version to 3.8.0
=> Flake8 3.8.0 fixes

parsl/executors/workqueue/executor.py, parsl/tests/configs/workqueue_ex.py
Adds the storage_access specification to the work queue executor.
=> add storage_access spec to wq executor

parsl/executors/workqueue/executor.py
=> Adds type annotations to WorkQueueExecutor

parsl/tests/configs/bluewaters.py, parsl/tests/site_tests/conda_setup.sh
Updating bluewaters site test to use `bwpy` module and `virtualenv`
=> Update bw site test

parsl/monitoring/visualization/views.py
This makes the URL space layout a bit cleaner:
.../task/  lists all tasks, and
.../task/1 lists task 1.
=> Make task list appear under .../task/ not under .../app/

parsl/tests/conftest.py
This option was implemented as a temporary workaround
to problems running the test suite with the workqueue
provider, and the only use of this option was removed
in PR#1705
=> Remove pytest option for one-DFK-per-test

parsl/dataflow/dflow.py
The runtime behaviour of _gather_all_deps is not changed.
=> Correct docstring, tidy comments, add type annotation for _gather_all_deps

parsl/monitoring/visualization/plots/default/workflow_plots.py
I made some color changes to the gantt chart PR #1767 . I think the color scheme below looks slightly better. Feel free to disregard if anyone does not agree.
=> Make some color changes for monitoring Gantt chart

parsl/dataflow/dflow.py
This removes some code duplication. It should not change parsl behaviour.
-  Code maintentance/cleanup
=> Factor out monitoring task info update

parsl/channels/ssh/ssh.py
- Type: new feature (improvement for SSH channel)
- Implements #1780
- Description
Checks whether underlying SSH transport is active before executing SSH commands or performing SFTP operations. Attempts to re-establish the connection if it is not active.
=> SSH channel - reconnect if the transport is not active

parsl/monitoring/db_manager.py
This PR renames the variable names for most message structures in the monitoring database to make it clearer what goes into each queue. Monitoring behaviour should be unaffected.
=> Rename and rearrange monitoring queues for clarity

parsl/executors/high_throughput/interchange.py
=> Tidy interchange start() docstring

parsl/executors/high_throughput/interchange.py
=> Remove unused LOOP_SLOWDOWN constant in htex interchange

docs/userguide/checkpoints.rst
=> Remove bad paragraph break in checkpoint doc

docs/userguide/monitoring.rst, parsl/monitoring/visualization/plots/default/workflow_plots.py, parsl/monitoring/visualization/views.py
Prior to this, a task state was inferred based on timing information
stored in monitoring.
This PR replaces that state inference with a lookup in the status
table which has more accurate information on task final states.
=> Use real final state to color DAG visualization

parsl/dataflow/task_status_poller.py, parsl/providers/local/local.py
I removed extraneous logs as were identified in issue #1826. 
Fixes #1826
=> Tyler #1826 Removing extraneous logs

README.rst
Adding NSF funding badge to readme
=> Add nsf badge

CONTRIBUTING.rst
adding a link about how to make PRs to CONTRIBUTING.rst, for new contributors 
=> adding a link about how to make PRs

CONTRIBUTING.rst
=> fix formatting of link

parsl/dataflow/dflow.py, parsl/dataflow/states.py, parsl/monitoring/visualization/plots/default/workflow_plots.py, parsl/tests/test_summary.py
This indicates whether a task has been completed by memoisation
or by execution.
Fixes #1485
=> Replace `done` state with exec_done and memo_done

parsl/dataflow/memoization.py
Add support for memoization of tuples.
Fixes #1664.
=> Add tuple memoization

README.rst
=> Added QuarkNet NSF award info

parsl/executors/high_throughput/interchange.py, parsl/monitoring/monitoring.py
=> Fix typos of "defauls" to "default"

parsl/tests/test_python_apps/test_basic.py
It is unlikely that stdout redirection will be implemented for python
apps (and it isn't even clear if there is any sensible meaning for that
at all)
=> Remove a skipped test that demonstrates not-implemented functionality

parsl/monitoring/db_manager.py
=> Remove unused username/password for monitoring db manager

mypy.ini, parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py
=> Add more aggressive static type checking to monitoring

parsl/tests/test_monitoring/test_memoization_representation.py
=> Add monitoring db test that asserts memo-related behaviour

docs/userguide/configuring.rst, parsl/configs/osg.py
This is a dupe of #1879 with some minor flake8 fixes that were failing CI.
#1879 
=> OSG configuration updates with minor cleanups added onto #1879

parsl/config.py
=> Update horribly outdated `executors` docstring for Config

docs/reference.rst, docs/stubs/parsl.utils.get_all_checkpoints.rst, docs/stubs/parsl.utils.get_last_checkpoint.rst, parsl/config.py, parsl/utils.py
=> Generally refresh checkpoint docstrings

parsl/tests/test_monitoring/test_basic.py
=> Test that monitoring resource rows are recorded for a long task

parsl/providers/aws/aws.py
Not every AWS availability zone supports all instance types. Rather than just selecting the first subnet from the list of created subnets, we should select a subnet in an availability zone that supports the user-provided instance type.
Fixes https://github.com/Parsl/parsl/issues/511
The issue above suggests switching the chosen subnet if there is an error. Rather than doing that, I think it is better to check which availability zones support the provided instance type, then choose the subnet accordingly. With my method, we won't have to try creating an EC2 instance twice.
As an example, if you have AWS CLI installed, try:
```
aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=t2.micro --region us-west-1 --output table
```
You …
=> Select Good AWS Availability Zone

parsl/data_provider/files.py
This is from benc-mypy typechecking work.
=> Remove old test code from the end of File definition

parsl/dataflow/rundirs.py
This is from benc-mypy typechecking work.
=> Add types to make_rundir and correct docstring

parsl/launchers/launchers.py
This is from benc-mypy typechecking work.
=> Remove old test code at end of launcher.py

parsl/tests/test_scaling/test_scale_down.py
=> Disable autoscaling test that fails 50% of the time in CI

parsl/addresses.py
This is from benc-mypy typechecking work.
=> Add typeguard on address helpers

Makefile, mypy.ini, parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py
One of the main points of this is to work towards more explicit descriptions
of what goes over each queue.
Another is that this code has been poorly tested in CI in the past, and
typechecking provides more resilience there.
=> Add much more aggressive type checking for monitoring

docs/userguide/data.rst
This gives python object parameters and file staging their
own top level table of contents entries.
This works better with more recent mindset where
regular parameters to/return values from an app
are very different from file staging.
There are a few consequential changes to the text,
but no serious reworking.
=> Split "Communication" section into two pieces

docs/userguide/checkpoints.rst
=> Rewrite function comparison paragraph

parsl/tests/test_python_apps/test_fibonacci_recursive.py, parsl/tests/test_python_apps/test_join.py
=> Tidy up tests for join_app introduced in PR #1860

parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py
=> Remove use of .value when comparing enums: enums can be compared directly

parsl/dataflow/strategy.py
=> Move htex strategy docstring to the correct strategy function

parsl/version.py
This PR only contains an update to the version string.
=> Updating version to 1.1.0a1 for an alpha release

parsl/app/bash.py
This makes it clearer what time period is actually being represented.
=> Add units to walltime human readable message

README.rst, docs/devguide/changelog.rst
Changelog for `v1.1.0` release
=> 1.1.0 docs update

docs/devguide/changelog.rst, parsl/version.py
Only contains version number update and minor wording change in changelog.
Fixes #1979 
=> Bumping version to v1.1.0

docs/devguide/changelog.rst
=> better formatting

parsl/utils.py
This is the first commit of the series to improve overall code quality. 
Part of #2045
=> Replace old string formatting with f-strings in utils.py

parsl/tests/configs/nscc_singapore.py, parsl/tests/configs/user_opts.py, parsl/tests/site_tests/conda_setup.sh, parsl/tests/site_tests/site_config_selector.py
This PR adds an example config for NSCC Singapore cluster for site testing purpose
=> Add nscc singapore example config

Makefile, parsl/executors/high_throughput/process_worker_pool.py
PR #2051 wants to use a piece of process_worker_pool, and that leads to process_worker_pool needing to typecheck. This PR does that.
=> Make process_worker_pool pass mypy

parsl/providers/slurm/slurm.py
=> Tidy up slurm state comment

parsl/monitoring/monitoring.py
=> Add missing f for an f-string

docs/reference.rst, docs/stubs/parsl.dataflow.states.FINAL_STATES.rst, docs/stubs/parsl.dataflow.states.States.rst, parsl/dataflow/states.py
=> Add documentation on meanings of states

parsl/executors/high_throughput/interchange.py
=> Remove documentation that interchange is walltime aware

parsl/dataflow/dflow.py
=> Remove unneeded task_id param from sanitize_and_wrap

docs/userguide/configuring.rst
=> Switch doc verb from invocated to invoked

README.rst
This is so potential contributors can be aware the repo is participating in a study and metrics will be gathered over this time. Please let me know if there's a better place to put this statement
@danielskatz is aware of this :)
=> Add research notice to readme

docs/userguide/configuring.rst
=> Rephrase ad-hoc config doc now that AdHocProvider (PR #1297) is implemented

parsl/executors/high_throughput/interchange.py
=> Fix incorrect order of manager and interchange versions in error text

parsl/__init__.py
=> Replace parsl's logging NullHandler with python's own NullHandler

parsl/monitoring/db_manager.py
=> Fix typo in two db error messages and make consistent with each other

parsl/log_utils.py
=> Correct docstring for set_file_logger

parsl/executors/high_throughput/interchange.py
=> Remove BadRegistration exception definition which has been unused since PR #1671

docs/devguide/changelog.rst, parsl/version.py
This is a summary of `git shortlog 1.1.0..origin/master`, manually categorised by topic.
=> Add Changelog for Parsl 1.2

test-requirements.txt
This is to get generally improved typechecking compared to the previous version.
=> Upgrade mypy

CONTRIBUTING.rst
=> Update contributing guide to refer to #parsl-hackers

parsl/providers/cobalt/template.py
Needed for the module environment on ThetaGPU to be functional
=> Start bash as if it is a login shell

parsl/providers/torque/torque.py
=> Remove stub main from PBS provider

parsl/tests/test_providers/test_local_provider.py
I have repeatedly hit this error:
```
def _start_sshd(config_dir: str):
server_config, priv_key, port = _init_sshd(config_dir)
sshd_thread = SSHDThread(server_config)
sshd_thread.start()
time.sleep(1.0)
if not sshd_thread.is_alive():
>           raise Exception('Failed to start sshd: {}'.format(sshd_thread.error))
E           Exception: Failed to start sshd: expected str, bytes or os.PathLike object, not NoneType
```
which does not point clearly to a resolution.
This commit adds in both logging so that pytest --log-cli-level=ERROR will
report stack traces for exceptions such as the above "not NoneType",
and adds an assertion for the common case that is triggering this for me,
which is that sshd cannot be found on the $PATH.
In the case that sshd is not on the $PATH, that error is now …
=> Make sshd channel test errors more obvious

parsl/dataflow/job_error_handler.py
=> Correct label of stderr in JobErrorHandler, from stdout

parsl/providers/cluster_provider.py
=> fix a FIXME in cluster provider docstring

docs/reference.rst, parsl/providers/error.py
=> Remove unused ChannelRequired exception

.wci.yml
Adding WCI configuration file for listing on the workflows community website.
=> Create wci file

parsl/providers/kubernetes/kube.py
=> Tidy up a couple of comments in kubernetes provider

parsl/providers/provider_base.py
=> Change docstring example to htex or WQ, rather than IPP/Swift/T

parsl/providers/pbspro/pbspro.py, parsl/providers/torque/torque.py
=> Tidy up documentation for PBS providers

parsl/monitoring/monitoring.py
=> Rephrase Hub when it means router

parsl/dataflow/dflow.py
=> Fix obk->obj typo in DFK docstring

parsl/providers/pbspro/pbspro.py, parsl/providers/pbspro/template.py
Moves the PBSPro scheduler option to the top of the template. 
Fixes #2220 
=> Allow configurable `-l select` options in PBSPro provider

parsl/providers/provider_base.py
=> Elaborate JobStatus docstring to include stdout/err info

parsl/executors/high_throughput/interchange.py
=> remove a done TODO

docs/userguide/configuring.rst, parsl/configs/illinoiscluster.py
This adds an example Parsl configuration for the Illinois Campus Cluster system.
=> example config for Illinois CC

parsl/executors/status_handling.py
=> Remove unused _set_provider

parsl/providers/cluster_provider.py
=> syntax level tidying in cluster provider write_script

parsl/monitoring/monitoring.py
=> Clarify that resource_monitoring_enabled controls all worker side monitoring

parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py, parsl/monitoring/visualization/models.py, parsl/monitoring/visualization/plots/default/task_plots.py, parsl/monitoring/visualization/templates/task.html, parsl/monitoring/visualization/views.py
=> Remove monitoring CPU percentages, which are broken

parsl/monitoring/visualization/plots/default/workflow_plots.py
This plot counts tries, not tasks.
=> Rename tasks/app to tries/app to reflect retries

parsl/executors/high_throughput/interchange.py
This hasn't been used for a long time, since 8fbee5f2a577dafa1f777bb03ba0455655fb8941
=> Remove unused ShutdownRequest exception

docs/userguide/workflow.rst
Just noticed the typo when reading the docs.
Documentation update
=> Fix typo in documentation

parsl/providers/cobalt/cobalt.py, parsl/providers/grid_engine/grid_engine.py, parsl/providers/lsf/lsf.py, parsl/providers/slurm/slurm.py
Use logger, not print
Do not use !
Refer to submit, not scale out
=> Tidy provider.submit() failure errors

parsl/executors/high_throughput/interchange.py
=> Add @wrap_with_logs around interchange

parsl/executors/extreme_scale/mpi_worker_pool.py, parsl/executors/high_throughput/executor.py, parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/process_worker_pool.py
this will allow adding new kinds of messages - specifically monitoring messages
=> add a type tag to htex messages.

parsl/monitoring/db_manager.py
=> Add a stronger type assertion around monitoring code being rearranged

parsl/tests/test_bash_apps/test_error_codes.py
=> remove test that is testing bash exit code behaviour, not parsl

parsl/dataflow/dflow.py, parsl/monitoring/monitoring.py
=> Pass rundir around some more for use in upcoming FilesystemRadio

docs/userguide/checkpoints.rst, docs/userguide/configuring.rst, parsl/tests/sites/cori.rst, parsl/tests/sites/midway.rst
This became a problem for me when running vscode which wants all .rst
files to make sense.
=> Change >>> doctest RST markup to code blocks

parsl/dataflow/dflow.py
=> Add debug information about choosing workflow name

parsl/app/errors.py
Python does not pickle an exception chain and so this needs to be handled by hand. Do this by saving the cause exception as another `RemoteExceptionWrapper` object.
Chained exceptions allow raising a more specific exception with additional information while still keeping the entire information of the initial exception (like `raise SpecificException("additional information") from e`). However if this happens remotely with Parsl, the original exception is lost. With this change, the entire exception with all its causes are transferred.
Example script:
```python
import parsl
from parsl.app.app import python_app
from parsl.providers import LocalProvider
from parsl.channels import LocalChannel
from parsl.config import Config
from parsl.executors import HighThroughputExecutor
local_htex = …
```
=> Transfer chained exception from remote

parsl/dataflow/dflow.py
Although mostly this doesn't happen, in the case of issue #2252,
a KeyError was being raised by hash_lookup, and this was being
placed into the checkpoint result rather than propagated.
This PR reworks that code to not use hash_lookup at all, and
remove that entire exception code path.
This does not address #2252 but makes the behaviour a bit more
consistent.
=> Rework checkpointing to avoid race conditions and incorrectly checkpointed exceptions

parsl/dataflow/dflow.py, parsl/tests/conftest.py
=> Make some ValueErrors into RuntimeErrors

parsl/dataflow/rundirs.py
=> Log full exception at rundir creation failure

parsl/dataflow/states.py, parsl/monitoring/db_manager.py, parsl/monitoring/monitoring.py, parsl/monitoring/visualization/plots/default/workflow_plots.py
=> Introduce a running_ended state

parsl/providers/slurm/slurm.py
If the user has SQUEUE_FORMAT set, the results from squeue
might not be in the expected format. Changed the code to be
explicit about this format from squeue. This also allows a
briefer format with simpler parsing because we can dump the
header and columns we don't care about.
=> slurm: have squeue be explicit about the format

parsl/monitoring/monitoring.py
The DFK can send many more messages than that under reasonable load,
and they queue up in the router process causing a lot of memory bloat.
I am able to reproduce this bloat with a tight loop submitting 200000 tasks.
before this patch:
There is a delay of loop freq (* some multiple) for every DFK message received,
if other non-dfk receives have to timeout.
with this patch:
the DFK receive loops tightly until there are no more messages to receive. on my
laptop this means the router uses hardly any extra memory (750mb compared to
550mb at router startup)
=> Avoid 50msg/sec rate limit in monitoring router for DFK messages

README.rst
=> Remove accidentally merged test on end of README

test-requirements.txt
This allows new type checking features to be used
=> Upgrade mypy from 0.910 to 0.961

parsl/executors/high_throughput/executor.py
This can help in understanding why scaling in is not
scaling in as many as task load would suggest.
=> Add logging around scale in behaviour

parsl/dataflow/dflow.py
This is to help understand ongoing issues with
parsl not exiting cleanly / hanging at exit.
=> Add more log messages around exiting

parsl/executors/extreme_scale/mpi_worker_pool.py, parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/process_worker_pool.py
=> 0mq and zmq are the same thing. Use a single name.

parsl/executors/high_throughput/process_worker_pool.py
=> Log *what* the manager is connected to

parsl/monitoring/monitoring.py
=> Refactor a bunch of casts and tuple construction in monitoring

parsl/executors/workqueue/executor.py
=> Add debug logging around Work Queue shutdown, based on investigating hangs

parsl/dataflow/strategy.py
I have experienced user confusion about why scaling is
or is not happening, which these log messages are intended
to address.
=> Add a lot of debug logging to explain strategies

parsl/dataflow/flow_control.py
=> Make FlowControl not store unused DFK reference

parsl/dataflow/flow_control.py
=> Remove an unused code path in flow control

parsl/dataflow/flow_control.py
=> Remove unused __main__ block from flow control source

parsl/executors/workqueue/executor.py
=> Fix typo in work queue logging

parsl/config.py
=> Refresh config.strategy docstring

parsl/monitoring/monitoring.py
This is to allow prototyping of other resource monitoring
information over radios - for example, node information
coming from nodes rather than from the interchange.
=> Allow monitoring radios to send messages with any tag.

parsl/monitoring/monitoring.py
More frequent resource usage accumulation can give more accurate
readings - mostly when subprocesses terminate and disappear, their final
resource usage will be lost, so more frequent readings will get
usage for those processes closer to their end.
In the case that resource messages are configured to be sent more frequently
than every 5s, resources will be accumulated more frequently.
=> Accumulate resource usage every 5s, even when message frequency is different

parsl/executors/high_throughput/interchange.py
This aligns with changes in the main body of parsl
=> Replace manual thread tags in interchange logs with log format metadata

parsl/executors/high_throughput/process_worker_pool.py
=> General rework of process worker pool logs

parsl/configs/theta.py
Quick change the Theta example. The current one has issues with CPU masking
=> Performance improvements to Theta config

parsl/executors/high_throughput/interchange.py
=> Remove unused poller in htex

parsl/executors/high_throughput/interchange.py
=> Rename _ready_manager_queue, becaues it is not a queue

parsl/executors/high_throughput/interchange.py
=> Add space in log message

Makefile, mypy.ini, parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/manager_record.py
This PR especially adds typing for the ready_managers
dictionary, which is now represented by a ManagerRecord
TypedDict.
=> Add more typing for interchange

parsl/executors/high_throughput/interchange.py
=> Log which manager a message batch comes from

parsl/executors/high_throughput/interchange.py
These are based on practical experience debugging the interchange.
=> Add more interchange debugging logs

parsl/executors/high_throughput/interchange.py
See issue #2030 for motivations around this tidyup.
=> Reduce dictionary lookups for ready_managers in interchange

parsl/dataflow/usage_tracking/usage.py
=> Correct docstring for usage tracking send message, and add corresponding type annotation

parsl/executors/high_throughput/executor.py
This talks about a vague idea for resource monitoring that was
actually implemented by the monitoring system in a very different
way.
=> Remove outdated docstring

parsl/serialize/concretes.py
=> Fix typos/spelling in serializer docstrings

parsl/dataflow/dflow.py, parsl/dataflow/flow_control.py, parsl/dataflow/strategy.py, parsl/dataflow/task_status_poller.py, parsl/dataflow/usage_tracking/usage.py
This comes from the benc-mypy branch
The benc-mypy branch contains some more complicated situations,
which are not merged by this PR.
=> Add lots of simple type annotations throughout parsl/dataflow

parsl/executors/high_throughput/interchange.py
The interchange is terminated by process termination, not by
STOP messages, so these code paths are unused.
=> Remove STOP/kill event handling from interchange task_puller

parsl/app/errors.py
=> Correct docstring for BadStdStreamFile

.github/workflows/python-publish-to-testpypi.yml
Adding a manual dispatch event and cron-based weekly dispatch event
=> Adding better triggers

parsl/executors/high_throughput/interchange.py
=> Make kill event a local var, after #2429 removed shared use

README.rst
A checker reported
```
Code of Conduct
============
:99: (WARNING/2) Title underline too short.
Code of Conduct
============
```
=> minor markup fix to address compliance

docs/userguide/configuring.rst, parsl/configs/polaris.py
Adds an example configuration for ALCF's Polaris
=> Polaris example configuration

parsl/tests/sites/test_start_method.py
We had a bug in the testing script!
=> Actually test the start methods

parsl/dataflow/dflow.py
This information is very useful when trying to understand other logs, to the extent that it is frustrating when it is missing.
=> Log configuration at INFO level

parsl/tests/test_error_handling/test_resource_spec.py
=> Clean up resource error test source

CONTRIBUTING.rst
* Versioning docs reflect the calendar versioning and automated deploy system
* Removed stale references to travis and replaced with github actions
=> Update CONTRIBUTING doc

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py
The previous default was not used, and there is no reason why that specific value should be the default.
=> Make viz resource efficiency type mandatory

parsl/monitoring/visualization/plots/default/workflow_resource_plots.py
This PR removes unused default parameters, as there are no values there that should be favoured.
It also adds in stronger validation of those values, rather than falling off the end of if statements or defaulting to an incorrect case.
A couple of variables named after apps are renamed after their actual use as task identifiers - this is probably a cut and paste vestige.
Similar motivation to PR #2478
=> Tidy resource_distribution_plot source code

parsl/monitoring/visualization/templates/workflow.html, parsl/monitoring/visualization/views.py
Other explicit SQL queries are handled as pandas dataframes.
=> Use a dataframe for task summary in viz, for consistency

parsl/monitoring/visualization/views.py
=> Tidy up dag_group_by_states parameters in parsl-visualize

parsl/app/errors.py
Prior to this PR, RemoteExceptionWrappers explicitly serialised their wrapper exception information using dill.
This serialization was done to give an object that could more easily be sent over the network, as executor serializers could not serialize tracebacks at the time.
However, the implementation would serialize even when this was not needed, specifically when using the ThreadPoolExecutor.
This meant that some exceptions which did not serialize well (such as raised by Globus, issue #785) but which were mostly only raised by tasks running in the ThreadPoolExecutor (when using Globus file staging).
More recently, parsl has moved to expecting executors to be better able to serialize things that can be serialised (see parsl.serialize) rather than having ad-hoc serialization like this. …
=> Let RemoteExceptionWrappers serialize via executor serialization

README.rst
See corresponding introduction PR #2097
=> Remove research notice valid for June 2021 - June 2022

parsl/dataflow/strategy.py
=> Refer to strategy class as Scaling strategy, not flow control strategy

parsl/dataflow/strategy.py
=> Add missing seconds units on idle duration log

mypy-stubs/typeguard.pyi
=> Remove unused List import from typeguard stub

parsl/dataflow/dflow.py
=> Fix scitps => scripts typo in docstring

parsl/providers/kubernetes/kube.py
=> Fix typo in kubernetes provider comment

parsl/dataflow/dflow.py
Tasks are now be wiped from the tasks table as soon as they complete with a separate queue to manage checkpointing that contains direct references to task records.
See issue #2014 which tracks work to remove task-ID based lookups into self.tasks.
Fixes a heisenbug described inside #2014 with a race between two different calls to wipe_tasks - after this PR, wipe_tasks is only called in one place.
Fixes #1996 - task garbage collection doesn't remove failed tasks with checkpointing turned on
=> Remove use of self.tasks[] from checkpointing system.

parsl/monitoring/db_manager.py, test-requirements.txt
This PR removes a "type: ignore" which is not needed after this PR.
=> Upgrade mypy to 0.991

mypy.ini
This can catch some bugs in comparisons
=> Enable strict equality everywhere

parsl/tests/test_python_apps/test_worker_fail.py
=> Make small tidyups to worker fail test

mypy.ini, requirements.txt
This PR adds some type stubs for packages that are used, and removes some ignored imports that are no longer used so do not need to be ignored.
=> Reduce number of ignored imports in mypy

parsl/tests/test_providers/test_local_provider.py
This comes from work in benc-mypy branch
=> Bugfix an incorrect call to provider.submit in test suite

MANIFEST.in
Include requirements.txt in pip package to enable building from source
https://github.com/conda-forge/parsl-feedstock/pull/9
=> Include requirements.txt in pip package to enable building from source

parsl/executors/high_throughput/interchange.py
=> Split main interchange loop into four separate topical methods

parsl/executors/high_throughput/interchange.py
=> Remove a TODO in htex from 2018 that we have been fine without doing

parsl/executors/high_throughput/executor.py
=> Fix a docstring typo

parsl/executors/high_throughput/process_worker_pool.py
=> Remove an htex manager comment that describes something that isn't happening

parsl/dataflow/dflow.py
=> Remove whitespace at start of docstring

parsl/dataflow/strategy.py
=> Remove unused config/label field from scaling strategy executor dictionary

mypy.ini, parsl/app/errors.py, parsl/executors/flux/executor.py, parsl/executors/status_handling.py
=> Turn on mypy warn-unused-ignores and subsequent tidyup

Makefile
=> Remove incorrect comment in Makefile

parsl/executors/workqueue/executor.py
=> Remove a "not implemented" docstring on an implemented method

parsl/tests/test_bash_apps/test_error_codes.py
=> Remove unreachable test case code

.github/workflows/python-publish-to-testpypi.yml
* Replacing the `set-output` method to the recommended output params model from GH actions.
* YAML linting fixes
=> Gh action updates round2

.github/workflows/python-publish-to-testpypi.yml
=> Typo fix. Replacing YY-MM-DD with YY.MM.DD

Makefile, parsl/benchmark/perf.py, setup.py
=> Add a performance measurement CLI

parsl/monitoring/db_manager.py, setup.py
SQLAlchemy 1.4 was released in March 2021, more than two years ago.
=> Advance SQLAlchemy lower bound and remove special case for <1.4

mypy.ini
=> Tighten mypy around modules that don't need any code changes

parsl/channels/errors.py
=> Make ChannelErrors be ParslErrors

parsl/executors/base.py
=> Remove a "we should simply" TODO that isn't so simple

parsl/dataflow/dflow.py
=> Add type annotations to load_checkpoints

Makefile
Fix the environment setup to correctly reuse the installed environment.
Fixes # n/a
=> Fix make virtual environment for developers

docs/userguide/apps.rst, docs/userguide/mpi_apps.rst
Addresses the suggestions made by @benclifford on #2731 
=> Minor fixes to MPI docs

parsl/data_provider/globus.py
Updating Globus provider to SDK 3. Changing task_wait args. 
Fixes #2734
=> Update globus provider args

docs/userguide/workflow.rst
=> Add a link to exaworks warmable functions tutorial

parsl/tests/test_serialization/test_basic.py
=> Add some basic unit tests of serializer components

docs/faq.rst
=> Update FAQ on what can be serialised

docs/index.rst, docs/quickstart.rst
Makes sure the links to the example configurations are available easily.
=> Link to the configuration examples

parsl/serialize/facade.py
=> Refactor serializer selector code

parsl/launchers/errors.py, parsl/providers/cluster_provider.py
=> Remove callables-as-Launchers for better type checking

parsl/data_provider/files.py, parsl/tests/conftest.py, parsl/tests/test_data/test_file_apps.py, parsl/tests/test_data/test_file_staging.py, parsl/utils.py
This is a follow-up commit after a couple of review comments in [PR #2773](https://github.com/Parsl/parsl/pull/2773) (509e8e2761d7) and the ensuing issue.
Fixes: #2785
=> Teach File to be PathLike aware

.readthedocs.yaml
=> Add PDF format to readthedocs configuration

parsl/tests/conftest.py, parsl/tests/test_scaling/test_scale_down.py
Locally, I was consistently seeing this test take 56s.  This commit reduces that to 12s locally.
There are two main changes:
- Bind to 127.0.0.1, rather than to all live interfaces.  Some of the delay was from the network stack
- Replace the littered `time.sleep()` calls with an "Event" based approach (polled files on the filesystem)
The other addition of note is `try_assert()`.  This my approximation of JUnit's `assertTimeout` or QT's `QTRY_VERIFY`: continually try a test condition for a timeout period.
I'm not able to discern at this time if this robustly resolves #1885.
=> Reduce test_scale_out delay

parsl/tests/test_bash_apps/test_apptimeout.py
No sense in waiting extra time.
=> Reduce apptimeout test delays

parsl/tests/sites/test_concurrent.py
=> Bind an HTex test to localhost and shorten heartbeat periods

docs/userguide/configuring.rst
=> Replace Polaris configuration documentation with link to ALCF website

parsl/monitoring/remote.py
See issue #2848 for a bunch of description and benchmarking.
Fixes #2848 
=> Remove monitoring vs serialization cache as causes space explosion

.wci.yml
I added Flux to the `.wci.yml` resource managers list.
=> Update .wci.yml to include Flux

mypy.ini, parsl/addresses.py, parsl/monitoring/db_manager.py, parsl/utils.py
=> Require mypy # type: ignore specifies what is being ignored

parsl/executors/high_throughput/executor.py
=> Use capital letter at start of log message

parsl/jobs/error_handlers.py, parsl/jobs/job_status_poller.py, parsl/jobs/strategy.py
These come from the benc-mypy branch
=> Add some more type annotations to parsl.jobs

parsl/app/bash.py
=> Replace [appname] with English text in bash app exceptions

docs/devguide/roadmap.rst
I updated the roadmap using content/copy from the working Google Doc developed by the core team: https://docs.google.com/document/d/1IOgSyKhQq5eNOn0mLHa6znmVTMdfCF5kKpqNLNB2_AA/edit?usp=sharing. Our roadmap needs to be updated to complement our NumFOCUS application.
=> Remove historical info and update roadmap

parsl/executors/taskvine/factory.py, parsl/executors/taskvine/manager_config.py
This PR fixes the issue in #2903.
Fixes # (issue): 2903
=> TaskVineExecutor: Fix Issue 2903

parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/zmq_pipes.py, parsl/executors/status_handling.py, parsl/utils.py
This comes from flake8-bugbear branch, working towards eliminating bugbear B007 errors there.
This PR does not address B007 errors in visualization or in the test suite.
=> Remove unused loop variables

parsl/utils.py
This is work from benc-mypy branch
=> Move some checkpoint types from list to sequences to tighter constrain mutability

parsl/tests/test_python_apps/test_lifted.py
This should have been fixed by PR #2916
=> Re-enable test that was skipped because of issue #2908

parsl/executors/workqueue/executor.py
=> Fix a typo in Work Queue code comment

parsl/providers/slurm/slurm.py
=> Fix typo in slurm error message

parsl/executors/workqueue/parsl_coprocess.py
Issue resolving relative task directory
#2914 
- Bug fix
=> move dir fix parsl_coprocess.py

parsl/tests/test_staging/test_elaborate_noop_file.py
Teach test to use `tmpd_cwd` so as to cleanup test detritus.  While here, also implement a test fixture to handle the parsl setup and cleanup to make the test kernels more focused (easier to read).
=> Cleanup test detritus

parsl/tests/conftest.py
In pursuit of no test detritus, set the default working directory of executors and the `dfk` to a test-run-specific temporary directory.  For "conforming" tests, (i.e., those that are aware of the fixtures in `conftest.py` that attempt to make fresh configurations), this enables auto-cleanup.  The rest will follow in piecemeal PRs "as we get there."
=> Set default test executor working dir

parsl/dataflow/dflow.py
... and include an IDE-suggested change to `t = ...`
=> Favor one-line over backslash continuation

parsl/tests/test_checkpointing/test_python_checkpoint_1.py, parsl/tests/test_checkpointing/test_python_checkpoint_2.py
Current checkpoint tests an app that generates a random number to infer that subsequent calls are being pulled from the cache. This PR updates the random apps to instead use uuid which comes with better uniqueness guarantees to simplify the tests. 
=> Minor refactor of checkpoint tests

parsl/executors/high_throughput/executor.py
=> Rephrase docstring for htex.scale_in

parsl/executors/taskvine/manager.py
Add a parsl tag to catalog info if catalog has been enabled
- New feature
=> TaskVine: add parsl tag to catalog info

parsl/curvezmq.py
The underlying `zmq.Context` object has its own `__del__` method, which calls `self.destroy()`, so we only need to close the auth thread.
=> Simplify curvezmq ctx destructor

parsl/benchmark/perf.py
This parameter controls the size of a generated parameter to the test app that is invoked by parsl-perf, specifying how many bytes that parameter should have.
Example usage:
parsl-perf --config parsl/tests/configs/htex_local.py --argsize=1000
will create an argument of 1000 bytes to be passed to each test app invocation.
Example performance using this parameter, against Parsl 2024.02.05, on my laptop:
With parsl/tests/htex_local.conf:
```
Default 0:  2030 tasks/sec
--argsize 1000:  1983 tasks/sec
--argsize 100000:   271 tasks/sec
--argsize 1000000:    32 tasks/sec
```
New functionality that should not affect existing behaviour.
- New feature
=> Add parsl-perf argument size parameter

parsl/executors/high_throughput/interchange.py, parsl/executors/high_throughput/process_worker_pool.py
See PR #2588 which actually removed the relevant code paths.
This should not change anything: the only code change is a local variable rename
=> Remove obsolete text and variables about managers requesting tasks

parsl/tests/test_serialization/test_htex_code_cache.py
=> Add integration test for htex vs caching code serializer

parsl/executors/high_throughput/process_worker_pool.py
Before this PR, this loop runs repeatedly, under high load quite often, but slowing down exponentially until reaching once per heartbeat period.
The other things happening in this loop:
* emit a debug log
* check heartbeat related events (motivating upcoming drain work in PR #3063 would like to add an additional event there)
This PR calculates the earliest of the two heartbeat related events and wait in poll until that time.
This will change:
i) the two heartbeat checks may happen earlier than previously, closer to the calculated time, because this loop will more accurately aim for the heartbeat time. This might uncover bugs or misassumptions elsewhere in Parsl code or users. Related to this, this PR changes time comparisons from > to >= so that events can fire in the same …
=> Change htex pull_tasks iteration from exponential backoff to calculated time

.flake8, parsl/dataflow/dflow.py, parsl/executors/high_throughput/process_worker_pool.py
Reduced flake-8 maximum length and changed some lines which violate the new configuation
This pr wont change any behaviour of the project
Fixes #3105
=> Reduce flake8 max-line-length

docs/README.rst
This PR adds instructions on launching a local python3 http server to view freshly rebuilt docs.
Only doc changes
=> Update docs README with addition on viewing docs locally

README.rst
Add a badge NSF badge to the README 
Which existing user workflows or functionality will behave differently after this PR?
=> Added NSF badge for award 150475

parsl/monitoring/monitoring.py, parsl/monitoring/router.py
This is ongoing work to split up monitoring.py into more topical pieces - see also PRs #2468, #2439
=> Split monitoring router and hub into separate files

parsl/monitoring/monitoring.py
It already does! except indirected via self.logger. This PR removes that indirection.
none
=> Use module-scope logger in MonitoringHub

parsl/jobs/error_handlers.py
=> Add return annotation to windowed_error_handler

parsl/executors/status_handling.py
=> Tighten executor simulated status type: block_ids are str

parsl/dataflow/dflow.py, parsl/monitoring/monitoring.py
=> Remove a hard-coded indirection to monitor_wrapper

parsl/tests/test_monitoring/test_basic.py
* use a tmpd_cwd working directory
* remove logging
* use DFK as a context manager
This should not change what is tested.
=> Update monitoring basic test to recent style

parsl/jobs/strategy.py
This PR adds a type annotation to the function signature.
That has the knock-on effect of enabling type checking within the method, revealing two mypy errors.
One is unreachable code: because the strategy will only be called with a BlockProviderExecutor executor, it does not need to check if it has been called with a BlockProviderExecutor.
The other type error comes from mypy not realising that a path is unreachable: the idle time of an executor may be None, but at the point of the type error, an `if` statement has ensured that it is never none. This PR adds an assert statement to assert that assertion to the type checker (and, incidentally, to the logs via wrap_with_logs).
none
=> Fix typing on general strategy

parsl/executors/status_handling.py, parsl/jobs/job_status_poller.py
This should not change behaviour: it is a code move.
=> Move send_monitoring_info method into BlockProviderExecutor

parsl/tests/test_monitoring/test_stdouterr.py
This removes 16 x 5s = 80 seconds of realtime during test execution.
=> Decrease strategy poll period in stdout/err vs monitoring test

parsl/tests/conftest.py
=> Fix typo in marker doc string

parsl/tests/test_htex/test_basic.py
The name suggests that some failure is being tested, but that's not the case. This PR renames that. This PR also adds a very simple assert on the return value for a small amount of extra behavioural testing.
=> Tidy up wrong looking htex test

parsl/tests/unit/test_file.py
Remove the mistaken conditional check from an apparent vestigial thought-process during initial implementation.
- Bug fix  (of a test!)
=> Actually test the file: prefix.

parsl/data_provider/zip.py, parsl/tests/test_staging/test_zip_in.py, parsl/tests/test_staging/test_zip_to_zip.py
=> Implement stage-in for zip staging provider

docs/userguide/workflow.rst
Fixed a typo / variable name bug in the docs
nothing
no issue opened yet
=> fix variable name

parsl/dataflow/dflow.py, parsl/jobs/job_status_poller.py
The use of this parameter was removed in PR #3346
=> Remove vestigial monitoring parameter

parsl/monitoring/radios.py
=> Correct grammar in monitoring docstring

parsl/providers/pbspro/pbspro.py
Minor cleanup to avoid circular dependency when we isort the import lines in a follow up PR.
N/A
=> Fixing potential circular dependency

docs/userguide/overview.rst
Minor doc update regarding slurm's command reference
N/A
Fixes #3419 
=> [DOC]: fix `slurm` command reference

parsl/tests/test_mpi_apps/test_mpi_mode_disabled.py
=> Remove unused logging import in MPI test

CONTRIBUTING.rst
=> Add CONTRIBUTING note on local test config framework

CONTRIBUTING.rst
=> Turn flake8 CONTRIBUTING note into its own section

CONTRIBUTING.rst
=> Merge conflicting CONTRIBUTING sections on the best place for discussion

parsl/tests/test_serialization/test_3495_deserialize_managerlost.py
Stupid thinko.  This should have been the test&nbsp;&mdash;&nbsp;and was&nbsp;&mdash;&nbsp;but I lost the thread while getting the test to fail before making the actual refactor.
Fixes #3495 
=> Refactor test

parsl/executors/status_handling.py
This should not change any behaviour
=> Bring status() next to poll_facade() which is the only user

docs/userguide/checkpoints.rst
=> Update checkpoint docs to follow #1945 and #2667

parsl/monitoring/router.py
This is to support rearrangement of the structure of the router code into multiple threads and methods, without having to manually wire all of the multiprocessing objects between the new methods and threads.
These objects are part of the context of the router object, rather than parameters to individual methods which might change, and they are all multiprocessing objects which are thread-safe.
none
=> Move monitoring router parameters into object attributes

parsl/executors/high_throughput/interchange.py
=> Fix incorrect string template introduced in PR #3597

docs/quickstart.rst, docs/userguide/usage_tracking.rst
Update usage tracking docs with information about the tracking levels and dashboard
=> Update docs with new usage tracking info

parsl/executors/high_throughput/process_worker_pool.py
=> Fix typo in "fully drained" log message

parsl/dataflow/dflow.py
=> Remove docstring saying dfk.submit returns DataFutures. It does not.

parsl/executors/high_throughput/process_worker_pool.py
=> Remove incorrect outline docstring of htex worker algorithm

parsl/monitoring/radios.py, parsl/monitoring/remote.py
crossref PR #3666 which removes a different unused monitoring source identifier.
=> Remove unused monitoring radio source ID

parsl/dataflow/dflow.py
This was previously used by the AdHocProvider, removed in PR #3676
=> Remove unused DFK initialization for multiple provider channels

parsl/tests/integration/test_channels/remote_run.sh
=> Remove unused channel test files

README.rst
To complete our NumFOCUS onboarding, we must add their badge to our repository and website. Adding the "Powered by NumFOCUS" badge to our README.
N/A
N/A
=> Add NumFOCUS badge

parsl/dataflow/rundirs.py
=> Update make_rundir docstring

parsl/executors/high_throughput/interchange.py
This is a follow on from #3752 - see that PR for some motivation
some performance reduction
- New feature
=> Remove HTEX interchange control channel thread into main thread

parsl/executors/high_throughput/executor.py
Just assert what's already happening (and _should_ be happening).  Use it to remove an indent level.
Should be no changed behavior for users.
=> Programmer error protection: there can be only one

parsl/tests/test_python_apps/test_memoize_1.py
=> Correct test docstring for basic memoization test

parsl/executors/high_throughput/mpi_resource_management.py
Otherwise only an almost-helpful log line.
No change of note; log line is level INFO, not WARNING, and include the task id.  Most users will likely never heed this line.
=> Add task info to log line

parsl/monitoring/monitoring.py
=> Rephrase monitoring router port report failure error message

parsl/executors/high_throughput/process_worker_pool.py
No sense in uselessly iterating this thread when there's no incoming message, just to handle the "time to quit" event.  Instead, just inject a poison pill when it's time to go away.
Before, if the workers were in debug mode, whether or not there were any messages to handle the block's `manager.log` file would fill with lines like:
```
... parsl:475 ... Monitoring-Handler [DEBUG]  Starting monitor_queue.get()
... parsl:478 ... Monitoring-Handler [DEBUG]  monitoring_queue.get() has timed out
```
Now, the lines are only emitted when an event happens (blocking for a new item in the queue, or an item is received):
```
... parsl:472 ... Monitoring-Handler [DEBUG]  Starting monitor_queue.get()
... ...
... parsl:476 ... Monitoring-Handler [DEBUG]  Got a monitoring message
```
This change …
=> Make PPW monitoring thread blocking

parsl/executors/high_throughput/process_worker_pool.py
The detail of interest is to follow up after sending SIGTERM to each worker process.  This implementation now waits for up to 1s for each child process, before forcibly killing it (SIGKILL).
While here, move the storage to a non-class variable.
No user workflows will change; just make intended shutdown of process pool worker more robust in the errant case.
=> Refactor worker shutdown procedure

parsl/monitoring/radios/zmq_router.py
=> Add debug log before potential hang point in zmq radio

parsl/dataflow/dflow.py, parsl/executors/base.py
The use of this was removed in #3795.
none
=> Remove unused executor.hub_address

parsl/executors/taskvine/executor.py
For context on this change, see in issue #3723
This addresses a problem where the taskvine manager sometimes hangs when trying to make a log entry.
probably slower startup times. above bugfix.
- Bug fix
=> Move TaskVine to use spawn context multiprocessing

parsl/executors/workqueue/executor.py
For context on this change, see in issue #3723
startup probably a bit slower now
- Bug fix
=> Move Work Queue to use spawn context multiprocessing

parsl/executors/high_throughput/interchange.py
The results handling currently moves the messages around twice for no benefit.  Just remove the tasks from the manager's bookkeeping data structure, and prepare the final list to send.  No need for the second iteration nor the `got_result` boolean.
None.
=> Remove unnecessary intermediate collection

parsl/executors/status_handling.py
This is mostly to satisfy the IDE linter, which didn't like the piecemeal creation of the dictionary.  Go ahead and inline the list as well.
None.
=> Inline list and dictionary creation

parsl/tests/test_scaling/test_scale_down.py
On my laptop:
Before this PR: 16 seconds
After this PR: 7 seconds
=> Shorten scale down test duration

parsl/tests/conftest.py
In networking contexts, the general advice for polling for specific events is "exponential backoff."  I don't think this is related to our recent CI test failures as 20ms is a super long time to wait (the standard game frame time is 1/60s or ~16.7ms, for example, and considered a low-bar to beat) and all of the test infrastructure is on the same host.  Regardless, exponential backoff is good hygiene in general, so "let's see what happens."
No user-facing change.
=> Move try_assert to exponential backoff

parsl/tests/test_monitoring/test_basic.py
The expectations for ThreadPoolExecutor are a different to the existing configurations. This PR adds conditions around some asserts to deal with that.
=> Test ThreadPoolExecutor monitoring

parsl/monitoring/monitoring.py, parsl/monitoring/radios/filesystem_router.py
See PR #2973 for justification of forcing kwargs.
=> Force mandatory kwargs for filesystem radio starter

parsl/monitoring/errors.py
=> Remove unused MonitoringHubStartError

parsl/monitoring/monitoring.py, parsl/monitoring/radios/filesystem_router.py, parsl/tests/test_monitoring/test_radio_filesystem.py, parsl/tests/test_shutdown/test_kill_monitoring.py
This is similar to what PR #3879 does for the UDP radio, for the same reasons.
=> Modularize filesystem monitoring radio receiver and test more

Makefile
No functionality change, but update the set of targets advertized upon a naked `make` invocation or `make help`.
None for users.
=> Update advertised Makefile targets

parsl/providers/local/local.py
For the local provider, teach `_is_alive()` to use `os.kill()` directly from in-process, rather than outsourcing to multiple external processes and parsing. In context, this is negligibly more performant, but also removes some unnecessary noise in logs.  The biggest detail is just "simpler."
There are no user-facing or functionality changes.
=> Teach LocalProvider to use os.kill() directly

parsl/tests/site_tests/test_site.py
=> Remove comment noise

parsl/executors/high_throughput/mpi_resource_management.py
Remove an unused variable.
No changed behavior.
=> Remove unused variable

parsl/tests/test_mpi_apps/test_mpi_scheduler.py
No need to reserialize the same dummy data multiple times.
No external changes; only an automated test internal change.
=> Serialize test data once

parsl/executors/high_throughput/interchange.py
A minor syntax sugar change.
There are no behavior changes.
=> Minor syntax sugar update

parsl/dataflow/dflow.py
Prior to this PR, the memoizer was told about the result in the AppFuture result callback.
By the time this happens, the user workflow code can also observe that the task is completed and also observe that the memoizer has not got a copy of the result: for example, by invoking the same app again immediately and seeing a duplicate execution.
The AppFuture callback shouldn't have anything in it that is related to user-observable task completion, but this PR does not remove other stuff in there.
This PR moves update_memo earlier, to before setting the AppFuture result, so that the memoizer is strictly before future changes state.
Checkpointing behaviour will now be slightly less racy. In situations where that race condition would have fired, the user will now see fewer apps actually …
=> Tell memoizer the task result earlier, to fix race condition #3762
